### ISSUE TITLE
Controlled fail in state definitions

### ISSUE THREAD

**Issue by cznewt** [saltstack/salt#10723]
Hello, puppet has mechanism to deliberately fail if some conditions are not met (i.e. os_family is not supported) like:

fail("No support for OSfamily \"${::osfamily}\"")

does salt have something similar, it would be very useful

**Comment by powellchristoph** [comment]
+1 I would love to have this functionality.

**Comment by whiteinge** [comment]
I think we have answers to all the asks in this thread now with the upcoming 2015.8 release of Salt. Is there anything anyone would still like to see or can we close this issue out? We should add a "Throwing and Handling Errors" section to the states/formulas docs that lists each approach.

Reacting to, or recovering from, a failed state.

```yaml
create_lots_of_files:
    cmd.run:
        - name: for i in {1..99999}; do touch mydirectory/$i ;done

"Unable to create tmp files. Check disk space?":
  cmd.run:
    - name: rm mydirectory/*
    - onfail:
      - cmd: create_lots_of_files
```

Throwing an exception during the Pillar compilation phase:

```jinja
{% if salt['file.exists']('/path/that/must/exist') %}
...
{% else %}
{{ salt.test.exception("/path/that/must/exist does not exist!!") }}
{% endif %}
```

Requiring certain Pillar values (or Pillar types) with the [test.check_pillar](http://docs.saltstack.com/en/develop/ref/states/all/salt.states.test.html#salt.states.test.check_pillar) state function:

```yaml
is-pillar-foo-present-and-bar-is-int:
  test.check_pillar:
    - present:
        - foo
    - integer:
        - bar
```

**Comment by powellchristoph** [comment]
@whiteinge Thank you for the update. The test.check_pillar is very nice!

**Comment by mitar** [comment]
`{{ salt.test.exception("/path/that/must/exist does not exist!!") }}` to me does not work. It seems like it returns the value with `_error` set to "Failed to return clean data" but it does not fail the compilation of the whole state.

**Comment by whiteinge** [comment]
@mitar Sorry for the bad wording above. Throwing an exception will stop the parsing of only the .sls file containing that error when generating Pillar. It will stop the full execution of a state run, however.

**Comment by mitar** [comment]
So maybe I am not testing this correctly. But i have a state `test.sls` like:

```
group-users:
  group.present:
    - gid: |
        {{ salt.test.exception("/path/that/must/exist does not exist!!") }}
```

I call:

```
salt-ssh '*' state.show_sls test
```

And I get:

```
testserver:
    ----------
    group-users:
        ----------
        __env__:
            base
        __sls__:
            test
        group:
            |_
              ----------
              gid:
                  {'retcode': 0, '_error': 'Failed to return clean data', 'stderr': 'Traceback (most recent call last):\n  File "/var/tmp/.mitar_cb9e2b_salt/salt-call", line 15, in <module>\n    salt_call()\n  File "/var/tmp/.mitar_cb9e2b_salt/py2/salt/scripts.py", line 379, in salt_call\n    client.run()\n  File "/var/tmp/.mitar_cb9e2b_salt/py2/salt/cli/call.py", line 58, in run\n    caller.run()\n  File "/var/tmp/.mitar_cb9e2b_salt/py2/salt/cli/caller.py", line 134, in run\n    ret = self.call()\n  File "/var/tmp/.mitar_cb9e2b_salt/py2/salt/cli/caller.py", line 197, in call\n    ret[\'return\'] = func(*args, **kwargs)\n  File "/var/tmp/.mitar_cb9e2b_salt/py2/salt/modules/test.py", line 512, in exception\n    raise Exception(message)\nException: /path/that/must/exist does not exist!!', 'stdout': ''}
            - present
            |_
              ----------
              order:
                  10000
```

So it did not raise the exception, but convert it to an object with `retcode`, `_error` and some other fields.

**Comment by whiteinge** [comment]
I see. This looks like a consistency issue with salt-ssh. 😦 

Regardless of which behavior we finalize on, `salt-ssh` and `salt` should decidedly produce the same outcome. Will you please file a separate issue for that and tag me on it?

**Comment by mitar** [comment]
Done: #42065.

**Comment by cebe** [comment]
old issue but still not implemented or documented as far as I see. Should stay open.

**Comment by basepi** [comment]
@saltstack/team-triage

**Comment by bwesemann-cxp** [comment]
@cebe There is a "test" salt module for states documented [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.test.html) that can be used as a controlled fail. How I've used it in relation to the original post:
```
{% if grains['os'] in ['Ubuntu', 'CentOS'] %}
new_repo:
  pkgrepo.managed:
    - blah
{% else %}
failure:
  test.fail_without_changes:
    - name: "OS not supported!"
    - failhard: True
{% endif %}
```
output looks like this
```
server1:
    ----------
    test_|-failure_|-OS not supported!_|-fail_without_changes:
        ----------
        __id__:
            failure
        __run_num__:
            0
        __sls__:
            wazuh
        changes:
            ----------
        comment:
            Failure!
        duration:
            1.224
        name:
            OS not supported!
        result:
            False
        start_time:
            23:53:14.395904
```

**Comment by disaster123** [comment]
this is still "unfixed"

**Comment by sagetherage** [comment]
the documentation looks to be added - is there more to do here @disaster123?

**Comment by mitar** [comment]
I think the problem is that it does not work over salt SSH: #42065

**Comment by sagetherage** [comment]
ok closing this issue in favor of #42065 docs looks to be added in all branches, please mention me if this is incorrect.

**Comment by ScriptAutomate** [comment]
https://github.com/saltstack/salt/pull/56913 (merged to `master` in Sodium)
