### ISSUE TITLE
[salt-cloud] Add merging ability to profile/provider extensions

### ISSUE THREAD

**Issue by rthomas** [saltstack/salt#11492]
This is duplicated from salt-cloud issue here: https://github.com/saltstack/salt-cloud/issues/908

When one profile extends another - only the applied profiles grains will be added to the instance, rather than merging the grains.

For example:

```
ubuntu_13.10_az_1:
  provider: ec2-ap-southeast-2
  image: ami-XXXXXXXX
  ssh_username: ubuntu
  location: ap-southeast-2
  availability_zone: ap-southeast-2a
  subnetid: subnet-XXXXXXXX
  script: /srv/salt/infrastructure-profiles/platform.sh
  minion:
    master: X.X.X.X
  grains:
    location: ap-southeast-2a
```

and

```
AIO_zk_1_profile:
  size: m3.xlarge
  grains:
    aio_role: zookeeper
  extends: ubuntu_13.10_az_1
```

Then invoking `# salt-call grains.items | grep location` on the new instance will not return anything.

Checking for the grain from the sub-node will return the correct value:

```
# salt-call grains.items | grep aio_role
  aio_role: zookeeper
```

**Comment by rallytime** [comment]
I am making my way around to some old bugs, and I can confirm that this one is still present in 2015.5. Here's an example of my profile:
```
ec2-ubuntu-14:
  provider: ec2-config
  image: ami-98aa1cf0
  size: t1.micro
  sh_username: ec2-user
  grains:
    hello: world

ec2-extends-grains:
  grains:
    foo: bar
  extends: ec2-ubuntu-14
```
First, I made a VM with only the primary profile with `salt-cloud -p ec2-ubuntu-14 nt-grains-test`. The `hello: world` grain is applied appropriately:
```
# salt nt-grains-test grains.item hello
nt-grains-test:
    ----------
    hello:
        world
```
Then, I made a VM with the extends profile with `salt-cloud -p ec2-extends-grains nt-grains-test-1`. The `hello: world` grains seems to be getting over-written by the `foo: bar` grain in the extends profile:
```
# salt nt-grains-test-1 grains.item hello
nt-grains-test-1:
    ----------
# salt nt-grains-test-1 grains.item foo
nt-grains-test-1:
    ----------
    foo:
        bar
```
Versions Report:
```
# salt-cloud --versions
            Salt: 2015.5.1-97-g88a997e
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
 Apache Libcloud: 0.17.0
```

**Comment by rallytime** [comment]
Ah, the final opts that get returned from the `cloud_config` function in `salt/config.py` indeed only contains the grains from the extending profile and not the original profile:
```
'ec2-extends-grains': {
    'profile': 'ec2-extends-grains',
    'grains': {'foo': 'bar'},
    'provider': 'ec2-config:ec2',
    'image': 'ami-98aa1cf0',
    'sh_username': 'ec2-user',
    'size': 't1.micro'
}
```

**Comment by rallytime** [comment]
Ok, after some more digging and after speaking with @s0undt3ch, this is happening because of the way the `extends` code was written. The extending profile overwriting the targeted key/val or entire dictionary is essentially "intended behavior" at the moment. For example. the examples in the [extending profiles docs](http://docs.saltstack.com/en/latest/topics/cloud/config.html#extending-profiles) is supplying a different image name in the extending profile. it's intended to overwrite the image name in the original profile.

That being said, I am going to change this to a feature request instead of a bug and change the title to more broadly reflect this sentiment. What I think should be done here, if someone wants to tackle this, is to maintain the current behavior by default, but then provide a flag wherein setting it to True would more explicitly "extend" (or add) to other keys, such as this grain example. I am thinking something along the line of:
```
ec2-extends-grains:
  grains:
    foo: bar
  extends: ec2-ubuntu-14
  merge: True
```
or something like that, where `merge` defaults to `False` to maintain current behavior. There might be a better name for the flag.

However! One should take care in thinking about how to handle things like when certain keys can/should be merged (like grains) and when only one key/value should be present (like image names). What if someone wants to extend a profile with a different image name and add additional grain information in the same extending profile?

**Comment by techhat** [comment]
This was fixed a while ago... configuration is merged from main cloud config into providers, then profiles (including grains).

**Comment by SJern** [comment]
Hi @techhat, exactly which commit fixed this? I'm currently on salt-master 2017.7.0, but the grains still do not seem to merge.
