### ISSUE TITLE
salt.state.iptables.append and salt.state.iptables.insert keeps inserting duplicate rules with each state run

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#17217]
I have seen issues regarding this earlier and there has been suggested fixes. I'm still having this problem because of which using these state functions to append or insert an iptable rule seems useless. 

Here's relevant information:

Master:
```
[root@nitin-saltmaster ~]# salt --versions-report
           Salt: 2014.7.0rc6-2571-g0d6e33a
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
[root@nitin-saltmaster ~]# 
```

Minion:
```
[root@nitin-saltmaster ~]# salt '*jenkins' test.versions_report
nitin-jenkins:
               Salt: 2014.1.13
             Python: 2.6.6 (r266:84292, Sep  4 2013, 07:46:00)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
             PyYAML: 3.10
              PyZMQ: 14.3.1
                ZMQ: 3.2.4
[root@nitin-saltmaster ~]# 
```

Both my master and minion are RHEL 6.5

**Comment by GermanG** [comment]
In such case, I'd prefer an error message being clear about not supporting iptables without --check.
I'll go the cmd.run / unless route.

Regards

**Comment by tjstansell** [comment]
I was going to suggest having the user specify a comment for the rule and use that to match on, but then if someone changed the parameters for an existing rule, the new rule wouldn't get added as it would think the rule was already there.  However, salt could auto-generate a comment field (or prefix one supplied by the user) that was unique to that rule and use that to match.  Perhaps simply take the full rule definition built by salt and hash it.  Then you don't rely on iptables-save format or anything else.  You simply look for the hash in the comment and know if the rule already exists.

**Comment by tjstansell** [comment]
looks like i commented too soon.  pull request #15204 seems to be fixing this for 2015.2 by inserting the rule in a temporary chain, then comparing the result from iptables-save.

**Comment by rallytime** [comment]
@tjstansell @nmadhok Based on the last couple of comments, do you guys consider this one fixed in the newer releases?

**Comment by nmadhok** [comment]
@rallytime The last time I checked, the issue still existed.

**Comment by rallytime** [comment]
Ok. I'll remove the "fixed..." label. thanks.

**Comment by bocig** [comment]
Yep confirmed, the issue  still exists under Cent 6.4. Thanks!

**Comment by garethgreenaway** [comment]
if you look at @gtmanfred's comment from December 2014 it explains why this issue still exists with CentOS 6.4.
