### ISSUE TITLE
localemod does not generate locale for Arch

### ISSUE THREAD

**Issue by tomashavlas** [saltstack/salt#17245]
Hello,
I have found out that if I try to use locale.present() state on ArchLinux, nothing really happens.
I have looked into localemod.py module and found out that locale is acually generated only for Debian and Ubuntu, however I'm quite sure that code which is used for Debian is suitable for Arch too.

**Comment by aboe76** [comment]
@tomashavlas I'm trying to debug this with the develop version to see if it is still present.

But when I read the documentation what locale.present, it test if the name of the given locale is 
in the locale.avail list:
```
salt 'salt.example.com' locale.list_avail         
salt.example.com:
    - C
    - POSIX
    - dutch
    - en_US
    - en_US.iso88591
    - en_US.utf8
    - nl_NL
    - nl_NL.iso88591
    - nl_NL.iso885915@euro
    - nl_NL.utf8
    - nl_NL@euro
```

so any locale.present with these names are already present and the module shouldn't do anything.
testing the module with: locale/init.sls
```yaml
en_IE@euro ISO-8859-15:
  locale.present:
    - name: en_IE@euro ISO-8859-15
```

it works:
```
salt 'salt.example.com' state.sls locale test=true
salt.example.com:
----------
          ID: en_IE@euro ISO-8859-15
    Function: locale.present
      Result: None
     Comment: Locale en_IE@euro ISO-8859-15 needs to be generated
     Started: 21:25:09.871022
    Duration: 11.776 ms
     Changes:   

Summary
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
```

**Comment by bricewge** [comment]
I have the same issue.
The problem is that `locale.present` do a `locale-gen $name` but don't uncomment locales in`/etc/locale.gen`. A workaroud for it is to keep your custom `/etc/locale.gen` in salt with the correct locales uncommented.

**Comment by jfindlay** [comment]
@bricewge, what version of salt are you using and what distro are you generating locales on?

**Comment by bricewge** [comment]
I'm on a up-to-date Archlinux with saltstack 2014.7.4.

**Comment by jfindlay** [comment]
@bricewge, that patch should fix the issue.

**Comment by bricewge** [comment]
I tried the latest commit on the branch 2014.07 and it doesn't fix the issue, `/etc/locale.gen` is not edited, but it work on Debian.
Maybe it's comming from the formatting of `/etc/locale.gen`, in Archlinux it is like this:
```
#es_UY.UTF-8 UTF-8  
#es_UY ISO-8859-1  
#es_VE.UTF-8 UTF-8  
#es_VE ISO-8859-1 
```
Whereas is Debian it is:
```
# ja_JP.EUC-JP EUC-JP
# ja_JP.UTF-8 UTF-8
```

**Comment by jfindlay** [comment]
This is the code in the locale module.

```python
    if os.path.exists('/etc/locale.gen'):
        __salt__['file.replace'](
            '/etc/locale.gen',
            r'^#\s*{0}$'.format(locale),
            '{0}'.format(locale),
            append_if_not_found=True
        )
```

This will match both `#es_UY.UTF-8 UTF-8` and `# es_UY.UTF-8 UTF-8`, however it seems that your `/etc/locale.gen` sample from arch has trailing whitespace in it.  We could generalize the search pattern to `r'^\s*#\s*{locale}\s*$'`.

**Comment by bricewge** [comment]
Nice, now it edit the `/etc/locale.gen` but `salt '*' locale.gen_locale "ca_ES.UTF-8 UTF-8"` did this `ca_ES.UTF-8 UTF-8#ca_ES ISO-8859-1` witch `locale-gen` don't like.

**Comment by jfindlay** [comment]
@bricewge, that is strange.  I'll look at this some more.  I suspect something interesting may be happening with file.replace.
