### ISSUE TITLE
salt.function returns success when the function is unavailable

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#18512]
This orchestration should fail:
```yaml
not.a.real.function:
  salt.function:
    - tgt: dev
```
But, instead, I get this:
```
dev:
----------
          ID: not.a.real.function
    Function: salt.function
      Result: True
     Comment: Function ran successfully. Function not.a.real.function ran on dev.
     Started: 08:12:51.062564
    Duration: 285.664 ms
     Changes:   
              dev:
                  'not.a.real.function' is not available.

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
An unavailable function should translate to a failure state.

**Comment by jfindlay** [comment]
@amendlik are you still having this issue?

**Comment by amendlik** [comment]
As far as I know, no one has worked on it yet. So the behavior hasn't
changed.

**Comment by basepi** [comment]
@amendlik It's a common occurrence in Salt that someone fixes a bug without realizing there's an issue open for that bug, or in conjunction with the fix for another issue. So it's useful to test from time to time, as sometimes bugs are fixed by happenstance. =)

**Comment by amendlik** [comment]
I suppose that's true. In any case, I just checked the code and it hasn't
changed:
https://github.com/saltstack/salt/blob/develop/salt/states/saltmod.py#L216

**Comment by amendlik** [comment]
I've just tested this on 2014.7 and 2015.2 and I'm still getting the same results:
```
dev:
----------
          ID: not.a.real.function
    Function: salt.function
      Result: True
     Comment: Function ran successfully.
     Started: 10:34:34.578302
    Duration: 17077.746 ms
     Changes:   

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

**Comment by steverweber** [comment]
salt opencs-app\* cmd.run 'salt --version'
opencs-app.salt.math.uwaterloo.ca:
    salt 2015.2.0-530-ga0440c6 (Lithium)

salt opencs-app\* state.highstate
```
----------
          ID: not.a.real.function
    Function: salt.function
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1554, in call                                                                                                                                                                                      
                  **cdata['kwargs'])                                                                                                                                                                                                                                           
                File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 375, in function                                                                                                                                                                          
                  cmd_ret = __salt__['saltutil.cmd'](tgt, fun, **cmd_kw)                                                                                                                                                                                                       
                File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 705, in cmd                                                                                                                                                                             
                  client = _get_ssh_or_api_client(cfgfile, ssh)                                                                                                                                                                                                                
                File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 667, in _get_ssh_or_api_client                                                                                                                                                          
                  client = salt.client.get_local_client(cfgfile)                                                                                                                                                                                                               
                File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 91, in get_local_client                                                                                                                                                                  
                  return LocalClient(mopts=opts, skip_perm_errors=skip_perm_errors)                                                                                                                                                                                            
                File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 131, in __init__                                                                                                                                                                         
                  self.key = self.__read_master_key()                                                                                                                                                                                                                          
                File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 156, in __read_master_key                                                                                                                                                                
                  self.skip_perm_errors)                                                                                                                                                                                                                                       
                File "/usr/lib/python2.7/dist-packages/salt/utils/verify.py", line 374, in check_path_traversal                                                                                                                                                                
                  raise SaltClientError(msg)                                                                                                                                                                                                                                   
              SaltClientError: Could not access /var/cache/salt/master. Path does not exist.                                                                                                                                                                                   
     Started: 08:34:13.501835
    Duration: 233.912 ms
     Changes:   
```

**Comment by steverweber** [comment]
it seems interesting that @amendlik ran for 17077.746 ms.

**Comment by cachedout** [comment]
I did see something similar is **no** minions return. I resolved that in #22606 

If a minion does return, however, I get the following on the HEAD of 2015.2:
```
mp@silver ~ % sudo salt-run state.orch issue_18512
[ERROR   ] {'ret': {'silver': "'not' __virtual__ returned False"}, 'out': 'highstate'}
suffix:
    progress
silver_master:
    ----------
    salt_|-not.a.real.function_|-not.a.real.function_|-function:
        ----------
        __run_num__:
            0
        changes:
            ----------
            out:
                highstate
            ret:
                ----------
                silver:
                    'not' __virtual__ returned False
        comment:
            Running function not.a.real.function failed on minions: silver Function not.a.real.function ran on silver.
        duration:
            296.804
        name:
            not.a.real.function
        result:
            False
        start_time:
            12:15:42.351066
```

With the state as follows:

```
not.a.real.function:
  salt.function:
    - tgt: silver
```

**Comment by cachedout** [comment]
No response from above comment and we have a fix in for the condition we did find. I'm going to go ahead and close this. If it's not fully resolved, please leave a comment and we'll happily re-examine this issue. Thanks!
