### ISSUE TITLE
Error while setting sysctl in FreeBSD

### ISSUE THREAD

**Issue by nbari** [saltstack/salt#19016]
Same like this https://github.com/saltstack/salt/issues/3403 but with FreeBSD 10.1:

I am getting the same problem under FreeBSD 10.1, this is my state:

    net.inet.ip.portrange.reservedhigh:
      sysctl.present:
        - value: 0

And this is the error:

          ID: net.inet.ip.portrange.reservedhigh
    Function: sysctl.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1533, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/states/sysctl.py", line 56, in present
                  configured = __salt__['sysctl.show'](config_file=True)
              TypeError: show() takes no arguments (1 given)
     Started: 12:37:59.554324
    Duration: 407.332 ms
     Changes: 

    # salt --versions-report
               Salt: 2014.7.0
             Python: 2.7.8 (default, Dec  4 2014, 09:32:53)
             Jinja2: 2.7.3
           M2Crypto: 0.22
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
             PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed

**Comment by nbari** [comment]
Hi, this is the output of ``salt 'minion' grains.items os``

    > salt freebsd_minion grains.item os
    freebsd_minion:
        ----------
        os:
            FreeBSD

**Comment by ari** [comment]
Isn't this the fix for this bug: https://github.com/saltstack/salt/commit/5ef3bf5e8a3cfe09381e94ed40a12a09dfff8f8a

**Comment by nbari** [comment]
I just tried using https://github.com/saltstack/salt/commit/5ef3bf5e8a3cfe09381e94ed40a12a09dfff8f8a , but continue to get the same error.

I updated the ``salt/modules/freebsd_sysctl.py`` and ``salt/states/sysctl.py`` files.

**Comment by JaseFace** [comment]
I'm seeing the same error on FBSD 10.1

```
----------
          ID: net.inet.tcp.rfc3390
    Function: sysctl.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1533, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/states/sysctl.py", line 56, in present
                  configured = __salt__['sysctl.show'](config_file=True)
              TypeError: show() takes no arguments (1 given)
     Started: 14:27:18.542662
    Duration: 170.105 ms
     Changes:
```

With a straight forward state:

```
net.inet.tcp.rfc3390:
  sysctl.present:
    - value: 0
```

**Comment by JaseFace** [comment]
Also, FreeBSD has a couple different files that have sysctl style entries, namely loader.conf which are boot time only tunables.  This basically means salt cannot change the value of it, so I think it'd be handy to add an option to sysctl.present such as 'enact', so we can tell the state to not try to modify the live value, but simply add it.

```
net.link.ifqmaxlen:
  sysctl.present:
    - value: 10240
    - enact: False
    - config: /boot/loader.conf
```

**Comment by JaseFace** [comment]
@nbari - This is actually fixed in 2014.7.1

**Comment by nbari** [comment]
Just tried with 2014.1.2 and still have this issue:

          ID: net.ip.portrange.reservedhigh
    Function: sysctl.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1533, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/states/sysctl.py", line 56, in present
                  configured = __salt__['sysctl.show'](config_file=True)
              TypeError: show() takes no arguments (1 given)
     Started: 15:51:18.180151
    Duration: 193.677 ms
     Changes:

**Comment by nbari** [comment]
I just updated the minions and now is working :+1:
