### ISSUE TITLE
salt-run stacktraces on latest 2015.2

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#21178]
If you run `salt-run` without any module.function parameters, the following exception occurs:
```
# salt-run
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError:
Traceback (most recent call last):
  File "/usr/local/bin/salt-run", line 10, in <module>
    salt_run()
  File "/root/SaltStack/salt/salt/scripts.py", line 243, in salt_run
    client.run()
  File "/root/SaltStack/salt/salt/cli/run.py", line 54, in run
    runner.run()
  File "/root/SaltStack/salt/salt/runner.py", line 138, in run
    self.functions[low['fun']],
  File "/root/SaltStack/salt/salt/loader.py", line 854, in __getitem__
    mod = super(LazyLoader, self).__getitem__(key)
  File "/root/SaltStack/salt/salt/utils/lazy.py", line 62, in __getitem__
    if self._load(key):
  File "/root/SaltStack/salt/salt/loader.py", line 1052, in _load
    raise KeyError
KeyError
Traceback (most recent call last):
  File "/usr/local/bin/salt-run", line 10, in <module>
    salt_run()
  File "/root/SaltStack/salt/salt/scripts.py", line 243, in salt_run
    client.run()
  File "/root/SaltStack/salt/salt/cli/run.py", line 54, in run
    runner.run()
  File "/root/SaltStack/salt/salt/runner.py", line 138, in run
    self.functions[low['fun']],
  File "/root/SaltStack/salt/salt/loader.py", line 854, in __getitem__
    mod = super(LazyLoader, self).__getitem__(key)
  File "/root/SaltStack/salt/salt/utils/lazy.py", line 62, in __getitem__
    if self._load(key):
  File "/root/SaltStack/salt/salt/loader.py", line 1052, in _load
    raise KeyError
KeyError
```
If you add the module.function parameter to the command, such as `salt-run manage.down` but the master is not running, the following stack trace occurs:
```
# salt-run manage.down
[ERROR   ] Salt request timed out. If this error persists, worker_threads may need to be increased.
Exception occurred in runner manage.down: Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/client/mixins.py", line 314, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/root/SaltStack/salt/salt/runners/manage.py", line 113, in down
    ret = status(output=False).get('down', [])
  File "/root/SaltStack/salt/salt/runners/manage.py", line 42, in status
    minions = client.cmd('*', 'test.ping', timeout=__opts__['timeout'])
  File "/root/SaltStack/salt/salt/client/__init__.py", line 517, in cmd
    **kwargs)
  File "/root/SaltStack/salt/salt/client/__init__.py", line 275, in run_job
    return self._check_pub_data(pub_data)
  File "/root/SaltStack/salt/salt/client/__init__.py", line 210, in _check_pub_data
    'Failed to authenticate!  This is most likely because this '
EauthAuthenticationError: Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```
However, if the salt-master is running, you still get the first stacktrace in the exact same manner, but the second one goes away and the correct output prints:
```
# salt-run manage.down
- nt-master
- nt-test-linode
```
Here's my versions report:
```
# salt --versions-report
           Salt: 2015.2.0rc1-81-g01daca4
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
@ssgward I didn't see an issue filed yet for this when we talked about it the other day as I think we were thinking #20597 was a duplicate (however it is a different issue). Please feel free to close this one if this has already been filed.

@cro I'm not sure if this has been discussed or not, but I wanted to be sure you knew about this one. Feel free to change the severity if deemed necessary.

**Comment by cachedout** [comment]
Fixed the no-args issue. The second one (master-not-running) has already been fixed.

**Comment by rallytime** [comment]
@cachedout The runner errors that happen when no args are passed in is indeed fixed, but the stacktrace that happens when the was is not running is not fixed yet. I tried this first from pulling down the PR that you linked above, and when that didn't work, tried again from the HEAD of 2015.2:
```
# salt-run manage.down
[ERROR   ] Salt request timed out. If this error persists, worker_threads may need to be increased.
Exception occurred in runner manage.down: Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/client/mixins.py", line 314, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/root/SaltStack/salt/salt/runners/manage.py", line 113, in down
    ret = status(output=False).get('down', [])
  File "/root/SaltStack/salt/salt/runners/manage.py", line 42, in status
    minions = client.cmd('*', 'test.ping', timeout=__opts__['timeout'])
  File "/root/SaltStack/salt/salt/client/__init__.py", line 517, in cmd
    **kwargs)
  File "/root/SaltStack/salt/salt/client/__init__.py", line 275, in run_job
    return self._check_pub_data(pub_data)
  File "/root/SaltStack/salt/salt/client/__init__.py", line 210, in _check_pub_data
    'Failed to authenticate!  This is most likely because this '
EauthAuthenticationError: Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```
```
# ps aux | grep salt
root     23570  0.0  0.0  11984   916 pts/0    S+   17:16   0:00 grep --color=auto salt
```
```
# salt --versions-report
           Salt: 2015.2.0rc1-124-g558f5e4
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
Is there another issue somewhere tracking the master-not-running bug?

**Comment by cachedout** [comment]
Hrm.

```
mp@silver ~ % ps -ef|egrep master
mp       24483   584  0 12:17 pts/1    00:00:00 grep -E master
mp@silver ~ % sudo salt-run manage.up
[ERROR   ] Unable to connect to the publisher! You do not have permissions to access /var/run/salt/master
Failed to connect to the Master, is the Salt Master running?
```

Also from HEAD of 2015.2

**Comment by cachedout** [comment]
@rallytime Please try #21501

**Comment by rallytime** [comment]
@cachedout Hrm...I gave this another try, and I now see the message, but the traceback is still showing:
```
# salt-run manage.down
[ERROR   ] Unable to connect to the salt master publisher at /var/run/salt/master
The salt master could not be contacted. Is master running?
Exception occurred in runner manage.down: Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/client/mixins.py", line 327, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/root/SaltStack/salt/salt/runners/manage.py", line 113, in down
    ret = status(output=False).get('down', [])
  File "/root/SaltStack/salt/salt/runners/manage.py", line 42, in status
    minions = client.cmd('*', 'test.ping', timeout=__opts__['timeout'])
  File "/root/SaltStack/salt/salt/client/__init__.py", line 524, in cmd
    **kwargs)
  File "/root/SaltStack/salt/salt/client/__init__.py", line 280, in run_job
    sys.exit(1)
SystemExit: 1
```

**Comment by rallytime** [comment]
Is it possible that a race condition could be happening here? I just pulled down the most recent HEAD of 2015.2 (6cf822561ac00ef38431547c357a3b0a1226437e) and when I have that checked out, I no longer see the stack trace. HOWEVER after chatting with @ssgward, he is doing the same things (salt-master is stopped and runs `salt-run manage.up` or `salt-run manage.down`) he is seeing the stackrace from the same sha.

@cachedout Have you been able to reproduce the stacktraces I was seeing (and @ssgward is now seeing)?

**Comment by cachedout** [comment]
I'm working on a more comprehensive fix. Stand by.

**Comment by rallytime** [comment]
Ok cool. Thanks @cachedout!

**Comment by cachedout** [comment]
#21501 re-opened. Give that a whirl.

**Comment by rallytime** [comment]
This looks good now. After testing the fix listed above, I am no longer seeing the stacktrace:
```
root@nt-master:~/SaltStack/salt# git fetch upstream pull/21501/head:mike-fix-3
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/saltstack/salt
 * [new ref]         refs/pull/21501/head -> mike-fix-3
root@nt-master:~/SaltStack/salt# git checkout mike-fix-3
Switched to branch 'mike-fix-3'
root@nt-master:~/SaltStack/salt# salt --versions
           Salt: 2015.2.0rc1-144-g51ef66b
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
root@nt-master:~/SaltStack/salt# ps aux | grep salt
root     28273  0.0  0.0  11984   920 pts/0    S+   20:23   0:00 grep --color=auto salt
root@nt-master:~/SaltStack/salt# rm -rf ./* && git reset --hard HEAD
HEAD is now at 51ef66b Catch timeout errors and other general exceptions and bubble them as saltclienterror
root@nt-master:~/SaltStack/salt# salt-run manage.up
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
root@nt-master:~/SaltStack/salt# salt-master -d
root@nt-master:~/SaltStack/salt# ps aux | grep salt
root     28356  8.7  0.1 148660 29696 ?        S    20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28357 17.5  0.2 232740 30996 ?        Sl   20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28358  0.0  0.1 230404 28868 ?        Sl   20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28361  0.0  0.1 230404 28952 ?        Sl   20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28385  0.5  0.1 967908 29316 ?        Sl   20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28388  1.2  0.1 148660 28256 ?        S    20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28389  6.7  0.1 476688 30044 ?        Sl   20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28392  6.7  0.1 476672 30028 ?        Sl   20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28395  6.2  0.1 476672 30028 ?        Sl   20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28398  6.7  0.1 476688 30044 ?        Sl   20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28401  6.7  0.1 476672 30028 ?        Sl   20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28404  0.0  0.1 328908 29092 ?        Sl   20:24   0:00 /usr/bin/python /usr/local/bin/salt-master -d
root     28625  0.0  0.0  11984   920 pts/0    S+   20:24   0:00 grep --color=auto salt
root@nt-master:~/SaltStack/salt# salt-run manage.up
- nt-cent6
root@nt-master:~/SaltStack/salt# killall salt-master
root@nt-master:~/SaltStack/salt# ps aux | grep salt
root     28972  0.0  0.0  11984   916 pts/0    S+   20:25   0:00 grep --color=auto salt
root@nt-master:~/SaltStack/salt# salt-run manage.up
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
root@nt-master:~/SaltStack/salt#
```

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt/issues/21460 has some overlap with this issue. I've fixed it in https://github.com/saltstack/salt/pull/21508 (tests are green)
