### ISSUE TITLE
alternatives.set_ state unavailable 2014.7.1

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#21482]
Hi,

I have the following "problem". I want to set an alternative in Ubuntu. According to the documentation (http://salt.readthedocs.org/en/latest/ref/states/all/salt.states.alternatives.html#salt.states.alternatives.set_) the state function to use would be ``alternatives.set_`` 
however, this state is reported to be unavailable, and I have to use
``alternatives.set`` instead. That means one has to remove the ``_``.
I'm not sure if this is reported or documented somewhere, if not I think this is a documentation problem.

Thx for your feedback.

Cheers,

**Comment by techhat** [comment]
This is a documentation issue. `alternatives.set` is correct. This technique is used throughout Salt.

**Comment by rallytime** [comment]
This is fixed in our current docs site: http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.alternatives.html#salt.modules.alternatives.set

We're no longer supporting the documentation in readthedocs, as discussed in #12015, and will be removing it (hopefully) sometime soon to reduce confusion. Since this is fixed in the current documentation and the question was answered here, I'm going to close this issue up. Thanks again!

**Comment by enblde** [comment]
I guess that we have a regression here. Current docs still have the underscore after 'set', and the state returns:  State 'alternatives.set_' was not found in SLS [...].

http://docs.saltstack.com/en/2015.5/ref/states/all/salt.states.alternatives.html

**Comment by rallytime** [comment]
@jacobhammons Can you take a look at this one?

**Comment by rallytime** [comment]
@enblde Looks like this is fixed now it the current release, 2015.8.0: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.alternatives.html#salt.states.alternatives.set

It's also fixed in develop, so I'll go ahead and close this again. Hopefully this stays fixed! ;)
