### ISSUE TITLE
[2015.5] Multi-Master Minions Block on Authentication

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#21744]
When setting up multi-master on the HEAD of the 2015.2 branch, when the minion starts, the minion will block until it authenticates with the first master in the minion's list of masters. Once that auth has taken place, it will then block on the authentication of the second master, and so on (if more than two).

This is a regression in behavior since 2014.7 (and, after testing on the HEAD of 2014.7, is not an issue there). In 2014.7, the minion would try to auth with both masters, before eventually settling on whichever masters were up after a number of iterations (see #17032). 

The blocking behavior causes several problems with multi-master:

1. When the minion is started and the 1st master is up but the second master is down, the minion auths with the first master and then blocks. The 1st master, which is running, cannot send commands to the minion(s), because the minions aren't receiving the event, processing it, and sending returns. The CLI on the master says "Minion did not return. [No response]".

2. When the minion is started and the 2nd master is up but the 1st master is down, the minion blocks on authing to the first master. Commands can't be sent from the 2nd master to the minion(s) because the minions haven't authenticated and are not receiving events.

ping @cachedout

**Comment by rallytime** [comment]
I can still reproduce this problem on my testing setup and it doesn't appear fixed. @cachedout Let's look at this again and see if I am just missing something.

**Comment by cachedout** [comment]
This does work but only if ```auth_retry``` and ```auth_timeout``` are dialed down from their original defaults. However, that has other (potentially serious) side effects, especially at scale.

**Comment by bernieke** [comment]
We need this functionality to work for the next release of our product next month, so I've forked the repository and made a branch off of the version we're currently using (2014.7.0)

I've had a go at fixing it on that branch. It works for us, but is obviously not ready to be merged. (For starters it doesn't touch the Syndic and Proxy cases since we don't use those, but without modifications to take into account the connected attribute as is done for the MultiMinion and Minion cases these are now probably broken.)

I'm just mentioning all this here in case anyone decides to take this ticket up and would like some inspiration.

The repository is on awingu/salt, the branch is called v2014.7.0-awingu, and this is the diff: https://github.com/saltstack/salt/compare/2014.7...Awingu:v2014.7.0-awingu

**Comment by cachedout** [comment]
@bernieke Very cool! Is your plan to contribute those changes back or just to provide them as inspiration for people who want to fix this upstream?

**Comment by bernieke** [comment]
It's just as inspiration. It works for our specific use case (both single and multi master that push to minions), and I'm sure it shouldn't take much to get it to work for the other use cases as well, provided you're already set up to quickly test all use cases.

But I work at a small startup, with 5 developers and short deadlines, so unfortunately I can't afford to spend the time necessary to set up an environment and test all available cases. (Let alone getting up to speed with the development and test practices the project uses.) The fact we're still on 2014.7.0 should tell you something here :)

**Comment by Ch3LL** [comment]
448

**Comment by bernieke** [comment]
This is fixed in 2015.8

**Comment by Ch3LL** [comment]
@bernieke i am still seeing this bug in 2015.8. Can you paste the output of the following command:
`salt --versions-report`
for you masters and a minion. 

Also have you changed any of the default values for the following configurations in your salt minion configuration file:
`auth_timeout`
`auth_tries`
If so can you paste the values as well. I also noticed that you created your own fork with a fix earlier. Are you possibly still using those same changes or fixes?

I will try to recreate your exact setup and see if I still see the bug based off of your responses.

**Comment by bernieke** [comment]
The possibly relevant bits of my minion config:
```
restart_on_error: true
auth_timeout: 15
random_reauth_delay: 15
auth_safemode: true
rejected_retry: true
auth_tries: 1
```

And in the master config:
```
failhard: true
timeout: 120
```

salt --versions-report:
```
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.22
           Mako: 0.9.0
         PyYAML: 3.11
          PyZMQ: 14.3.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-65-generic
         system: Ubuntu 14.04 trusty
```

I abandoned our fork of 2014.7 when we switched to 2015.8, I did have to make some new changes to get everything working, but these were accepted into 2015.8 and are now part of 2015.8.1

**Comment by Ch3LL** [comment]
@bernieke thanks I'll see if i can replicate your setup and post the results here

**Comment by Ch3LL** [comment]
@bernieke I was able to confirm that the bug is still present with default configurations but  when I set the following parameters on the minion:

`auth_timeout: 15`
`auth_tries: 1`
`auth_safemode: True`

It started working and the minions were not blocked anymore. Just as a note for anyone else looking at this issue, as @cachedout stated before, changing these parameters could have impact at scale. I will keep this bug open since in my opinion its not resolved, but this is definitely a workaround.

**Comment by Ch3LL** [comment]
ZD456

**Comment by cachedout** [comment]
All steps below apply to v2015.8.0.

OK, so this issue is slightly different that originally described. My test case is as follows:

1) Bring up a minion and point it at two masters. One of the masters should be up and the other master should be down (or non-existent). 

2) Verify that the minion can be reached from the master which is up.

3) Wait 30 seconds. Verify that the minion can no longer be reached from the original master.

Obviously, this is exceedingly bad, since it seems to indicate that a minion will eventually be unreachable from ALL masters if ANY masters go down.

To debug this issue, I added the following patch:

```
diff --git a/salt/minion.py b/salt/minion.py
index ae916fd..c8a04b0 100644
--- a/salt/minion.py
+++ b/salt/minion.py
@@ -603,6 +603,7 @@ class MultiMinion(MinionBase):
         self.max_auth_wait = self.opts['acceptance_wait_time_max']
 
         self.io_loop = zmq.eventloop.ioloop.ZMQIOLoop()
+        self.io_loop.set_blocking_log_threshold(1)
 
     def _spawn_minions(self):
         '''
```

This produces a stacktrace as follows: https://gist.github.com/cachedout/7f1ca341b624fcf0a338

As a result, it seems fairly clear that the issue in question is outlined in the ZeroMQ repo here: https://github.com/zeromq/pyzmq/issues/102

And adjusted for in other places in the Salt event system here: https://github.com/saltstack/salt/pull/2979

Thus far, I have tried multiple variations of adjusting the ZeroMQ linger in the AsyncZeroMQPubChannel class. I could find no value which did not eventually produce the above stacktrace indicating that the thread was blocked for greater than 1s and resulted in the minion being unreachable from the alive master.

An approach that _does_ work, however, is the following: https://gist.github.com/cachedout/4f7432f3549a1733e446

As evidenced in the ZeroMQ documentation this is _not_ threadsafe, however: https://zeromq.github.io/pyzmq/api/zmq.html#zmq.Context.destroy

The counterpoint to this is that we're closing the socket above it using the very call which the documentation warns against being thread safe, so I'm not sure that thread safety is really an issue here. (Though I could be wrong.)

So, I'm soliciting opinions on the above findings. Will using `destroy()` here be too aggressive? Why doesn't simply setting a linger option on the socket have the same effect? I would love to hear ideas:

cc: @s0undt3ch @thatch45 @jacksontj @plastikos @DmitryKuzmenko

**Comment by plastikos** [comment]
While libzmq starts multiple threads, I believe the thread safety question is about what is calling into libzmq.  So, to me, the question is about Salt being multi-*threaded*.  From everything I know Salt is a multi-*processing* design - consequently I don't think that the `destroy()` call is a problem.  Additionally, in newer libzmq, `zmq_ctx_destroy()` thunks directly to `zmq_ctx_term()`.  I have seen that there has been some new work to make libzmq more thread safe.

Yeah - that's some hand-waving that isn't definitive help.

**Comment by plastikos** [comment]
I'm also interested to know how certain you are that the linger value was being set on the AsyncZeroMQPubChannel?  With some of the work I've been doing with config files and opts being passed I don't trust that options get passed properly in older versions of Salt.  Hard-coding a value is the ticket for being sure.

**Comment by cachedout** [comment]
@plastikos I set the linger both in the init and in the __del__ with hard-coded values. Neither had the desired effect. I don't think this was a configuration value issue.

**Comment by plastikos** [comment]
Hmmm.  I'd like to watch the internals of libzmq with my instrumented version to see what is going on.  Unfortunately I'm not sure when I'd set those tests up.  Do you have a nice, contained test for this?

**Comment by cachedout** [comment]
@plastikos The steps to reproduce it are in the comment I left above: https://github.com/saltstack/salt/issues/21744#issuecomment-150335440. All that's needed is a single master and a single minion.

**Comment by DmitryKuzmenko** [comment]
My 5 cents: ZeroMQ workflow have to be the following:
* create context
* create socket
* work until get shutdown signal
* workers:
  * set socket linger
  * close socket
* master:
  * wait workers
  * terminate context

Here it looks we haven't close a socket somewhere.

**Comment by DmitryKuzmenko** [comment]
Caught it!
As I said we don't close the ZeroMQ socket. Will review all the zeromq transport layer and send PR in an hour or two.

**Comment by cachedout** [comment]
@DmitryKuzmenko Great! As you probably say in my comments, calling `destroy()` on the context will force-close the socket(s) but you may have an approach which is more selective. Looking forward to seeing what you come up with.

**Comment by DmitryKuzmenko** [comment]
Checked other zeromq channels, AsyncZeroMQPubChannel is the only one who doesn't close it's socket in some cases: when stream was never created.

**Comment by cachedout** [comment]
@Ch3LL Please see if you can verify the fix from @DmitryKuzmenko and we'll get this closed.

**Comment by Ch3LL** [comment]
Forgot to update this thread. Tests passed in 2015.8.0. :)

**Comment by DmitryKuzmenko** [comment]
Yes! Thank you @Ch3LL !

**Comment by usernkey** [comment]
Does this fix the failover or just the active-active ?

**Comment by Ch3LL** [comment]
@usernkey only active-active (master_type: str)

**Comment by usernkey** [comment]
is there any plan to fix it on the failover configuration ?

**Comment by Ch3LL** [comment]
@usernkey its definitely on our radar. There's a couple issues opened for multi-master failover that you can track here: #24243 #27152

Please confirm you are seeing the same problems reported in those issues. Thanks
