### ISSUE TITLE
When running the 2015.2 windows minion there are several import/namespace issues

### ISSUE THREAD

**Issue by polliard-jmfe** [saltstack/salt#21884]
There seems to be a collision with namespace or the imports are overriding site-libraries.  
The current active library problems are:
  - libnacl
  - six

There are more but taking these one at a time is going to be faster and more fruitful.  I can't even provide a detailed version report because of the issues.  

Trying to provide detailed 'version' information results in:
```
PS C:\salt> ./salt-call.bat --version
salt-call 2015.2.0-801-g1ef636c (Lithium)
```
```python
PS C:\salt> ./salt-call.bat --versions-report
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 222, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 20, in run
    self.parse_args()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 131, in parse_args
    self.print_versions_report()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 198, in print_versions_report
    print('\n'.join(version.versions_report()), file=file)
  File "C:\salt\bin\lib\site-packages\salt\version.py", line 574, in versions_report
    libs = list(versions_information(include_salt_cloud=include_salt_cloud))
  File "C:\salt\bin\lib\site-packages\salt\version.py", line 559, in versions_information
    imp = __import__(imp)
  File "C:\salt\bin\lib\site-packages\libnacl\__init__.py", line 75, in <module>
    nacl = _get_nacl()
  File "C:\salt\bin\lib\site-packages\libnacl\__init__.py", line 37, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium, tweetnacl
```
Original problem:
```python
File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 1528, in managed
    follow_symlinks)
  File "c:\salt\bin\lib\site-packages\salt\modules\file.py", line 3514, in manage_file
    ret, _ = check_perms(name, ret, user, group, mode, follow_symlinks)
  File "c:\salt\bin\lib\site-packages\salt\modules\file.py", line 3038, in check_perms
    if isinstance(orig_comment, six.string_types):
NameError: global name 'six' is not defined

2015-03-22 10:37:07,539 [salt.state       ][ERROR   ][4672] Unable to manage file: global name 'six' is not defined
```
I noticed that the six.py in the salt/ext/ is 1.8.0 and the version 'installed' in C:\salt\bin\lib\site-packages is 1.9.0.  libnacl is 1.4.2

**Comment by polliard-jmfe** [comment]
The libnacl issue is resolved.  Thanks to @UtahDave for pointing out that the libnacl is only needed if RAET is in use.  Windows Minion = ! RAET yet....  The six issues are still open and having grepped through the *.py files I don't see a missing import of salt.ext.six as six.  I'll keep looking.

**Comment by polliard-jmfe** [comment]
@UtahDave @twangboy  So I used to get an error when I didn't import pyOpenssl but importing that forces the six libraries to be pip installed.  What if any dependency needs the pyOpenssl.  The new dev_env.pl doesn't install the OpenSSL libraries anymore so maybe the pyOpenssl was an old requirement?

**Comment by UtahDave** [comment]
@polliard-jmfe Yeah, I'm not finding that odd six import either.  How did you install the Salt Minion? You might try removing Salt and installing from the latest 2015.2 branch. We fixed a few of these imports on Friday and that one may have been caught.

**Comment by twangboy** [comment]
OpenSSL is now included in Python 2.7.9. To test this, open a Python prompt and type the following:
>>>import ssl
>>>ssl.OPENSSL_VERSION
You should get the following:
'OpenSSL 1.0.1j 15 Oct 2014'

**Comment by deuscapturus** [comment]
Yep! SSL issues seem to be resolved with the requests library.  Thank you!

ssl.OPENSSL_VERSION -> OpenSSL 1.0.1j 15 Oct 2014
requests.certs.where() -> C:\salt\bin\lib\site-packages\requests\cacert.pem

**Comment by twangboy** [comment]
I just updated the script and zip files.

On Mon, Mar 23, 2015 at 5:01 PM, Theodore Cowan <notifications@github.com>
wrote:

> Yep! SSL issues seem to be resolved with the requests library. Thank you!
>
> ssl.OPENSSL_VERSION -> OpenSSL 1.0.1j 15 Oct 2014
> requests.certs.where() -> C:\salt\bin\lib\site-packages\requests\cacert.pem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/21884#issuecomment-85240413>.
>



-- 
*Shane Lee*
*Windows Platform Engineer*
Salt Stack, Inc.

Join us at SaltConf15 <http://www.saltconf.com/> - March 3-5, 2015 - Salt
Lake City

**Comment by deuscapturus** [comment]
running latest windows-dev environment script and pull from develop today I still see the error mentioned for this issue.

```
          ID: public-web
    Function: file.managed
        Name: d:\data\public-web-2015-03-25-08-57-08-15871.zip
      Result: False
     Comment: Unable to manage file: global name 'six' is not defined
     Started: 10:21:19.319000
    Duration: 113423.0 ms
     Changes:
```

```
Salt Version:
           Salt: 2015.2.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
            ZMQ: 4.0.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
       pycrypto: 2.6

System Versions:
           dist:
        machine: AMD64
        release: 2012Server
         system: 2012Server 6.2.9200  Multiprocessor Free
```

**Comment by twangboy** [comment]
I get this error when I apply a state file that copies a file to the minion. This problem only happens in the develop branch.

Here's the Error:
```
slee_win_2008r2_64:
----------
          ID: my_file
    Function: file.managed
        Name: c:\stuff1.txt
      Result: False
     Comment: Unable to manage file: global name 'six' is not defined
     Started: 14:06:19.498000
    Duration: 8.0 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

Here's the state file:
```
my_file:
  file.managed:
   - name: c:\stuff1.txt
   - contents: 'hello and a few other things world'
```

Here's the versions report:
```
 Salt Version:                                                                      
            Salt: 2015.2.0-836-ga32b375                                             
                                                                                    
 Dependency Versions:                                                               
          Jinja2: 2.7.3                                                             
        M2Crypto: 0.21.1                                                            
            Mako: Not Installed                                                     
          PyYAML: 3.11                                                              
           PyZMQ: 14.5.0                                                            
          Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
            RAET: Not Installed                                                     
             ZMQ: 4.0.5                                                             
           ioflo: Not Installed                                                     
         libnacl: Not Installed                                                     
    msgpack-pure: Not Installed                                                     
  msgpack-python: 0.4.5                                                             
        pycrypto: 2.6                                                               
                                                                                    
 System Versions:                                                                   
            dist:                                                                   
         machine: AMD64                                                             
         release: 2008ServerR2                                                      
          system: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free                     
```

**Comment by UtahDave** [comment]
@deuscapturus and @twangboy could you test this fix for this six issue?

https://github.com/saltstack/salt/pull/22045
