### ISSUE TITLE
pkgrepo.managed for APT systems creates duplicate entries

### ISSUE THREAD

**Issue by skrobul** [saltstack/salt#22412]
I needed to pre-configure APT repository that is always trusted. According to [the manual](http://manpages.ubuntu.com/manpages/precise/ja/man5/sources.list.5.html), this is done by specifying `trusted=yes` option after `deb` in the name. It is valid statement and it works perfectly with APT. Problem is, that salt creates this repository on every run.

Example state:

```
"my repo":
  pkgrepo.managed:
    - name: "deb [trusted=yes] http://apt.example.net/ binary/"
```
## Bug description

```
staging:/srv/salt# cat /etc/apt/sources.list
deb http://ftp.us.debian.org/debian wheezy main
deb-src http://ftp.us.debian.org/debian wheezy main
staging:/srv/salt#

staging:/srv/salt# salt-call --local state.sls example.sls
[...]
----------
          ID: strategic repo
    Function: pkgrepo.managed
        Name: deb [trusted=yes] http://apt.example.net/ binary/
      Result: True
     Comment: Configured package repo 'deb [trusted=yes] http://apt.example.net/ binary/'
     Started: 13:19:39.065776
    Duration: 12555.233 ms
     Changes:
              ----------
              repo:
                  deb [trusted=yes] http://apt.example.net binary/
[...]
staging:/srv/salt# cat /etc/apt/sources.list
deb http:[kk//ftp.us.debian.org/debian wheezy main
deb-src http://ftp.us.debian.org/debian wheezy main
deb [trusted=yes] http://apt.example.net binary/staging:/srv/salt#

```

Notice missing `\n` on the end. It's not the biggest problem, but if you run the state again, this is what you get:

```
staging:/srv/salt# cat /etc/apt/sources.list
deb http://ftp.us.debian.org/debian wheezy main
deb-src http://ftp.us.debian.org/debian wheezy main
deb [trusted=yes] http://apt.example.net binary/

deb [trusted=yes] http://apt.example.net binary/deb [trusted=yes] http://apt.example.net binary/staging:/srv/salt#
```

This obviously results in non-working repo. Is there any other way to specify APT repository options to avoid this bug?

**Comment by rallytime** [comment]
@skrobul Can you post the output of `salt --versions-report`?

**Comment by skrobul** [comment]
@rallytime: Sure:
```
staging:# salt-call --versions-report
                  Salt: 2014.7.2
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2014.7.2+ds-1~bpo70+1
staging:#
```

**Comment by rallytime** [comment]
Thanks @skrobul. I know we have some other bugs open in regards to pkgrepo.managed and apt, but I couldn't find any that were similar to this one. I don't know of a workaround offhand. If you remove the `[trusted=yes]` part, does it exhibit the same behavior?

**Comment by skrobul** [comment]
No, this does not happen when I don't provide any repo options. We are using standard pkgrepo managed in multiple places in our state tree and it works fine. 

Don't worry about workaround, I already found one. I just create file.managed with `'deb [trusted=yes]...'` line as a contents and drop it into `/etc/apt/sources.d/myrepo.list`.
While it's not exactly the same (it does not run apt-get update),  but it's good enough.

**Comment by rallytime** [comment]
@skrobul Thanks for the update and for posting that workaround.

**Comment by darkwyrm** [comment]
I have had a similar problem on 2014.7.5 which I believe is caused by the same bug. The SLS that I have seen the problem in has these contents:

clipgrab:
  pkgrepo:
    - managed
    - ppa: clipgrab-team/ppa
    - require_in:
      - pkg: clipgrab
  pkg:
    - latest

The result after the first run appends the word clipgrab to sources.list. If it runs a second time, without removing the buggy entry, it crashes with this crawl:

onyx:
----------
          ID: stdpkgs
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1542, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/pkg.py", line 711, in installed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pkg.py", line 151, in _find_install_targets
                  cur_pkgs = __salt__['pkg.list_pkgs'](versions_as_list=True, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 932, in list_pkgs
                  virtpkgs_all = _get_virtual()
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 164, in _get_virtual
                  apt_cache = apt.cache.Cache()
                File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 107, in __init__
                  self.open(progress)
                File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 155, in open
                  self._list.read_main_list()
              SystemError: E:Type 'clipgrab' is not known on line 2 in source list /etc/apt/sources.list
     Started: 08:01:54.864352
    Duration: 3783.788 ms
     Changes:   

Pardon me if I've broken protocol here, but I've never posted before... kinda new at this. I hope this helps find the bug.

**Comment by jthigpen** [comment]
Same thing continues to happen for me.

```
$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.0.0
                  RAET: Not Installed
                   ZMQ: 3.2.2
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1precise2
```

**Comment by jthigpen** [comment]
Our workaround:

```
# We use a file.managed instead of a pkgrepo.managed because pkgrepo.managed generates
# duplicate entries.
# https://github.com/saltstack/salt/issues/22412
gemfury-deb-repo:
  file.managed:
    - contents_pillar: gemfury:deb_url
    - contents_newline: True
    - name: /etc/apt/sources.list.d/gemfury.list
    - user: root
    - group: root
    - mode: 644

# pkgrepo.managed would run apt-get update for us, but since we're hacking around it
# we trigger it manually.
post-gemfury-refresh:
  cmd.wait:
    - name: apt-get update
    - watch:
      - file: gemfury-deb-repo
```

**Comment by CodingMinds** [comment]
Any updates on this issue ?

**Comment by rallytime** [comment]
The PR #45603 should fix this. Can anyone confirm?

**Comment by EHJ-52n** [comment]
This is still an issue for me using the following states:

```sls
office_signal_desktop:
  cmd.run:
    - name: wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > /usr/share/keyrings/signal-desktop-keyring.gpg
    - creates: /usr/share/keyrings/signal-desktop-keyring.gpg
    - require_in:
      - pkg: signal-desktop
  pkgrepo.managed:
    - humanname: Signal Desktop Repo
    - name: "deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main"
    - file: /etc/apt/sources.list.d/signal.list
    - key_url: https://updates.signal.org/desktop/apt/keys.asc
    - require_in:
      - pkg: signal-desktop
  pkg.latest:
    - name: signal-desktop
```

salt-version:

```shell
~/opt/salt (prod@local-repo ✗) sudo salt-call --versions-report
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 8.9.1
      dateutil: 2.8.1
     docker-py: 4.4.4
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: 1.1.0
      M2Crypto: 0.37.1
          Mako: 1.1.3
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.9.7
        pygit2: 1.4.0
        Python: 3.9.7 (default, Sep 10 2021, 14:59:43)
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 21.10 impish
        locale: utf-8
       machine: x86_64
       release: 5.13.0-40-generic
        system: Linux
       version: Ubuntu 21.10 impish
```

When applying the states twice:

```shell
----------
          ID: office_signal_desktop
    Function: cmd.run
        Name: wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > /usr/share/keyrings/signal-desktop-keyring.gpg
      Result: True
     Comment: /usr/share/keyrings/signal-desktop-keyring.gpg exists
     Started: 10:44:49.597770
    Duration: 268.283 ms
     Changes:   
----------
          ID: office_signal_desktop
    Function: pkgrepo.managed
        Name: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
      Result: True
     Comment: Configured package repo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main'
     Started: 10:44:49.866173
    Duration: 3318.331 ms
     Changes:   
----------
          ID: office_signal_desktop
    Function: pkg.latest
        Name: signal-desktop
      Result: True
     Comment: Package signal-desktop is already up-to-date
     Started: 10:44:53.185009
    Duration: 70.904 ms
     Changes:   

Summary for local
-------------
Succeeded: 33
Failed:     0
-------------
Total states run:     33
Total run time:    9.254 s
     1  deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
     2  deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial maindeb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial maindeb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main%
[...]
Summary for local
-------------
Succeeded: 33
Failed:     0
-------------
Total states run:     33
Total run time:    8.991 s
     1  deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
     2  deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial maindeb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial maindeb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial maindeb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main%
```
