### ISSUE TITLE
Master-of-Master doesn't catch returns from Syndic Master

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#23233]
We have one top-level Master to which are connected ~1,000 minions and one Salt-Syndic master, which is handling just an additional 6 minions from a separate environment. The Syndic Master can communicate fine with its own minions, but when the top-level Master sends a command to the minions connected to the Syndic Master, it doesn't register any returns.

The following log is from the salt-syndic process on the syndic master. You can see that it receives the command from the top-level master, successfully passes it to the local master, receives the returns from the minions and claims to be forwarding the events back to the top-level master, but on the top-level master itself, these returns are never seen. The top-level master sends out the follow-up "find_job" commands, which are also received passed to the minions by the syndic, the minions reply to it, and the top-level master never gets those replies.

Top-Level Master --

```
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.5+ds-1ubuntu1
```

Salt-Syndic Master --

```
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.5+ds-1ubuntu1
```

```
[TRACE   ] Handling payload
[DEBUG   ] User root Executing syndic command test.ping with jid 20150430123709158622
[DEBUG   ] Command details: {'tgt_type': 'glob', 'jid': '20150430123709158622', 'tgt': 'SEC*', 'ret': '', 'to': 14, 'user': 'root', 'arg': [], 'fun': 'test.ping'}
[TRACE   ] Polling timeout: 1.000000
[TRACE   ] Got event 20150430123709158622
[TRACE   ] Got event new_job
[TRACE   ] Got event salt/job/20150430123709158622/new
[TRACE   ] Polling timeout: 0.499381
[TRACE   ] Got event salt/auth
[TRACE   ] Polling timeout: 0.041568
[TRACE   ] Got event salt/auth
[TRACE   ] Polling timeout: 0.040812
[TRACE   ] Got event salt/auth
[TRACE   ] Polling timeout: 0.017950
[TRACE   ] Polling timeout: 0.000525
[TRACE   ] Polling timeout: 0.000264
[TRACE   ] Polling timeout: 0.000036
[TRACE   ] Forwarding events
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[TRACE   ] Polling timeout: 1.000000
[TRACE   ] Got event 20150430123709158622
[DEBUG   ] LazyLoaded mysql.get_load
[TRACE   ] Got event salt/job/20150430123709158622/ret/SEC-OEM-HTXXX12
[TRACE   ] Got event 20150430123709158622
[TRACE   ] Got event salt/job/20150430123709158622/ret/SEC-OEM-HTMXX12
[TRACE   ] Polling timeout: 0.494357
[TRACE   ] Got event 20150430123709158622
[TRACE   ] Polling timeout: 0.456572
[TRACE   ] Got event salt/job/20150430123709158622/ret/SEC-OEM-HTRXX12
[TRACE   ] Polling timeout: 0.455761
[TRACE   ] Forwarding events
[INFO    ] Returning information for job: 20150430123709158622
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[TRACE   ] ret_val = 
[TRACE   ] Polling timeout: 1.000000
[TRACE   ] Got event salt/auth
[TRACE   ] Polling timeout: 0.499934
[TRACE   ] Polling timeout: 0.000023
[TRACE   ] Forwarding events
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[TRACE   ] Polling timeout: 1.000000
```

**Comment by rallytime** [comment]
Thanks for this report @V3XATI0N. When you say that the "returns are never seen", do mean the Top-Level-Master never receives the return in the logs and just continually sends out "find job" commands until it times out, or you're not seeing minions return on the command line?

Also, just to be sure, you have `order_masters: True` set in the Top-Level-Master's `/etc/salt/master` file and then the `syndic_master: <ip>` option set on the Syndic Master's `/etc/salt/master` file as well, correct?

**Comment by V3XATI0N** [comment]
The replies do not appear in the Master's logs. The config options are set
as you mention on both Master and Syndic. The same configuration was
working well in 2014.7.1, there has been no change to the conf files.

**Comment by rallytime** [comment]
Thanks for the extra info here. Anything else of use that I might be able to try and reproduce this with? Maybe what OSes the Top Master and Syndic Master are running on?

**Comment by V3XATI0N** [comment]
Both top master and syndic master are Ubuntu 14.04.2

**Comment by jeanneret** [comment]
Hi I got the same problem on Debian...
Do you got a solution?

**Comment by rallytime** [comment]
@jeanneret Doesn't look like anyone has had a chance to look at this yet. Can you also post your versions report? Are you guys still seeing this on newer versions of salt (current stable is 2015.5.1)?

**Comment by V3XATI0N** [comment]
The problem does still occur with 2015.5, yes.

**Comment by markTward** [comment]
Our topology moved to one where we require syndics and hoped to target their minions through the master-of-master running salt-api.  I can confirm that no results are returned with correct configuration values set as described.  

I first reported this issue today first here: https://github.com/saltstack/salt/issues/9141

We're running ubuntu 14.04 and salt 2015.5.1 on master, syndics and minions

salt-master --versions-report
           Salt: 2015.5.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed

**Comment by cachedout** [comment]
Likely fixed by https://github.com/saltstack/salt/pull/33021

**Comment by dpetre** [comment]
@cachedout #33021 doesn't seem to fix this one. We're using salt 2015.8.10 which has the changes in #33021 and the issue is still present.

**Comment by faelin** [comment]
This issue does not appear to have been resolved, as I am experiencing the same problem. Please reopen this thread.

**Comment by mconnley** [comment]
Any updates on this issue?

**Comment by rallytime** [comment]
@Ch3LL or @garethgreenaway Can one of you reopen this?
