### ISSUE TITLE
log output of salt orchestrate run changed between 2014.7.5 and 2015.5.0 significantly - hard to debug

### ISSUE THREAD

**Issue by hoonetorg** [saltstack/salt#23789]
see difference:
2014.7.5: https://gist.github.com/anonymous/c81f4445c5c94f9ed0f5

2015.5.0: https://gist.github.com/anonymous/41f6b28cecde6cef5129

System CentOS 7.1:
Salt packages from EPEL (2015-05-15)

On master:
```console
[root@hperhlws0802 orchestration]# rpm -qa |grep salt 
salt-2015.5.0-1.el7.noarch
salt-master-2015.5.0-1.el7.noarch
salt-minion-2015.5.0-1.el7.noarch
```
Difficult to debug, because , 
1. Output is not ordered in the order of execution
2. Some information is missing
3. I'm generally missing some output of some orchestration states (probably I oversee because of the reordering)

P.S.: Me feeling they are reordered by name of orchestration state

**Comment by rallytime** [comment]
Thanks for the report @hoonetorg. I am not super familiar with using the orchestrate state, but I bet @whiteinge might have some good input here.

**Comment by whiteinge** [comment]
The orchestrate output is not getting run through the `highstate`
outputter in that gist. That is a definite bug and regression. There
was a similar regression in the jobs runner for
state.highstate/state.sls output in 2015.2. It may be related to the
switch to event-based runners.

**Comment by hoonetorg** [comment]
thanks for the quick answer.
I'm happy to test a patch on my environment, once available.

**Comment by ivan-californias** [comment]
Same problem over here.

To get a work around I am running salt-run command like this:
```
salt-run --out=highstate state.orchestrate
```
but I am getting a little bit different output, I mean in previous version I would gotten the stderr or stdout, but now I am just getting that the state failed and the result, like this:
```
                  ----------
                            ID: apache
                      Function: service.running
                        Result: False
                       Comment: Service apache is already enabled, and is dead
                       Started: 16:54:12.805440
                      Duration: 556.212 ms
                       Changes:   
                  apache:
                      False
                  ----------
```
When state is cmd.run I am getting just the PID, like this
```
                  ----------
                            ID: db-create-testdb
                      Function: cmd.run
                          Name: sudo -u postgres createdb --encoding=LATIN1 testdb
                        Result: False
                       Comment: Command "sudo -u postgres createdb --encoding=LATIN1 testdb" run
                       Started: 16:52:15.816972
                      Duration: 65.04 ms
                       Changes:   
                  pid:
                      8242
                  ----------
```

This makes it hard to debug as the issue tells. I'd also be happy to test a patch. Thanks in advance.

**Comment by cachedout** [comment]
This is a core bug, not a platform bug. Re-labeling.

**Comment by arthurlogilab** [comment]
affected by this too. interrested in the fix.

**Comment by anitakrueger** [comment]
+1 we use the orchestrate runner quite extensively and after updating to 2015.5.3 and I can't find what happens to my states and functions anymore

**Comment by multani** [comment]
Same here, and @ivan-californias workaround (using ``--out highstate``) doesn't work, I still get the same output.

**Comment by basepi** [comment]
Question for anyone for whom `--out=highstate` is not working: when you pass in that extra option, are you seeing any errors in the logs? If that addition doesn't work, it usually means that the highstate outputter is erroring out in some way, and seeing the error in the log will be useful in tracking down the source.

**Comment by anitakrueger** [comment]
@basepi It looks like this is fixed in 2015.8.3 because I am not using the highstate outputter anymore and orchestration outputs look good. In fact, then I use ```--out=highstate``` the orchestration borks.

**Comment by basepi** [comment]
Strange! If it's already using the highstate outputter, explicitly telling it to use the highstate outputter shouldn't hurt anything.... Glad to hear it's fixed for you, though.

**Comment by basepi** [comment]
I fixed a couple of errors in #30756. Not sure if it will fix all issues, but I'm happy to look at additional stacktraces in the highstate outputter if anyone can provide them.

**Comment by anitakrueger** [comment]
Hi @basepi, I just tried one of my orchestration states with explicitly specifying ```--out=highstate``` and got the following stacktrace:
```
2016-02-01 14:13:28,361 [salt.output                                         ][ERROR   ] Nested output failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 43, in try_printout
    return get_printout('nested', opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in _format_host
    key=lambda k: data[k].get('__run_num__', 0)):
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in <lambda>
    key=lambda k: data[k].get('__run_num__', 0)):
AttributeError: 'str' object has no attribute 'get'
2016-02-01 14:13:28,384 [salt.output                                         ][ERROR   ] Nested output failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 43, in try_printout
    return get_printout('nested', opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in _format_host
    key=lambda k: data[k].get('__run_num__', 0)):
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in <lambda>
    key=lambda k: data[k].get('__run_num__', 0)):
AttributeError: 'str' object has no attribute 'get'
2016-02-01 14:13:28,389 [salt.output                                         ][ERROR   ] Nested output failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 43, in try_printout
    return get_printout('nested', opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 139, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 408, in _format_changes
    s, c = _format_host(host, hostdata)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 139, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 423, in _format_changes
    __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 164, in out_format
    return try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout('raw', opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in _format_host
    key=lambda k: data[k].get('__run_num__', 0)):
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in <lambda>
    key=lambda k: data[k].get('__run_num__', 0)):
AttributeError: 'str' object has no attribute 'get'
2016-02-01 14:13:28,404 [salt.output                                         ][ERROR   ] Nested output failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 43, in try_printout
    return get_printout('nested', opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in _format_host
    key=lambda k: data[k].get('__run_num__', 0)):
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in <lambda>
    key=lambda k: data[k].get('__run_num__', 0)):
AttributeError: 'str' object has no attribute 'get'
2016-02-01 14:13:28,967 [salt.log.setup                                      ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 354, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 41, in run
    runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 181, in run
    False)  # Don't daemonize
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 407, in _proc_function
    return self.low(fun, low)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 350, in low
    namespaced_event.fire_event(data, 'ret')
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 700, in fire_event
    self.print_func(tag, data)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 482, in print_async_event
    salt.output.display_output(event_data, outputter, self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 86, in display_output
    display_data = try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout('raw', opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 139, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 408, in _format_changes
    s, c = _format_host(host, hostdata)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 139, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 423, in _format_changes
    __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 164, in out_format
    return try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout('raw', opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in _format_host
    key=lambda k: data[k].get('__run_num__', 0)):
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in <lambda>
    key=lambda k: data[k].get('__run_num__', 0)):
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 354, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 41, in run
    runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 181, in run
    False)  # Don't daemonize
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 407, in _proc_function
    return self.low(fun, low)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 350, in low
    namespaced_event.fire_event(data, 'ret')
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 700, in fire_event
    self.print_func(tag, data)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 482, in print_async_event
    salt.output.display_output(event_data, outputter, self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 86, in display_output
    display_data = try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout('raw', opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 139, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 408, in _format_changes
    s, c = _format_host(host, hostdata)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 139, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 423, in _format_changes
    __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 164, in out_format
    return try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout('raw', opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in _format_host
    key=lambda k: data[k].get('__run_num__', 0)):
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 131, in <lambda>
    key=lambda k: data[k].get('__run_num__', 0)):
AttributeError: 'str' object has no attribute 'get'
```

Running the same orchestration without the additional outputter, works fine.
But...it looks like the orchestration worked. It just threw the stacktrace.

For reference, here's my versions-report:
```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.4
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.8.0-38-generic
         system: Ubuntu 12.04 precise
```

**Comment by basepi** [comment]
Thanks, the stacktrace is helpful. And yes, the orchestration was successful, it's just stacktracing on output.

**Comment by basepi** [comment]
@anitakrueger would you mind sending me the output without `--out=highstate` for that state run? There's an anomaly in the formatting of the data and I want to track it down before I slap a bandaid on it, because I'm not sure under what circumstances this anomaly would happen.

**Comment by anitakrueger** [comment]
This is the output without ```--out==highstate``` (I changed the name of the salt master):
```
salt.example.com_master:
  Name: apt-mirror - Function: salt.state - Result: Changed
  Name: salt-master-versions - Function: salt.state - Result: Changed
  Name: state.highstate - Function: salt.function - Result: Changed

Summary for salt.example.com_master
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total run time:  54.426 s
```
Not much there...

The debug log constantly shows that it's reloading the highstate outputter...
```
2016-02-01 14:13:28,368 [salt.utils.lazy                                     ][DEBUG   ] LazyLoaded highstate.output
2016-02-01 14:13:28,370 [salt.utils.lazy                                     ][DEBUG   ] LazyLoaded highstate.output
2016-02-01 14:13:28,374 [salt.utils.lazy                                     ][DEBUG   ] LazyLoaded highstate.output
2016-02-01 14:13:28,380 [salt.utils.lazy                                     ][DEBUG   ] LazyLoaded highstate.output
```

**Comment by basepi** [comment]
Interesting! It appears the summary output is tripping it up. I will look at this more closely when I get a chance.

**Comment by multani** [comment]
I noticed that if I have the following orchestration step, I got the garbled output as reported by OP in the first post, but if I remove the step, I get the "right" output:
```
Refresh everything:
  salt.function:
    - tgt: "*"
    - name: saltutil.sync_all
```

**Comment by tristianc** [comment]
I am using Salt 2015.8.8.

I no longer have to use the --out=highstate flag in order to get the orchestration output as formatted in: [https://gist.github.com/anonymous/c81f4445c5c94f9ed0f5](https://gist.github.com/anonymous/c81f4445c5c94f9ed0f5). This has been possibly fixed?

In fact, if I use the --out=highstate flag while applying orchestration states, I run into #29796

**Comment by rallytime** [comment]
@tristianc Thank you for the update. The issue you mentioned you're hitting in #29796 is fixed at the HEAD of the 2015.8 branch and will be included in the upcoming 2015.8.9 release. I'd love to hear if this is all resolved for you if/when you get a chance to test it.

**Comment by multani** [comment]
I'm still facing this issue with 2015.8.10 (?):

```
$ cat states/test.sls
Refresh everything:
  salt.function:
    - tgt: 'test*'
    - name: saltutil.sync_all

$ sudo salt-run state.orchestrate --out=highstate test
salt-master_master:
    ----------
    salt_|-Refresh everything_|-saltutil.sync_all_|-function:
        ----------
        __run_num__:
            0
        changes:
            ----------
            out:
                highstate
            ret:
                ----------
                test1:
                    ----------
                    beacons:
                    grains:
                    log_handlers:
                    modules:
                    output:
                    proxymodules:
                    renderers:
                    returners:
                    sdb:
                    states:
                    utils:
        comment:
            Function ran successfully. Function saltutil.sync_all ran on test1.
        duration:
            1700.319
        name:
            saltutil.sync_all
        result:
            True
        start_time:
            11:18:18.389249
$ sudo salt-run state.orchestrate test
salt-master_master:
    ----------
    salt_|-Refresh everything_|-saltutil.sync_all_|-function:
        ----------
        __run_num__:
            0
        changes:
            ----------
            out:
                highstate
            ret:
                ----------
                test1:
                    ----------
                    beacons:
                    grains:
                    log_handlers:
                    modules:
                    output:
                    proxymodules:
                    renderers:
                    returners:
                    sdb:
                    states:
                    utils:
        comment:
            Function ran successfully. Function saltutil.sync_all ran on test1.
        duration:
            1352.89
        name:
            saltutil.sync_all
        result:
            True
        start_time:
            11:18:25.816269
```

It also happens with other functions, but not all.

For example, this one produces a good output:
```
test run:
  salt.function:
    - tgt: 'test*'
    - name: cmd.run
    - kwarg:
        cmd: id
```

But this one produces a garbled output (some kind as above):
```
test script:
  salt.function:
    - tgt: 'test*'
    - name: cmd.script
    - kwarg:
        source: salt://id.sh
```

(with ``id.sh`` being 
```
#!/bin/sh
id
```
)
