### ISSUE TITLE
Some documentation code blocks are not rendered correctly

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#23793]
It looks like yaml and bash are okay (http://docs.saltstack.com/en/latest/topics/best_practices.html), but the python code block (such as here: http://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.py.html) do not render correctly. I'm mentioning @christabor since he originally implemented it, but I'm not sure what would have broken it with the new design.

**Comment by rallytime** [comment]
Thanks @gravyboat.

ping @jacobhammons

**Comment by gravyboat** [comment]
@jacobhammons This is the same issue you and I discussed on Friday, I just forgot to tag you. Thanks @rallytime!

**Comment by nmadhok** [comment]
@gravyboat @rallytime It looks exactly like it looked before so i'm not sure what you meant by "what would have broken it with the new design". This is how it looked before:

![screen shot 2015-05-19 at 10 38 10 am](https://cloud.githubusercontent.com/assets/3374962/7705591/33603ee0-fe13-11e4-8df2-b39da58bb7bc.png)

This is how it looks now:

![screen shot 2015-05-19 at 10 39 40 am](https://cloud.githubusercontent.com/assets/3374962/7705634/6a370624-fe13-11e4-96b6-00bda880cdf7.png)

Why do you think it's broken? Is it because of the line numbers you see?

**Comment by rallytime** [comment]
@nmadhok Interesting...I don't have a screen shot to prove it, but I never saw the "Python" (or whatever code-block name is present) outside of the gray code-block box on the old site. The blue Python code-block label should be inside the gray area, lined up with the borders. (It must have been a bug for you, and maybe others, on the old site and we should definitely fix this on the new site.)

**Comment by jacobhammons** [comment]
I pushed a fix for this, you might need to refresh to see it.

**Comment by rallytime** [comment]
Aye, LGTM @jacobhammons! What say you, @gravyboat and @nmadhok?

**Comment by gravyboat** [comment]
Looks better to me as well @jacobhammons, thanks! @nmadhok as @rallytime said at one point that was rendering correctly, good to know it was still broken on the old version as well though.

**Comment by nmadhok** [comment]
@jacobhammons @rallytime @gravyboat Seems like this has been fixed! I think it'll be a good idea to link the Pull Request to the issue it fixes so that it's easier to find out what the fix for the issue was.

**Comment by gravyboat** [comment]
Going to close this. Thanks!
