### ISSUE TITLE
Problems disabling a service in SLES11 SP3.

### ISSUE THREAD

**Issue by dumol** [saltstack/salt#23971]
The problematic state tries to disable firewalls on some OS'es and works perfectly for everything we have, except SLES 11 SP3. We use `service.dead` and then require it in another state. The current incarnation is:
```salt
#
# State for disabling firewall when not necessary and interfering with 
# our stuff, eg. zabbix-agent. For now just for RHEL/CentOS 7 and SLES.
#

{% if grains['os_family'] == 'RedHat' and grains['osrelease'].startswith('7') %}
    {% set firewall_service_name = 'firewalld' %}
{% elif grains['osfullname'] == 'SLES' %}
    {% if grains['osrelease'].startswith('11') %}
        {% set firewall_service_name = 'SuSEfirewall2_setup' %}
    {% else %}
        {% set firewall_service_name = 'SuSEfirewall2' %}
    {% endif %}
{% else %}
    # Required for minions with no firewall to disable.
    {% set firewall_service_name = 'aFakeNameToPleaseSalt' %}
{% endif %}

Disable firewall:
  service.dead:
    - name: {{firewall_service_name}}
    - enable: False
```
Salt minion version 2015.5.0 (Lithium) running on  SLES 11 SP 3 (still supported by SUSE) returns:
```python-traceback
          ID: Disable firewall
    Function: service.dead
        Name: aFakeNameToPleaseSalt
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib64/python2.6/site-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
                  self.gen.throw(type, value, traceback)
                File "/usr/lib64/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
                  yield
                File "/usr/lib64/python2.6/site-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib64/python2.6/site-packages/salt/states/service.py", line 327, in dead
                  ret.update(_disable(name, None, **kwargs))
                File "/usr/lib64/python2.6/site-packages/salt/states/service.py", line 164, in _disable
                  if __salt__['service.disabled'](name):
                File "/usr/lib64/python2.6/site-packages/salt/modules/rh_service.py", line 498, in disabled
                  return not _sysv_is_enabled(name)
                File "/usr/lib64/python2.6/site-packages/salt/modules/rh_service.py", line 144, in _sysv_is_enabled
                  result = _chkconfig_is_enabled(name, runlevel)
                File "/usr/lib64/python2.6/site-packages/salt/modules/rh_service.py", line 162, in _chkconfig_is_enabled
                  cols = result['stdout'].splitli
```
This seems to partly be a rehash of https://github.com/saltstack/salt/issues/4315, because I can fix the error if I replace in `salt/modules/rh_service.py` this:
```python
    cmdline = '/sbin/chkconfig --list {0}'.format(name)
    result = __salt__['cmd.run_all'](cmdline, python_shell=False)
```
with this:
```python
    cmdline = '/sbin/chkconfig --list {0} | grep "0:off"'.format(name)
    result = __salt__['cmd.run_all'](cmdline, python_shell=True)
```
taking into account that xinetd-related lines look like this
```salt
xinetd based services:
        chargen:            off
```
while the lines that we want look like this:
```
SuSEfirewall2_setup       0:off  1:off  2:off  3:off  4:off  5:off  6:off
```
I guess it's a safe assumption that all services we want to check are off in level 0.

With the above change, I get no errors. The output on the minion for `salt --versions-report`:
```yaml
           Salt: 2015.5.0
         Python: 2.6.8 (unknown, May 29 2012, 22:30:44)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by dumol** [comment]
A version that works on SLES11 SP3 too, but looks repetitive:
```
{% if grains['os_family'] == 'RedHat' and grains['osrelease'].startswith('7') %}

Disable firewall:
  service.dead:
    - name: firewalld
    - enable: False

{% elif grains['osfullname'] == 'SLES' %}

{% if grains['osrelease'] == '12' %}
Disable firewall:
  service.dead:
    - name: SuSEfirewall2
    - enable: False
{% else %}
Disable firewall:
  service.dead:
    - name: SuSEfirewall2_setup
    - enable: False
{% endif %}

{% else %}

# Required for minions not running on RedHat/CentOS.
Disable firewall:
  service.dead:
    - name: JustAFakeNameToPleaseSalt
    - enable: False

{% endif %}
```

**Comment by jfindlay** [comment]
@dumol, thanks for the report.

**Comment by jfindlay** [comment]
@dumol, this is fixed in #28891.

**Comment by dumol** [comment]
Thanks for working on this! But sorry, it still doesn't work for me… The error I get from the SLES 11 minion using your RPM package version 2015.8.7-228.5 when applying the aforementioned state:

          ID: Disable firewall
    Function: service.dead
        Name: SuSEfirewall2_setup
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib64/python2.6/site-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/lib64/python2.6/site-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib64/python2.6/site-packages/salt/states/service.py", line 379, in dead
                  before_toggle_enable_status = __salt__['service.enabled'](name)
                File "/usr/lib64/python2.6/site-packages/salt/loader.py", line 900, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/usr/lib64/python2.6/site-packages/salt/utils/lazy.py", line 93, in __getitem__
                  raise KeyError(key)
              KeyError: 'service.enabled'
     Started: 11:16:30.517291
    Duration: 607.646 ms
     Changes:   

The relevant lines in the debug seem to be:
```
2016-03-28 11:16:30,600 [salt.loader                                            ][ERROR   ][13727] Exception raised when processing __virtual__ function for rh_service. Module will not be loaded local variable 'osrelease' referenced before assignment
2016-03-28 11:16:30,600 [salt.loader                                            ][WARNING ][13727] salt.loaded.int.module.rh_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'rh_service', please fix this.
2016-03-28 11:16:30,601 [salt.loader                                            ][DEBUG   ][13727] Error loading module.rh_service: Exception raised when processing __virtual__ function for rh_service. Module will not be loaded local variable 'osrelease' referenced before assignment
```
Here are the full debug logs for invoking the state: https://gist.github.com/dumol/691e06e156b1a545f8dc

**Comment by dumol** [comment]
And a dirty fix for our SLES 11 minion:
```
--- /usr/lib64/python2.6/site-packages/salt/modules/rh_service.py.orig  2016-03-28 13:59:14.000000000 +0300
+++ /usr/lib64/python2.6/site-packages/salt/modules/rh_service.py       2016-03-28 13:57:11.000000000 +0300
@@ -61,7 +61,7 @@
         if __grains__['os'] == 'XenServer':
             return __virtualname__
         try:
-            osrelease = float(__grains__.get('osrelease', 0))
+            osrelease = 11.0 #float(__grains__.get('osrelease', 0))
         except ValueError:
             return (False, 'Cannot load rh_service module: '
                            'osrelease grain, {0}, not a float,'.format(osrelease))
```

**Comment by dumol** [comment]
I've retested this with the upstream `salt-minion-2015.8.10-76.12`  package and the problem doesn't reproduce any more in SLES 11. Thanks!
