### ISSUE TITLE
Salt not working anymore in 2015.8/develop: ValueError: 'scope' is not in list

### ISSUE THREAD

**Issue by lichtamberg** [saltstack/salt#25268]
Upgraded to 2015.8 (from 2015.5, which works)... Same problem with develop branch:
No salt-call works anymore (no salt-ssh, salt-cloud,...), not even salt --versions-report:

```
=> salt --versions-report

Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 269, in salt_ssh
    client = salt.cli.ssh.SaltSSH()
  File "/usr/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 128, in __init__
    optparse.OptionParser.__init__(self, *args, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1220, in __init__
    add_help=add_help_option)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 204, in _populate_option_list
    mixin_setup_func(self)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 1014, in _mixin_setup
    config.minion_config(None)
  File "/usr/local/lib/python2.7/site-packages/salt/config.py", line 1415, in minion_config
    opts = apply_minion_config(overrides, defaults, cache_minion_id=cache_minion_id)
  File "/usr/local/lib/python2.7/site-packages/salt/config.py", line 2504, in apply_minion_config
    cache_minion_id=cache_minion_id)
  File "/usr/local/lib/python2.7/site-packages/salt/config.py", line 2473, in get_id
    newid = salt.utils.network.generate_minion_id()
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 275, in generate_minion_id
    for addr in salt.utils.network.ip_addrs():
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 969, in ip_addrs
    return _ip_addrs(interface, include_loopback, interface_data, 'inet')
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 944, in _ip_addrs
    else interfaces()
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 760, in interfaces
    return linux_interfaces()
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 647, in linux_interfaces
    salt.utils.to_str(cmd2)))
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 508, in _interfaces_ip
    ipaddr, netmask, broadcast, scope = parse_network(value, cols)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 480, in parse_network
    scope = cols[cols.index('scope') + 1]
ValueError: 'scope' is not in list
```

**Comment by cachedout** [comment]
Probably related to this: edce034e

What network interfaces do you have configured on your machine?

**Comment by lichtamberg** [comment]
Yeah, its exactly this commit i think...

```
eth0      Link encap:Ethernet  HWaddr 00:aa:aa:aa:aa:aa
          inet addr:100.123.233.21  Bcast:100.113.213.255  Mask:255.255.254.0
          inet6 addr: fe80::20a:2aff:fe21:f02f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:207678 errors:0 dropped:0 overruns:0 frame:0
          TX packets:79541 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:245456789 (245.4 MB)  TX bytes:14405391 (14.4 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:7716 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7716 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2606569 (2.6 MB)  TX bytes:2606569 (2.6 MB)
```

**Comment by lichtamberg** [comment]
Looks like line 480 should be something like this (but I'm not a python/salt expert :)), because on my machine scope is written with big "S"..

```
scope = cols[cols.lower().index('scope') + 1]
```

**Comment by jleroy** [comment]
Hi @lichtamberg,

Can you post the output of the following commands : 
`ip link show`

`ip addr show`

Thanks.

**Comment by lichtamberg** [comment]
Sure, thanks for the quick reply: 

```shell
root@mytest:~$ ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:0d:3c:2a:f0:2f brd ff:ff:ff:ff:ff:ff

root@mytest:~$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:21:f0:2f brd ff:ff:ff:ff:ff:ff
    inet 100.123.118.21/23 brd 120.123.239.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20b:3afd:fe21:f02f/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by jleroy** [comment]
I haven't managed to reproduce this issue, but I've fixed it in #25274.

**Comment by lichtamberg** [comment]
Great! Thanks! With this patch everything works fine again!

**Comment by rallytime** [comment]
Thanks for the fix here @jleroy. @lichtamberg is this issue ok to close?

**Comment by lichtamberg** [comment]
Sure, if it gets merged :D

Thanks for the great work guys!

**Comment by rallytime** [comment]
Nice! I just merged it. Thanks!

**Comment by lichtamberg** [comment]
Works fine now in 2015.8, but in develop i still get this error?

**Comment by rallytime** [comment]
@lichtamberg My guess it is likely has gotten all of the way into develop yet via a merge-forward: https://github.com/saltstack/salt/blob/ba4877d71a3e0c42bfb320b3972fef18fa84dedc/salt/utils/network.py#L479

If this is still broken after the next merge-forward from 2015.8 to develop, then we can apply this patch directly.

**Comment by lichtamberg** [comment]
Ah ok! Thanks!
