### ISSUE TITLE
Batch mode - some minion's result missing in output

### ISSUE THREAD

**Issue by ze42** [saltstack/salt#26254]
Tested versions, with same behaviours:
- 2015.5.3 (debian package)
- git v2015.5.3
- git v2015.8.0rc3
- git develop (commit: eca42b1 from Wed Aug 12 09:20:54 2015 -0600)

Testing with just test.version as command, the batch mode seems to "miss" some results.

Since some time (was not in 2014.7, but is present in 2015.5), batch mode tends to relaunch the missing amount of minions when a few sent their results. That's nice to not wait for _everyone_ to finish before launching the next ones, but unfortunately, it fails to get all results, making it much harder to use.

Calling it directly gives a fast answer right away:

```
# time salt '*' test.version
minion00:
    2015.8.0rc3
minion01:
    2015.8.0rc3
minion07:
    2015.8.0rc3
minion05:
    2015.8.0rc3
minion08:
    2015.8.0rc3
minion02:
    2015.8.0rc3
minion06:
    2015.8.0rc3
minion09:
    2015.8.0rc3
minion03:
    2015.8.0rc3
minion04:
    2015.8.0rc3

real    0m2.626s
user    0m0.140s
sys     0m0.128s
```

But calling it in batch mode can lead to missing answers:

```
# time salt -b 3 --out=yaml --out-file=/tmp/versions '*' test.version

Executing run on ['minion09', 'minion08', 'minion01']


Executing run on ['minion00', 'minion03']


Executing run on ['minion02']


Executing run on ['minion05']


Executing run on ['minion04']


Executing run on ['minion07']


Executing run on ['minion06']


real    0m22.795s
user    0m0.272s
sys     0m0.156s
```

With output file:

```
minion08: 2015.8.0rc3
retcode: 0
minion01: 2015.8.0rc3
retcode: 0
minion09: 2015.8.0rc3
retcode: 0
minion03: 2015.8.0rc3
retcode: 0
minion00: 2015.8.0rc3
retcode: 0
minion02: {}
minion05: {}
minion04: {}
minion07: {}
minion06: {}
```

Some minions with "missed" result gives an empty dict, rather than having a retcode and the version.

Checking jobs, they did get reply pretty fast, but were ignored.

Easily reproduced with a small amount of minions, just need to batch with more than 1, and less then all. Might need to run it multiple time to have the buggy behaviour.

**Comment by ze42** [comment]
Note: if test.version tends to reply too fast, you can also try to use some more random delay, like:

```
salt -b 3 '*' cmd.run 'sleep $(echo "(1 + $RANDOM % 30) / 10" | bc) ; date'
```

**Comment by jfindlay** [comment]
@ze42, thanks for the report.

**Comment by nicholascapo** [comment]
Ref #25937

**Comment by ze42** [comment]
Seems to be fixed by https://github.com/saltstack/salt/pull/26000, now present in both develop and branch 2015.5.
Forgot to test 2015.5 branch, only tested tags... :(

**Comment by jfindlay** [comment]
@ze42, no problem, thanks for reporting.  @nicholascapo, can you verify that the fix works for you as well?

**Comment by jfindlay** [comment]
Thanks @driskell for your excellent fix.

**Comment by nicholascapo** [comment]
@jfindlay Sorry I don't have a test environment with more than 1 minion, If you guys think its fixed that's enough for me. I can wait till the next release.

**Comment by cachedout** [comment]
I think we'll go ahead and close this then. Thanks, everyone!

**Comment by rbjorklin** [comment]
I've been seeing this (or maybe a similar) problem and while trying to reproduce it the following happend.

    root@salt:~# salt -b 3 '*' test.version
    ...
    ...

    Executing run on ['test.home.loc']

    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    ValueError: list.remove(x): x not in list
    Traceback (most recent call last):
     File "/usr/bin/salt", line 10, in <module>
       salt_main()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 454, in salt_main
       client.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
      File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 173, in run
    minion_tracker[queue]['minions'].remove(id)
     ValueError: list.remove(x): x not in list
     Traceback (most recent call last):
      File "/usr/bin/salt", line 10, in <module>
    salt_main()
        File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 454, in salt_main
    client.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
      File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 173, in run
    minion_tracker[queue]['minions'].remove(id)
      ValueError: list.remove(x): x not in list

**Comment by jettero** [comment]
I was getting list.remove(x): x not in list in 2015.8.1 and discovered it was really because of having more than one node with the same id.

**Comment by boboli** [comment]
I'm running into this problem as well, and I'm using salt version 2015.8.7 on both master and minions. And in my case, I'm batching with size 1, and occasionally getting "retcode: 0" as the only output.

**Comment by jfindlay** [comment]
@boboli, how many minions are you batching over?  Are you able to try the suggested fix in https://github.com/saltstack/salt/issues/29298#issuecomment-214863550?

**Comment by boboli** [comment]
I don't see the `list.remove(x): x not in list`, I just get minions that give no summaries with just a "retcode: 0" as the only result. I'm batching over anywhere from 5 to 80 minions.

**Comment by jfindlay** [comment]
@boboli, thanks for reporting.

**Comment by rallytime** [comment]
The `ist.remove(x): x not in list,` stack trace was fixed by #32686, which is available in 2015.8.9 and up for the 2015.8 branch releases and the 2016.3.x releases. 

@boboli Are you still running into this problem on newer versions of salt? There was some good work put into the batch functionality in the 2016.3 releases, but I don't know if you have upgraded to that version yet or not.

**Comment by boboli** [comment]
No I'm still on 2015.8.7, so I'm still seeing this issue pretty frequently. Upgrading salt is never a simple exercise, as I have to make sure every box still works with the new version, so I haven't had the resources to do so.

**Comment by rallytime** [comment]
@boboli Thank you for the update. I tested this on 2016.3.2 and I wasn't able to reproduce it, but I completely understand the task of updating salt.

**Comment by rbjorklin** [comment]
Running 2016.3.3 and batching seems to work fine. There is a difference from before though, it always prints `retcode: 0` for every targeted node, is this by design?

**Comment by rallytime** [comment]
@rbjorklin Hmm...I remember a change going in for the `retcode` to come through for each minion, but now I can't find the pull request or issue about that. I think it makes sense to pass that information on per minion, so you can get the ret code back for the command on each minion, rather than one general return. 
```
root@rallytime:~# salt -b 2 \* test.ping

Executing run on ['rally-test', 'rallytime']

rallytime:
    True
retcode:
    0
rally-test:
    True
retcode:
    0

Executing run on ['rally-cent7-1']

rally-cent7-1:
    True
retcode:
    0
```
