### ISSUE TITLE
fileclient does not work if ':' in filename

### ISSUE THREAD

**Issue by jagguli** [saltstack/salt#26839]
Example:

    salt dev-vm0 cp.get_file salt://files/test:file C:\\testfile

Happens with 2015.8.0rc3 minions on windows

**Comment by jfindlay** [comment]
@jagguli, thanks for the report.  Do you have the specific error that results or any debug log information?

**Comment by cachedout** [comment]
This is definietely a 2015.8 regression and is not limited to Windows.

**Comment by cachedout** [comment]
Bug introduced here: https://github.com/jfindlay/salt/commit/29a023aaad31b093fc0b97ef00d5c055c9083732

**Comment by cachedout** [comment]
This is now fixed by #26970. Closing.

**Comment by deamen** [comment]
This issue still exists in 2015.8.3, 2015.8.4 and 2015.8.5, however, it happens on Windows minion only, it works fine on Linux minion.
 
PS C:\Users\vagrant> salt-call cp.get_file salt://saltmaster.vagrant.om.net/C:/test/test1/test2/test3.tz C:\test_101.tz -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'app.vagrant.om.net', 'tcp://192.168.99.2:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8843)
[DEBUG   ] Setting zmq_reconnect_ivl to '8843ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'app.vagrant.om.net', 'tcp://192.168.99.2:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'app.vagrant.om.net', 'tcp://192.168.99.2:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'app.vagrant.om.net', 'tcp://192.168.99.2:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded cp.get_file
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'app.vagrant.om.net', 'tcp://192.168.99.2:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'app.vagrant.om.net', 'tcp://192.168.99.2:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'app.vagrant.om.net', 'tcp://192.168.99.2:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'app.vagrant.om.net', 'tcp://192.168.99.2:4506')
[DEBUG   ] LazyLoaded nested.output
local:
PS C:\Users\vagrant>
