### ISSUE TITLE
manage.bootstrap runner quotation escape bug

### ISSUE THREAD

**Issue by imchairmanm** [saltstack/salt#26913]
Hello!

When using `salt-run manage.bootstrap ...`, I'm receiving the following error:

```
  File "<string>", line 1
    import urllib; print urllib.urlopen(https://bootstrap.saltstack.com).read()
                                             ^
SyntaxError: invalid syntax
```

The issue appears to be a buggy quotation escape in `runners/manage.py`.  around the script name.

**Comment by cachedout** [comment]
@imchairmanm What version of Salt do you see this on? Looking at the code, it appears this is quoted correctly.

**Comment by s0undt3ch** [comment]
Is this while running on python 3?

**Comment by imchairmanm** [comment]
@cachedout: I am on the latest development (or at least I think so).  For some reason the `'\'' + script +  '\''` at least appears to be the problem.  If I change the file to `'"' + script + '"'`, it functions correctly again.  I'm not sure why that is the case.

```
Salt Version:
           Salt: 2015.8.0-361-gc3a2355
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-57-generic
         system: Ubuntu 14.04 trusty
```

**Comment by gauravsaxena26** [comment]
I am seeing the same problem. I am using 

# salt-run --version
salt-run **2015.8.1** (Beryllium)

I see the below error when running a *manage.bootstrap* command

`
$ sudo salt-run manage.bootstrap hosts=192.168.122.112 root_user=True script=http://bootstrap.saltstack.com
root@192.168.122.112's password: 
  File "<string>", line 1
    import urllib; print urllib.urlopen(http://bootstrap.saltstack.com).read()
                                            ^
SyntaxError: invalid syntax
`

**Comment by jacobweinstock** [comment]
I am seeing the same issue, same version, as well. 

Workaround: Escaping double quotes inside of single quotes.
<code>$ salt-run manage.bootstrap script='\"https://bootstrap.saltstack.com/develop\"'  </code>

**Comment by vutny** [comment]
Looks like this issue should be resolved in the future version of Salt. See PR #31490.
As for me, current version of `manage.bootstrap` runner function is not very useful, though.

I'm developing my own bootstrap runner module for this purpose:
https://github.com/vutny/salt-contrib/blob/bootstrap-runner/runners/bootstrap.py

It's still far away from being perfect... Feel free to check it out and leave me your comments/suggestions.

**Comment by s0undt3ch** [comment]
#31490 has been merged, can you please verify that this is fixed?

**Comment by rallytime** [comment]
@imchairmanm Just a nudge here to if you have had a chance to check out the fix mentioned above.

**Comment by jacobweinstock** [comment]
I'm still seeing the same issue in version 2015.8.10

`# salt-run --version
salt-run 2015.8.10 (Beryllium)`

`# salt-run manage.bootstrap hosts='172.17.0.3' script='https://bootstrap.saltstack.com/develop'
  File "<string>", line 1
    import urllib; print urllib.urlopen(https://bootstrap.saltstack.com/develop).read()
                                             ^
SyntaxError: invalid syntax
None`

**Comment by rallytime** [comment]
@jacobweinstock Ah, that fix only applied to the develop branch, now that I look more closely. I can submit a PR in a moment that avoids the syntax error.

**Comment by rallytime** [comment]
@imchairmanm And @jacobweinstock - please see PR #33443.
