### ISSUE TITLE
xmpp.returner problem

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#27702]
running 2015.5.2

Not sure if this is due to my xmpp config or nto.. can someone shed some light on this before i dig thru .. 
```
2015-10-06 00:23:44,449 [salt.minion                              ][INFO    ][28198] returner xmpp
2015-10-06 00:23:44,510 [salt.loaded.int.returner.postgres_local_cache][INFO    ][28198] Could not import psycopg2, postges_local_cache disabled.
2015-10-06 00:23:44,512 [salt.minion                                  ][ERROR   ][28198] The return failed for job 20151006002344395534 'xmpp.returner'
2015-10-06 00:23:44,514 [salt.minion                                  ][ERROR   ][28198] Traceback (most recent call last):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/minion.py", line 1265, in _thread_return
    returner
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/utils/lazy.py", line 90, in __getitem__
    raise KeyError(key)
KeyError: 'xmpp.returner'
```

**Comment by rallytime** [comment]
@mimianddaniel This is likely due to a missing binary. Looks like the same bug as in #26882 and #26280 and should be fixed by #27681.

**Comment by mimianddaniel** [comment]
thanks for the quick reply- - just tested after using #27681  but still seeing same issue

**Comment by rallytime** [comment]
@mimianddaniel Oh, you're right. That stack trace looks similar to the issues I mentioned, but isn't the same. I didn't see you were using the returner. 

Is there any other information you can provide? If you run the command in debug mode is there a more complete stacktrace?

**Comment by mimianddaniel** [comment]
even in running in debug from on master and salt client itself, i dont see much other than what i had already posted up above.

**Comment by mimianddaniel** [comment]
taking a look at the code, each loader call checks __virtual__ and within xmpp, requirement is to have sleekxmpp module, shoudlve been easy catch if you know how the modules are loaded for salt .. i guess. 
you can close now

**Comment by rallytime** [comment]
@mimianddaniel So you're able to get this to work if you install `sleekxmpp`?

**Comment by mimianddaniel** [comment]
correct -- could we get xmpp module/returned backed ported to 2015.5 soon ?

**Comment by rallytime** [comment]
@mimianddaniel I don't think we're going to backport a whole module, but you should be able to add the 2015.8 module to your `_modules` directory and use it there, if you'd like. And I just checked and the xmpp returner is identical in the 2015.5 and 2015.8 branches.

We should certainly get that error cleaned up and help with checking for the proper dependencies, however.
