### ISSUE TITLE
blockdev.formatted failing on 2nd+ run, despite disk already being formatted 

### ISSUE THREAD

**Issue by edhgoose** [saltstack/salt#28203]
Hi,

I'm seeing an issue with my use of `blockdev.formatted` state.

I've set up a new Amazon EC2 instance using the standard Amazon AMI and I've founded a second EBS volume with 50gb of space. The disk is mounted at `/dev/sdf` which Amazon shows as `/dev/xvdf` on the instance.

I'm using the following state configuration to format and then mount the disk:

```
formatted_elasticsearch_data:
  blockdev.formatted:
    - name: /dev/xvdf
    - fs_type: ext4

mnt_elasticsearch_data:
  mount.mounted:
    - name: {{ elasticsearch.data_dir }}
    - device: /dev/xvdf
    - fstype: ext4
    - mkmnt: True
```

Everything works perfectly the first time. The volume is formatted and mounted at the correct point. I can continue as normal from there.

However, when I run this state again I get the following output:

```
----------
          ID: formatted_elasticsearch_data
    Function: blockdev.formatted
        Name: /dev/xvdf
      Result: False
     Comment: Failed to format /dev/xvdf
     Started: 09:19:23.718308
    Duration: 434.387 ms
     Changes:
```

From looking at the code at https://github.com/saltstack/salt/blob/develop/salt/states/blockdev.py, I see the following line is used to investigate whether the disk has the correct `fstype` (at both lines 130 and 162 in current development branch):

`blk = __salt__['cmd.run']('lsblk -o fstype {0}'.format(name)).splitlines()`

If I run `lsblk -o fstype` (plus a few other columns) on the instance directly I note that the fstype is not set to `ext4` as I would expect:

```
NAME    FSTYPE LABEL MOUNTPOINT
xvda
└─xvda1 ext4   /     /
xvdf                 /usr/local/var/data/elasticsearch/disk1
```

This output would trigger the error path that I'm seeing on line 169 and then 175.

Is there an alternate way the system can determine if the block is formatted correctly? Amazon suggests using this command `sudo file -s /dev/xvdf` here http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html, which outputs the below, but I'm way out of my depth here!

Output from: `sudo file -s /dev/xvdf`:

```
/dev/xvdf: Linux rev 1.0 ext4 filesystem data, UUID=2891c754-391e-4e80-bc3b-b70d7089a042 (needs journal recovery) (extents) (large files) (huge files)
```

Alternatively, does `df -T` work?

```
Filesystem     Type 1K-blocks    Used Available Use% Mounted on
/dev/xvdf      ext4  51475068 3350592  45486652   7% /usr/local/var/data/elasticsearch/disk1
```

Here's my output from salt --versions-report (I'm aware that I'm not running the latest, but I couldn't see anything in the blockdev.formatted implementation that would change the outcome given the underlying command appears to be giving an unexpected output).

```
Salt: 2015.5.5
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

**Comment by jfindlay** [comment]
@edhgoose, thanks for the report.  This is fixed in #28265, which will come out in 2015.8.2.

**Comment by edhgoose** [comment]
Thanks @jfindlay that's hugely appreciated.

**Comment by edhgoose** [comment]
Hi, @jfindlay + @rallytime, I'm afraid this is still happening for me - apologies for the huge delay in being able to test it, we've only recently upgraded Salt.

Here's what the master is running:

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.9 (unknown, Jul 20 2016, 20:52:42)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 4.4.10-22.54.amzn1.x86_64
         system: Linux
        version: Not Installed
```

And the minion:

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Jul 20 2016, 20:52:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 4.4.11-23.53.amzn1.x86_64
         system: Linux
        version: Not Installed
```

Is this a regression?

Output from Salt was:

```
----------
          ID: formatted_elasticsearch_data
    Function: blockdev.formatted
        Name: /dev/xvdf
      Result: False
     Comment: Failed to format /dev/xvdf
     Started: 14:24:00.860779
    Duration: 32657.457 ms
     Changes:
```

And `lsblk` gives:
```
NAME    MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
xvda    202:0    0   8G  0 disk
└─xvda1 202:1    0   8G  0 part /
xvdf    202:80   0   1T  0 disk /usr/local/var/data/elasticsearch/disk1
```

And `cat /etc/fstab` gives:

```
#
LABEL=/     /           ext4    defaults,noatime  1   1
tmpfs       /dev/shm    tmpfs   defaults        0   0
devpts      /dev/pts    devpts  gid=5,mode=620  0   0
sysfs       /sys        sysfs   defaults        0   0
proc        /proc       proc    defaults        0   0
/dev/xvdf      		/usr/local/var/data/elasticsearch/disk1	ext4   	defaults       	0 0
```

Any ideas?

**Comment by rallytime** [comment]
Thanks for letting us know @edhgoose. I have re-opened this issue.

**Comment by rallytime** [comment]
I am not sure if this is a regression or not. It would be good to get some tests written for this issue.

**Comment by jbussdieker** [comment]
Has anyone tried running `udevadm trigger` on a failed host? I was getting the same issue on 2016.3.1 running on Amazon Linux.

**Comment by DaveQB** [comment]
Just chiming in to say I am seeing this too.


Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo
