### ISSUE TITLE
state boto_secgroup.present fails to find vpc_name

### ISSUE THREAD

**Issue by mlalpho** [saltstack/salt#28469]
I'm getting a error when attempting to use the salt.boto_secgroup state to manage security groups. Am I doing something wrong? (some content redacted)

```yaml
----------
          ID: create_sg
    Function: boto_secgroup.present
        Name: xxxxx
      Result: False
     Comment: Security group xxxxx created. xxxxx security group configuration could not be retrieved.
     Started: 16:10:53.486125
    Duration: 293.442 ms
     Changes:
              ----------
              new:
                  ----------
                  secgroup:
                      None
              old:
                  ----------
                  secgroup:
                      None
    Warnings: 'vpc_name' is an invalid keyword argument for
              'boto_secgroup.present'. If you were trying to pass additional
              data to be used in a template context, please populate 'context'
              with 'key: value' pairs. Your approach will work until Salt Carbon
              is out. Please update your state files.
```

```sls
create_sg:
  boto_secgroup.present:
    - name        : xxxxx
    - description : descr
    - vpc_name    : xxxvpc
    - rules       :
      - ip_protocol: all
        from_port: -1
        to_port: -1
        cidr_ip:
          - 0.0.0.0/0
      - ip_protocol: icmp
        from_port: -1
        to_port: -1
        source_group_name: xxx_sq
    - rules_egress:
      - ip_protocol: all
        from_port: -1
        to_port: -1
        cidr_ip:
          - 0.0.0.0/0
    - region: us-west-2
    - keyid: xxxxxxxxddddd
    - key: xkcdxkcdxkcdxkcd
```

```sh
# salt --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```
`Package python-boto-2.38.0-2.el7.noarch already installed and latest version
Nothing to do`

Changing state to contain a 'context' dict that contains vpc_name also fails with a similar message.

If I change the state to to use the real vpc_id instead of vpc_name:
```yaml
----------
          ID: create_sg
    Function: boto_secgroup.present
        Name: xxxxx
      Result: True
     Comment: Security group xxxxx created.  Created rules on xxxxx security group.
     Started: 16:38:22.252943
    Duration: 831.458 ms
     Changes:
              ----------
              new:
                  ----------
                  rules:
                      |_
                        ----------
                        cidr_ip:
                            0.0.0.0/0
                        from_port:
                            None
                        ip_protocol:
                            -1
                        to_port:
                            None
                      |_
                        ----------
                        from_port:
                            -1
                        ip_protocol:
                            icmp
                        source_group_group_id:
                            sg-1241234
                        source_group_owner_id:
                            123542345
                        to_port:
                            -1
                  rules_egress:
                      |_
                        ----------
                        cidr_ip:
                            0.0.0.0/0
                        from_port:
                            None
                        ip_protocol:
                            -1
                        to_port:
                            None
                  secgroup:
                      ----------
                      description:
                          descr
                      group_id:
                          sg-1241234
                      name:
                          xxxxx
                      owner_id:
                          123542345
                      rules:
                      rules_egress:
                          |_
                            ----------
                            cidr_ip:
                                0.0.0.0/0
                            from_port:
                                None
                            ip_protocol:
                                -1
                            to_port:
                                None
              old:
                  ----------
                  rules:
                  rules_egress:
                      |_
                        ----------
                        cidr_ip:
                            0.0.0.0/0
                        from_port:
                            -1
                        ip_protocol:
                            -1
                        to_port:
                            -1
                  secgroup:
                      None
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 831.458 ms
```
Second run:
```yaml
----------
          ID: create_sg
    Function: boto_secgroup.present
        Name: xxxx
      Result: True
     Comment: Security group xxxxx present.
     Started: 16:34:10.178922
    Duration: 227.62 ms
     Changes:
```

To confirm, everything works as expected if i leave out vpc_name and define vpc_id. I would really like to see vpc_name working, however. Please advise. Thank You.

**Comment by rallytime** [comment]
@mlalpho Thank you for this excellent report. It looks like there is just a bug with using vpc_name and we'll fix it up. In the mean time, please use the vpc_id argument.

**Comment by rallytime** [comment]
@mlalpho Oh, it looks like support for `vpc_name` was added after 2015.8.1 was released in pull request #27581. Are you in a position to give this a try on the HEAD of 2015.8? Otherwise, 2015.8.2 will have this functionality.

I've added a "version added" tag to vpc_name in #28534 so it is more clear that the functionality isn't available until the 2015.8.2 release.

**Comment by mlalpho** [comment]
I merged in PR #27581 and restarted the master and synced all.

Then my access key started being passed around in place of my 'region'. I'm guessing that the params got mixed up somewhere? idk

Output
```sls

create_secgroup_xxxxxx_xxxxxx_vpc_xxxxxx-vpc:
  boto_secgroup.present:
    - name        : xxxxxx-sq
    - description : dsfsdf
    - vpc_name    : xxxxxx-vpc
    - rules:
      - ip_protocol: icmp
        from_port: -1
        to_port: -1
        source_group_name:
          - xxxxxx-sq
      - ip_protocol: all
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0
    - rules_egress:
      - ip_protocol: all
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0
    - region: us-west-2
    - keyid: KEYIDKEYIDKEYIDKEYID
    - key: KEYKEYKEYKEYKEYKEYKEY


[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('create_secgroup_xxxxxx_xxxxxx_vpc_xxxxxx-vpc', OrderedDict([('boto_secgroup.present', [OrderedDi                                                                                                                          ct([('name', 'xxxxxx-sq')]), OrderedDict([('description', 'dsfsdf')]), OrderedDict([('vpc_name                                                                                                                          ', 'xxxxxx-vpc')]), OrderedDict([('rules', [OrderedDict([('ip_protocol', 'icmp'), ('from_port', -1), ('to_port',                                                                                                                           -1), ('source_group_name', ['xxxxxx-sq'])]), OrderedDict([('ip_protocol', 'all'), ('from_port', -1), ('to_port'                                                                                                                          , -1), ('cidr_ip', ['0.0.0.0/0'])])])]), OrderedDict([('rules_egress', [OrderedDict([('ip_protocol', 'all'), ('from                                                                                                                          _port', -1), ('to_port', -1), ('cidr_ip', ['0.0.0.0/0'])])])]), OrderedDict([('region', 'us-west-2')]), OrderedDict                                                                                                                          ([('keyid', 'KEYIDKEYIDKEYIDKEYID')]), OrderedDict([('key', 'KEYKEYKEYKEYKEYKEYKEY')])])]))])
[DEBUG   ] LazyLoaded boto.assign_funcs
[DEBUG   ] LazyLoaded boto_secgroup.exists
[DEBUG   ] LazyLoaded boto_secgroup.present
[INFO    ] Running state [xxxxxx-sq] at time 10:18:37.200672
[INFO    ] Executing state boto_secgroup.present for xxxxxx-sq
[DEBUG   ] LazyLoaded boto_vpc.get_id
[DEBUG   ] The filters criteria {'filters': {'tag:Name': 'xxxxxx-vpc'}} matched the following VPCs:[VPC:vpc-b754                                                                                                                          0fd2]
[INFO    ] Matching VPC: vpc-b7540fd2
[DEBUG   ] getting group for xxxxxx-sq in vpc_id vpc-b7540fd2
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1591, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/states/boto_secgroup.py", line 166, in present
    profile=profile)
  File "/usr/lib/python2.7/site-packages/salt/states/boto_secgroup.py", line 385, in _rules_present
    region=region, key=key, keyid=keyid, profile=profile
  File "/usr/lib/python2.7/site-packages/salt/modules/boto_secgroup.py", line 249, in get_group_id
    group = _get_group(conn, name, vpc_id, vpc_name, region, key, keyid, profile)
  File "/usr/lib/python2.7/site-packages/salt/modules/boto_secgroup.py", line 159, in _get_group
    vpc_id = _check_vpc(vpc_id, vpc_name, region, key, keyid, profile)
  File "/usr/lib/python2.7/site-packages/salt/modules/boto_secgroup.py", line 112, in _check_vpc
    key=key, keyid=keyid, profile=profile)
  File "/usr/lib/python2.7/site-packages/salt/modules/boto_vpc.py", line 490, in get_id
    key=key, keyid=keyid, profile=profile)}
  File "/usr/lib/python2.7/site-packages/salt/modules/boto_vpc.py", line 458, in _get_id
    key=key, keyid=keyid, profile=profile)
  File "/usr/lib/python2.7/site-packages/salt/modules/boto_vpc.py", line 419, in _find_vpcs
    conn = _get_conn(region=region, key=key, keyid=keyid, profile=profile)
  File "/usr/lib/python2.7/site-packages/salt/utils/boto.py", line 202, in get_connection
    'valid.'.format(region))
SaltInvocationError: Region "KEYKEYKEYKEYKEYKEYKEY" is not valid.

[INFO    ] Completed state [xxxxxx-sq] at time 10:18:37.406166
local:
----------
          ID: create_secgroup_xxxxxx_xxxxxx_vpc_xxxxxx-vpc
    Function: boto_secgroup.present
        Name: xxxxxx-sq
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/boto_secgroup.py", line 166, in present
                  profile=profile)
                File "/usr/lib/python2.7/site-packages/salt/states/boto_secgroup.py", line 385, in _rules_present
                  region=region, key=key, keyid=keyid, profile=profile
                File "/usr/lib/python2.7/site-packages/salt/modules/boto_secgroup.py", line 249, in get_group_id
                  group = _get_group(conn, name, vpc_id, vpc_name, region, key, keyid, profile)
                File "/usr/lib/python2.7/site-packages/salt/modules/boto_secgroup.py", line 159, in _get_group
                  vpc_id = _check_vpc(vpc_id, vpc_name, region, key, keyid, profile)
                File "/usr/lib/python2.7/site-packages/salt/modules/boto_secgroup.py", line 112, in _check_vpc
                  key=key, keyid=keyid, profile=profile)
                File "/usr/lib/python2.7/site-packages/salt/modules/boto_vpc.py", line 490, in get_id
                  key=key, keyid=keyid, profile=profile)}
                File "/usr/lib/python2.7/site-packages/salt/modules/boto_vpc.py", line 458, in _get_id
                  key=key, keyid=keyid, profile=profile)
                File "/usr/lib/python2.7/site-packages/salt/modules/boto_vpc.py", line 419, in _find_vpcs
                  conn = _get_conn(region=region, key=key, keyid=keyid, profile=profile)
                File "/usr/lib/python2.7/site-packages/salt/utils/boto.py", line 202, in get_connection
                  'valid.'.format(region))
              SaltInvocationError: Region "KEYKEYKEYKEYKEYKEYKEY" is not valid.
     Started: 10:18:37.200672
    Duration: 205.494 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 548.859 ms
```

**Comment by rallytime** [comment]
Hrm. It appears that this state has seen some churn on the 2015.8 branch and  `_rules_present` function has changed since 2015.8.1 was released. If you have some time, I'd recommend applying #27927 to see if that clears things up here until I have a chance to circle back around to this issue.

If it doesn't, does testing from the HEAD of the 2015.8 also have this error? If neither of those things work, then we have another bug to fix here and I am surprised no one has reported it yet!

**Comment by rallytime** [comment]
@mlalpho I was able to swing back around here and the 2015.8 branch was stacktracing like this as well. There was a function that was passing positional args incorrectly. I've fixed the stack trace with #28710.

**Comment by bogdanr** [comment]
I pulled up to 1931870f26f6dafec7f0c12902db38049e5a05e6 in 2015.8 and I still get the same error as before. Also, just as before, the security group gets created but no rules get added.

    Security group XXX created. XXX security group configuration could not be retrieved. XXX security group configuration could not be retrieved.
