### ISSUE TITLE
salt boto_rds.present fails to execute, too many arguments

### ISSUE THREAD

**Issue by mlalpho** [saltstack/salt#28470]
When attempting to apply a boto_rds.present state shown below, I receive this output:
```
----------
          ID: create_rds
    Function: boto_rds.present
        Name: rdstest
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/boto_rds.py", line 197, in present
                  tags, region, key, keyid, profile)
                File "/usr/lib/python2.7/site-packages/salt/states/boto_rds.py", line 249, in _rds_present
                  keyid, profile)
                File "/usr/lib/python2.7/site-packages/salt/modules/boto_rds.py", line 236, in create
                  publicly_accessible, tags)
              TypeError: create_db_instance() takes at most 26 arguments (27 given)
     Started: 17:21:47.279723
    Duration: 114.53 ms
     Changes:

```

```sls
create_rds:
  boto_rds.present:
    - name: rdstest
    - allocated_storage: 100
    - storage_type: gp2
    - db_instance_class: db.m1.large
    - engine: PostgreSQL
    - engine_version: 9.3.9
    - auto_minor_version_upgrade: True
    - master_username: xrs
    - master_user_password: dewfvae
    - vpc_security_group_ids:
      - sg-124236
    - availability_zone: us-west-2b
    - db_subnet_group_name: rds-db-sg
    - multi_az: False
    - publicly_accessible: True
    # - wait_status: available
    - region: us-west-2
    - keyid: xxxfe2w3fw
    - key: asdfw34f234f234fa
```
```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```
`Package python-boto-2.38.0-2.el7.noarch already installed and latest version`

Am I doing something wrong? Please advise.

Also, is there any chance that this state module could support vpc_security_group_names ??

Thank You.

**Comment by rallytime** [comment]
@mlalpho We'll take a look here. However, is it possible that you're access credentials aren't correct? I've seen those types of misleading stack traces in other modules before and that was usually the culprit. If that is the case, then we certainly need to clean that up and provide a more helpful error.

**Comment by rallytime** [comment]
@mlalpho PR #28561 was just submitted to the 2015.8 branch and it should fix this up nicely for you. Are you in a position to give this change a try and confirm that the issue is fixed for you?

**Comment by mlalpho** [comment]
Nice going! :+1:  I will give this a try later today and get back :)

Thank You!

**Comment by mlalpho** [comment]
I'm afraid this isn't this one is still borked. 

Need an update to:
`salt/states/boto_rds.py`

`storage_type` argument is still present in the signature

New Trace:
```sls
----------
          ID: create_rds
    Function: boto_rds.present
        Name: atlassian-rds-dev
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/boto_rds.py", line 197, in present
                  tags, region, key, keyid, profile)
                File "/usr/lib/python2.7/site-packages/salt/states/boto_rds.py", line 249, in _rds_present
                  keyid, profile)
              TypeError: create() takes at most 30 arguments (31 given)
     Started: 14:15:15.612705
    Duration: 134.934 ms
     Changes:

```

**Comment by rallytime** [comment]
@mlalpho Oh! Right! Because only the module was updated. I'll take a look at this later today. Thanks for testing!

**Comment by mlalpho** [comment]
No problemo, Let me know if you need me to try again. Appreciate the quick fixes ! :) :+1:

**Comment by rallytime** [comment]
@mlalpho Alright, #28612 should help. Can you give that a try?

**Comment by mlalpho** [comment]
Confirmed this is working, now.

A word of warning, though. You cannot use `engine: PostgreSQL`. However, `engine: postgres` works just fine :) -- the docs reference `engine: MySQL` so the support for the full name was assumed. I looked at the amazon RDS console, however and it shows `DB Engine postgres` during the launch wizard, so that's what fixed it for me :+1: 

The error message from state run is missing the error description from the raw aws api result.

```sls

[INFO    ] Running state [RDS123456789] at time 21:04:28.833222
[INFO    ] Executing state boto_rds.present for RDS123456789
[DEBUG   ] DBInstanceNotFound: 404 Not Found
{u'RequestId': u'cd946958-8400-11e5-b662-a1eccfab6b76', u'Error': {u'Message': u'DBInstance RDS123456789 not found.', u'Code': u'DBInstanceNotFound', u'Type': u'Sender'}}
[DEBUG   ] DBInstanceNotFound: 404 Not Found
{u'RequestId': u'cd9ca629-8400-11e5-ac3f-9d77128923fd', u'Error': {u'Message': u'DBInstance RDS123456789 not found.', u'Code': u'DBInstanceNotFound', u'Type': u'Sender'}}
[DEBUG   ] JSONResponseError: 400 Bad Request
{u'RequestId': u'cda2c171-8400-11e5-8cc9-0d34623fc808', u'Error': {u'Message': u'Invalid DB engine', u'Code': u'InvalidParameterValue', u'Type': u'Sender'}}
[ERROR   ] Failed to create RDS RDS123456789, reason: {u'RequestId': u'cda2c171-8400-11e5-8cc9-0d34623fc808', u'Error': {u'Message': u'Invalid DB engine', u'Code': u'InvalidParameterValue', u'Type': u'Sender'}}
[ERROR   ]  Failed to create RDS123456789 RDS.
[INFO    ] Completed state [RDS123456789] at time 21:04:29.640355
[DEBUG   ] File /var/cache/salt/minion/accumulator/27226640 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion-id', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'minion-id', 'tcp://127.0.0.1:4506')
[DEBUG   ] LazyLoaded highstate.output
[TRACE   ] data = {'local': {'boto_rds_|-create_rds_|-RDS123456789_|-present': {'comment': u' Failed to create RDS123456789 RDS.', 'name': 'RDS123456789', 'start_time': '21:04:28.833222', 'result': False, 'duration': u'807.133 ms', '__run_num__': 0, 'changes': {}}}}
local:
----------
          ID: create_rds
    Function: boto_rds.present
        Name: RDS123456789
      Result: False
     Comment: Failed to create RDS123456789 RDS.
     Started: 21:04:28.833222
    Duration: 807.133 ms
     Changes:
```

Thanks all!

**Comment by rallytime** [comment]
Oh, thanks for the info! It looks like `PostgreSQL` is not a supported engine type from boto: http://boto.readthedocs.org/en/latest/ref/rds.html#boto.rds.RDSConnection.create_dbinstance.

I've added some documentation in #28653 that supplies a list of acceptable values for the engine parameter. 

@mlalpho With the doc clarification, do you think this one is good to close up?

**Comment by mlalpho** [comment]
Awesome, thank ya!
