### ISSUE TITLE
Exception raised when processing __virtual__ function for nova. Module will not be loaded global name 'novaclient' is not defined

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#29511]
A quick look at the code, the bug seems to be in salt/utils/openstack/nova.py where novaclient is try/except importerror but then check_nova uses novaclient which doesn't exist. 

```
# salt-call --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 2.3.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2 
```

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for the report.  I have looked at `salt.utils.openstack.nova.check_nova` and it only uses `novaclient` if `HAS_NOVA` is `True`.  Is it possible for you to post more context on the error?

**Comment by mf-collinhayden** [comment]
I get this same error when running a simple highstate on a remote node.  The remote node's /var/log/salt/minion contains the following error:

salt.loader      ][ERROR   ][22892] Exception raised when processing __virtual__ function for nova. Module will not be loaded global name 'novaclient' is not defined

# cat /etc/issue
Ubuntu 14.04.3 LTS \n \l

# salt-minion --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-29-generic
         system: Ubuntu 14.04 trusty

**Comment by TheBigBear** [comment]
on all winrepo-ng pkg installs I now get the following error since I upgraded to 2015.8.3

```
C:\salt>salt-call pkg.install adobeair
[ERROR   ] Exception raised when processing __virtual__ function for nova. Module will not be loaded global name 'novaclient' is not defined
[WARNING ] salt.loaded.int.module.nova.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'nova', please fix this.
```

**Comment by rallytime** [comment]
This has been fixed by #29455. Can anyone on this thread confirm?

**Comment by jfindlay** [comment]
@rallytime, that doesn't actually fix the error, `global name 'novaclient' is not defined`, but rather the warning `... is wrongly returning None'`.  If you can figure out what is going on in `salt.utils.openstack.nova`, then you're smarter than me because I've spent several minutes trying to decipher why this error is happening at all.  All references to `novaclient` are protected by `HAS_NOVA`.  I have also been unable to reproduce the error.

**Comment by rallytime** [comment]
This error has been fixed at the HEAD of the 2015.8 branch with #29196. The confusion here of why this bug is happening in the release and how to fix it that @jfindlay is referring to above is because the fix for this was merged into the 2015.8 branch the day after the release was tagged. This fix will be available in 2015.8.4.

**Comment by jfindlay** [comment]
@rallytime, thanks for the explanation.

**Comment by jumping** [comment]
On python26 has same issue.

**Comment by rallytime** [comment]
@jumping Yes, thanks for the extra info. This should be fixed on the 2015.8 branch, and will be resolved in the upcoming 2015.8.4 release.

**Comment by basepi** [comment]
I'm going to close this. Keep us posted if it's not fixed in the new release.
