### ISSUE TITLE
2016.3.1 breaks diskusage beacon

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#33972]
The disk usage beacon is working on a Windows minion (no errors and events are fired) but doesn't seem to be working on a Debian minion (I've not tested any other platforms). To re-create the problem:

/srv/pillar/top.sls
<pre>base:
  'linuxminion':
    - beacons</pre>
/srv/pillar/beacons.sls
<pre>beacons:
  diskusage:
    - interval: 60
    - /: 5%</pre>
(I've also tried quoting the forward slash)

`salt linuxminion saltutil.refresh_pillar`

(I've also tried restarting the minion process)
<pre>2016-06-13 14:08:43,808 [salt.beacons     ][TRACE   ][11953] Beacon processing: diskusage
2016-06-13 14:08:43,809 [salt.utils.lazy  ][DEBUG   ][11953] LazyLoaded diskusage.beacon
2016-06-13 14:08:43,810 [salt.beacons     ][DEBUG   ][11953] Unable to process beacon diskusage
2016-06-13 14:08:44,807 [salt.beacons     ][TRACE   ][11953] Beacon processing: diskusage
2016-06-13 14:08:44,808 [salt.utils.lazy  ][DEBUG   ][11953] LazyLoaded diskusage.beacon
2016-06-13 14:08:44,809 [salt.beacons     ][DEBUG   ][11953] Unable to process beacon diskusage
2016-06-13 14:08:45,807 [salt.beacons     ][TRACE   ][11953] Beacon processing: diskusage
2016-06-13 14:08:45,808 [salt.utils.lazy  ][DEBUG   ][11953] LazyLoaded diskusage.beacon
2016-06-13 14:08:45,809 [salt.beacons     ][DEBUG   ][11953] Unable to process beacon diskusage
2016-06-13 14:08:46,808 [salt.beacons     ][TRACE   ][11953] Beacon processing: diskusage
2016-06-13 14:08:46,809 [salt.utils.lazy  ][DEBUG   ][11953] LazyLoaded diskusage.beacon
2016-06-13 14:08:46,810 [salt.beacons     ][DEBUG   ][11953] Unable to process beacon diskusage
2016-06-13 14:08:47,808 [salt.beacons     ][TRACE   ][11953] Beacon processing: diskusage
2016-06-13 14:08:47,809 [salt.utils.lazy  ][DEBUG   ][11953] LazyLoaded diskusage.beacon
2016-06-13 14:08:47,810 [salt.beacons     ][DEBUG   ][11953] Unable to process beacon diskusage
2016-06-13 14:08:48,808 [salt.beacons     ][TRACE   ][11953] Beacon processing: diskusage
2016-06-13 14:08:48,808 [salt.utils.lazy  ][DEBUG   ][11953] LazyLoaded diskusage.beacon
2016-06-13 14:08:48,809 [salt.beacons     ][DEBUG   ][11953] Unable to process beacon diskusage</pre>

Tested on 2016.3.0

**Comment by Ch3LL** [comment]
@morganwillcock I'm able to see beacon events from a centos7 minion while configuring beacons via pillar and minion config on centos7. What version of debian are you seeing this on? 7 or 8?

```
beacons:
  diskusage:
    - interval: 2
    - /: 5%
```

**Comment by morganwillcock** [comment]
@Ch3LL Thanks for looking at this. I tried it on 7 and 8, but only checked the logs on 8.

**Comment by morganwillcock** [comment]
Just checked, the same error is logged on 7.

**Comment by cachedout** [comment]
Possibly fixed here? https://github.com/saltstack/salt/pull/33474

**Comment by morganwillcock** [comment]
I've just tried applying that, but still have the same result.

**Comment by morganwillcock** [comment]
Sorry this was my fault. I had assumed that psutils was installed as standard dependency of the minion package, installing this lets the beacon process correctly.

@cachedout I had to revert #33474 as I was getting a traceback with it applied.

<pre>2016-06-15 11:29:39,287 [salt.minion      ][CRITICAL][20575] The beacon errored: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 2022, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 380, in process_beacons
    return self.beacons.process(b_conf)  # pylint: disable=no-member
  File "/usr/lib/python2.7/dist-packages/salt/beacons/__init__.py", line 91, in process
    raw = self.beacons[fun_str](b_config[mod])
  File "/usr/lib/python2.7/dist-packages/salt/beacons/diskusage.py", line 74, in beacon
    _current_usage = psutil.disk_usage(mount)
  File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 1690, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/lib/python2.7/dist-packages/psutil/_psposix.py", line 121, in disk_usage
    st = os.statvfs(path)
TypeError: must be string, not dict</pre>

**Comment by rallytime** [comment]
@morganwillcock Thank you for you investigation and for the fix. Your PR has been merged, and I have back-ported your change in #34176 to the 2015.8 branch. Can this be closed now?

**Comment by morganwillcock** [comment]
Yes, thank you.
