### ISSUE TITLE
Can't install package on VZ7 (Centos 7)

### ISSUE THREAD

**Issue by valintinr** [saltstack/salt#35123]
Hi!
Can't install any package on new OS called VZ7 https://download.openvz.org/virtuozzo/releases/7.0/x86_64/iso/
This OS based on Centos 7.
Getting next errors

`          ID: etckeeper
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'etckeeper'
              Reason: 'pkg' __virtual__ returned False`

And lot of other similar messages.

`Summary
-------------
Succeeded: 32
Failed:    46
-------------
Total states run:     78
`
Master
`[root@salt-master ~]# rpm -qa | grep -i salt
salt-master-2015.2-alt3
python-module-salt-2015.2-alt3
salt-api-2015.2-alt3
`

Minion
`salt-2016.3.1-1.el7.noarch
salt-minion-2016.3.1-1.el7.noarch`

**Comment by Ch3LL** [comment]
@valintinr can you please paste the other related logs when attempting to install a package?

also what is the output of `salt 'minion' grains.item os` and `salt 'minion' grains.item os_family`?

Looks like we need to add support for this OS.

**Comment by valintinr** [comment]
Hi!

`[root@salt-master ~]# salt 'nl32*' grains.item os
nl32.tanhost.com:
    ----------
    os:
        Virtuozzo
[root@salt-master ~]# salt 'nl32*' grains.item os_family
nl32.tanhost.com:
    ----------
    os_family:
        Virtuozzo
[root@salt-master ~]# 
`
No other important logs
`2016-08-03 04:00:05,291 [salt.state       ][ERROR   ][16834] The named service atop is not available
2016-08-03 04:00:05,292 [salt.state       ][ERROR   ][16834] The named service crond is not available
2016-08-03 04:00:05,293 [salt.state       ][ERROR   ][16834] The named service postfix is not available
2016-08-03 04:00:05,294 [salt.state       ][ERROR   ][16834] The named service rsyslog is not available
2016-08-03 04:00:05,295 [salt.state       ][ERROR   ][16834] The named service bacula-fd is not available
2016-08-03 04:00:05,296 [salt.state       ][ERROR   ][16834] State 'pkg.installed' was not found in SLS 'smartd'
Reason: 'pkg' __virtual__ returned False

2016-08-03 04:00:05,335 [salt.state       ][ERROR   ][16834] State 'pkg.installed' was not found in SLS 'snmpd'
Reason: 'pkg' __virtual__ returned False

2016-08-03 04:00:05,371 [salt.state       ][ERROR   ][16834] State 'pkg.installed' was not found in SLS 'etckeeper'
`
We see that erros because pkackages not installed. Seems no any other important errors reported.

**Comment by valintinr** [comment]
Hi!
Any updates?

**Comment by valintinr** [comment]
So?

**Comment by jtand** [comment]
@valintinr Those errors come up on pkg.installed and others because the os/os_family grains aren't matching up with what we have in the __virual__ function here: https://github.com/saltstack/salt/blob/develop/salt/modules/yumpkg.py#L60-L76

It looks like we have `virtuozzolinux` being checked in the state, so it may need to be adjusted to match what the os/os_family grains are actually returning.

If you're interested in fixing this yourself we can help you, or we can do it at a later. Let me know what you think!

**Comment by valintinr** [comment]
Hello,
Im glad that someone answered me.
Sure I can fix it myself if you tell what I should to do.

**Comment by jtand** [comment]
@valintinr Sure thing! All you will need to do is add `Virtuozzo` to the list of RHEL systems [here](https://github.com/saltstack/salt/blob/fd7f24d993785d4decadf9efb450f51e12a8c2e5/salt/modules/yumpkg.py#L72). Once you add that you can create a pull request so we can review and merge it! Our contributing docs are [here](https://docs.saltstack.com/en/latest/topics/development/contributing.html).

**Comment by valintinr** [comment]
Many thanks for help!

**Comment by rallytime** [comment]
Fixed via #36115

**Comment by valintinr** [comment]
Updated both master and minion by new commit but still getting same error

`Summary for local
-------------
Succeeded: 24
Failed:    47
-------------
Total states run:     71
Total run time:  666.940 ms
`
`[root@nl32 salt]# grep -n Virtuozzo /usr/lib/python2.7/site-packages/salt/modules/yumpkg.py
72:    enabled = ('amazon', 'xcp', 'xenserver', 'virtuozzolinux', 'Virtuozzo')
`

`[root@salt-master ~]# grep -n Virtuozzo /usr/lib/python2.7/site-packages/salt/modules/yumpkg.py
72:    enabled = ('amazon', 'xcp', 'xenserver', 'virtuozzolinux', 'Virtuozzo')
`

**Comment by rallytime** [comment]
@valintinr I didn't catch this on your initial pull request, but I think the reason your fix didn't work is because we're lower-casing the characters in the os/os_family grain return in the `try/except` block before adding `Virtuozzo` to the `enabled` set. If you change `Virtuozzo` to `virtuozzo` will that work for you? Give that a try and if that test works for you (I don't currently have a VZ7 box to test this on), we can get that cleaned up.

**Comment by valintinr** [comment]
Yes, you right, lover-case did the trick.
What I need to do now? New pull request?

**Comment by rallytime** [comment]
@valintinr yeah, that would be great! Thank you!

**Comment by rallytime** [comment]
Thank you for following up here and for making a new pull request. I just merged it in. Is this ready to close now?

**Comment by valintinr** [comment]
Seems now working, thanks for help.
