### ISSUE TITLE
cp.push remove_source problem

### ISSUE THREAD

**Issue by lkx007** [saltstack/salt#36568]
### I can use cp.push properly like this:
[root@localhost salt]# salt 'worker' cp.push /root/a 
worker:
    True
[root@localhost salt]# 

### But when I add remove_source error occurs as follows:
[root@localhost salt]# salt 'worker' cp.push /root/a remove_source=True
worker:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 814, in push
        salt.utils.rm_rf(path)
      File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1870, in rm_rf
        shutil.rmtree(path, onerror=_onerror)
      File "/usr/lib64/python2.7/shutil.py", line 239, in rmtree
        onerror(os.listdir, path, sys.exc_info())
      File "/usr/lib64/python2.7/shutil.py", line 237, in rmtree
        names = os.listdir(path)
    OSError: [Errno 20] Not a directory: '/root/a'
[root@localhost salt]# 

### Versions Report
[root@localhost salt]# salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
 
[root@localhost salt]#

**Comment by cachedout** [comment]
@lkx007 This is a bug. Please see #36572 for the fix.

**Comment by lkx007** [comment]
@cachedout  thanks a lot!

**Comment by lkx007** [comment]
In windows platform minion , I have fixed the #36572 bug, however,the same problem happens as follows:
[root@localhost salt]# salt 'window' cp.push c:\\a.bat 
window:
    True
[root@localhost salt]# 
[root@localhost salt]# salt 'window' cp.push c:\\a.bat remove_source=True
window:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\cp.py", line 815, in push
        salt.utils.rm_rf(path)
      File "c:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 1872, in rm_rf
        os.remove(path)
    WindowsError: [Error 32] : 'c:\\a.bat'
[root@localhost salt]# 

 'salt-minion --versions-report' in windows platform minion 
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2
 
System Versions:
           dist:   
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.10240  Multiprocessor Free
 
Can you please help me?  @cachedout

**Comment by cachedout** [comment]
@lkx007 Unfortunately, I still don't have access to a Windows machine to do any development on. @twangboy or @UtahDave will have to look at this.

**Comment by lkx007** [comment]
Why windows machine throw exception WindowsError: [Error 32]??
Can someone helps me? thanks a lot....
@cachedout @rallytime @twangboy @UtahDave @cro
