### ISSUE TITLE
cp.push not working

### ISSUE THREAD

**Issue by jayma777** [saltstack/salt#37133]
### Description of Issue/Question

Trying to push file from minion to master:

File size:  28 bytes
# : `salt 'minion' cp.push /root/myip.txt`

minion:
    False

All minions (400) have the same issue.  Minion versions range from 2015.5.3 up to 2016.3.3.  The only minion that does work is the minion running locally on the salt-master.
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

The salt master has this setting in /etc/salt/master
**file_recv: True**

Both Salt master and salt minion processes have been restarted many times.
### Steps to Reproduce Issue

Sorry for the log file blast, but I didn't want to leave anything out

**Master debug log** (log_level: all)
2016-10-20 17:13:04,004 [salt.utils.event                                     ][DEBUG   ][6535] Sending event - data = {'tgt_type': 'glob', 'jid': '20161020171304002177', 'tgt': 'MINION_ID', '_stamp': '2016-10-20T22:13:04.003420', 'user': 'sudo_USER', 'arg': ['/root/myip.txt'], 'fun': 'cp.push', 'minions': ['MINION_ID']}
2016-10-20 17:13:04,005 [salt.utils.event                                     ][TRACE   ][6507] get_event() received = {'tag': '20161020171304002177', 'data': {'_stamp': '2016-10-20T22:13:04.002262', 'minions': ['MINION_ID']}}
2016-10-20 17:13:04,005 [salt.returners                                       ][INFO    ][6535] Using default for mysql ssl_key
2016-10-20 17:13:04,005 [salt.utils.reactor                                   ][DEBUG   ][6507] Gathering reactors for tag 20161020171304002177
2016-10-20 17:13:04,006 [salt.returners                                       ][INFO    ][6535] Using default for mysql ssl_cert
2016-10-20 17:13:04,006 [salt.returners                                       ][INFO    ][6535] Using default for mysql port
2016-10-20 17:13:04,006 [salt.utils.event                                     ][TRACE   ][6507] get_event() received = {'tag': 'salt/job/20161020171304002177/new', 'data': {'tgt_type': 'glob', 'jid': '20161020171304002177', 'tgt': 'MINION_ID', '_stamp': '2016-10-20T22:13:04.003420', 'user': 'sudo_USER', 'arg': ['/root/myip.txt'], 'fun': 'cp.push', 'mini
ons': ['MINION_ID']}}
2016-10-20 17:13:04,007 [salt.returners                                       ][INFO    ][6535] Using default for mysql ssl_ca
2016-10-20 17:13:04,007 [salt.utils.reactor                                   ][DEBUG   ][6507] Gathering reactors for tag salt/job/20161020171304002177/new
2016-10-20 17:13:04,007 [salt.loaded.int.returner.mysql                       ][DEBUG   ][6535] Trying to reuse MySQL connection pool
2016-10-20 17:13:04,011 [salt.master                                          ][INFO    ][6535] User sudo_USER Published command cp.push with jid 20161020171304002177
2016-10-20 17:13:04,011 [salt.master                                          ][DEBUG   ][6535] Published command details {'tgt_type': 'glob', 'jid': '20161020171304002177', 'tgt': 'MINION_ID', 'ret': '', 'user': 'sudo_USER', 'arg': ['/root/myip.txt'], 'fun': 'cp.push'}
2016-10-20 17:13:04,017 [salt.client      ][TRACE   ][24378] func get_cli_event_returns()
2016-10-20 17:13:04,023 [salt.utils.lazy  ][DEBUG   ][24378] LazyLoaded mysql.get_load
2016-10-20 17:13:04,028 [salt.utils.lazy  ][DEBUG   ][24378] LazyLoaded config.option
2016-10-20 17:13:04,028 [salt.returners   ][INFO    ][24378] Using default for mysql ssl_key
2016-10-20 17:13:04,028 [salt.returners   ][INFO    ][24378] Using default for mysql ssl_cert
2016-10-20 17:13:04,029 [salt.returners   ][INFO    ][24378] Using default for mysql port
2016-10-20 17:13:04,029 [salt.returners   ][INFO    ][24378] Using default for mysql ssl_ca
2016-10-20 17:13:04,029 [salt.loaded.int.returner.mysql][DEBUG   ][24378] Generating new MySQL connection pool
2016-10-20 17:13:04,051 [salt.client      ][DEBUG   ][24378] get_iter_returns for jid 20161020171304002177 sent to set(['MINION_ID']) will timeout at 17:13:09.050518
2016-10-20 17:13:04,052 [salt.utils.event ][TRACE   ][24378] _get_event() waited 0 seconds and received nothing
2016-10-20 17:13:04,064 [salt.utils.event ][TRACE   ][24378] get_event() received = {'tag': 'salt/job/20161020171304002177/new', 'data': {'tgt_type': 'glob', 'jid': '20161020171304002177', 'tgt': 'MINION_ID', '_stamp': '2016-10-20T22:13:04.003420', 'user': 'sudo_USER', 'arg': ['/root/myip.txt'], 'fun': 'cp.push', 'minions': ['MINION_ID']}}
2016-10-20 17:13:04,072 [salt.master                                          ][TRACE   ][6560] AES payload received with command _file_recv
2016-10-20 17:13:04,073 [salt.master                                          ][TRACE   ][6560] Master function call _file_recv took 1.90734863281e-05 seconds
2016-10-20 17:13:04,086 [salt.master                                          ][TRACE   ][6551] AES payload received with command _return
2016-10-20 17:13:04,087 [salt.utils.job                                       ][INFO    ][6551] Got return from MINION_ID for job 20161020171304002177
2016-10-20 17:13:04,088 [salt.utils.event                                     ][DEBUG   ][6551] Sending event - data = {'fun_args': ['/root/myip.txt'], 'jid': '20161020171304002177', 'return': False, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2016-10-20T22:13:04.087391', 'fun': 'cp.push', 'id': 'MINION_ID'}
2016-10-20 17:13:04,089 [salt.returners                                       ][INFO    ][6551] Using default for mysql ssl_key
2016-10-20 17:13:04,089 [salt.returners                                       ][INFO    ][6551] Using default for mysql ssl_cert
2016-10-20 17:13:04,090 [salt.utils.event                                     ][TRACE   ][6507] get_event() received = {'tag': 'salt/job/20161020171304002177/ret/MINION_ID', 'data': {'fun_args': ['/root/myip.txt'], 'jid': '20161020171304002177', 'return': False, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2016-10-20T22:13:04.087391', 'fun': 
'cp.push', 'id': 'MINION_ID'}}
2016-10-20 17:13:04,090 [salt.utils.event ][TRACE   ][24378] get_event() received = {'tag': 'salt/job/20161020171304002177/ret/MINION_ID', 'data': {'fun_args': ['/root/myip.txt'], 'jid': '20161020171304002177', 'return': False, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2016-10-20T22:13:04.087391', 'fun': 'cp.push', 'id': 'MINION_ID'}}
2016-10-20 17:13:04,090 [salt.utils.reactor                                   ][DEBUG   ][6507] Gathering reactors for tag salt/job/20161020171304002177/ret/MINION_ID
2016-10-20 17:13:04,090 [salt.returners                                       ][INFO    ][6551] Using default for mysql port
2016-10-20 17:13:04,091 [salt.returners                                       ][INFO    ][6551] Using default for mysql ssl_ca
2016-10-20 17:13:04,091 [salt.client      ][DEBUG   ][24378] jid 20161020171304002177 return from MINION_ID
2016-10-20 17:13:04,091 [salt.loaded.int.returner.mysql                       ][DEBUG   ][6551] Trying to reuse MySQL connection pool
2016-10-20 17:13:04,095 [salt.master                                          ][TRACE   ][6551] Master function call _return took 0.00797820091248 seconds
2016-10-20 17:13:04,096 [salt.utils.lazy  ][DEBUG   ][24378] LazyLoaded nested.output
2016-10-20 17:13:04,097 [salt.output      ][TRACE   ][24378] data = {'MINION_ID': False}
2016-10-20 17:13:04,198 [salt.utils.event ][TRACE   ][24378] _get_event() waited 0 seconds and received nothing
2016-10-20 17:13:04,199 [salt.client      ][DEBUG   ][24378] jid 20161020171304002177 found all minions set(['MINION_ID'])

**Minion debug log** (log_level: all)
2016-10-20 17:17:17,516 [salt.minion                                          ][INFO    ][8164] User sudo_USER Executing command cp.push with jid 20161020171304002177
2016-10-20 17:17:17,517 [salt.minion                                          ][DEBUG   ][8164] Command details {'tgt_type': 'glob', 'jid': '20161020171304002177', 'tgt': 'MINION_ID', 'ret': '', 'user': 'sudo_USER', 'arg': ['/root/myip.txt'], 'fun': 'cp.push'}
2016-10-20 17:17:17,540 [salt.minion                                          ][INFO    ][8283] Starting a new job with PID 8283
2016-10-20 17:17:17,543 [salt.utils.lazy                                      ][DEBUG   ][8283] LazyLoaded cp.push
2016-10-20 17:17:17,545 [salt.minion                                          ][TRACE   ][8283] Executors list ['direct_call.get']
2016-10-20 17:17:17,546 [salt.utils.lazy                                      ][DEBUG   ][8283] LazyLoaded direct_call.get
2016-10-20 17:17:17,546 [salt.loaded.int.module.cp                            ][DEBUG   ][8283] Trying to copy '/root/myip.txt' to master
2016-10-20 17:17:17,546 [salt.crypt                                           ][DEBUG   ][8283] Initializing new SAuth for ('/etc/salt/pki/minion', 'MINION_ID', 'tcp://MASTER_IP:4506')
2016-10-20 17:17:17,550 [salt.crypt                                           ][DEBUG   ][8283] Loaded minion key: /etc/salt/pki/minion/minion.pem
2016-10-20 17:17:17,556 [salt.transport.zeromq                                ][DEBUG   ][8283] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'MINION_ID', 'tcp://MASTER_IP:4506', 'aes')
2016-10-20 17:17:17,557 [salt.crypt                                           ][DEBUG   ][8283] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'MINION_ID', 'tcp://MASTER_IP:4506')
2016-10-20 17:17:17,559 [salt.transport.zeromq                                ][TRACE   ][8283] Inserted key into loop_instance_map id 43644256 for key ('/etc/salt/pki/minion', 'MINION_ID', 'tcp://MASTER_IP:4506', 'aes') and process 8283
2016-10-20 17:17:17,571 [salt.loaded.int.module.cp                            ][ERROR   ][8283] cp.push **Failed transfer failed. Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the master.**
2016-10-20 17:17:17,573 [salt.minion                                          ][DEBUG   ][8283] Minion return retry timer set to 7 seconds (randomized)
2016-10-20 17:17:17,573 [salt.minion                                          ][INFO    ][8283] Returning information for job: 20161020171304002177
2016-10-20 17:17:17,574 [salt.transport.zeromq                                ][DEBUG   ][8283] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'MINION_ID', 'tcp://MASTER_IP:4506', 'aes')
2016-10-20 17:17:17,574 [salt.crypt                                           ][DEBUG   ][8283] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'MINION_ID', 'tcp://MASTER_IP:4506')
2016-10-20 17:17:17,578 [salt.transport.zeromq                                ][TRACE   ][8283] Inserted key into loop_instance_map id 43644112 for key ('/etc/salt/pki/minion', 'MINION_ID', 'tcp://MASTER_IP:4506', 'aes') and process 8283
2016-10-20 17:17:17,594 [salt.minion                                          ][TRACE   ][8283] ret_val = None
2016-10-20 17:17:22,168 [salt.utils.process                                   ][TRACE   ][8164] Process manager iteration
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Master version:  

Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final

Minion version:

Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: unknown
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Feb 22 2013, 00:00:18)
   python-gnupg: 0.3.8
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 6.4 Final
        machine: x86_64
        release: 2.6.32-358.el6.x86_64
         system: Linux
        version: CentOS 6.4 Final

**Comment by jbouse** [comment]
I've experienced this as well... 

```
# salt minion cp.push /etc/fstab
minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 799, in push
        load_path_list = os.path.split(load_path_split_drive)
      File "/usr/lib/python2.7/posixpath.py", line 92, in split
        i = p.rfind('/') + 1
    AttributeError: 'tuple' object has no attribute 'rfind'
```

Going on to the minion itself and running Python interpreter while running the lines of modules/cp.py manually I get the following through debugging:

```
>>> path = '/etc/fstab'
>>> load_path = path.lstrip(os.sep)
>>> load_path
'etc/fstab'
>>> load_path_normal = os.path.normpath(load_path)
>>> load_path_normal
'etc/fstab'
>>> load_path_split_drive = os.path.splitdrive(load_path_normal)[1:]
>>> load_path_split_drive
('etc/fstab',)
>>> load_path_list = os.path.split(load_path_split_drive)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/posixpath.py", line 92, in split
    i = p.rfind('/') + 1
AttributeError: 'tuple' object has no attribute 'rfind'
```

It looks like it is [81c4d136](https://github.com/saltstack/salt/commit/81c4d136c5e3ac7b8cc208e0a9079c7ebb018b0c} that introduced this change.

**Comment by jayma777** [comment]
That error was fixed in another PR.  

You can either downgrade to 2016.3.2  (which supposedly fixes it, haven't verified that)

or

In /usr/lib/python2.7/dist-packages/salt/modules/cp.py change:
load_path_split_drive = os.path.splitdrive(load_path_normal)[1:]
to
load_path_split_drive = os.path.splitdrive(load_path_normal)[1]
(Somewhere around line 790)

This worked for me.  You'll need to change it for each minion.

**Comment by gtmanfred** [comment]
This is going to be fixed in 2016.3.4.

**Comment by gtmanfred** [comment]
@jayma777 is your issue different than that one?

**Comment by gtmanfred** [comment]
This appears to be a duplicate of https://github.com/saltstack/salt/issues/36860 if it is a new issue.

**Comment by jayma777** [comment]
My issue is different from the one presented by jbouse.  It *might* be related or duplicate of #36860.  It's difficult to tell.   It seems as if the master is ignoring the file_recv setting.  If there is a way to view the "loaded" settings, I might be able to figure out why the master doesn't see it.

**Comment by gtmanfred** [comment]
If you run `salt-call config.get file_recv` and you don't have file_recv in any minion pillar or grains configs, i believe it should pull the config from the master.

**Comment by gtmanfred** [comment]
And if you are saying that the minion on the salt master works, that would be why my testing may have not been able to replicate it in the other bug.

**Comment by jayma777** [comment]
salt-call config.get file_recv returns false on all minions,  even the minion running on the master.  file_recv isn't defined anywhere, other than /etc/salt/master.

**Comment by gtmanfred** [comment]
Hrm, yeah i am getting the same, but I setup an extra minion and hooked it up, using 2016.3.3, and I am still able to do a cp.push.

```
[root@salt ~]# find /var/cache/salt/master/minions/ -name fstab
[root@salt ~]# salt \* cp.push /etc/fstab
salt.c.gtmanfred-1263.internal:
    True
test.c.gtmanfred-1263.internal:
    True
[root@salt ~]# find /var/cache/salt/master/minions/ -name fstab
/var/cache/salt/master/minions/salt.c.gtmanfred-1263.internal/files/etc/fstab
/var/cache/salt/master/minions/test.c.gtmanfred-1263.internal/files/etc/fstab
```

**Comment by Qtrain** [comment]
Getting the same..

```
root@ubuntu:#~ salt --version
salt 2016.3.3 (Boron)
root@ubuntu:#~ salt-call config.get file_recv
[WARNING ] /usr/lib/python2.7/dist-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:

```    False

**Comment by gtmanfred** [comment]
Can you give me any more information.  It does not look like the file_recv is available to the minion from the master through config.get.

I was not able to replicate this issue.  Can you make sure that your salt master has done a full restart and not just a reload after the config file has been changed?

**Comment by Qtrain** [comment]
@gtmanfred When we set up our Salt master configuration, we enabled the file_recv option, but when trying to push files back up to master cp.push is returning false.  We are using salt-cloud.

**Comment by Qtrain** [comment]
@gtmanfred Hi. any update on this?

**Comment by gtmanfred** [comment]
I am still unable to reproduce this error on 2016.3.3 or 2016.3.4, can you provide the output of 

```
python -c "import salt.config; print salt.config.client_config('/etc/salt/master').get('file_recv')"
```

**Comment by jassuncao** [comment]
I'm experiencing the same issue with windows minions.
The following commands fails with a return False:
`salt 27407 cp.push "c:\\test.txt"
 salt 27407 cp.push "c:/test.txt"
`
I tracked the problem to the method _file_recv in master.py, to the section where, before storing the file data,  a bit of path checking is performed. I noticed os.path.isabs(normpath) was returning false because  `normpath='\test.txt'`.

I'm able to push files if I use upload_path:
`salt 27407 cp.push "c:\\test.txt" upload_path="test.txt"`

**Comment by GabLeRoux** [comment]
I get the same problem here.
my salt master:
```
 sudo salt --versions-report 
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```

My salt minion:
```

```
sudo salt-call --versions-report             
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.4.2
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```

On the minion:
```
echo "hi" > test.txt && sudo salt-call cp.push test.txt                                                                                                                                                                               
[WARNING ] /usr/lib/python2.7/dist-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
    False
```

From `tail -f /var/log/salt/master` I get the following error:
```
Received bad data when setting the match from the top file
```

**Comment by GabLeRoux** [comment]
:tada: I confirm it works when the `saltmaster` is updated to `2016.11.1`, worked when `salt-minion` was on both `2016.3.3` and `2016.11.1` ;)

**Comment by kodybrown** [comment]
Thanks everyone for the helpful discussion here! I'll also confirm that my issue was fixed by upgrading my master to 2016.11.1. My minions vary between these: 2016.3.3, 2016.3.4, 2016.11.0, and 2016.11.1. (I even had one from 2015, but I upgraded it also!)

**Comment by johncagle** [comment]
I have this problem with a master running 2016.3.4 and minion running 2015.5.0.  I even updated the master to 2016.11.2 (since kodybrown says above the problem was fixed in 2016.11.1), and still see the problem on the 2015.5.0 minion:

2017-02-20 19:55:29,501 [salt.loaded.int.module.cp][ERROR   ][5736] cp.push Failed transfer failed. Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the master.

Minions that are running 2016.3.4 did not have a problem with the master running 2016.3.4.

**Comment by steverweber** [comment]
confirmed issue with
```
root@salt-master-p01-01:/srv/salt/document# salt-master --version
salt-master 2016.11.4 (Carbon)
```
when using `cp` on minions `salt-call 2015.8.8 (Beryllium)`

success on minions: `2016.11.0-648-g88ec2d2`

this issue needs a priority set.

**Comment by steverweber** [comment]
https://github.com/saltstack/salt/issues/38477

**Comment by neomag** [comment]
Version:            Salt: 2016.11.5   master & minion

problem still exists

**Comment by gtmanfred** [comment]
I am still unable to replicate this issue.

I set file_recv to True on the master, and restart the master, and then I am able to push data, on a master and minion on the same box, and different boxes.

Can anyone provide me with more information on how to replicate this?

```
[root@salt salt]# tail -c +0 /etc/salt/{master,minion}
==> /etc/salt/master <==
file_recv: True

==> /etc/salt/minion <==
master: localhost
[root@salt salt]# tree /var/cache/salt/master/minions/
/var/cache/salt/master/minions/
├── minion.c.gtmanfred-1263.internal
│   └── data.p
└── salt.c.gtmanfred-1263.internal
    └── data.p

2 directories, 2 files
[root@salt salt]# salt \* cp.push /etc/hosts
minion.c.gtmanfred-1263.internal:
    True
salt.c.gtmanfred-1263.internal:
    True
[root@salt salt]# tree /var/cache/salt/master/minions/
/var/cache/salt/master/minions/
├── minion.c.gtmanfred-1263.internal
│   ├── data.p
│   └── files
│       └── etc
│           └── hosts
└── salt.c.gtmanfred-1263.internal
    ├── data.p
    └── files
        └── etc
            └── hosts

6 directories, 4 files
```

Thanks,
Daniel

**Comment by GabLeRoux** [comment]
@gtmanfred see my comment: https://github.com/saltstack/salt/issues/37133#issuecomment-270500057

I was having the issue when the *salt master* was on `2016.3.3`, I wasn't able to reproduce on `2016.11.1` or later.

**Comment by gtmanfred** [comment]
What version was the minion on?

**Comment by GabLeRoux** [comment]
@gtmanfred `2016.3.3` (as shown in the linked comment's `sudo salt-call --versions-report`

**Comment by swohlerLL** [comment]
This problem also occurs after upgrading our master from 2015.8.8 to 2015.8.13. The minions did not change (2015.5.3).

Versions:

**MASTER**

```
xxxxx@xxxxx-salt-master:/etc/salt$ sudo salt --versions-report
Salt Version:
           Salt: 2015.8.13

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-81-generic
         system: Ubuntu 16.04 xenial
```

**MINION**

```
xxxxx@xxxxx-salt-master:/etc/salt$ sudo salt '*16-a0' cmd.run 'salt-call --versions-report'
xxxxx_00-0d-b9-40-16-a0:
                      Salt: 2015.5.3
                    Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                    Jinja2: 2.6
                  M2Crypto: 0.21.1
            msgpack-python: 0.1.10
              msgpack-pure: Not Installed
                  pycrypto: 2.6
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: 13.1.0
                      RAET: Not Installed
                       ZMQ: 3.2.3
                      Mako: Not Installed
                   Tornado: Not Installed
     Debian source package: 2015.5.3+ds-1~bpo70+2
```

**COMMANDS**

```
xxxxx@xxxxx-salt-master:/etc/salt$ sudo salt '*16-a0' cp.push /tmp/salt_log.gz
xxxxx_00-0d-b9-40-16-a0:
    False

xxxxx@xxxxx-salt-master:/etc/salt$ sudo salt '*16-a0' cmd.run 'salt-call config.get file_recv'
xxxxx_00-0d-b9-40-16-a0:
    local:
        False
```

**CONFIG**

```
xxxxx@xxxxx-salt-master:/etc/salt$ cat master | grep file_recv
file_recv: True
file_recv_size_max: 400
```

**Comment by ngeovanis** [comment]
Is there a resolution for this problem as of 1 October 2017?

**Comment by gtmanfred** [comment]
As far as I am aware, cp.push is still working.

the 2015 versions that are mentioned in this issue are not supported anymore.  I have still never been able to replicate this issue.

If someone can provide me a vagrant environment, or steps to reliably reproduce this, we can take a look.

Thanks,
Daniel

**Comment by ngeovanis** [comment]
I can confirm that the issue exists with a master at 2016.11.3 and minions at 2016.3.1. The master runs on Debian 8.7 and the failing minions at Debian 7.7 and 7.11.
All other minions here are at 2015.5.0 and 2015.5.3, and all fail with the "cp.push Failed transfer failed. Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the master."

Despite the message:
root@salt01:/tmp# grep 'file_recv' /etc/salt/master
file_recv: True
file_recv_max_size: 100
root@salt01:/tmp#

**Comment by ngeovanis** [comment]
I should have added that the issue does _not_ occur with the 2016.11.3 master and minions which are at 2016.11.2 and 2016.11.3.

**Comment by gtmanfred** [comment]
Ok, i have been able to replicate this with the minion on 2016.3.1, but once I update to 2016.3.8 it all works, so it looks like it was fixed in a 2016.3 release.

Thanks,
Daniel

**Comment by markuskramerIgitt** [comment]
```cp.push``` returns ```False```
master: 2016.11.5 (Debian)
minions: 2016.11.3 (Windows)

**Comment by gaetanquentin** [comment]
pb still here.
master: 2017.7.7 , ubuntu 14.04
minion: 2016.3.2 , Microsoft Windows Server 2016 Datacenter
