### ISSUE TITLE
push_dir windows 

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#38159]
### Description of Issue/Question
When a minion on windows tries to push a directory under a Linux master and the directory has sub directories then the paths are created with windows folder separation.

when trying to push c:\salt\conf

```
drwxr-xr-x  2 root root 4096 Dec  8 14:56 \salt\conf\pki\minion
drwxr-xr-x  2 root root 4096 Dec  8 14:56 \salt\conf\minion.d
drwxr-xr-x  2 root root 4096 Dec  8 14:56 \salt\conf
 ```

### Versions Report
2016.3.4 but it should be like that in dev also

**Comment by tsaridas** [comment]
a solution would be to push a list for each folder + file from the minion 

```
['salt', 'conf', 'minion' ]
```
and assemble the list at the master _file_recv() with os.sep.join(list) so we don't care if master is linux or windows.

**Comment by Ch3LL** [comment]
hmmm I thought this was already resolved with this pr: #35413

Is your windows minion also on 2016.3.4. It seems that pr is indeed in the code

**Comment by tsaridas** [comment]
yes the minion is 2016.3.4

the patch has nothing to do with the issue I'm describing and doesn't fix the operating system separator issue.

I'll try to give you an example 

- user uploads dir c:\salt

- push_dir function searches for files in the path and finds 
c:\salt\pki\minion.pub
.. etc

- push_dir calls push for every file it found
load_path_list would be ('\\salt\\pki\\', minion.pub) and would be sent to the master
master is linux and it will try to create folder \salt\pki\ and put the file minion.pub there

**Comment by tsaridas** [comment]
not sure if I should keep this open until fix goes to stable branch

**Comment by rallytime** [comment]
@tsaridas Since this fix is now in 2016.11.2 with PR #38203, I'll go ahead and close this. Thanks again for the fix!
