### ISSUE TITLE
After upgrading to Carbon on RHEL 6, service salt-minion takes minutes

### ISSUE THREAD

**Issue by pradermecker** [saltstack/salt#40489]
### Description of Issue
service salt-minion status takes minutes to come back

### Steps to Reproduce Issue
Given a running salt-master, install the salt-minion (no specific configuration). As root, run the following command line:
```
> time service salt-minion status
salt-minion:root:jenkinsmaster.sandbox.srv.cirb.lan is running: 15811

real    2m8.711s
user   0m53.917s
sys    0m16.873s
```
This is happening with all RHEL 6 machines from 6.7 to 6.9. No other daemon running (machines have been rebooted)

Nothing in logs. Running `salt-minion -l debug` is quick without anomalies.

### Expecting behavior
Comparing with the same config (and same salt master) on RHEL 7 : 
```
[ 0 ] root # time service salt-minion status
Redirecting to /bin/systemctl status  salt-minion.service
● salt-minion.service - The Salt Minion
   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-03-22 16:39:32 CET; 1 weeks 4 days ago
 Main PID: 1053 (salt-minion)
   CGroup: /system.slice/salt-minion.service
           ├─1053 /usr/bin/python /usr/bin/salt-minion
           ├─1984 /usr/bin/python /usr/bin/salt-minion
           └─2586 /usr/bin/python /usr/bin/salt-minion

```
real	0m0.022s
user	0m0.008s
sys	0m0.013s

### Versions Report
salt-minion 2016.11.3 (Carbon)
RHEL 6.7 or 6.9

**Comment by pradermecker** [comment]
Maybe this will help https://github.com/saltstack/salt/issues/40489 ? Is it going to be released as part of `2016.11.4` ?

**Comment by gtmanfred** [comment]
This should be fixed here.

https://github.com/saltstack/salt/pull/39104

Can you add `--notrim` to the service restart?

This has been backported and will be part of the 2016.11.4 release.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Duplicate of https://github.com/saltstack/salt/issues/39052

**Comment by PierreR** [comment]
#39052 has been closed but this issue still exists even in the latest 2016.11.5 ... I am still unable to update to 2016 on RHEL6 (using RHEL 6.7)

**Comment by PierreR** [comment]
@gtmanfred would you mind re-open this issue or link me to an open duplicate ? Thanks.

**Comment by gtmanfred** [comment]
Can you open a new issue?  Also, you are on RHEL 6 at least right? because we did not patch this on RHEL 5, because there will be no more releases for that because RedHat has end of lifed it.

Thanks,
Daniel
