### ISSUE TITLE
salt-ssh - ImportError: No module named backports.ssl_match_hostname

### ISSUE THREAD

**Issue by davidjb** [saltstack/salt#41020]
### Description of Issue/Question

When running `salt-ssh 2017.5.0-95-g1c0c53b` (latest `develop` as of today) against a target of RHEL 6.9 (a target that was previously provisioned fine with `salt-ssh v2015.5.3`), any salt function invocation will fail with the error:

```
$ salt-ssh '*' test.ping
...[A full traceback follows below]...
ImportError: No module named backports.ssl_match_hostname
```

Running raw shell commands works fine, though:

```
$ salt-ssh '*' --raw 'ls'
hostname:
    ----------
    retcode:
        0
    stderr:
    stdout:
        install.log
        install.log.syslog
```

The issue can be worked around by manually ssh'ing into the machine and running:
```
pip install backports.ssl_match_hostname
```
(or running raw commands via `salt-ssh '*' -r 'pip install ...'`) but this isn't ideal.

#### Linked issues

This issue seems to have come up a lot across various different targets, including Debian and CentOS, but the only fix committed was later reverted:

* #37358 (merged then reverted fix; comments about `salt-ssh` unusable with CentOS 6.6)
* #37355 (fix merged, reverted, then issue closed)
* #34600
* #33470 (workaround which I followed)
* #27355

### Setup

* macOS 10.12.4 source
* RHEL 6.9 x86_64 target

### Steps to Reproduce Issue

1. Install salt-ssh from `develop` branch
2. Run `salt-ssh '*' test.ping` to target RHEL or CentOS 6.9.
3. Note the following error:

```python
hostname:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_3d2557_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_3d2557_salt/py2/salt/scripts.py", line 386, in salt_call
            import salt.cli.call
          File "/var/tmp/.root_3d2557_salt/py2/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/var/tmp/.root_3d2557_salt/py2/salt/utils/parsers.py", line 28, in <module>
            import salt.config as config
          File "/var/tmp/.root_3d2557_salt/py2/salt/config/__init__.py", line 101, in <module>
            _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
          File "/var/tmp/.root_3d2557_salt/py2/salt/config/__init__.py", line 91, in _gather_buffer_space
            import salt.grains.core
          File "/var/tmp/.root_3d2557_salt/py2/salt/grains/core.py", line 46, in <module>
            import salt.utils.dns
          File "/var/tmp/.root_3d2557_salt/py2/salt/utils/dns.py", line 29, in <module>
            import salt.modules.cmdmod
          File "/var/tmp/.root_3d2557_salt/py2/salt/modules/cmdmod.py", line 34, in <module>
            import salt.utils.templates
          File "/var/tmp/.root_3d2557_salt/py2/salt/utils/templates.py", line 24, in <module>
            import salt.utils.http
          File "/var/tmp/.root_3d2557_salt/py2/salt/utils/http.py", line 42, in <module>
            import salt.loader
          File "/var/tmp/.root_3d2557_salt/py2/salt/loader.py", line 26, in <module>
            import salt.utils.event
          File "/var/tmp/.root_3d2557_salt/py2/salt/utils/event.py", line 69, in <module>
            import tornado.iostream
          File "/var/tmp/.root_3d2557_salt/py2/tornado/iostream.py", line 40, in <module>
            from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
          File "/var/tmp/.root_3d2557_salt/py2/tornado/netutil.py", line 56, in <module>
            import backports.ssl_match_hostname
        ImportError: No module named backports.ssl_match_hostname
    stdout:
```

### Versions Report

```
Salt Version:
           Salt: 2017.5.0-95-g1c0c53b

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Dec 18 2016, 07:03:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: x86_64
        release: 16.5.0
         system: Darwin
        version: 10.12.4 x86_64
```

**Comment by gtmanfred** [comment]
So, we would love to fix this, but there is no really good way to fix it that we have found.  If you can figure out a way to make work but not create other issues we would love a PR.

As it stands right now, the best way to address this issue is to install the backports on that minion you are connecting to.

Thanks,
Daniel

**Comment by MatthiasKuehneEllerhold** [comment]
We've got the same problem with this constellation:
* Debian Stretch as Salt-Master
* Mac OS 10.6.8 as Target
* Using Salt-SSH

I could resolve this problem via this commands:
* `apt-get install python-backports.ssl-match-hostname` on the master
* `rm -Rf cache/thin/thin.gz` on the master
* `rm -Rf /var/tmp/*salt*` on the minion

**Comment by gtmanfred** [comment]
Instead of removing the thin tarball and the tmp cache on the minion, you can pass `-t -w` starting with 2017.7

**Comment by Firewire2002** [comment]
> If you can figure out a way to make work but not create other issues we would love a PR.

I suggest a symlink from backport to ext directory to fix this issue. But PR was reverted without any comment.
So which issues do you mean?

In the meanwhile I moved the symlink creation to salt-call:

```
--- /var/tmp/.root_0b18cf_salt/salt-call.orig   2018-11-10 02:51:44.996728002 +0100
+++ /var/tmp/.root_0b18cf_salt/salt-call        2018-11-10 02:20:22.452763637 +0100
@@ -11,6 +11,10 @@
     )
 )

+SSRC=os.path.join(os.path.dirname(__file__),'py{0[0]}'.format(sys.version_info),'salt','ext')
+SDEST=os.path.join(os.path.dirname(__file__),'py{0[0]}'.format(sys.version_info),'backports')
+os.symlink(SSRC,SDEST)
+
 from salt.scripts import salt_call
 if __name__ == '__main__':
     salt_call()
```

**Comment by gtmanfred** [comment]
This should be fixed by additions made that will be in the fluorine release that allows the user to customize their thin tarball for salt-ssh.

@saltstack/team-triage just fyi.

**Comment by sagetherage** [comment]
closing as fixed please comment or open a new ticket if that is not the case

**Comment by Firewire2002** [comment]
This issue is very old, reported several times, suggested patches were ignored and issue still existing. Did you ever tried to run a highstate on older distributions? 

The needed python class is already in the thin.tar.gz. But it's only in the wrong directory ...
SaltStack offers enterprise support - but there is no developer who is able to place an existing file in the correct directory? Really?

Comment of Nov 2018 said that there will be a feature to customize the tarball. So where is it?
I can't find anything about this in the documentation.
