### ISSUE TITLE
rest_tornado is not able to return normal result 

### ISSUE THREAD

**Issue by szin2012** [saltstack/salt#42659]
### Description of Issue/Question
rest_tornado is not able to return normal result 

### Setup
Structure is master ---  syndic --- minion, three machines is distributed on different machines but same local network
 

master configure file:
```
order_masters: True

rest_tornado:
    port: 8100
    debug: True
    disable_ssl: True
    address: 0.0.0.0



external_auth:
  pam:
    saltapi:
      - .*
      - '@runner'
      - '@wheel'

log_level_logfile: all
gather_job_timeout: 60
```

syndic configure file :
```
syndic_master: 10.10.75.126
```

minion configure file :
```id: minion2
master: 10.10.75.127
```

### Steps to Reproduce Issue
 there is no result return for salt-api on master
```
-bash-4.2# curl -k http://127.0.0.1:8100          -H 'Content-type: application/json'         -H "X-Auth-Token: 97b58f8870f88e28dc6036c85064c91ed4285d12bee44b112545640c2398f9ff"  -d '[{"client": "local","tgt": "minion2","fun": "test.ping"}]'

{"return": [{}]} 
```

there is result return for test.ping on master 
```
-bash-4.2# salt minion2 test.ping 
minion2:
    True
```

### Versions Report
```
master:  
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core


syndic:  
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

minion:   
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by szin2012** [comment]
any news ? if i add  two line comments below in saltnado.py ， then salt-api can work properly . 
```
        # if we have a min_wait, do that
        #if syndic_min_wait is not None:
        #    yield syndic_min_wait
        # we are completed when either all minions return or the job isn't running anywhere
```

**Comment by PierreR** [comment]
This is the feedback we get after 6 months of something labelled as `bug` `high severity` ??

**Comment by whytewolf** [comment]
Have validated this issue. It only seems to affect rest_tornado. rest_cherrypy does not seem affected. 

From the API log 

```
2018-03-20 20:50:33,478 [salt.transport.zeromq][DEBUG   ][16043] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'master_master', 'tcp://127.0.0.1:4506', 'clear')
2018-03-20 20:50:33,479 [salt.transport.zeromq][TRACE   ][16043] Inserted key into loop_instance_map id 48397344 for key ('/etc/salt/pki/master', 'master_master', 'tcp://127.0.0.1:4506', 'clear') and process 16043
2018-03-20 20:50:38,382 [salt.utils.process][TRACE   ][16034] Process manager iteration
2018-03-20 20:50:43,969 [tornado.access   ][INFO    ][16043] 200 POST / (::1) 20967.88ms
2018-03-20 20:50:43,969 [tornado.application][ERROR   ][16043] Future exception was never retrieved: TimeoutException
```

```
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

checking the jobs system the job is shown there and completed without issue.

**Comment by whytewolf** [comment]
ZD-2345

**Comment by gtmanfred** [comment]
This should be getting fixed here.

https://github.com/saltstack/salt/pull/47415

Thanks,
Daniel

**Comment by frogunder** [comment]
@gtmanfred 

It still does not work for me with #47415 . It still shows no result for me. 
This is in a master---syndic---minion setup.

```
[root@li992-107 ~]# salt minion2 test.ping
minion2:
    True
[root@li992-107 ~]# curl -k http://127.0.0.1:8100          -H 'Content-type: application/json'         -H "X-Auth-Token: 7d324146cb01896c2bd8d5f20f4c249ab719064de35c4fa2909d96b252db0ac6"  -d '[{"client": "local","tgt": "minion2","fun": "test.ping"}]'
{"return": [{}]}[root@li992-107 ~]# 
[root@li992-107 ~]# salt --version
salt 2017.7.5-441-g4627bad (Nitrogen)
```

I see this in the api log
```
2018-05-08 14:45:02,603 [salt.transport.zeromq:92  ][DEBUG   ][8870] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'li992-107.members.linode.com_master', 'tcp://127.0.0.1:4506', 'clear')
2018-05-08 14:45:02,604 [salt.transport.zeromq:35  ][TRACE   ][8870] Inserted key into loop_instance_map id 51304712 for key ('/etc/salt/pki/master', 'li992-107.members.linode.com_master', 'tcp://127.0.0.1:4506', 'clear') and process 8870
2018-05-08 14:45:02,605 [salt.transport.ipc:255 ][DEBUG   ][8870] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
2018-05-08 14:45:02,606 [salt.transport.ipc:35  ][TRACE   ][8870] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
2018-05-08 14:45:09,853 [salt.utils.process:35  ][TRACE   ][8859] Process manager iteration
2018-05-08 14:45:19,864 [salt.utils.process:35  ][TRACE   ][8859] Process manager iteration
2018-05-08 14:45:29,874 [salt.utils.process:35  ][TRACE   ][8859] Process manager iteration
2018-05-08 14:45:39,885 [salt.utils.process:35  ][TRACE   ][8859] Process manager iteration
2018-05-08 14:45:49,896 [salt.utils.process:35  ][TRACE   ][8859] Process manager iteration
2018-05-08 14:45:59,907 [salt.utils.process:35  ][TRACE   ][8859] Process manager iteration
2018-05-08 14:46:02,834 [tornado.access   :1907][INFO    ][8870] 200 POST / (127.0.0.1) 65277.15ms
2018-05-08 14:46:09,917 [salt.utils.process:35  ][TRACE   ][8859] Process manager iteration
2018-05-08 14:46:19,928 [salt.utils.process:35  ][TRACE   ][8859] Process manager iteration
2018-05-08 14:46:29,939 [salt.utils.process:35  ][TRACE   ][8859] Process manager iteration
2018-05-08 14:46:39,949 [salt.utils.process:35  ][TRACE   ][8859] Process manager iteration
2018-05-08 14:46:49,960 [salt.utils.process:35  ][TRACE   ][8859] Process manager iteration
```

**Comment by rallytime** [comment]
@frogunder Can you test this again with the fix in #48193 when you get a moment?

**Comment by frogunder** [comment]
@rallytime this is working for me now with that fix

**Comment by rallytime** [comment]
@frogunder Fantastic! Thank you for confirming.
