### ISSUE TITLE
Using zmq built with --enable-draft breaks Salt

### ISSUE THREAD

**Issue by dragonpaw** [saltstack/salt#43995]
### Description of Issue/Question

Recently we were experimenting with using ZMQ transport for one of our own apps using the newer draft protocols. (Also PY3, though unsure if that matters) To do this we rebuilt the pyzmq module and this broke Salt badly. Though this isn't currently the default build for ZMQ, my understanding is that it will be one day RealSoonNow(TM).

```
salt-call state.apply base.foo
[WARNING ] py.warnings - /usr/local/lib/python3.5/dist-packages/salt/minion.py:652: DeprecationWar
ning: ZMQLoop and zmq.eventloop.ioloop.install are deprecated in pyzmq 17. Special eventloop integ
ration is no longer needed.
  io_loop = zmq.eventloop.ioloop.ZMQIOLoop()

Exception ignored in: <bound method AsyncZeroMQReqChannel.__del__ of <salt.transport.zeromq.AsyncZ
eroMQReqChannel object at 0x7f837e616908>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/salt/transport/zeromq.py", line 169, in __del__
    self.message_client.destroy()
  File "/usr/local/lib/python3.5/dist-packages/salt/transport/zeromq.py", line 862, in destroy
    message_client.destroy()
  File "/usr/local/lib/python3.5/dist-packages/salt/transport/zeromq.py", line 917, in destroy
    self.stream.io_loop.remove_handler(self.stream.socket)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 735, in remove_handler
    fd, obj = self.split_fd(fd)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 657, in split_fd
    return fd.fileno(), fd
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 161, in fileno
    return self.FD
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/attrsettr.py", line 45, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/attrsettr.py", line 49, in _get_attr_opt
    return self.get(opt)
  File "zmq/backend/cython/socket.pyx", line 477, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 137, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
```

### Steps to Reproduce Issue
`pip3 install pyzmq --no-binary :all: --verbose --pre --install-option=--enable-drafts --upgrade --force-reinstall`

Reinstall zmq as above but without the `--install-option=--enable-drafts` and the errors disappear again.

### Versions Report
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 17 2016, 17:05:23)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0.b1
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-93-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I am able to replicate this error, and a similar warning on python2.  It still works and is able to transport , but it throws some errors that should be fixed.

Thanks for letting us know.

```
[root@salt ~]# salt \* test.ping
[WARNING ] /root/src/salt/salt/utils/async.py:56: DeprecationWarning: ZMQLoop and zmq.eventloop.ioloop.install are deprecated in pyzmq 17. Special eventloop integration is no longer needed.
  self.io_loop = LOOP_CLASS()

Exception ignored in: <bound method AsyncZeroMQReqChannel.__del__ of <salt.transport.zeromq.AsyncZeroMQReqChannel object at 0x7ff616585dd8>>
Traceback (most recent call last):
  File "/root/src/salt/salt/transport/zeromq.py", line 160, in __del__
    self.message_client.destroy()
  File "/root/src/salt/salt/transport/zeromq.py", line 853, in destroy
    message_client.destroy()
  File "/root/src/salt/salt/transport/zeromq.py", line 908, in destroy
    self.stream.io_loop.remove_handler(self.stream.socket)
  File "/usr/lib64/python3.6/site-packages/tornado/ioloop.py", line 735, in remove_handler
    fd, obj = self.split_fd(fd)
  File "/usr/lib64/python3.6/site-packages/tornado/ioloop.py", line 657, in split_fd
    return fd.fileno(), fd
  File "/usr/lib64/python3.6/site-packages/zmq/sugar/socket.py", line 161, in fileno
    return self.FD
  File "/usr/lib64/python3.6/site-packages/zmq/sugar/attrsettr.py", line 45, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/usr/lib64/python3.6/site-packages/zmq/sugar/attrsettr.py", line 49, in _get_attr_opt
    return self.get(opt)
  File "zmq/backend/cython/socket.pyx", line 477, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 137, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Exception ignored in: <bound method AsyncReqMessageClientPool.__del__ of <salt.transport.zeromq.AsyncReqMessageClientPool object at 0x7ff616585518>>
Traceback (most recent call last):
  File "/root/src/salt/salt/transport/zeromq.py", line 849, in __del__
    self.destroy()
  File "/root/src/salt/salt/transport/zeromq.py", line 853, in destroy
    message_client.destroy()
  File "/root/src/salt/salt/transport/zeromq.py", line 908, in destroy
    self.stream.io_loop.remove_handler(self.stream.socket)
  File "/usr/lib64/python3.6/site-packages/tornado/ioloop.py", line 735, in remove_handler
    fd, obj = self.split_fd(fd)
  File "/usr/lib64/python3.6/site-packages/tornado/ioloop.py", line 657, in split_fd
    return fd.fileno(), fd
  File "/usr/lib64/python3.6/site-packages/zmq/sugar/socket.py", line 161, in fileno
    return self.FD
  File "/usr/lib64/python3.6/site-packages/zmq/sugar/attrsettr.py", line 45, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/usr/lib64/python3.6/site-packages/zmq/sugar/attrsettr.py", line 49, in _get_attr_opt
    return self.get(opt)
  File "zmq/backend/cython/socket.pyx", line 477, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 137, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
salt:
    True
Exception ignored in: <bound method AsyncReqMessageClient.__del__ of <salt.transport.zeromq.AsyncReqMessageClient object at 0x7ff61652e630>>
Traceback (most recent call last):
  File "/root/src/salt/salt/transport/zeromq.py", line 917, in __del__
    self.destroy()
  File "/root/src/salt/salt/transport/zeromq.py", line 908, in destroy
    self.stream.io_loop.remove_handler(self.stream.socket)
  File "/usr/lib64/python3.6/site-packages/tornado/ioloop.py", line 735, in remove_handler
    fd, obj = self.split_fd(fd)
  File "/usr/lib64/python3.6/site-packages/tornado/ioloop.py", line 657, in split_fd
    return fd.fileno(), fd
  File "/usr/lib64/python3.6/site-packages/zmq/sugar/socket.py", line 161, in fileno
    return self.FD
  File "/usr/lib64/python3.6/site-packages/zmq/sugar/attrsettr.py", line 45, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/usr/lib64/python3.6/site-packages/zmq/sugar/attrsettr.py", line 49, in _get_attr_opt
    return self.get(opt)
  File "zmq/backend/cython/socket.pyx", line 477, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 137, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
```

To test this, I am uploading a docker container `gtmanfred/issues:43995`

To start this, run

```
docker run -d --privileged --name testzmq gtmanfred/issues:43995
docker exec -ti testzmq bash
```

salt is installed with python 3.6 and in `/root/src/salt`

@saltstack/team-core 

Thanks,
Daniel

**Comment by DmitryKuzmenko** [comment]
I've met such issues before. The issue happened when tornado's `io_loop` passed with a ZMQ socket object. I mean original tornado `io_loop`, not ZMQ `io_loop`. And the issue was produced by the transport layer by falling back to creation of a default `io_loop` when no one have been passed by arguments.
But I'm not sure how urgen this issue since `drafts` are unstable for now: https://github.com/zeromq/pyzmq/blob/master/docs/source/draft.rst

**Comment by Ch3LL** [comment]
@DmitryKuzmenko this has been approved as a 2017.7.3 blocker. would you mind taking a look at a fix for this?

**Comment by DmitryKuzmenko** [comment]
Fixed by #45368

**Comment by dawidmalina** [comment]
When this ticket will be closed? Isn't fixed? If fixed when 2017.7.3 will be released?

**Comment by DmitryKuzmenko** [comment]
Yes, it could be closed. It's merged into 2017.7 branch that means it will be released in 2017.7 and oxygen.

**Comment by dawidmalina** [comment]
Ok the question is when as all tickets from this milestone are closed now.

**Comment by gtmanfred** [comment]
Soon, if you want to follow the actual release tracking, we have #releases channel in our community slack where updates on testing the tag will be put.

you can get an invite to it here. https://saltstackcommunity.herokuapp.com
