### ISSUE TITLE
How to checkout git tag v2017.7.2 ?

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#44043]
### Description of Issue/Question
I want to checkout tag v2017.7.2 to build the Windows installer. 

`git checkout v2017.7.0` works fine
`git checkout v2017.7.1` works fine
`git checkout v2017.7.2` results in "error: pathspec 'v2017.7.2' did not match any file(s) known to git."

### Setup
```
git clone https://github.com/markuskramerIgitt/salt.git
git remote add upstream https://github.com/saltstack/salt.git
git fetch --all
git pull upstream develop
```

**Comment by gtmanfred** [comment]
You can try `git fetch --tags` but `git fetch --all` should be working.

The tag is available on the remote https://github.com/saltstack/salt/tree/v2017.7.2

**Comment by markuskramerIgitt** [comment]
After both `git fetch --tags` and `git fetch -all`, still the same error on `git checkout v2017.7.2`

**Comment by markuskramerIgitt** [comment]
My fork seems to cause the problem. 
I can checkout the tag when I clone directly github.com/saltstack/salt.git
I will build the Windows installer with a direct clone of  saltstack/salt.git

**Comment by markuskramerIgitt** [comment]
To retrieve all tags from upstream one must use `git fetch --tags --all`
`--tags` means "all tags"
`--all` means "all remotes" (i.e. origin and upstream)

The procedure to update the GithHub fork therefore is:
```
git clone https://github.com/markuskramerIgitt/salt.git
git remote add upstream https://github.com/saltstack/salt.git
.
.
.
git fetch --tags --all
git pull upstream develop
```
