### ISSUE TITLE
WIN_LGPO requires unsetting certain policies before configuring new policies

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#46236]
### Description of Issue/Question
When trying to use the `lgpo.set` state I get the following error if some Group Policies are set (listed in Steps to Produce):
```
# sudo salt 'minion1' state.apply config_win_updates
minion1:
----------
          ID: My Local Group Policy
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1851, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 301, in set_
                  adml_language=adml_language)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 5525, in set_
                  raise CommandExecutionError(msg)
              CommandExecutionError: Error while attempting to write Administrative Template Policy data.  Some changes may not be applied as expected
     Started: 10:30:07.663000
    Duration: 93120.0 ms
     Changes:   

Summary for minion1
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  93.120 s
```

The request is for the module to not fail when these settings are pre-configured. I thought of just adding these settings to my state to have the state set them, but they are not available for configuration in the `win_lgpo.py` module. 

### Setup
Configure a master on 2017.7.3 (Any Linux OS)
Configure a 2017.7.3 Python 2 AMD64 minion on Windows 10/2016

### Steps to Reproduce Issue
Manually configure any of the settings in this list to anything but "Not Configured". From what I can tell it can be any mix of these, but as long as at least one of them is configured the error will occur:
```
Prevent installation of devices using drivers 
Prevent installation of devices that match any of these device IDs 
Join Microsoft MAPS
Send file samples when further analysis is required
Let Windows apps access trusted devices
Let Windows apps access location
Let Windows apps access messaging
Let Windows apps access account information
Let Windows apps access calendar
Let Windows apps access motion
Let Windows apps access contacts
Let Windows apps access email
Let Windows apps access camera
Boot-Start Driver Initialization Policy
Configure Windows Defender Smartscreen
Prevent bypassing Windows Defender SmartScreen prompts for sites
Enable/Disable PerfTrack
Turn off the Windows Messenger Customer Experience Improvement Program
Turn off Windows Error Reporting
Configure Offer Remote Assistance
```

Then run this state:
```
Company Local Group Policy:
    lgpo.set:
        - computer_policy:
            Configure Automatic Updates:
                Configure automatic updating: 4 - Auto download and schedule the install
                Scheduled install day: 0 - Every day
                Scheduled install time: "14:00"
                Install during automatic maintenance: True
                Install updates for other Microsoft products: True
                'If you have selected “4 – Auto download and schedule the install” for your scheduled install day and specified a schedule, you also have the option to limit updating to a weekly, bi-weekly or monthly occurrence, using the options below: Every week': True
                First week of the month: False
                Second week of the month: False
                Third week of the month: False
                Fourth week of the month: False
```
### Versions Report
```
    Salt Version:
               Salt: 2017.7.3
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: unknown
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.16299  Multiprocessor Free
```

**Comment by doesitblend** [comment]
ZD-2280

**Comment by twangboy** [comment]
@lomeroe ^^^

**Comment by lomeroe** [comment]
sorry, just realized I'm not getting github email notifications for some reason...

I don't see the "If you have selected..." item under 'Configure Automatic Updates' in either a Win2016 or Win10 system I have access to.

Was that added in a rollup or something that I am missing?  Or added by SCCM or something else?

I have no issues without that (in fact, my system won't even render the yaml with that item line in there, throwing a decode error).

**Comment by kevinhe-okta** [comment]
Hi,

I might be able to add some additional info as I was the one who sent in the ticket for this.

I noticed that the additional configuration items under "Configure Automatic Updates" were added in the 1709 version of Windows 10 Enterprise. The details of one of the laptops I'm testing on is:
- Edition: Windows 10 Enterprise
- Version: 1709
- OS Build: 16299.125

I think these settings were added in 1709 as I did not see these before updating from 1703 to 1709.

As far as the issues with rendering the yaml with that line in there. I am not sure what to add other than I don't get a rendering error.

If anyone needs any additional info from me, please let me know.

Thanks

**Comment by lomeroe** [comment]
@kevinhe-okta thanks for the additional info. 

No worries on the yaml error, I'm sure it was on my end and I should have probably left that out.

I'll have to see if I can get access to a Win10 v1709.

Could you run this command and provide the output:
```
salt-call --local lgpo.get_policy_info "Configure Automatic Updates" machine
```

Additionally, from the output of that command, would you take the "element_id" of the "If you selected..." policy element and run this powershell and provide the output:
```
Get-childitem c:\windows\PolicyDefinitions\ -Recurse | select-string ELEMENT_ID_HERE
```

**Comment by kevinhe-okta** [comment]
@lomeroe Sure the output for the first command was:

```
PS C:\WINDOWS\system32> salt-call --local lgpo.get_policy_info "Configure Automatic Updates" machine
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Failed to import grains aws:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1334, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "c:\salt\var\cache\salt\minion\extmods\grains\aws.py", line 2, in <module>
    import boto3
ImportError: No module named boto3
[CRITICAL] Failed to load grains defined in grain file kb4041676_flag_grain.testGrains in function <function testGrains at 0x0000000007A57DD8>, error:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 724, in grains
    ret = fun()
  File "c:\salt\var\cache\salt\minion\extmods\grains\kb4041676_flag_grain.py", line 3, in testGrains
    with open('C:\kb4041676_flag') as f:
IOError: [Errno 2] No such file or directory: 'C:\\kb4041676_flag'
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded lgpo.get_policy_info
[DEBUG   ] LazyLoaded file.file_exists
[DEBUG   ] found an ADML entry matching the string! {Microsoft.Policies.WindowsUpdate}string -- {'id': 'AutoUpdateCfg'}
[DEBUG   ] searching for displayName == $(string.AutoUpdateCfg)
[DEBUG   ] found the ADMX policy matching the display name Configure Automatic Updates -- <Element {Microsoft.Policies.WindowsUpdate}policy at 0x93e5f08>
[DEBUG   ] LazyLoaded nested.output
local:
    ----------
    message:
    policy_aliases:
        - Configure Automatic Updates
        - AutoUpdateCfg
        - Windows Components\Windows Update\Configure Automatic Updates
    policy_class:
        machine
    policy_elements:
        |_
          ----------
          element_aliases:
              - AutoUpdateMode
              - Configure automatic updating
          element_id:
              AutoUpdateMode
        |_
          ----------
          element_aliases:
              - AutoUpdateAutomaticMaintenanceEnabled
              - Install during automatic maintenance
          element_id:
              AutoUpdateAutomaticMaintenanceEnabled
        |_
          ----------
          element_aliases:
              - AutoUpdateSchDay
              - Scheduled install day
          element_id:
              AutoUpdateSchDay
        |_
          ----------
          element_aliases:
              - AutoUpdateSchTime
              - Scheduled install time
          element_id:
              AutoUpdateSchTime
        |_
          ----------
          element_aliases:
              - AllowMUUpdateServiceId
              - Install updates for other Microsoft products
          element_id:
              AllowMUUpdateServiceId
        |_
          ----------
          element_aliases:
              - AutoUpdateSchEveryWeek
              - If you have selected ΓÇ£4 ΓÇô Auto download and schedule the installΓÇ¥ for your scheduled install day and specified a schedule, you also have the option to limit updating to a weekly, bi-weekly or monthly occurrence, using the options below: Every week
          element_id:
              AutoUpdateSchEveryWeek
        |_
          ----------
          element_aliases:
              - AutoUpdateSchFirstWeek
              - First week of the month
          element_id:
              AutoUpdateSchFirstWeek
        |_
          ----------
          element_aliases:
              - AutoUpdateSchSecondWeek
              - Second week of the month
          element_id:
              AutoUpdateSchSecondWeek
        |_
          ----------
          element_aliases:
              - AutoUpdateSchThirdWeek
              - Third week of the month
          element_id:
              AutoUpdateSchThirdWeek
        |_
          ----------
          element_aliases:
              - AutoUpdateSchFourthWeek
              - Fourth week of the month
          element_id:
              AutoUpdateSchFourthWeek
    policy_found:
        True
    policy_name:
        Configure Automatic Updates
    rights_assignment:
        False
```

The result of the Get-childitem command is:

```
PS C:\WINDOWS\system32> Get-ChildItem C:\windows\PolicyDefinitions\ -Recurse | select-string AutoUpdateSchEveryWeek

C:\windows\PolicyDefinitions\WindowsUpdate.admx:346:        <boolean id="AutoUpdateSchEveryWeek"
valueName="ScheduledInstallEveryWeek" />
C:\windows\PolicyDefinitions\en-US\WindowsUpdate.adml:585:        <checkBox refId="AutoUpdateSchEveryWeek"
defaultChecked="true">Every week</checkBox>
```

**Comment by lomeroe** [comment]
Does it make any difference if you use the element_id to define that setting?

In other words:
```
Company Local Group Policy:
    lgpo.set:
        - computer_policy:
            Configure Automatic Updates:
                Configure automatic updating: 4 - Auto download and schedule the install
                Scheduled install day: 0 - Every day
                Scheduled install time: "14:00"
                Install during automatic maintenance: True
                Install updates for other Microsoft products: True
                AutoUpdateSchEveryWeek: True
                First week of the month: False
                Second week of the month: False
                Third week of the month: False
                Fourth week of the month: False
```

**Comment by lomeroe** [comment]
@doesitblend this should be fixed in #46800 

can you test with that version of win_lgpo.py and let me know?

**Comment by rallytime** [comment]
@doesitblend Can you follow up here?

**Comment by doesitblend** [comment]
@rallytime @lomeroe This does not seem to quite fix the issue. I think this is close. I am attaching this screenshot to demonstrate what I am still seeing. I see that the settings I configured manually previously were configured and they appear correctly in `gpedit.msc`. However, for Windows Updates I have what you see in the screenshot. This may actually be okay, but I'm not an expert on Windows. This is on Windows 2016 with Python 2 and Salt 2017.7.3. I will test again shortly with 2017.7.5 and let you know if I still see the same issue.

![screen shot 2018-04-17 at 2 39 56 pm](https://user-images.githubusercontent.com/31517589/38895446-4fa31272-424d-11e8-8201-490923bd28f1.png)

**Comment by doesitblend** [comment]
@lomeroe @rallytime I tested this again with the same setup, but with 2017.7.5 and had the same result as above.

**Comment by doesitblend** [comment]
@rallytime Yes, I'm pulling the raw file, placing that in `_modules` and syncing that to the target minion for testing the module.

**Comment by rallytime** [comment]
Thanks @doesitblend for confirming.

@lomeroe and @twangboy can you take another look at this issue? Thanks!

**Comment by lomeroe** [comment]
@doesitblend can you provide what you have for your 'Configure Offer Remote Assistance' policy settings?

These lines in your debug file are perplexing to me, as element_valuenames and element_values should be equal in that particular policy
```
2018-04-02 22:41:58,992 [salt.loaded.ext.module.win_lgpo:3474][DEBUG   ][2736] _processValueItem has an explicit element_value of  
2018-04-02 22:41:58,992 [salt.loaded.ext.module.win_lgpo:3477][DEBUG   ][2736] element_valuenames == [1] and element_values ==  
```

For comparison my policy, with 'administrator' in the helpers element looks like this: 
```
[DEBUG   ] _processValueItem has an explicit element_value of ['administrator']
[DEBUG   ] element_valuenames == ['administrator'] and element_values == ['administrator']
```

**Comment by doesitblend** [comment]
@lomeroe Sorry for the delayed response. I rebuild this VM on a regular basis for testing. So I never configure this setting. 

I currently use the `mwrock/Windows2016` Vagrant image in Virtualbox. If you have a suggestion for a better image to test with I am happy to try that.

Here is the setting you wanted to know about.

![screen shot 2018-05-03 at 9 47 05 am](https://user-images.githubusercontent.com/31517589/39587532-fb2f9244-4eb6-11e8-8542-cfd44ea91187.png)

**Comment by lomeroe** [comment]
@doesitblend thanks for the screen shot, but that appears to be for 'Configure Solicited Remote Assistance' and not 'Configure Offer Remote Assistance', which is the policy causing an issue in your debug log.

If the 'Configure Offer Remote Assistance' is also not configured in your clean image, can you re-attempt to apply your policy and provide an updated debug log?

**Comment by doesitblend** [comment]
@lomeroe Testing this again in 2017.7.5 this issue appears fixed now.
