### ISSUE TITLE
[2018.3.0rc1] jinja indent filter now returns invalid output

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#46594]
### Description of Issue/Question

(This worked fine on 2017.x, as far back as 2016.x)
Some of my more complex states are now broken if they use the ```yaml(False)```

Some pillar data i fetched from a database/files.
```
[root@cronos /salt/states/smartos]# salt carbon pillar.get smartos:zones:isotope
carbon:
    ----------
    alias:
        isotope
    brand:
        joyent
    cpu_cap:
        800
    cpu_shares:
        50
    customer_metadata:
        ----------
        minion_key:
            -----BEGIN RSA PRIVATE KEY-----
            data here
            -----END RSA PRIVATE KEY-----
        minion_pub:
            -----BEGIN PUBLIC KEY-----
            data here
            -----END PUBLIC KEY-----
        primary_mac:
            aa:bb:cc:dd:ee:ff
    dns_domain:
        vlan10.example.org
    filesystems:
        ----------
        /workspace:
            ----------
            options:
                - nodevice
            source:
                /zdata/isotope
            type:
                lofs
    hostname:
        isotope
    image_uuid:
        a0dd9320-674b-11e7-9483-2ff90b43b416
    max_physical_memory:
        16384
    nics:
        ----------
        aa:bb:cc:dd:ee:ff:
            ----------
            gateways:
                - xx.xx.xx.1
            ips:
                - xx.xx.xx.yyy/24
                - xx:xx:xx:xx::yyy/64
            mtu:
                1500
            nic_tag:
                trunk
            primary:
                True
            vlan_id:
                10
    quota:
        10
    resolvers:
        - xx.xx.xx.1
        - xx:xx:xx:xx::1
    tags:
        ----------
        description:
            saltstack development workstation
        storage_data_path:
            /workspace
    zfs_io_priority:
        50
    zfs_root_compression:
        lz4
```

The following macro is used to generate the actual state SLS
```
{% macro add_zone(zone, zonecfg) %}
smartos.zone::{{ zone }}:
  smartos.vm_present:
    - name: {{ zone }}
    - config:
        reprovision: true
        auto_import: false
    - vmconfig:
        {{ zonecfg|yaml(False)|indent(8) }}
        {{- _create_check(zonecfg) -}}
        {{- _lx_check(zonecfg) -}}
{% endmacro %}
```

The state fails on:
```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:smartos' failed: expected alphabetic or numeric character, but found '#'; line 555

---
[...]
        alias: isotope
        brand: joyent
        cpu_cap: 800
        cpu_shares: 50
        customer_metadata:
          minion_key: &#39;-----BEGIN RSA PRIVATE KEY-----    <======================

            data here

            more data here

[...]
---
```

On previous versions of salt the ```&#39;``` is not there, it seems to chocke on these.

### Steps to Reproduce Issue
See above.

### Versions Report
```
[root@carbon ~]# salt-call --versions-report
Salt Version:
           Salt: 2018.3.0rc1
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: 8.8.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: 1.6.7
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Dec 30 2017, 15:38:16)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: 0.6.6
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: 646
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed

```

This does have the x509 and nacl fixes applied on top of rc1, but those should not effect this.

**Comment by sjorge** [comment]
I've narrowed it down to issues with ```-``` if I don't have any of those in the output it works fine.

**Comment by sjorge** [comment]
I think I've narrowed some characters that are used in yaml, like '-' at the beginning of a line.

```hello``` -> OK
```hello-world``` -> OK
```-hello-world-``` -> NOT OK

**Comment by sjorge** [comment]
It looks like once the yaml filter needs to quote the string it goes south.

E.g. a simpler string holding a mac-address has the same issue that it gets ```&#39;``` which is probably ' or " encoded in some way.

**Comment by sjorge** [comment]
Took me a while to find out where the filter came from ... https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.jinja.html#salt.renderers.jinja.render

**Comment by sjorge** [comment]
It a unicode thing, revering the change from https://github.com/saltstack/salt/commit/c65d4714e52000260512286d8d33ab40b5161975#diff-ba5eb26a99dc1516dc97de22dbcbeea4 in salt.renderer.jinja fixes the problem.

**Comment by rallytime** [comment]
@terminalmage Can you look into this one?

**Comment by terminalmage** [comment]
@sjorge I can't reproduce this. Can you provide a more concise example that I could use to troubleshoot this? Preferably one that doesn't involve using a smartos-specific state, but I can deal with if you can't. So far, I've been troubleshooting by stepping through the jinja renderer in a debugger and checking the rendered output before Salt tries to run the state. This is what I get:

```yaml

smartos.zone::foo:
  smartos.vm_present:
    - name: foo
    - config:
        reprovision: true
        auto_import: false
    - vmconfig:
        minion_key: '-----BEGIN RSA PRIVATE KEY-----

          data here

          -----END RSA PRIVATE KEY-----

        '
        minion_pub: '-----BEGIN PUBLIC KEY-----

          data here

          -----END PUBLIC KEY-----

        '
        primary_mac: aa:bb:cc:dd:ee:ff
```

**Comment by terminalmage** [comment]
Also, keep in mind that the `yaml` filter is part of jinja itself. It's more likely that whatever is causing this is within `salt/utils/templates.py`, in the `render_jinja_tmpl()` function.

**Comment by terminalmage** [comment]
OK, I actually misread the code, we *do* have the `yaml` filter defined in Salt code. So, this issue is most likely within our YAML dumper, or `salt.utils.jinja.SerializerExtension.format_yaml()`.

**Comment by terminalmage** [comment]
It might also help if you do an `--out=pprint` when dumping the pillar data so I can see what is actually in the pillar data, instead of guessing from the nested outputter.

**Comment by sjorge** [comment]
dumping a key file into a pillar (very simplified of what I do)

```
#!py
# Saltstack Issue 46594
# dump a key into a pillar via python

import os
key_file = "/opt/local/etc/salt/pki/minion/minion.pub"

def run():
  data = {}
  data['test_data'] = {}
  data['test_data']['name'] = '/tmp/test.key'
  data['test_data']['contents'] = open(key_file, 'r').read()
  return data
```

```
# Saltstack Issue 46594
# generate a state from the pillar
{% macro dump_pillar_file(id) %}
{% set data = salt.pillar.get(id) %}
issue::46594::{{ id }}:
  file.managed:
    - name: {{ data['name'] }}
    - contents: dummy
    - context:
        {{ data|yaml(False)|indent(8) }}
{% endmacro %}

{{ dump_pillar_file('test_data') }}
```

This is a minimal stripped example, here is the output again
```
[root@carbon ~]# salt-call -l debug state.sls test
[DEBUG   ] Reading configuration from /opt/tools/etc/salt/minion
[DEBUG   ] Including configuration from '/opt/tools/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /opt/tools/etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/opt/tools/etc/salt/minion.d/smtp.conf'
[DEBUG   ] Reading configuration from /opt/tools/etc/salt/minion.d/smtp.conf
[DEBUG   ] Including configuration from '/opt/tools/etc/salt/minion.d/staterun.conf'
[DEBUG   ] Reading configuration from /opt/tools/etc/salt/minion.d/staterun.conf
[DEBUG   ] Including configuration from '/opt/tools/etc/salt/minion.d/tweaks.conf'
[DEBUG   ] Reading configuration from /opt/tools/etc/salt/minion.d/tweaks.conf
[DEBUG   ] Configuration file path: /opt/tools/etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /opt/tools/etc/salt/minion
[DEBUG   ] Including configuration from '/opt/tools/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /opt/tools/etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/opt/tools/etc/salt/minion.d/smtp.conf'
[DEBUG   ] Reading configuration from /opt/tools/etc/salt/minion.d/smtp.conf
[DEBUG   ] Including configuration from '/opt/tools/etc/salt/minion.d/staterun.conf'
[DEBUG   ] Reading configuration from /opt/tools/etc/salt/minion.d/staterun.conf
[DEBUG   ] Including configuration from '/opt/tools/etc/salt/minion.d/tweaks.conf'
[DEBUG   ] Reading configuration from /opt/tools/etc/salt/minion.d/tweaks.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Loading static grains from /opt/tools/etc/salt/grains
[INFO    ] Executing command 'vmadm list -p -o uuid,alias,state,type' in directory '/root'
[DEBUG   ] output: private data here
[INFO    ] Executing command 'sysinfo' in directory '/root'
[DEBUG   ] output: {
private data here
}
[INFO    ] Executing command '/usr/sbin/zpool list -H -p -o name,size' in directory '/root'
[DEBUG   ] output: private data here
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Master URI: tcp://[2001:470:7ee7:30::130]:4506
[DEBUG   ] Initializing new AsyncAuth for (u'/usbkey/salt/pki/minion', u'carbon', u'tcp://[xx:xx:xx:xx::xx:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9895)
[DEBUG   ] Setting zmq_reconnect_ivl to '9895ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/usbkey/salt/pki/minion', u'carbon', u'tcp://[xx:xx:xx:xx::xx]:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://[xx:xx:xx:xx::xx]:4506
[DEBUG   ] Trying to connect to: tcp://[xx:xx:xx:xx::xx]:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: /usbkey/salt/pki/minion/minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://[xx:xx:xx:xx::xx]:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /usbkey/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/usbkey/salt/pki/minion', u'carbon', u'tcp://[xx:xx:xx:xx::xx]:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/usbkey/salt/pki/minion', u'carbon', u'tcp://[xx:xx:xx:xx::xx0]:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://[xx:xx:xx:xx::xx]:4506
[DEBUG   ] Trying to connect to: tcp://[xx:xx:xx:xx::xx0]:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /usbkey/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/usbkey/salt/pki/minion', u'carbon', u'tcp://[xx:xx:xx:xx::xx]:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/usbkey/salt/pki/minion', u'carbon', u'tcp://[xx:xx:xx:xx::xx]:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://[xx:xx:xx:xx::xx]:4506
[DEBUG   ] Trying to connect to: tcp://[2001:470:7ee7:30::130]:4506
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'test.sls' to resolve 'salt://test.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/test.sls' to resolve 'salt://test.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/test.sls
[DEBUG   ] Jinja search path: [u'/var/cache/salt/minion/files/base']
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/usbkey/salt/pki/minion', u'carbon', u'tcp://[xx:xx:xx:xx::xx]:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/usbkey/salt/pki/minion', u'carbon', u'tcp://[xxx:xx:xx:xx::xx]:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://[xx:xx:xx:xx::xx]:4506
[DEBUG   ] Trying to connect to: tcp://[xx:xx:xx:xx::xx]:4506
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test.sls' using 'jinja' renderer: 0.0283358097076
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/test.sls:
# Saltstack Issue 46594
# generate a state from the pillar




issue::46594::test_data:
  file.managed:
    - name: /tmp/test.key
    - contents: dummy
    - context:
        contents: '-----BEGIN PUBLIC KEY-----

          data here

          data here

          data herd

          data herd

          data here

          data here

          data here

          -----END PUBLIC KEY-----&#39;
        name: /tmp/test.key


[CRITICAL] Rendering SLS 'base:test' failed: found unexpected end of stream; line 31

---
[...]
          nwIDAQAB

          -----END PUBLIC KEY-----&#39;
        name: /tmp/test.key

    <======================
---
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/usbkey/salt/pki/minion', u'carbon', u'tcp://[xx:xx:xx:xx:xx:xx]:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/usbkey/salt/pki/minion', u'carbon', u'tcp://[xx:xx:xx:xx:xx:xx]:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://[xx:xx:xx:xx:xx:xx]:4506
[DEBUG   ] Trying to connect to: tcp://[xx:xx:xx:xx:xx:xx]:4506
[DEBUG   ] LazyLoaded highstate.output
local:
    Data failed to compile:
----------
    Rendering SLS 'base:test' failed: found unexpected end of stream; line 31

---
[...]
          nwIDAQAB

          -----END PUBLIC KEY-----&#39;
        name: /tmp/test.key

    <======================
---
```

**Comment by sjorge** [comment]
```[root@carbon ~]# salt-call --out=pprint pillar.get test_data
{u'local': {'contents': '-----BEGIN PUBLIC KEY-----\ndata\ndata\ndata\ndata\ndata\ndata\n-----END PUBLIC KEY-----',
            'name': '/tmp/test.key'}}
```

**Comment by terminalmage** [comment]
@sjorge Thanks! Taking a look now. I can confirm that the contents I had in my pillar data looked the same as yours.

**Comment by sjorge** [comment]
Might it have something to do with the locale being 'locale: 646' ? I just noticed it is not UTF-8 like I would expect and I have no idea why.

**Comment by terminalmage** [comment]
I thought it might, but I just edited `salt/__init__.py` and forced `__salt_system_encoding__` to `'646'` and I still can't reproduce. We try to auto-detect the system encoding, and `646` (i.e. ascii) is what is being detected.

**Comment by terminalmage** [comment]
I'm going to upgrade my jinja2 and PyYAML versions to match yours and test again.

**Comment by terminalmage** [comment]
Bingo! Seems to be a change in yaml or jinja2, as I'm now able to reproduce with the versions matching yours. I'll keep digging.

**Comment by terminalmage** [comment]
@sjorge OK, this breaks with jinja2 2.10 but not any previous versions. If you downgrade jinja2 to version 2.9.6, it should get rid of the error. I'll continue to narrow this down.

**Comment by terminalmage** [comment]
@sjorge This definitely looks like an upstream bug in jinja2. I can reproduce this on 2017.7 with jinja2 2.10.

**Comment by terminalmage** [comment]
OK, so the problem comes when jinja2 uses markupsafe to concatenate a string to a `markupsafe.Markup` instance.

```python
>>> from markupsafe import Markup
>>> Markup('foo bar\n') + "'"
Markup(u'foo bar\n&#39;')
>>> Markup('foo bar\n') + "'This is a test'"
Markup(u'foo bar\n&#39;This is a test&#39;')
```

In version 2.10, jinja2 changed how it's indent filter works, and now it does concatenation: https://github.com/pallets/jinja/commit/bb8ef40#diff-33dcdc15f917259c644200be7d924eb0R552

**Comment by sjorge** [comment]
@terminalmage I did not update jinja2 or pyyaml though, as they came form the system itself.

Let me try in a virtualenv with older versions to verify the problem is gone.

**Comment by sjorge** [comment]
Ok I completely borked most of the setup by manually installing jinja2-2.9 by copying the files from a different system, although salt no longer works the example you posted above now works correctly on the python shell.

Although that does not explain why the older salt did not have issues with the newer jinja2

**Comment by terminalmage** [comment]
But it does, or at least did in my testing.

**Comment by sjorge** [comment]
Odd, maybe something else changed between 2017 and 2018, maybe the string was not quoted before. Let me try and reinstall the entire compute node with older salt.

**Comment by terminalmage** [comment]
OK. From what I can see, there is no way any of this happens in Salt code, it's purely a byproduct of concatenating string types to `markupsafe.Markup` objects.

It turns out there was already an open bug report for this upstream, I've added a comment: https://github.com/pallets/jinja/issues/823#issuecomment-374319123

I've also opened a PR upstream to fix it: https://github.com/pallets/jinja/pull/826

**Comment by terminalmage** [comment]
@sjorge did you have a chance to test again?

**Comment by sjorge** [comment]
Manually downgrading with pip did indeed fix it.
Looks like your upstream fix got merged, so hopefully the 2018Q1 branch of pkgsrc will include the fixed upstream package.

**Comment by terminalmage** [comment]
OK, thanks for the follow-up. I'm going to go ahead and close it since we ended up finding the root cause and got it fixed upstream. Thanks for your help troubleshooting!

**Comment by jessebye** [comment]
@terminalmage is there something we can do to update to the fixed jinja2 version? I tried `pip install --upgrade jinja2` which installed `2.10` and still had the problem. To fix, I did `pip install -I jinja2==2.9` to downgrade to a working version.

**Comment by unix196** [comment]
Now in pip last verion of the Jinja2 is still 2.10 and  we have the same problem.

**Comment by unix196** [comment]
thanks!

**Comment by jessebye** [comment]
@terminalmage It looks like there is a new release 2.10.1 as of April 6, 2019. After upgrading to this version with `sudo pip install --upgrade Jinja2==2.10.1` and `sudo systemctl restart salt-minion` on affected machines, the problem is resolved!

**Comment by MeirSaada** [comment]
@jessebye Just tried what you proposed but it still fails. I had to go for `Jinja2 == 2.11.2` in order to get the fix.

**Comment by terminalmage** [comment]
Yeah, it seems that my upstream PR did not make it into 2.10, but rather 2.11.

I recently worked around this in https://github.com/saltstack/salt/pull/56860, so in the Sodium release this will be fixed even if you're not on Jinja >= 2.11.
