### ISSUE TITLE
getfullargspec and annotations

### ISSUE THREAD

**Issue by pimiento** [saltstack/salt#48735]
### Description of Issue/Question
I've got a strange error when I use type hinting for my salt module:

```
  The minion function caused an exception: Traceback (most recent call last):  File "/opt/alt/python35/lib/python3.5/site-packages/salt/minion.py", line 1589, in _thread_return
    data)
  File "/opt/alt/python35/lib/python3.5/site-packages/salt/minion.py", line 323, in load_args_and_kwargs
    argspec = salt.utils.args.get_function_argspec(func)
  File "/opt/alt/python35/lib/python3.5/site-packages/salt/utils/args.py", line 265, in get_function_argspec
    aspec = _getargspec(func)  # pylint: disable=redefined-variable-type
  File "/opt/alt/python35/lib/python3.5/site-packages/salt/utils/args.py", line 225, in _getargspec
    raise ValueError(\'Function has keyword-only arguments or annotations\'
   ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
   
'}}
```

The problem is that you check function annotations and raise an error when it has some annotations:

`site-packages/salt/utils/args.py`
```
   def _getargspec(func):
        '''
        Python 3 wrapper for inspect.getargsspec

        inspect.getargsspec is deprecated and will be removed in Python 3.6.
        '''
        args, varargs, varkw, defaults, kwonlyargs, _, ann = \
            inspect.getfullargspec(func)  # pylint: disable=no-member
        if kwonlyargs or ann:
            raise ValueError('Function has keyword-only arguments or annotations'
                             ', use getfullargspec() API which can support them')
        return _ArgSpec(args, varargs, varkw, defaults)
```

The code looks strange! There is a warning about `getargsspec` but you don't use `getargsspec`. There is exception message that give you advice to use `getfullargspec`, but you already use `getfullargspec`.

And I still don't know why do you raise an error if the function has an annotations. What is the reason?

### Versions Report
salt-minion 2018.3.0 (Oxygen)

**Comment by garethgreenaway** [comment]
@saltstack/team-core Thoughts?

**Comment by DmitryKuzmenko** [comment]
That check was added by @skizunov here https://github.com/saltstack/salt/pull/32329

@skizunov could you please take a look?

**Comment by skizunov** [comment]
@DmitryKuzmenko I took a fresh look at the code and I think it is fine to ignore annotations since they can exist, but we just won't make use of them (we don't need them to make the function calls, and we won't use them to do type validation at runtime). So I think the following code should be fine:

```
        args, varargs, varkw, defaults, kwonlyargs, _, _ = \
            inspect.getfullargspec(func)  # pylint: disable=no-member
        if kwonlyargs:
            raise ValueError('Function has keyword-only arguments'
                             ', use getfullargspec() API which can support them')
```

**Comment by DmitryKuzmenko** [comment]
Thank you @skizunov !
@pimiento could you please try to update you code with that suggestion?

**Comment by yur4enko** [comment]
issue is still valid.
this prevents the use of annotations

**Comment by terminalmage** [comment]
@yur4enko This should be resolved once https://github.com/saltstack/salt/pull/56713 is merged. It removes all use of getargspec and getfullargspec for Python 3, in favor of `inspect.Signature`.

**Comment by ShaneHutter** [comment]
I'm running a more recent version of SaltStack, and this still appears to be an issue.

```
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: 1.9.1
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: 0.28.1
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 0.28.0
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.11.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

In `salt/utils/arg.py` lines 27 to 43, `inspect.getfullargspec` is still in use, and this is throwing errors when writing modules whose arguments use type hints.
```
 27 def _getargspec(func):
 28     """
 29     Python 3 wrapper for inspect.getargsspec
 30 
 31     inspect.getargsspec is deprecated and will be removed in Python 3.6.
 32     """
 33     _ArgSpec = namedtuple("ArgSpec", "args varargs keywords defaults")
 34 
 35     args, varargs, varkw, defaults, kwonlyargs, _, ann = inspect.getfullargspec(
 36         func
 37     )  # pylint: disable=no-member
 38     if kwonlyargs or ann:
 39         raise ValueError(
 40             "Function has keyword-only arguments or annotations"
 41             ", use getfullargspec() API which can support them"
 42         )
 43     return _ArgSpec(args, varargs, varkw, defaults)
```

Was this deprecated function re-added for some reason?

**Comment by Garagoth** [comment]
Still happens in salt 3002.2.
Please re-open as it was newer solved in any version that we tested...

**Comment by msteed** [comment]
Thoughts on @skizunov 's suggestion [above](https://github.com/saltstack/salt/issues/48735#issuecomment-412660964)?

> I took a fresh look at the code and I think it is fine to ignore annotations since they can exist, but we just won't make use of them (we don't need them to make the function calls, and we won't use them to do type validation at runtime).

This seems like a simple fix. Maybe I'm missing something?

**Comment by terminalmage** [comment]
Yeah that makes sense... Though with getfullargspec on a deprecation path in the stdlib, I think it's worth dropping its use altogether in favor of inspect.signature.

**Comment by terminalmage** [comment]
:+1: There's already code in there that uses `inspect.signature`, so there shouldn't be too much to do. I think that the `_getargspec` helper can likely be removed, and the block of if/elseif in `get_function_argspec` that invokes the helper can probably also be removed. So it should mostly be removing code rather than writing new code.
