### ISSUE TITLE
Ubuntu 18.04 bionic removed ifdown-ifup

### ISSUE THREAD

**Issue by worlvlhole** [saltstack/salt#49078]
### Description of Issue/Question
Setting a static-ip  with `network.managed` and am getting command not found for ip-down.

> Given that ifupdown is no longer installed by default, the commands: ifup and ifdown are also unavailable. Please use the ip command to achieve similar functionality, specifically ip link set $device up and ip link set $device down.
[Ubuntu Release Notes](https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes) 

salt code that I beleive to be in question:  
- [ipdown](https://github.com/saltstack/salt/blob/develop/salt/modules/debian_ip.py#L1803)
- [ifup](https://github.com/saltstack/salt/blob/develop/salt/modules/debian_ip.py#L1864)

### Setup

`network.sls`
```yaml
eth0:
  network.managed:
    - enabled: True
    - type: eth
    - proto: static
    - ipaddr: 192.168.1.10
    - netmask: 255.255.255.0
    - gateway: 192.168.1.1
```

### Steps to Reproduce Issue
Running the above state that 

`salt 'minion` state.apply network`
```
----------
      Function: network.managed
      Result: False
     Comment: Unable to run command '[u'ifdown', u'ens160']' with the context '{u'timeout': None, u'with_communicate': True, u'shell': False, u'bg': False, u'stderr': -2, u'env': {'LANG': 'en_US.UTF-8', 'LC_NUMERIC': 'C', 'NOTIFY_SOCKET': '/run/systemd/notify', 'LC_MESSAGES': 'C', 'JOURNAL_STREAM': '9:38838', 'LC_IDENTIFICATION': 'C', 'LC_ADDRESS': 'C', 'LC_NAME': 'C', 'LC_COLLATE': 'C', 'LC_MEASUREMENT': 'C', 'LC_CTYPE': 'C', 'LC_TELEPHONE': 'C', 'LC_MONETARY': 'C', 'LC_PAPER': 'C', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LC_TIME': 'C', 'INVOCATION_ID': 'c736b3c72d224be28d6090a94f7ebb42'}, u'stdout': -1, u'close_fds': True, u'stdin': None, u'cwd': u'/root'}', reason: command not found
     Started: 15:35:08.626458
    Duration: 121.57 ms
     Changes:   
              ----------
              interface:
                  Added network interface.
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.27.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.0-23-generic
         system: Linux
        version: Ubuntu 18.04 bionic
 
```

**Comment by gtmanfred** [comment]
For the record, you can still install the `ifupdown` package, even though it does not come with ubuntu 18 by default.

**Comment by garethgreenaway** [comment]
If we're relying on it in the code, it should probably be a requirement for the package.  /cc @dmurphy18

**Comment by gtmanfred** [comment]
a check should be added in the `__virtual__`

**Comment by mrichar1** [comment]
This also affects places in `debian_ip.py` where systemd `networking.service` is used, since this is also added by the `ifupdown` package - e.g.:

https://github.com/saltstack/salt/blob/af96b6ea56979d2d97bd95c115c2ba726fdc8d1b/salt/modules/debian_ip.py#L1895-L1897

**Comment by dmurphy18** [comment]
@garethgreenaway So should add a dependency on package ifupdown for Ubuntu 18.04 LTS untill the Salt code has been updated to utilize netstat.io or ip set link etc. ?

**Comment by dmurphy18** [comment]
Will add package ifupdown for Ubuntu 18.04 LTS

**Comment by dmurphy18** [comment]
Updated packaging to add dependency for ifupdown for an immediate fix, until code changes have been applied.

see https://github.com/saltstack/salt-pack/pull/683 and https://github.com/saltstack/salt-pack-py3/pull/132

**Comment by dmurphy18** [comment]
PR https://github.com/saltstack/salt/pull/52670 submitted

**Comment by dmurphy18** [comment]
@worlvlhole This will appear in a future point release, unfortunately it has missed the cut off for 2019.2.1, but I shall see what I can do.

If this is sufficient, please consider closing this issue.

**Comment by ewenmcneill** [comment]
Per https://github.com/saltstack/salt-pack/issues/682#issuecomment-535210585 and https://github.com/saltstack/salt-pack/issues/702#issuecomment-536347725, I'd suggest that it'd perhaps be better to `Recommends:` or `Suggests:` `ifupdown` on Ubuntu 18.04 systems, rather than `Depends:`, until the `salt` network code can be made more portable.

Because `salt-common` / `salt-minion` / `salt-master` can function fine without `ifupdown`, for all features, except for this one specific (not yet updated 18 months after Ubuntu 18.04 release) feature.   And several of us do not want surprise installs of `ifupdown` on our `netplan` managed systems causing confusion (either to the people managing the systems, or to the booting and IP addressing).

Ewen

**Comment by dmurphy18** [comment]
@garethgreenaway Any comments on the the suggestion by @ewenmcneill  as to affecting Salt's operation

**Comment by dmurphy18** [comment]
reopened https://github.com/saltstack/salt-pack/issues/682 and shall make it Suggests:

**Comment by dmurphy18** [comment]
https://github.com/saltstack/salt-pack-py3/issues/161

**Comment by dmurphy18** [comment]
saltstack/salt-pack-py3#162

This should appear in the next point release which should be soon due a number of other issues in Salt 2019.2.1.

**Comment by d-shi** [comment]
FYI -- I just hit an issue WRT to this change to add a dependency on `ifupdown`. Adding this package causes any AWS AMI that has it installed to fail to launch. After upgrading to salt 2019.2.1 in our Packer builds, the subsequent EC2 instances that used the new AMIs were unreachable after launch.

**Comment by ewenmcneill** [comment]
Looks like the version with `Suggests: ifupdown` got released (2019.2.2):

```
ewen@naosr620:~$ dpkg -l | grep salt
ii  salt-common                           2019.2.2+ds-1                                   all          shared libraries that salt requires for all packages
ii  salt-minion                           2019.2.2+ds-1                                   all          client package for salt, the distributed remote execution system
ewen@naosr620:~$ apt-cache show salt-common | grep ifupdown
Suggests: ifupdown
ewen@naosr620:~$ 
```

So this issue could probably be closed again now.

Ewen

**Comment by lordvalium** [comment]
Ubuntu 18.04 is absolutely crap. Removed all the working stuff. Dont know why.

**Comment by otrapeznikov** [comment]
This issue is back with salt 2018.3.5

```
Package: salt-common
Priority: extra
Section: admin
Installed-Size: 26484
Maintainer: Debian Salt Team <pkg-salt-team@lists.alioth.debian.org>
Architecture: all
Source: salt
Version: 2018.3.5+ds-1
Depends: python-apt, python-dateutil, python-jinja2, python-msgpack (>= 0.4), python-pkg-resources, python-requests (>= 1.0.0), python-concurrent.futures, python-tornado (>= 4.2.1), python-yaml, python-systemd, python-psutil, python-gnupg, ifupdown, python:any (<< 2.8), python:any (>= 2.7.5-5~)
Recommends: lsb-release, python-mako
Breaks: python-mako (<< 0.7.0)
Filename: pool/extras/s/salt/salt-common_2018.3.5+ds-1_all.deb
Size: 6088964
MD5sum: 140842fd1cf22214cfb53d498af8f45d
SHA1: d8a6a4b4ad13f181bf8e271d7d60bc7914a19a94
SHA256: 333c1d727c5e95dbea24e6b276e5f1983dd0dd7832d56b121297e9ebbc32c37f
SHA512: e447b970bd6ccfe1e680d7fea4508c1b1795ec233982c8d4213151e3abc39e886d0da1a1e101d8b2a7cbd586868471e8ea8e4ae29fdd63f6421a42697197bd3e
Description: shared libraries that salt requires for all packages
Description-md5: aaa76a7bda4c75e02b81764c1dc6e91a
Homepage: http://saltstack.org/
```

**Comment by dmurphy18** [comment]
@worlvlhole @ewenmcneill Closing this since fixed in Salt v2019.2.2, and Salt 3000 just released.

Please reopen if you have additional fixes required for this issue

**Comment by OrangeDog** [comment]
@dmurphy18 the actual fix never got released before it was accidentally reverted: #57637

**Comment by allyunion** [comment]
I am still having this issue.  Shouldn't the dependency be on the ip command instead of ifupdown for the maximum compatibility?

**Comment by OrangeDog** [comment]
@allyunion yes, that's the fix that got accidentally reverted.
