### ISSUE TITLE
salt-cloud fails to query openstack

### ISSUE THREAD

**Issue by markododa** [saltstack/salt#49438]
### Description of Issue/Question
Querying openstack doesn't work, (salt-cloud -Q)
Listing sizes and images works just fine

### Setup
This is the config file:

openstack_provider:
  minion:
    master: salt
    master_type: str
  driver: openstack
  region_name: RegionOne
  auth:
    username: 'admin'
    password: admin
    project_name: 'admin'
    auth_url: 'http://192.168.80.16:5000'

### Steps to Reproduce Issue
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 271, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1612, in do_function
    driver: self.clouds[fun](call='function')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/openstack.py", line 413, in list_nodes_full
    ret[node.name]['image'] = node.image.name
AttributeError: 'dict' object has no attribute 'name'

### Versions Report
salt 2018.3.2 (Oxygen

**Comment by Ch3LL** [comment]
im not able to replicate this just running `sudo salt-cloud -Q` with openstack configured. was this working previously for you or is this a new setup?

**Comment by pzskc383** [comment]
I ran into this on rackspace connected via openstack driver.
I see no `name` in `node.image` dict there, only id.
For servers started from block storage, dict contsists of empty id only.

Catching raised attribute error gives no further errors when listing.

Hope this helps. 

Version report:
```
Salt Version:
            Salt: 2018.3.2
 
Dependency Versions:
 Apache Libcloud: 1.2.1
            cffi: 1.11.4
        cherrypy: 3.8.0
        dateutil: 2.6.1
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.10
         libgit2: Not Installed
         libnacl: 1.4.4
        M2Crypto: 0.24.0
            Mako: 1.0.6
    msgpack-pure: Not Installed
  msgpack-python: 0.5.1
    mysql-python: Not Installed
       pycparser: 2.14
        pycrypto: Not Installed
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.14 (default, Apr 16 2018, 06:30:00)
    python-gnupg: 0.4.1
          PyYAML: 3.12
           PyZMQ: 16.0.2
            RAET: Not Installed
           smmap: Not Installed
         timelib: 0.2.4
         Tornado: 4.4.2
             ZMQ: 4.2.2
 
System Versions:
            dist: gentoo 2.4.1 
          locale: UTF-8
         machine: x86_64
         release: 4.17.2-gentoo
          system: Linux
         version: Gentoo Base System 2.4.1 

```
Provider configuration:
```
rs:
    driver: openstack
    auth:
        username: [redacted]
        api_key: [redacted]
        auth_url: 'https://identity.api.rackspacecloud.com/v2.0/'
    auth_type: rackspace_apikey
    region_name: DFW
    database_service_type: rax:database
    compute_service_name: cloudServersOpenStack
    image_api_use_tasks: true
    image_format: vhd
    floating_ip_source: None
    secgroup_source: None
    requires_floating_ip: false
    volume_api_version: 1
    disable_vendor_agent:
        vm_mode: hvm
        xenapi_use_agent: false
    has_network: false
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud any ideas here?

**Comment by gtmanfred** [comment]
This is fixed in 2018.3.3

It happens when cloud servers are built with bootable volumes instead of on disk root devices.

https://github.com/saltstack/salt/pull/48956

**Comment by pzskc383** [comment]
Just got to testing this and noticed that #48956 didn't fix this error for me.

That PR adds check for missing image name in `show_instance` method,:
https://github.com/saltstack/salt/blob/bad995462c1772d99b755272e1aab2c9ed88ec49/salt/cloud/clouds/openstack.py#L469-L472

while `list_nodes_full` left unchanged:
https://github.com/saltstack/salt/blob/bad995462c1772d99b755272e1aab2c9ed88ec49/salt/cloud/clouds/openstack.py#L413

Fix should be trivial, I'll open PR when i have it tested.

**Comment by garethgreenaway** [comment]
@pzskc383 Did you have a chance to submit a PR with the above fix?

**Comment by sblaisot** [comment]
Should be fixed in #52990
