### ISSUE TITLE
service.running erroneously reports a failure to start a launchd service on macOS

### ISSUE THREAD

**Issue by kmdouglass** [saltstack/salt#49758]
### Description of Issue/Question

We have encountered a bug when using the `service.running` state on macOS where salt reports a failure to start the service even though the service has been successfully started.

Briefly, we have configured a salt state to start a launchd service on a macOS minion that is running masterless. The service is launched with the `service.running` state after a call to `salt-call --local state.apply`. The output from `state.apply` reports a failure when starting the service, but upon closer inspection the service is in fact running.  The output to the log file (included below) does not indicate the cause of the error.

We suspect that the `start` method in [salt/salt/modules/launchctl.py](https://github.com/saltstack/salt/blob/b44f0f1d0fd564690c6e45c6dd061c0e84d76def/salt/modules/launchctl.py#L295) may be erroneously returning a non-zero exit status despite the fact that launchctl returns an exit status of zero.

If we replace `service.running` with `cmd.run` and `- name: ...` with `launchctl load /Library/LaunchDaemons/com.mycompany.worker_darwin.plist` in the `worker_darwin.sls` file, then salt does not report an error when applying the highstate and successfully launches the service.

### Setup
**worker_darwin.sls**, the relevant salt state file with unnecessary states omitted:
```
{% from "concourse-ci/map.jinja" import concourse with context %}

{% if salt['environ.has_value']('INSIDE_VM', 'TRUE')-%}
concourse-worker_launchd_wrapper:
  file.managed:
  - name: {{ concourse.launchd_wrapper_path }}
  - context:
      worker_tsa_host: {{ salt['pillar.get']('worker_tsa_host', {}) }}
  - source: salt://concourse-ci/templates/launchd_wrapper.sh.jinja
  - user: {{ concourse.user }}
  - template: jinja
  - mode: 700

concourse-worker_launchd_plist:
  file.managed:
  - name: /Library/LaunchDaemons/com.mycompany.worker_darwin.plist
  - source: salt://concourse-ci/templates/com.mycompany.worker_darwin.plist.jinja
  - template: jinja
  - require:
    - concourse-worker_launchd_wrapper
  - mode: 600

Start concourse:
  service.running:
    - name: /Library/LaunchDaemons/com.mycompany.worker_darwin.plist
    - require:
      - concourse-worker_launchd_plist
{% endif -%}
```

#### Step 1
Verify that the service is not running on the minion.

```
$ launchctl list | grep mycompany
$ 
```

#### Step 2
Apply the highstate. Observe failure to start the service.

```
$ INSIDE_VM=TRUE salt-call --local --log-file-level=all state.apply
... (omitting other IDs)
----------
          ID: Start concourse
    Function: service.running
        Name: /Library/LaunchDaemons/com.mycompany.worker_darwin.plist
      Result: False
     Comment: Service /Library/LaunchDaemons/com.mycompany.worker_darwin.plist failed to start
     Started: 14:52:44.593674
    Duration: 297.393 ms
     Changes: 
... (omitting other IDs)
Summary for local
-------------
Succeeded: 32 (changed=1)
Failed:     1
-------------
Total states run:     33
Total run time:   11.301 s

```

The relevant lines inside `/var/log/salt/minion`:

```
2018-09-24 14:52:44,593 [salt.utils.lazy  :100 ][DEBUG   ][10725] LazyLoaded service.running
2018-09-24 14:52:44,593 [salt.state       :1789][INFO    ][10725] Running state [/Library/LaunchDaemons/com.mycompany.worker_darwin.plist] at time 14:52:44.593674
2018-09-24 14:52:44,594 [salt.state       :1822][INFO    ][10725] Executing state service.running for [/Library/LaunchDaemons/com.mycompany.worker_darwin.plist]
2018-09-24 14:52:44,594 [salt.utils.lazy  :100 ][DEBUG   ][10725] LazyLoaded mac_utils.available_services
2018-09-24 14:52:44,595 [py.warnings      :160 ][WARNING ][10725] /opt/salt/lib/python3.5/site-packages/salt/utils/__pycache__/mac_utils.cpython-35.py:323: DeprecationWarning: The readPlist function is deprecated, use load() instead

2018-09-24 14:52:44,596 [py.warnings      :92  ][WARNING ][10725] /opt/salt/lib/python3.5/site-packages/salt/utils/__pycache__/mac_utils.cpython-35.py:341: DeprecationWarning: Attribute access from plist dicts is deprecated, use d[key] notation instead

2018-09-24 14:52:44,890 [salt.state       :310 ][ERROR   ][10725] Service /Library/LaunchDaemons/com.mycompany.worker_darwin.plist failed to start
```

#### Step 3
Observe that the service is, in fact, running.

```
$ launchctl list | grep mycompany
10191   0       com.mycompany.worker_darwin
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: 13.0.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.7
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jun 18 2018, 16:05:29)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: US-ASCII
        machine: x86_64
        release: 17.7.0
         system: Darwin
        version: 10.13.6 x86_64
```

**Comment by Ch3LL** [comment]
if you use the `service.running` state against other services does it work? 

Also can you run `salt-call --local service.start <service_name>` and `salt-call --local service.status <service_name>` and report back if those fail or not?

**Comment by weswhet** [comment]
@Ch3LL I believe this issue is fixed on develop here https://github.com/saltstack/salt/pull/46206, This is what happens when salt tried to manage a service that doesn't have an active PID. I'm happy to patch this on 2018.3.* :)

**Comment by weswhet** [comment]
@kmdouglass you can drop my patched module in `_modules` as a temp workaround for this until a future release. https://github.com/mosen/salt-osx/blob/master/_modules/mac_service.py

**Comment by kmdouglass** [comment]
@Ch3LL Thanks for your response. Here's what I found out:

> if you use the service.running state against other services does it work?

I still see the same behavior with other services; salt-call reports an error when I apply the high state but the service is actually launched. If you want to reproduce this yourself, I made a simple plist file that writes text to /tmp/hello.txt every ten seconds. The file is called `/Library/LaunchDaemons/com.example.hello.plist`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>helloDaemon</string>
	<key>ProgramArguments</key>
	<array>
	        <string>/bin/bash</string>
	        <string>-c</string>
	        <string>echo "Hello daemon" >>/tmp/hello.txt</string>
        </array>
	<key>StartInterval</key>
	<integer>10</integer>
</dict>
</plist>
```

The salt state file is:
```
Start concourse:
  service.running:
    - name: /Library/LaunchDaemons/com.example.hello.plist
```

And after calling `salt-call --local state.apply` I get this error:

```
----------
          ID: Start concourse
    Function: service.running
        Name: /Library/LaunchDaemons/com.example.hello.plist
      Result: False
     Comment: Service /Library/LaunchDaemons/com.example.hello.plist failed to start
     Started: 13:50:51.249074
    Duration: 414.597 ms
     Changes:   
              ----------
              /Library/LaunchDaemons/com.example.hello.plist:
----------
```

The service is both running and writing "Hello daemon" to the text file every ten seconds:

```
$ launchctl list | grep hello
-       0       helloDaemon
```
-----
> Also can you run salt-call --local service.start <service_name> and salt-call --local service.status <service_name> and report back if those fail or not?

These actually work and do not produce any failures.

```
$ salt-call --local service.start /Library/LaunchDaemons/com.mycompany.worker_darwin.plist
local:
      True
$ salt-call --local service.status
local:
```
Both return exit codes `$?` of zero.

**Comment by kmdouglass** [comment]
Hi @weswhet 
Thanks for the suggestion. I simply copy/pasted the contents of https://github.com/mosen/salt-osx/blob/master/_modules/mac_service.py over the corresponding `mac_service.py` in salt's Python installation but this produced the same behavior that I originally reported. The service launches but salt says it failed to start.

**Comment by Ch3LL** [comment]
thanks for the easy test case. I was able to replicate it but I was also able to verify that it is fixed in the upcoming fluorine release.

Just to make sure when you replaced the file can you also make sure that you clear out pyc files as well. There is a known issue with python3 with the loader so it required cleaning out pyc files.

**Comment by kmdouglass** [comment]
Thanks @Ch3LL for your help. You are right in that I forgot to clear the .pyc files when I tried the patch. I am not in a position to easily test the patch from @weswhet  anymore, so I will wait until the next release of Salt to verify that it works.

**Comment by Ch3LL** [comment]
Are you okay closing this and then re-opening if it resurfaces since i verified its fixed? If you close it then you can re-open at any time
