### ISSUE TITLE
salt pip AttributeError: type object 'InstallRequirement' has no attribute 'from_line'

### ISSUE THREAD

**Issue by diepes** [saltstack/salt#49967]
### Description of Issue/Question
after pip upgrade on ubuntu 14.04 to 9.8 -> 18.1 salt state pip.install failing with

AttributeError: type object 'InstallRequirement' has no attribute 'from_line' 

To make the state work again uninstall new pip version
$ sudo pip uninstall pip
$ sudo apt install --reinstall python-pip
$ sudo pip install pip==9.0.1
#Note now the sls state pip.install below works

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

#sls file
docker:
  pip.installed:
    - name: docker
    - reload_modules: True

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
##Ubuntu 14.04
sudo pip install --upgrade pip
pip --version
vagrant@localsandbox:~$ pip --version
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
pip 18.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

vagrant@localsandbox:~$ salt-call --versions-report
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: 3.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: 0.4.3
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-137-generic
         system: Linux
        version: Ubuntu 14.04 trusty
 
vagrant@localsandbox:~$

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this. we will need to get this fixed up. thanks

**Comment by rallytime** [comment]
@gtmanfred I've assigned this one to your for 2018.3.4 :)

**Comment by lmbss** [comment]
i have de some error when i use module.pip for install pyinotify:

```
pip.pkgs:
  pip.installed:
    - pkgs:
      - pyinotify
    - proxy: CONFIDENTIAL
```



```
          ID: pip.pkgs
    Function: pip.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pip_state.py", line 681, in installed
                  out = _check_pkg_version_format(pkg)
                File "/usr/lib/python2.7/site-packages/salt/states/pip_state.py", line 147, in _check_pkg_version_format
                  install_req = InstallRequirement.from_line(pkg)
              AttributeError: type object 'InstallRequirement' has no attribute 'from_line'
     Started: 13:24:25.286429
    Duration: 232.88 ms
     Changes:
```

**Comment by lsh-0** [comment]
I'm seeing this too after upgrading from `2017.7.5` to `2017.7.7` in order to fix this bug: https://github.com/saltstack/salt/issues/46163

```
----------
          ID: global-python-requisites
    Function: pip.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1879, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1826, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 682, in installed
                  out = _check_pkg_version_format(pkg)
                File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 149, in _check_pkg_version_format
                  install_req = InstallRequirement.from_line(pkg)
              AttributeError: type object 'InstallRequirement' has no attribute 'from_line'
     Started: 03:38:45.261020
    Duration: 431.364 ms
     Changes:   
```

versions

```
# salt-call --versions
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1030-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
The salt version upgrade doesn't matter here, pip version 18.1 made some
changes that broke the way we used it.  downgrade pip and this will work
again.

**Comment by gtmanfred** [comment]
This is fixed with https://github.com/saltstack/salt/pull/50280

**Comment by plagov** [comment]
How can I install an older version of `pip` within a salt state? I tried the following declaration:

```yml
install python-pip:
  pkg.installed:
    - name: pip
    - version: 9.0.3

install python lib for docker:
  pip.installed:
    - name: docker == 3.6.0
    - require:
      - pkg: install python-pip
```

And still get the error. But also, I don't know what version of `pip` is being installed here.

**Comment by Ch3LL** [comment]
can you verify its actually installing 9.0.3 when you run that state?Also if you run it a second time do you still see the error?

**Comment by plagov** [comment]
@Ch3LL actually, I run it with the `test=True` flag, because the state is under WIP and I can't check the actual impact that the state mades.

**Comment by martinm82** [comment]
I see that this issue got fixed in 2018.3.4 (https://github.com/saltstack/salt/pull/50280) but I still get it with that version.
Am I doing something wrong?

**Comment by gtmanfred** [comment]
How are you installing 2018.3.4, because that hasn't been released yet.

**Comment by dwickwire** [comment]
Can I get a ball-park idea of when can we expect `2018.3.4` please?  Just upgraded all our minions to `2018.3.3` and am starting to try and use pip `v18.1`.   Thanks!

**Comment by martinm82** [comment]
I am so sorry, I just added the version in my kitchen.yml and I somehow missed the error that the version does not exist.

**Comment by gtmanfred** [comment]
you can check #releases on the salt community slack listed on the community page of saltstack.com https://saltstackcommunity.herokuapp.com

but @saltstack/team-triage might know a date.

I know right now they are working on getting an RC out for fluorine.

**Comment by gtmanfred** [comment]
if you have to use pip 18.1 right now, you can always drop the pip.py module into salt://_modules like all other dynamic modules.

https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

**Comment by dwickwire** [comment]
OK, I don't *need* pip `v18.1` but this is more of a blocker to get to python 3.7, which is more important to me.  Python doesn't seem to want to install 3.7 with pip `v9.0.3`, whereas it seems to install fine `v18.1`.  Its been two months since the fix, which is why I asked.   I'll check out the dynamic modules though, thanks for the tip.

**Comment by gtmanfred** [comment]
did you try pip 10.x?

**Comment by dwickwire** [comment]
Oh hey, good idea.  Just tried it, unfortunately python still won't install.  All I'm getting is:

```yml
----------
          ID: python-3.7.0
    Function: pyenv.installed
      Result: False
     Comment: Could not install python.
     Started: 13:21:55.953496
    Duration: 1069.615 ms
     Changes:   
```

This doesn't occur with pip 18.1, instead I get the known `AttributeError`.  I guess I can wait, its just nice to stay with the latest python.  Or I'll just look into the dynamic modules you cited.  Thanks again.
