### ISSUE TITLE
Can not use compound match in eauth

### ISSUE THREAD

**Issue by zbw1983** [saltstack/salt#50153]
### Description of Issue/Question
I want to use compound match in eauth configuration, I want to match 2 grains in my conf, but it can't work. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
My eauth conf like below, I want to match 2 grains in eauth, but it can't work. 
```
external_auth:
  ldap:
    test:
      - 'G@nodename:mytest-server and G@osmajorrelease:7':
        - .*
```
### Steps to Reproduce Issue
I use SALT-API to call my SALT-master, but it return "401 Unauthorized" 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2017.7.6

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 2.7.3
      docker-py: 1.7.2
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Feb 11 2014, 07:46:25)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 7.1 Maipo
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-229.1.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.1 Maipo
```

**Comment by gtmanfred** [comment]
This is fixed by https://github.com/saltstack/salt/pull/49236 and will be in 2017.7.9 and 2018.3.4.

We are currently working on getting 2017.7.8 and 2018.3.3 out, so this will be in the next version release.

**Comment by gtmanfred** [comment]
You will need to wait for 2017.7.9 for this.  it will not be in 2017.7.8.

Did you make sure to fully restart the master and salt-api after making this change?

**Comment by zbw1983** [comment]
Yes, I fully restart master and salt-api, but it still can't work. I use 2017.7.7 version, is there any other change I need do? Have you tested 2 grains match on eauth part? Many thanks.

**Comment by gtmanfred** [comment]
just so I make sure to replicate what you are doing, what command are you running that is returning a 401 error?

**Comment by gtmanfred** [comment]
It is working for me.

```
$  pepper minion1 test.ping
minion1:
    True
$ docker-compose exec salt cat /etc/salt/master
rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
external_auth:
  pam:
    saltdev:
    - 'G@id:minion1 and G@osmajorrelease:7':
      - .*
    - '@runner'
    - '@wheel'
    - '@jobs'
log_level: debug
vault:
  url: http://vault:8200
  auth:
    method: token
    token: mysecret
  policies:
  - myp
peer_run:
  .*:
  - vault.generate_token
```

With a simple example.

**Comment by zbw1983** [comment]
I just update my salt to 2017.7.8 version, and update my /usr/lib/python2.7/site-packages/salt/utils/minions.py file, but still can't work. 
Here is my conf 
```
external_auth:
  ldap:
    cd_af:
      - 'G@id:bjo-devops-008 and G@osmajorrelease:7':
        - .*
auth.enable_expanded_auth_matching: True```

and I can target my minion via those grains. 
```salt -C 'G@id:bjo-devops-008 and G@osmajorrelease:7' test.ping
bjo-devops-008:
    True```

But if I try to use that user target minion, I got error message
```
salt -a ldap bjo-devops-008 test.ping
username: cd_af
password:
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).```

Same result of SALT-API, 
```
curl http://localhost:8000 -H 'Accept: application/x-yaml' -d client=local -d tgt='bjo-devops-008' -d fun='test.ping' -H 'X-Auth-Token:8e1bb3053cda6e80995d8a67ce9b7eb6c3f38axx'
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
```

**Comment by gtmanfred** [comment]
If you remove the compound target, does it work?

**Comment by zbw1983** [comment]
Yes, if I use single grains match or use PCRE match, it can work.

**Comment by gtmanfred** [comment]
@Ch3LL can you also try and replicate this when you get a minute today? I was unable to replicate with 2017.7.8

Thanks,
Daniel

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this behavior. Heres a docker container to replicate it:

1. `docker run -it -v ~/git/salt:/testing/ ch3ll/issues:50153 /bin/bash` (where ~/git/salt/` is a local cloned git repo of salt)
2. `salt-master -d; salt-minion -d`
3. `salt --username=saltdev --password=saltdev --eauth=pam -l warning c6c2e89d6b0b test.ping`

I also tried on the head of 2017.7 and 2018.3.3 and still seeing the failure.

**Comment by gtmanfred** [comment]
@terminalmage can you take a look at this when you get a moment?

Thanks

**Comment by sagetherage** [comment]
@terminalmage is looking at this

**Comment by terminalmage** [comment]
This should be fixed via https://github.com/saltstack/salt/pull/50876. @Ch3LL can you confirm using your docker image?

**Comment by Ch3LL** [comment]
yep it works @terminalmage :) thanks!
