### ISSUE TITLE
Fix this warning please.

### ISSUE THREAD

**Issue by wzlee** [saltstack/salt#50994]
```
/usr/local/Cellar/salt/2018.3.3/libexec/lib/python3.7/site-packages/salt/utils/immutabletypes.py:38: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class ImmutableList(collections.Sequence):
[WARNING ] /usr/local/Cellar/salt/2018.3.3/libexec/lib/python3.7/site-packages/salt/daemons/__init__.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import namedtuple, Iterable, Sequence, Mapping

[WARNING ] /usr/local/Cellar/salt/2018.3.3/libexec/lib/python3.7/site-packages/salt/transport/ipc.py:280: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  self.unpacker = msgpack.Unpacker(encoding=encoding)

[WARNING ] /usr/local/Cellar/salt/2018.3.3/libexec/lib/python3.7/site-packages/salt/payload.py:145: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)
```

**Comment by garethgreenaway** [comment]
Fixed in https://github.com/saltstack/salt/pull/49487

**Comment by BrianSidebotham** [comment]
It looks like this was merged into the 2018.3 branch but not into the develop branch? I still get this warning when using the develop branch.

**Comment by garethgreenaway** [comment]
The fix in 2018.3 will be merged forward and make it's way into develop. A merge forward including that fix hasn't happened yet. Most likely sometime this week once the previous merge forward has cleared.

**Comment by BrianSidebotham** [comment]
@garethgreenaway Perfect, thanks for the confirmation. :+1:

**Comment by jakehilton** [comment]
Upgraded to 2018.3.4 and still seeing this:

Feb 28 17:42:41 host-smaster208 salt-master[7695]: [WARNING ] /usr/local/lib/python3.6/dist-packages/salt/payload.py:145: DeprecationWarning: encoding is deprecated, Use raw=False instead.

**Comment by twangboy** [comment]
It doesn't look like that PR addresses the msgpack deprecation warning.

**Comment by hackacad** [comment]
This issue has been fixed in https://github.com/saltstack/salt/commit/8e6546a079cc2fd55be22a05a834a496f4923085#diff-30108e69fa3d1358454431c6c9b08965 but wasn't merged into 2018.3.4

**Comment by hackacad** [comment]
This issue has been fixed in https://github.com/saltstack/salt/commit/1ad8ed89ac3a2938852ab8328648178f96f9f91f#diff-30108e69fa3d1358454431c6c9b08965
Sounds like a pycache issue again. Could you cleanup salt/__pycache__ and restart the master?

**Comment by wzlee** [comment]
OK, I see.

**Comment by rares-pop** [comment]
This doesn't seem to be fixed, in 2019.2.0, although I do have that PR changes:

(salt-venv) [asterisc@speedy salt-venv]$ salt -c ./etc/salt '*' test.version
[WARNING ] /home/asterisc/Work/salt/salt/transport/ipc.py:261: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  self.unpacker = msgpack.Unpacker(encoding=encoding)

[WARNING ] /home/asterisc/Work/salt/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

speedy:
    2019.2.0-317-gd98ab2e

**Comment by ccjetweat** [comment]
This doesn't seem to be fixed, in 2019.2.0, me

**Comment by ccjetweat** [comment]
This doesn't seem to be fixed, in 2019.2.0, me too:
my script => test.py
import salt.client
local = salt.client.LocalClient()
local.cmd('*', 'test.fib', [10])

result =>
/root/test/py3env/lib/python3.5/site-packages/salt/transport/ipc.py:292: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  self.unpacker = msgpack.Unpacker(encoding=encoding)
/root/test/py3env/lib/python3.5/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

my salt's version =>
# salt --version
salt 2019.2.0 (Fluorine)

**Comment by ccjetweat** [comment]
**This doesn't seem to be fixed, in 2019.2.0, me too:**
```
my script => test.py
import salt.client
local = salt.client.LocalClient()
local.cmd('*', 'test.fib', [10])
```
- **result** 
```
/root/test/py3env/lib/python3.5/site-packages/salt/transport/ipc.py:292: DeprecationWarning: encoding is deprecated, Use raw=False instead.
self.unpacker = msgpack.Unpacker(encoding=encoding)
/root/test/py3env/lib/python3.5/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)
```
- **my salt's version**
```
# salt --version
salt 2019.2.0 (Fluorine)
```

**Comment by arno01** [comment]
Same here when I use ``salt-ssh ... pillar.get ...``

**Comment by unficyp** [comment]
same here:
[WARNING ] /usr/local/lib/python3.6/site-packages/salt/transport/ipc.py:292: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  self.unpacker = msgpack.Unpacker(encoding=encoding)

[WARNING ] /usr/local/lib/python3.6/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

**Comment by ccjetweat** [comment]
> root @ salt_master：/ usr / local / etc / salt＃salt'*'test.version 
> [警告] /usr/local/lib/python3.6/site-packages/salt/transport/ipc.py:292:DreprecationWarning：不推荐使用编码，请改用raw = False。
> self.unpacker = msgpack.Unpacker（encoding = encoding）
> 
> [警告] /usr/local/lib/python3.6/site-packages/salt/payload.py:149：不推荐使用DeprecationWarning：encoding，而是使用raw = False。
> ret = msgpack.loads（msg，use_list = True，ext_hook = ext_type_decoder，encoding = encoding）
> 
> root @ salt_master：/ usr / local / etc / 
> salt #salt --version salt 2019.2.0（Fluorine）

It's OK ! Thanks

**Comment by visago** [comment]
Still happening in Salt 2019.20 with python3.6 (Ubuntu 18.04)
```
# salt '*' test.version
[WARNING ] /usr/local/lib/python3.6/dist-packages/salt/transport/ipc.py:292: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  self.unpacker = msgpack.Unpacker(encoding=encoding)

[WARNING ] /usr/local/lib/python3.6/dist-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)
```

**Comment by driverjb** [comment]
Still happening in Salt 2019.2.0 with python 2.7 (Fedora Server 30) installed from repository:

`dnf install salt-master`

```
$ sudo salt '*' test.version
[WARNING ] /usr/lib/python2.7/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)
```
