### ISSUE TITLE
logstash_udp_handler doesn't work in py3

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#51123]
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 634, in emit
    self.send(s)
  File "/usr/lib/python3.6/logging/handlers.py", line 692, in send
    self.sock.sendto(s, self.address)
TypeError: a bytes-like object is required, not 'str'
```

Needs e.g. a conversion to `six.binary_type` here:
https://github.com/saltstack/salt/blob/v2018.3.3/salt/log/handlers/logstash_mod.py#L381

**Comment by dwoz** [comment]
@OrangeDog Thanks for reporting this issue. Can you provide us with the output of `salt -V`?

**Comment by OrangeDog** [comment]
The zmq handler is similarly broken
```
Jan  9 16:56:40 csrf-admin-vm salt-minion[4115]:   File "zmq/backend/cython/socket.pyx", line 636, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/
socket.c:7314)
Jan  9 16:56:40 csrf-admin-vm salt-minion[4115]:   File "zmq/backend/cython/socket.pyx", line 676, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/
socket.c:6994)
Jan  9 16:56:40 csrf-admin-vm salt-minion[4115]: TypeError: unicode not allowed, use send_string
```

**Comment by OrangeDog** [comment]
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ISO-8859-1
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by kiemlicz** [comment]
What is the proper configuration of logstash in Salt?
 1. Does something like this:
```
logstash_udp_handler:
  host: logstash
  port: 1514
  version: 1
  msg_type: logstash
```
suffice and I should observe logs in logstash?
 2. or do I need to do more (like set also: `log_file: udp://logstash:1514`)?

Given I have fixed locally the issue with type conversion I still observe nothing in logstash.

**Comment by peterhirn** [comment]
Hello. Could you share your fix or do a pull request? Issues is still prevalent in v2019.2.0.

Thank you!

**Comment by kiemlicz** [comment]
Sure, will do but not at the moment  
Meanwhile you can find it here:
https://github.com/kiemlicz/ambassador/blob/master/salt/base/_log_handlers/logstash_mod.py
Putting `logstash_mod.py` under `_log_handlers` will override the 'stock' one

**Comment by OrangeDog** [comment]
@dwoz why is this Blocked?

**Comment by kiemlicz** [comment]
This is merged actually.  
I don't know if this should be closed now or once the fix is released?

**Comment by sagetherage** [comment]
It should be closed with the syntax in the PR body to close the issue it is linked to upon merge - but we are not very good about linking issues with PRs. @OrangeDog please comment and mention me if this isn't corrected for you.

**Comment by kiemlicz** [comment]
The syntax:
```
What issues does this PR fix or reference?
Fixes: #XXXX
```
Should do or there is some another syntax?

**Comment by OrangeDog** [comment]
Not sure when this got released, but it's fixed in 3000.3
