### ISSUE TITLE
MySQL: change of user password with password_hash not working for MySQL 8 / MariaDB 10.x

### ISSUE THREAD

**Issue by niclashoyer** [saltstack/salt#52023]
### Description of Issue/Question
Using just `password_hash` I get an error if I try to change a user password with MySQL > 8 / MariaDB 10.x.

The relevant part is here:
https://github.com/saltstack/salt/blob/develop/salt/modules/mysql.py#L1540

The `password` variable is undefined if the state uses `password_hash`. `password_sql` contains the hashed password from the state. AFAIK there is no way to just set the password hash with `ALTER USER`. Maybe this could be changed to `SET PASSWORD ...`?

### Setup
```yaml
mariadb.testuser:
  mysql_user.present:
    - name: testuser
    - host: localhost
    - password_hash: '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29'
```
### Steps to Reproduce Issue

I get the following error:
```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/mysql_user.py", line 174, in present
                  **connection_args):
                File "/usr/lib/python3/dist-packages/salt/modules/mysql.py", line 1475, in user_chpass
                  " IDENTIFIED BY '" + password + "';")
              TypeError: must be str, not NoneType
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-45-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by garethgreenaway** [comment]
@niclashoyer Using the latest 2019.2 branch I don't see the same error that you're seeing but I suspect it's not handling the situation properly as the state runs updates the password each time.

**Comment by niclashoyer** [comment]
I did not study the code thoroughly, but I suspect the hash might be hashed again.

I just ran `SELECT PASSWORD('secretpass')` in another MySQL instance. Does that produce the old hash? I don't remember the MySQL version I used, but it probably was 5.7.

**Comment by garethgreenaway** [comment]
@niclashoyer That query will generate the old MySQL password hash and the use of the `PASSWORD` command was dropped in MySQL 8.0.11.

**Comment by niclashoyer** [comment]
Okay, I've now read the documentation about the deprecation. I don't quiet get how one would generate a possible value for `password_hash` for MySQL 8.0 now. I read [this](https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/) about the new SHA2 mechanism and [here](https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html) are a bunch of new functions. But is it still possible to just generate a hash that I can put in my pillar?

**Comment by MartinMystikJonas** [comment]
@niclashoyer I just stumbled upon exact same error. Did you managed to solve it somehow?

**Comment by niclashoyer** [comment]
actually, no :disappointed: 
we now run `SET PASSWORD ...` manually on each host after the minion fails. After that the minion recognizes the correct password is set and is happy. In our case we only need to change the password once, but it is still super annoying.

**Comment by javierbertoli** [comment]
I arrived here following an issue I hit today in the [mysql-formula](https://github.com/saltstack-formulas/mysql-formula/) and while trying to debug it.

I'm using `Debian stable`. The formula runs OK when using `python-mysqldb 1.3.7`,  `Saltstack 2019.2` and `python 2.7.13`. All the users and databases can be created/updated/modified.

But when I changed to `python3-mysqldb 1.3.7`,  `Saltstack 2019.2` and `python 3.5.3` I begun finding this error.

When trying to debug it, I notice a couple of things that might help. Having this pillar:

```yaml
  user:
    frank:
      password: 'somepass'
      host: localhost
      ...
    bob:
      password_hash: '*6C8989366EAF75BB670AD8EA7A7FC1176A95CEF4'
      host: '%' # Any host
```

User `frank` is created correctly, but user `bob` fails with the error described.

However, logging into the instance and checking the database, I find that the user *IS* created:

```
MariaDB [mysql]> select user,password,host from user;
+------------+-------------------------------------------+-----------+
| user       | password                                  | host      |
+------------+-------------------------------------------+-----------+
| root       |                                           | localhost |
| frank      | *13883BDDBE566ECECC0501CDE9B293303116521A | localhost |
| bob        | *A906474A0497C57138D4490F4824BF5EB683F6B3 | %         |
+------------+-------------------------------------------+-----------+
4 rows in set (0.00 sec)

MariaDB [mysql]>
```

and the other interesting fact is that the hash of bob's password, which differs of the value set in `password_hash` is actually **the hash of the password_hash**:

```
MariaDB [mysql]> select password('*6C8989366EAF75BB670AD8EA7A7FC1176A95CEF4');
+-------------------------------------------------------+
| password('*6C8989366EAF75BB670AD8EA7A7FC1176A95CEF4') |
+-------------------------------------------------------+
| *A906474A0497C57138D4490F4824BF5EB683F6B3             |
+-------------------------------------------------------+
```

So, as I understand it, I think either `password` or `password_hash` are being passed as `password` at the *user creation function* but not at the other *user functions* (that's why it fails in subsequent runs or when trying to apply grants)

Hope my findings help (even if my final conclusion is not correct :yum:).

**Comment by garethgreenaway** [comment]
I believe the above PR fixes the issues here, if you're able to try out the changes that would be greatly appreciated.

**Comment by garethgreenaway** [comment]
May have jumped the gun, there are a few other functions that need to be updated.  Stay tuned :smile:

**Comment by garethgreenaway** [comment]
Okay. Should have taken care of the various bugs reported, if you're able to test the changes in the PR above that would be greatly appreciated.

**Comment by javierbertoli** [comment]
Hi @garethgreenaway. I tested the code above on a Debian host with MariaDB 10, Salt 2019.2 + py3 and python3-mysqldb.

Now the error is in a different place of the `mysql` module. With the following state file:
```yaml
mysql_user_someuser_10.10.10.1:
    mysql_user.present:
      - name: someuser
      - host: '10.10.10.1'
      - password_hash: '*A71F9D497CFA78B6D9CE9D497CFA7FA78F4E730D'
      - connection_charset: utf8

mysql_user_someuser_10.10.10.1_0:
  mysql_grants.present:
    - name: someuser_md_intramed_all
    - grant: all privileges
    - database: 'md_intramed.*'
    - grant_option: False

    - user: someuser
    - host: '10.10.10.1'
    - escape: True
    - connection_charset: utf8
    - require:
      - mysql_user: mysql_user_someuser_10.10.10.1
```

fails with:
```
[INFO    ] Running state [someuser] at time 07:48:20.500277
[INFO    ] Executing state mysql_user.present for [someuser]
[DEBUG   ] showvariables<--
[DEBUG   ] __do_query_into_hash<--(SHOW VARIABLES)
[DEBUG   ] Doing query: SHOW VARIABLES
[DEBUG   ] __do_query_into_hash-->
[DEBUG   ] showvariables-->2
[ERROR   ] MySQL Error: Unable to determine MySQL  version_comment, check connection arguments.
[ERROR   ] MySQL Error: Unable to determine MySQL  version_comment, check connection arguments.
[INFO    ] Completed state [someuser] at time 07:48:20.507010 (duration_in_ms=6.733)
```

it doesn't matter if I add

```yaml
    - connection_host: 'localhost'
    - connection_user: 'root'
    - connection_pass 'rootpass'
```
to the states (or any combination of the 3 parameters), the error is the same as above. 

Note that I usually have *NO* mysql configuration in `/etc/salt/minion` (I never did) as described in [the docs](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mysql.html#module-salt.modules.mysql), but adding it makes no difference.

Hope this helps

**Comment by garethgreenaway** [comment]
@javierbetroli thanks!  Will check out this scenario. Are you allowing local connections to mysql without the need for a password?

**Comment by javierbertoli** [comment]
Yes, the setup is using the default configuration, allowing `root` passwordless access through the `unix_socket` plugin. 

Locally, the mysql client connects OK.

Something else that [I found out today](https://github.com/saltstack/salt/issues/51559#issuecomment-501636724) is that the `states/mysql_database.py` can connect to the database (although it's throwing other errors not related to the connection itself). Perhaps this fact can help to debug the issue?

**Comment by garethgreenaway** [comment]
@javierbertoli Thanks for the update.  I think it's probably the `unix_socket` support, it might not be being taken into account when attempting to determine the version of MySQL that is installed.

**Comment by garethgreenaway** [comment]
@javierbertoli Can you try running the `mysql.version` and `mysql.version_comment` commands, to verify if they're working as expected?

**Comment by javierbertoli** [comment]
```bash
~# salt-call --local mysql.version
local:
    10.1.38-MariaDB-0+deb9u1
```
```bash
~# salt-call --local mysql.version_comment
local:
    None
```
and when run with `-l all`
```bash
~# salt-call --local mysql.version_comment -l all
...
...
[DEBUG   ] LazyLoaded mysql.version_comment
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] showvariables<--
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] __do_query_into_hash<--(SHOW VARIABLES)
[DEBUG   ] Doing query: SHOW VARIABLES
[DEBUG   ] __do_query_into_hash-->
[DEBUG   ] showvariables-->2
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'local': None}
```

**Comment by garethgreenaway** [comment]
@javierbertoli Thanks!  one more, `mysql.getvariable version_comment` and if possible can you log into the MariaDB console and show the query `SHOW VARIABLES` verify that `version_comment` is there?  Thanks!

**Comment by javierbertoli** [comment]
* Salt
```bash
~# salt-call --local mysql.getvariable version_comment
local:
    ----------
```
* with debug
```
~# salt-call --local mysql.getvariable version_comment -l al;
...
[DEBUG   ] LazyLoaded mysql.getvariable
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] showvariables<--
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] __do_query_into_hash<--(SHOW VARIABLES)
[DEBUG   ] Doing query: SHOW VARIABLES
[DEBUG   ] __do_query_into_hash-->
[DEBUG   ] showvariables-->2
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'local': {}}
local:
    ----------
```

* MariaDB
```bash
MariaDB [(none)]> show variables like 'version%' ;
...
+-------------------------+--------------------------+
| Variable_name           | Value                    |
+-------------------------+--------------------------+
| version                 | 10.1.38-MariaDB-0+deb9u1 |
| version_comment         | Debian 9.8               |
| version_compile_machine | x86_64                   |
| version_compile_os      | debian-linux-gnu         |
| version_malloc_library  | system jemalloc          |
| version_ssl_library     | YaSSL 2.4.4              |
+-------------------------+--------------------------+
6 rows in set (0.00 sec)
```

**Comment by garethgreenaway** [comment]
@javierbertoli Found the issue.  The data in from "SHOW VARIABLES" was being returned as bytestrings under Python3.  I updated the PR to account for that.  Could you give it another test?  Thanks@

**Comment by javierbertoli** [comment]
Now the error changed to a *Type* error:

```
[INFO    ] Running state [someuser] at time 08:05:12.676103
[INFO    ] Executing state mysql_user.present for [someuser]
[DEBUG   ] showvariables<--
[DEBUG   ] __do_query_into_hash<--(SHOW VARIABLES)
[DEBUG   ] Doing query: SHOW VARIABLES
[DEBUG   ] __do_query_into_hash-->
[DEBUG   ] showvariables-->2
[DEBUG   ] Doing query: SELECT VERSION()
[DEBUG   ] An exception occurred in this state: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1939, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/mysql_user.py", line 159, in present
    **connection_args):
  File "/usr/lib/python3/dist-packages/salt/modules/mysql.py", line 1466, in user_exists
    if 'mariadb' in _version_comment.lower() or 'mariadb' in _version.lower():
TypeError: a bytes-like object is required, not 'str'
```

**Comment by garethgreenaway** [comment]
@javierbertoli Apologies forgot to commit a change, just updated the PR so it should be good now.  Thanks!

**Comment by javierbertoli** [comment]
Awesome work, @garethgreenaway ! Thnaks! It works OK now. 

There's an issue with character escaping in dbnames with underscores, but that's not related to this issue/fix (most probably related to #51559, #47460, #50433).

**Comment by garethgreenaway** [comment]
@javierbertoli Awesome!  Glad to hear it!  I'll take a peek at those other issues.

**Comment by hbonath** [comment]
I believe I am hitting this bug too - is this something that should be fixed when 2019.2.2 drops?

**Comment by jeffdyke** [comment]
for anyone still getting bit by this, here is a patch  you can apply to `salt/modules/mysql.py`
```
1438,1439d1437
<             qry += ' IDENTIFIED BY %(password)s'
<         else:
1440a1439,1440
>         else:
>             qry += ' IDENTIFIED BY %(password)s'
1555c1555
<         qry = "ALTER USER %(user)s@%(host)s IDENTIFIED BY %(password)s;"
---
>         qry = "ALTER USER %(user)s@%(host)s IDENTIFIED BY PASSWORD %(password)s;"
```

**Comment by jeffdyke** [comment]
@garethgreenaway I think this should be moved to P1 and released ASAP.  I don't trust this module in anything but develop, so i add people manually.  This has been broken and open for just shy of a year.  I have posted this patch in other PRs, i would be happy to test my config against master which looks to be fixed....but this is a state that can take down your **entire** production environment, if you're not sure of these subtleties.   I realize the hardships of keeping up with a module like this, which is why i'll test.  I have not run this in production in over a year b/c of this.

**Comment by jeffdyke** [comment]
and btw @garethgreenaway , i know you give a s**t, which is why i tagged  you :)

**Comment by emmettu** [comment]
For visibility: just ran into this issue as well running MariaDB `10.2.30`. Salt applies `password_hash` as a regular password and not a hash when `ALTER`ing a user.

**Comment by garethgreenaway** [comment]
We've released 3000.1 so this issue should be resolved.  If the issues mentioned above persist or new ones pop up please open a new issue.  Thanks!
