### ISSUE TITLE
Compiling pillar fails after upgrade to 2019.2.0

### ISSUE THREAD

**Issue by davtex** [saltstack/salt#52266]
Hi,

We have an issue with compiling pillar data after upgrade from 2018.3.2 to 2019.2.0. Problem disappears after downgrade to 2018.3.2 and reappears after repeated upgrade. Configuration in both cases is the same.

In our setup, we use ext_pillar script (zz_group.py) to load pillar data from MongoDB for each minion. This pillar data is then used in top.sls to target minions for additional pillar data calculation. I went through the release notes and can't see anything that could be causing this. All minions are affected.

In new version, pillar compilation fails as soon as Salt tries to target minions using pillar in top.sls.

**2018.3.2**
```
> 2019-03-20 19:15:39,321 [salt.utils.lazy                                       :100 ][DEBUG   ][32288] LazyLoaded zz_groups.ext_pillar
> 2019-03-20 19:15:39,321 [salt.loaded.ext.pillar.zz_groups                      :288 ][DEBUG   ][32288] ext_pillar.zz_groups.get_connection: conn_opts: {'host': [u'XXX.YYY.com:27017', u'XXX2.YYY.com:27017'], 'readPreference': 'secondaryPreferred', 'replicaset': u'rsmongo'}
> 2019-03-20 19:15:39,340 [salt.loaded.ext.pillar.zz_groups                      :900 ][DEBUG   ][32288] ext_pillar.zz_groups: found document, returning whole doc
> 2019-03-20 19:15:39,340 [salt.loaded.ext.pillar.zz_groups                      :933 ][DEBUG   ][32288] ext_pillar.zz_groups: looking up vhost pillar data
> 2019-03-20 19:15:39,351 [salt.utils.lazy                                       :100 ][DEBUG   ][32288] LazyLoaded jinja.render
> 2019-03-20 19:15:39,352 [salt.utils.lazy                                       :100 ][DEBUG   ][32288] LazyLoaded yaml.render
> 2019-03-20 19:15:39,353 [salt.minion                                           :3371][DEBUG   ][32288] compound_match: XXX.YYY.com ? *
> 2019-03-20 19:15:39,353 [salt.minion                                           :3440][DEBUG   ][32288] compound_match XXX.YYY.com ? "*" => "True"
> 2019-03-20 19:15:39,353 [salt.minion                                           :3371][DEBUG   ][32288] compound_match: XXX.YYY.com ? ZZZ2.YYY.com or ZZZ7.YYY.com
> 2019-03-20 19:15:39,354 [salt.minion                                           :3440][DEBUG   ][32288] compound_match XXX.YYY.com ? "ZZZ2.YYY.com or ZZZ7.YYY.com" => "False or False"
> 2019-03-20 19:15:39,354 [salt.minion                                           :3234][DEBUG   ][32288] grains target: zz_environment:test
> 2019-03-20 19:15:39,354 [salt.utils.data                                       :571 ][DEBUG   ][32288] Attempting to match 'test' in 'zz_environment' using delimiter ':'
> 2019-03-20 19:15:39,354 [salt.minion                                           :3234][DEBUG   ][32288] grains target: zz_region:emea
> 2019-03-20 19:15:39,355 [salt.utils.data                                       :571 ][DEBUG   ][32288] Attempting to match 'emea' in 'zz_region' using delimiter ':'
> 2019-03-20 19:15:39,355 [salt.minion                                           :3288][DEBUG   ][32288] pillar target: zz_server_group:elk
> 2019-03-20 19:15:39,355 [salt.utils.data                                       :571 ][DEBUG   ][32288] Attempting to match 'elk' in 'zz_server_group' using delimiter ':'
> 2019-03-20 19:15:39,355 [salt.minion                                           :3288][DEBUG   ][32288] pillar target: zz_server_group:sensu
```

**2019.2.0**
```
> 2019-03-20 19:15:44,619 [salt.utils.lazy                                       :104 ][DEBUG   ][11670] LazyLoaded zz_groups.ext_pillar
> 2019-03-20 19:15:44,619 [salt.loaded.ext.pillar.zz_groups                      :288 ][DEBUG   ][11670] ext_pillar.zz_groups.get_connection: conn_opts: {'host': [u'XXX.YYY.com:27017', u'XXX2.YYY.com:27017'], 'readPreference': 'secondaryPreferred', 'replicaset': u'rsmongo'}
> 2019-03-20 19:15:44,639 [salt.loaded.ext.pillar.zz_groups                      :900 ][DEBUG   ][11670] ext_pillar.zz_groups: found document, returning whole doc
> 2019-03-20 19:15:44,640 [salt.loaded.ext.pillar.zz_groups                      :933 ][DEBUG   ][11670] ext_pillar.zz_groups: looking up vhost pillar data
> 2019-03-20 19:15:44,653 [salt.utils.lazy                                       :104 ][DEBUG   ][11670] LazyLoaded jinja.render
> 2019-03-20 19:15:44,654 [salt.utils.lazy                                       :104 ][DEBUG   ][11670] LazyLoaded yaml.render
> 2019-03-20 19:15:44,655 [salt.utils.lazy                                       :104 ][DEBUG   ][11670] LazyLoaded confirm_top.confirm_top
> 2019-03-20 19:15:44,658 [salt.utils.lazy                                               :104 ][DEBUG   ][11670] LazyLoaded compound_match.match
> 2019-03-20 19:15:44,660 [salt.loaded.int.matchers.compound_match                       :32  ][DEBUG   ][11670] compound_match: XXX.YYY.com ? *
> 2019-03-20 19:15:44,661 [salt.utils.lazy                                               :104 ][DEBUG   ][11670] LazyLoaded glob_match.match
> 2019-03-20 19:15:44,661 [salt.loaded.int.matchers.compound_match                       :105 ][DEBUG   ][11670] compound_match XXX.YYY.com ? "*" => "True"
> 2019-03-20 19:15:44,664 [salt.utils.lazy                                               :104 ][DEBUG   ][11670] LazyLoaded compound_match.match
> 2019-03-20 19:15:44,666 [salt.loaded.int.matchers.compound_match                       :32  ][DEBUG   ][11670] compound_match: XXX.YYY.com ? ZZZ2.YYY.com or ZZZ7.YYY.com
> 2019-03-20 19:15:44,667 [salt.utils.lazy                                               :104 ][DEBUG   ][11670] LazyLoaded glob_match.match
> 2019-03-20 19:15:44,668 [salt.loaded.int.matchers.compound_match                       :105 ][DEBUG   ][11670] compound_match XXX.YYY.com ? "ZZZ2.YYY.com or ZZZ7.YYY.com" => "False or False"
> 2019-03-20 19:15:44,671 [salt.utils.lazy                                               :104 ][DEBUG   ][11670] LazyLoaded grain_match.match
> 2019-03-20 19:15:44,671 [salt.loaded.int.matchers.grain_match                          :19  ][DEBUG   ][11670] grains target: zz_environment:test
> 2019-03-20 19:15:44,671 [salt.utils.data                                               :615 ][DEBUG   ][11670] Attempting to match 'test' in 'zz_environment' using delimiter ':'
> 2019-03-20 19:15:44,674 [salt.utils.lazy                                               :104 ][DEBUG   ][11670] LazyLoaded grain_match.match
> 2019-03-20 19:15:44,674 [salt.loaded.int.matchers.grain_match                          :19  ][DEBUG   ][11670] grains target: zz_region:emea
> 2019-03-20 19:15:44,674 [salt.utils.data                                               :615 ][DEBUG   ][11670] Attempting to match 'emea' in 'zz_region' using delimiter ':'
> 2019-03-20 19:15:44,677 [salt.utils.lazy                                               :104 ][DEBUG   ][11670] LazyLoaded pillar_match.match
> 2019-03-20 19:15:44,678 [salt.loaded.int.matchers.pillar_match                         :18  ][DEBUG   ][11670] pillar target: zz_server_group:elk
> 2019-03-20 19:15:44,678 [salt.master                                                   :1845][ERROR   ][11670] Error in function _pillar:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/salt/master.py", line 1838, in run_func
>     ret = getattr(self, func)(load)
>   File "/usr/lib/python2.7/site-packages/salt/master.py", line 1543, in _pillar
>     data = pillar.compile_pillar()
>   File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 1005, in compile_pillar
>     matches = self.top_matches(top)
>   File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 675, in top_matches
>     self.opts.get('nodegroups', {}),
>   File "/usr/lib/python2.7/site-packages/salt/matchers/confirm_top.py", line 36, in confirm_top
>     return m(match)
>   File "/usr/lib/python2.7/site-packages/salt/matchers/pillar_match.py", line 24, in match
>     __opts__['pillar'], tgt, delimiter=delimiter
> KeyError: u'pillar'
```

OS:
CentOS release 6.8

Python:
Python 2.7.13

**Comment by garethgreenaway** [comment]
@davtex Thanks for the report.  Can you provide a copy of the external pillar, that will help us to try to determine what is going wrong.  Thanks!

**Comment by davtex** [comment]
@garethgreenaway 

I upgraded to 2019.2.0 again and emptied out top.sls. Pillar in this case compiled successfully as it only consisted of ext_pillar.

I have also tried compiling pillar for one of our ELK servers, where ext_pillar actually returns zz_server_group:elk, however Salt still fails at exactly the same step (when targeting zz_server_group:elk).

**Non-ELK host:**
> XXX.YYY.com:
>     ----------
>     zz_fw:
>         ----------
>         salt:
>             ----------
>     zz_instance_info:
>         ----------
>     zz_instances:
>         ----------
>         salt:
>     zz_k8s_instance_info:
>         ----------
>     zz_k8s_instances:
>         ----------
>         salt:
>     zz_k8s_mapping:
>         ----------
>     zz_line:
>         1
>     zz_server_group:
>         - salt
>     zz_server_group_env:
>         prod
>     zz_server_group_tier:
>         ----------
>         salt:
>             - app
>     zz_software:
>         ----------
>         salt:
>             ----------
>     zz_tier:
>         - app
>     zz_vhosts:
>         ----------
>     zz_zone:
>         internal

**ELK Host**

> XXX.YYY.com:
>     ----------
>     zz_destination_servers:
>         ----------
>         elk:
>             ----------
>             primary:
>                 - XXX
>             secondary:
>                 - YYY
>     zz_fw:
>         ----------
>         elk:
>             ----------
>     zz_instance_info:
>         ----------
>         alerta:
>             ----------
>             port:
>                 443
>             uri_authority_paths:
>                 - alerta
>         alerta/api:
>             ----------
>             port:
>                 5005
>             uri_authority_paths:
>                 - alerta/api
>         auth:
>             ----------
>             port:
>                 5006
>             uri_authority_paths:
>                 - auth
>         elasticsearch:
>             ----------
>             port:
>                 9200
>             uri_authority_paths:
>                 - elasticsearch
>         grafana:
>             ----------
>             port:
>                 3001
>             uri_authority_paths:
>                 - grafana
>         kibana:
>             ----------
>             port:
>                 5601
>             uri_authority_paths:
>                 - kibana
>     zz_instances:
>         ----------
>         elk:
>             - auth
>             - grafana
>             - elasticsearch
>             - kibana
>             - alerta
>             - alerta/api
>     zz_k8s_instance_info:
>         ----------
>     zz_k8s_instances:
>         ----------
>         elk:
>     zz_k8s_mapping:
>         ----------
>     zz_line:
>         1
>     zz_server_group:
>         - elk
>     zz_server_group_env:
>         prod
>     zz_server_group_tier:
>         ----------
>         elk:
>             - web
>             - app
>     zz_software:
>         ----------
>         elk:
>             ----------
>             alerta_webui:
>                 ----------
>                 pkg_iteration:
>                     2
>                 vendor:
>                     alertaio
>                 version_name:
>                     3.0.0
>             elasticsearch:
>                 ----------
>                 pkg_iteration:
>                     1
>                 vendor:
>                     elastic
>                 version_name:
>                     6.6.1
>             zz_apache:
>                 ----------
>                 pkg_iteration:
>                     1
>                 vendor:
>                     firstdata
>                 version_name:
>                     2.4.27
>             grafana:
>                 ----------
>                 pkg_iteration:
>                     1
>                 vendor:
>                     grafana
>                 version_name:
>                     6.0.0
>             java:
>                 ----------
>                 pkg_iteration:
>                     None
>                 vendor:
>                     oracle
>                 version_name:
>                     1.8.144
>             kibana:
>                 ----------
>                 pkg_iteration:
>                     1
>                 vendor:
>                     elastic
>                 version_name:
>                     6.6.1
>     zz_tier:
>         - web
>         - app
>     zz_vhosts:
>         ----------
>         elk:
>             ----------
>             XXX.YYY.com:
>                 ----------
>                 connection:
>                     elk_web
>                 healthcheck:
>                     dynamic
>                 instances:
>                     - grafana
>                     - kibana
>                     - uchiwa
>                     - elasticsearch
>                     - alerta
>                     - auth
>                     - alerta/api
>                 k8s_instances:
>                 listener_ip:
>                     - XXX
>                 listener_name:
>                     YYY
>                 uri_authority_host:
>                     XXX
>                 uri_authority_port:
>                     443
>                 uri_scheme:
>                     https
>                 vipa_name:
>                     None
>     zz_zone:
>         internal
>

**Comment by rbjorklin** [comment]
I'm hitting the same stack trace with 2019.02 when using Jinja templating in my pillars. An example of my pillar can be seen [here.](https://github.com/rbjorklin/nomad-demo/blob/pillar-match-key-error/pillar/base/consul/init.sls#L30-L33)

```
# salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Oct 15 2018, 15:26:09)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.0.2
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 29 Twenty Nine
         locale: UTF-8
        machine: x86_64
        release: 5.0.9-200.fc29.x86_64
         system: Linux
        version: Fedora 29 Twenty Nine
```

**Comment by rbjorklin** [comment]
Thanks for the fix @Ch3LL. I tried this for my use-case and I'm still seeing this stack trace after running `bootstrap.sh git develop` which should have had your fix in it, right?

```
ay 08 17:09:58 node01 salt-master[8911]: [ERROR   ] u'pillar'
May 08 17:09:58 node01 salt-master[8911]: Traceback (most recent call last):
May 08 17:09:58 node01 salt-master[8911]:   File "/usr/lib/python2.7/site-packages/salt/modules/match.py", line 142, in pillar
May 08 17:09:58 node01 salt-master[8911]:     return matchers['pillar_match.match'](tgt, delimiter=delimiter, opts=__opts__)
May 08 17:09:58 node01 salt-master[8911]:   File "/usr/lib/python2.7/site-packages/salt/matchers/pillar_match.py", line 26, in match
May 08 17:09:58 node01 salt-master[8911]:     opts['pillar'], tgt, delimiter=delimiter
May 08 17:09:58 node01 salt-master[8911]: KeyError: u'pillar'
May 08 17:09:58 node01 salt-master[8911]: [ERROR   ] u'pillar'
May 08 17:09:58 node01 salt-master[8911]: Traceback (most recent call last):
May 08 17:09:58 node01 salt-master[8911]:   File "/usr/lib/python2.7/site-packages/salt/modules/match.py", line 142, in pillar
May 08 17:09:58 node01 salt-master[8911]:     return matchers['pillar_match.match'](tgt, delimiter=delimiter, opts=__opts__)
May 08 17:09:58 node01 salt-master[8911]:   File "/usr/lib/python2.7/site-packages/salt/matchers/pillar_match.py", line 26, in match
May 08 17:09:58 node01 salt-master[8911]:     opts['pillar'], tgt, delimiter=delimiter
May 08 17:09:58 node01 salt-master[8911]: KeyError: u'pillar'
May 08 17:09:58 node01 salt-master[8911]: [ERROR   ] u'pillar'
May 08 17:09:58 node01 salt-master[8911]: Traceback (most recent call last):
May 08 17:09:58 node01 salt-master[8911]:   File "/usr/lib/python2.7/site-packages/salt/modules/match.py", line 142, in pillar
May 08 17:09:58 node01 salt-master[8911]:     return matchers['pillar_match.match'](tgt, delimiter=delimiter, opts=__opts__)
May 08 17:09:58 node01 salt-master[8911]:   File "/usr/lib/python2.7/site-packages/salt/matchers/pillar_match.py", line 26, in match
May 08 17:09:58 node01 salt-master[8911]:     opts['pillar'], tgt, delimiter=delimiter
May 08 17:09:58 node01 salt-master[8911]: KeyError: u'pillar'
```

I've realized that my use case isn't working on 2018.3.4 either but it's not throwing stack traces on that version.

**Comment by Ch3LL** [comment]
@rbjorklin sorry i missed your message when i posted the fix. The fix is merged into the 2019.2.1 branch. So if you run `bootstrap.sh git 2019.2.1` it should install with the patch.

**Comment by Ch3LL** [comment]
most likely a duplicate of https://github.com/saltstack/salt/issues/52597

can you try the fix in https://github.com/saltstack/salt/pull/52851

**Comment by rbjorklin** [comment]
@Ch3LL I'm still seeing stack traces after running `bootstrap.sh git 2019.2.1` but as a I mentioned my use case seems to be invalid to start with. Apparently it's not possible to populate pillars with `salt.mine` from what I've gathered.

```
May 09 16:55:50 node01 salt-master[21662]: [ERROR   ] u'pillar'
May 09 16:55:50 node01 salt-master[21662]: Traceback (most recent call last):
May 09 16:55:50 node01 salt-master[21662]:   File "/usr/lib/python2.7/site-packages/salt/modules/match.py", line 140, in pillar
May 09 16:55:50 node01 salt-master[21662]:     return matchers['pillar_match.match'](tgt, delimiter=delimiter)
May 09 16:55:50 node01 salt-master[21662]:   File "/usr/lib/python2.7/site-packages/salt/matchers/pillar_match.py", line 24, in match
May 09 16:55:50 node01 salt-master[21662]:     __opts__['pillar'], tgt, delimiter=delimiter
May 09 16:55:50 node01 salt-master[21662]: KeyError: u'pillar'
May 09 16:55:50 node01 salt-master[21662]: [ERROR   ] u'pillar'
May 09 16:55:50 node01 salt-master[21662]: Traceback (most recent call last):
May 09 16:55:50 node01 salt-master[21662]:   File "/usr/lib/python2.7/site-packages/salt/modules/match.py", line 140, in pillar
May 09 16:55:50 node01 salt-master[21662]:     return matchers['pillar_match.match'](tgt, delimiter=delimiter)
May 09 16:55:50 node01 salt-master[21662]:   File "/usr/lib/python2.7/site-packages/salt/matchers/pillar_match.py", line 24, in match
May 09 16:55:50 node01 salt-master[21662]:     __opts__['pillar'], tgt, delimiter=delimiter
May 09 16:55:50 node01 salt-master[21662]: KeyError: u'pillar'
```

**Comment by davtex** [comment]
> most likely a duplicate of #52597
> 
> can you try the fix in #52851

Sorry I couldn't reply sooner - I have applied the fix and everything is working correctly now.  Thank you very much for the help! Looking forward to 2019.2.1
