### ISSUE TITLE
integration.states.test_pip_state.PipStateTest.test_issue_6912_wrong_owner_requirements_file

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#53931]
### Description of Issue
**Find a solution when artifacts isn't available** 
Failure on https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2/76/

**Comment by bryceml** [comment]
I believe the issue was codecov was down.  This is fixed on branch jobs, we need to fix it on pr jobs at some point.  This was the change to fix it: https://github.com/saltstack/sre-jenkins/commit/04a1daa86e2f6d2fcab6e0c3e5e66ff9e4b4fd09

**Comment by DmitryKuzmenko** [comment]
It looks it's not fixed.
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2016-py2/179/
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2019-py2/180/

**Comment by sagetherage** [comment]
closing if this isn't fixed - then open a new ticket with latest from Jenkins
