### ISSUE TITLE
`file.recurse` not returning changes when test=true

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#54160]
The `file.recurse` state does not return any changes in test mode, which causes requisites like `prereq`, `onchanges`, `watch` not working properly.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: 1.4.2.post1
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 12 2019, 20:35:44)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE-p10
         system: FreeBSD
        version: Not Installed
```

**Comment by twangboy** [comment]
This issue was fixed by: https://github.com/saltstack/salt/pull/49832
It was backported to the 2018.3 branch by: https://github.com/saltstack/salt/pull/52415
It will be available in the next 2018.3 release

**Comment by angeloudy** [comment]
@twangboy 
That PR didn't fix `file.recurse`, it only fixed `file.managed`.
