### ISSUE TITLE
state pkg.installed not working when version is specified

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#55630]
I have the following state file.
```
mariadb_pkg:
  pkg.installed:
    - name: mariadb103-server
    - version: {{ salt['pillar.get']('mariadb:version', default_db_version) }}
```
It worked fine for two year until I recently upgraded salt to 2019.2.2

When I run it in debug mode, I got the following message:
```
16:02:31,455 [DEBUG   ] Current version ({'origin': 'databases/mariadb103-server', 'version': ['10.3.20']}) did not match desired version specification (10.3.20), adding to installation targets
```
It seems that salt was trying to compare a `dict` with `str` and decided that it didn't match.

### Versions Report

```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.4.2.post1
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov 12 2019, 23:28:35)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 12.1-RELEASE
         system: FreeBSD
        version: Not Installed
```

**Comment by waynew** [comment]
@angeloudy what version were you previously on?

**Comment by angeloudy** [comment]
@waynew 
My previous version is 2018.3.3

**Comment by asomers** [comment]
This issue is addressed by PR #54074 .  However, I don't think that the currently posted PR contains the best possible solution.

**Comment by waynew** [comment]
I'm working on verifying this, still getting Salt up & running on a BSD box.

**Comment by waynew** [comment]
I was able to reproduce this, and discovered the actual cause (discussed at #54074). There's a bit more digging to decide on the appropriate fix, but for a workaround, one could patch `states/pkg.py` removing these two lines:

https://github.com/saltstack/salt/blob/4fed7e0/salt/states/pkg.py#L1844-L1845

I'm not sure *why* that was introduced a very long time ago, but it appears that the `pkgng.py` state ends out doing the wrong thing in this case.

**Comment by asomers** [comment]
I think I know why that change was introduced.  Every FreeBSD port has an "origin", which is basically the category of the port.  Categories include stuff like "graphics", "devel", "astro", etc.  Though rare, two ports can have the same name but different origins.  Examples include devel/atlas and math/atlas or multimedia/dragon and devel/dragon.  When installing such a port through pkg(8), you _must_ specify the origin in order to unambiguously identify the correct package.  So I would say we cannot simply remove the two lines that set `with_origin`.

**Comment by waynew** [comment]
@asomers that makes a lot of sense.

I wonder - would it make sense to allow passing `with_origin` in? With a default of `True` on FreeBSD?

Another thought is that if we can unambiguously return an installed version there's really no reason for us to require a `with_origin`, right?

**Comment by asomers** [comment]
My idea is to replace `list_pkgs`'s `with_origin` flag with a `verbose` flag, that would be recognized by all pkg implementations.  Without `verbose` set, the output would look like it does today without `with_origin` set.  But with `verbose`, the output would look like it does today when `with_origin` is set, for all package implementations.  But the `origin` field would only be present where it makes sense.  So For FreeBSD it might return something like `{'dragon': {'version': '1.0.0', 'origin': 'devel'}}` but on Debian it would exclude `origin`, like this: `{'dragon': {'version': '1.0.0'}}`.  The nice thing about this approach is that it would minimize inconsistencies between different OSes.

**Comment by fzipi** [comment]
Is there an expected timeline for this?

**Comment by asomers** [comment]
@fzipi I don't have any time allocated for it right now.

**Comment by whytewolf** [comment]
zd-4827

**Comment by sagetherage** [comment]
https://github.com/saltstack/salt/pull/54074

**Comment by s0undt3ch** [comment]
@krionbsd is looking into this one

**Comment by sagetherage** [comment]
this still needs a test case written, I removed `Aluminium` label from the PR, but will leave it on the issue to see if we can find time to write tests next week. If not, this will likely be de-scoped from the `Aluminium` release.

**Comment by dwoz** [comment]
Same root cause as #68886 (FreeBSD pkg.list_pkgs with_origin=True returns {origin, version} dict, breaking version comparison in _verify_install). Fixed by 11e4c5e8bbc, present on 3006.x/3007.x/3008.x/master. Regression test tests/pytests/unit/states/test_pkg.py::test_verify_install_freebsd_with_origin covers matching, mismatching, and unversioned cases.
