### ISSUE TITLE
[BUG] win_powercfg._get_current_scheme() raises exception

### ISSUE THREAD

**Issue by bergentroll** [saltstack/salt#57393]
**Description**
`win_powercfg._get_current_scheme()` raises an exception on Windows 10 minion.

**Setup**
Very default set of Debian 10 master and Windows 10 minion.

**Steps to Reproduce the behavior**
`salt 'minion1' powercfg.set_standby_timeout 0` (or `set_whatever_timeout`).

gives:
```
Minion1:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt-3000.3-py3.5.egg\salt\minion.py", line 1676, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt-3000.3-py3.5.egg\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt-3000.3-py3.5.egg\salt\modules\win_powercfg.py", line 195, in set_disk_timeout
        value=timeout)
      File "c:\salt\bin\lib\site-packages\salt-3000.3-py3.5.egg\salt\modules\win_powercfg.py", line 77, in _set_powercfg_value
        scheme = _get_current_scheme()
      File "c:\salt\bin\lib\site-packages\salt-3000.3-py3.5.egg\salt\modules\win_powercfg.py", line 41, in _get_current_scheme
        return matches.groups()[0].strip()
    AttributeError: 'NoneType' object has no attribute 'groups'
ERROR: Minions returned with non-zero exit code  
```

**Expected behavior**
```
minion1:
  True
```

**Versions Report**
<details><summary>SaltStack 3000.3</summary>

```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1251
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free
```
</details>

**Comment by twangboy** [comment]
I am unable to reproduce this.
What does the following command return?
```
powercfg /getactivescheme
```
mine returns the following:
```
C:\dev\salt>powercfg /getactivescheme
Power Scheme GUID: 381b4222-f694-41f0-9685-ff5bb260df2e  (Balanced)
```

**Comment by bergentroll** [comment]
@twangboy, absolutely.
```
powercfg /getactivescheme
GUID схемы питания: 381b4222-f694-41f0-9685-ff5bb260df2e  (Сбалансированная)
```
(There is Cyrillic signs in output.)

With salt (Cyrillic chars are missing):
```
salt 'minion1' cmd.run 'powercfg /getactivescheme'
Minion1:
    GUID ????? ???????: 381b4222-f694-41f0-9685-ff5bb260df2e  (????????????????)
```

**Comment by sagetherage** [comment]
@cmcmarrow Shane looks like he isn't able to follow up here, can you, please?

**Comment by damon-atkins** [comment]
Console output is fixed in Python 3.6

**Comment by sagetherage** [comment]
closing this as corrected with supported Python versions

**Comment by marianomd** [comment]
This is still happening with 3005.1:

`salt '*' powercfg.get_standby_timeout`

```
TAS-0001:
    The minion function caused an exception: Traceback (most recent call last):
      File "salt\minion.py", line 1935, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "salt\minion.py", line 1894, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "salt\loader\lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "salt\loader\lazy.py", line 1228, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "salt\loader\lazy.py", line 1243, in _run_as
        return _func_or_method(*args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\bin\salt\executors\direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "salt\loader\lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "salt\loader\lazy.py", line 1228, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "salt\loader\lazy.py", line 1243, in _run_as
        return _func_or_method(*args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\bin\salt\modules\win_powercfg.py", line 294, in get_standby_timeout
        return _get_powercfg_minute_values(
      File "C:\Program Files\Salt Project\Salt\bin\salt\modules\win_powercfg.py", line 47, in _get_powercfg_minute_values
        scheme = _get_current_scheme()
      File "C:\Program Files\Salt Project\Salt\bin\salt\modules\win_powercfg.py", line 38, in _get_current_scheme
        return matches.groups()[0].strip()
    AttributeError: 'NoneType' object has no attribute 'groups'
```
