### ISSUE TITLE
[BUG] "RuntimeError: dictionary changed size during iteration" when running genesis.mksls

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#57845]
**Description**
Receive the a 'RuntimeError: dictionary changed size during iteration' when running genesis.mksls to convert a kickstart file to an SLS file

**Setup**
Create the following kickstart file on /tmp/anaconda-ks.cfg:

```
#version=DEVEL
# System authorization information
auth --enableshadow --passalgo=sha512
# Install OS instead of upgrade
install
repo --name="Server-HighAvailability" --baseurl=file:///run/install/repo/addons/HighAvailability
repo --name="Server-ResilientStorage" --baseurl=file:///run/install/repo/addons/ResilientStorage
repo --name="Server-Mysql" --baseurl=file:///run/install/repo/addons/Mysql
# Use CDROM installation media
cdrom
# Use text mode install
text
# Firewall configuration
firewall --disabled
firstboot --disable
ignoredisk --only-use=sda
# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=static --device=link --gateway=192.0.2.249 --ip=192.0.2.253 --nameserver=192.0.2.1 --netmask=255.255.255.248 --ipv6=auto --activate
network  --bootproto=dhcp --hostname=host2.example.com
# Reboot after installation
reboot --eject
# Root password
rootpw --iscrypted $6$/lIb80D7DgbjByl1$dfDyvmmSeiT3le5eWNRUb/gNtfE1Y.5X5GfsUIkViV3rsCsidHnanVlnUOhwxrz8JX6GTFzXzCAXg4G.YSAb//
# SELinux configuration
selinux --disabled
# System services
services --enabled="chronyd"
# Do not configure the X Window System
skipx
# System timezone
timezone UTC --isUtc
user --groups=s-em7-core --name=em7admin --password=$6$/lIb80D7DgbjByl1$dfDyvmmSeiT3le5eWNRUb/gNtfE1Y.5X5GfsUIkViV3rsCsidHnanVlnUOhwxrz8JX6GTFzXzCAXg4G.YSAb// --iscrypted --shell=/bin/bash
# System bootloader configuration
bootloader --location=mbr --boot-drive=sda
reqpart
# Clear the Master Boot Record
zerombr
# Partition clearing information
clearpart --all
# Disk partitioning information
part pv.60 --asprimary --fstype="lvmpv" --size=91647
part /boot --asprimary --fstype="xfs" --size=512 --label=/boot
volgroup em7vg --pesize=4096 pv.60
logvol /var/log  --fstype="xfs" --size=5120 --name=var_log --vgname=em7vg
logvol /var/log/audit  --fstype="xfs" --size=2048 --name=var_log_audit --vgname=em7vg
logvol /data.local/db  --fstype="xfs" --grow --size=4096 --fsoptions="noatime" --name=db --vgname=em7vg
logvol /home  --fstype="xfs" --size=512 --fsoptions="nosuid" --name=home --vgname=em7vg
logvol /tmp  --fstype="xfs" --size=4608 --name=tmp --vgname=em7vg
logvol /var  --fstype="xfs" --size=6144 --name=var --vgname=em7vg
logvol /  --fstype="xfs" --grow --maxsize=10240 --size=4096 --name=root --vgname=em7vg
logvol swap  --fstype="swap" --size=6016 --name=swap --vgname=em7vg

%pre
# This script will generate /tmp/kickstart_config.out - included above
/usr/bin/python /mnt/install/repo/scripts/install_wizard.py > /dev/tty1
%end

%post --nochroot
export EM7_ISO_INSTALLATION=1
chroot /mnt/sysimage /bin/bash <<'EOT'
if ! [ -d /data/db/mysql ]; then
  /bin/mv /var/lib/mysql/* /data/db/ || true
  /bin/chown -R mysql:mysql /data/db || true
fi
/opt/em7/share/scripts/em7_install.sh cu
source /opt/em7/share/scripts/environment.sh
EOT
%end

%packages
@base
@core
@em7-core
chrony
em7-local-db
em7-model-cu

%end

%addon com_redhat_kdump --disable --reserve-mb='auto'

%end
```

**Steps to Reproduce the behavior**

```
$ sudo salt host1.example.com genesis.mksls kickstart /tmp/anaconda-ks.cfg
host1.example.com:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1870, in _thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/genesis.py", line 739, in mksls
        return salt.utils.kickstart.mksls(src, dst)
      File "/usr/lib/python3.6/site-packages/salt/utils/kickstart.py", line 927, in mksls
        ks_opts["auth"] = parse_auth(line)
      File "/usr/lib/python3.6/site-packages/salt/utils/kickstart.py", line 116, in parse_auth
        args = clean_args(vars(parser.parse_args(rules)))
      File "/usr/lib/python3.6/site-packages/salt/utils/kickstart.py", line 21, in clean_args
        for arg in args:
    RuntimeError: dictionary changed size during iteration
```

**Expected behavior**
An SLS file to me output

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-147.el8.x86_64
         system: Linux
        version: CentOS Linux 8 Core
```
</details>

**Comment by cmcmarrow** [comment]
@ggiesen thanks for the report. line 21 should be 'for arg in tuple(args):'

**Comment by ggiesen** [comment]
I don't mind creating a PR for this to fix this simple one-line issue. That being said:

1) There are currently no unit tests for kickstart.py. Do you want tests created? I suspect the reason for lack of unit tests is the difficulty in working with the files in the first place.

2) Even after the shrinking dictionary loop fix, the minion times out with no file generated.

host2.example.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20200702211245514717
ERROR: Minions returned with non-zero exit code

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/57869

**Comment by ggiesen** [comment]
FYI I pulled in @terminalmage's fixes and ran minion in debug mode and minion still not returning anything:

```
[INFO    ] User sudo_user Executing command genesis.mksls with jid 20200706174901338968
[DEBUG   ] Command details {'fun': 'genesis.mksls', 'arg': ['kickstart', '/tmp/anaconda-ks.cfg'], 'tgt': 'host2.example.com', 'jid': '20200706174901338968', 'ret': '', 'tgt_type': 'glob', 'user': 'sudo_user'}
[DEBUG   ] Subprocess ProcessPayload-Job-20200706174901338968 added
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Starting a new job 20200706174901338968 with PID 255595
[DEBUG   ] Could not LazyLoad direct_call.allow_missing_func: 'direct_call.allow_missing_func' is not available.
[DEBUG   ] LazyLoaded genesis.mksls
usage: salt-minion [-h] [--vckeymap VCKEYMAP] [--xlayouts XLAYOUTS]
                   [--switch SWITCH]
                   keyboard
salt-minion: error: the following arguments are required: keyboard
[DEBUG   ] Subprocess ProcessPayload-Job-20200706174901338968 cleaned up
[INFO    ] User sudo_user Executing command saltutil.find_job with jid 20200706174906354339
[DEBUG   ] Command details {'fun': 'saltutil.find_job', 'arg': ['20200706174901338968'], 'tgt': ['host2.example.com'], 'jid': '20200706174906354339', 'ret': '', 'tgt_type': 'list', 'user': 'sudo_user'}
[DEBUG   ] Subprocess ProcessPayload-Job-20200706174906354339 added
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Starting a new job 20200706174906354339 with PID 255596
[DEBUG   ] Could not LazyLoad direct_call.allow_missing_func: 'direct_call.allow_missing_func' is not available.
[DEBUG   ] LazyLoaded saltutil.find_job
[DEBUG   ] Minion return retry timer set to 8 seconds (randomized)
[INFO    ] Returning information for job: 20200706174906354339
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'host2.example.com', 'tcp://192.0.2.37:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'host2.example.com', 'tcp://192.0.2.37:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://192.0.2.37:4506
[DEBUG   ] Trying to connect to: tcp://192.0.2.37:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] minion return: {'success': True, 'return': {}, 'retcode': 0, 'jid': '20200706174906354339', 'fun': 'saltutil.find_job', 'fun_args': ['20200706174901338968']}
[DEBUG   ] Subprocess ProcessPayload-Job-20200706174906354339 cleaned up
```

**Comment by ggiesen** [comment]
The issue with keyboard is the keyboard argument was being stripped here:

https://github.com/saltstack/salt/blob/master/salt/utils/kickstart.py#L391

And then being required here:

https://github.com/saltstack/salt/blob/master/salt/utils/kickstart.py#L395

I think the simplistic fix is just to remove:

`    rules.pop(0)`

But I'm not sure if that will break anything else

**Comment by terminalmage** [comment]
@techhat wrote this initially and would probably be best to ask on this.

**Comment by ggiesen** [comment]
Found another bug... it doesn't handle "--no-activate" for network configuration. The "--activate" flag doesn't appear to actually do anything, so similarly I added the following line (which does nothing):

`    parser.add_argument("--no-activate", dest="activate", action="store_false")`

right after:

https://github.com/saltstack/salt/blob/b95213ec903402f25c1e0aeb3990fe8452ab63ce/salt/utils/kickstart.py#L537

**Comment by terminalmage** [comment]
@ggiesen These other bugs probably require separate bug reports, since the merging of my PR will automatically close this one.
