### ISSUE TITLE
[BUG] Included pillar file is ignored, if it is referenced more than once, even if the target key differs.

### ISSUE THREAD

**Issue by dheuvels** [saltstack/salt#58967]
**Description**
The SaltStack documentation mentions [pillar includes with targets (`key`) and template variables (`defaults`)](https://docs.saltstack.com/en/latest/topics/pillar/#including-other-pillars). This kind of templating only makes sense, if the included file can be referenced more than once, but Salt ignores repeated includes with the same filename.

**Setup**
Create an example pillar like this:
`./top.sls`:
```
base:
  'test_minion':
    - users
```
`./users/init.sls`:
```    
include:
  - users.templates.admins:
      defaults:
        uid: 1000
      key: users:tick
  - users.templates.developers:
      defaults:
        uid: 1001
      key: users:trick
  - users.templates.developers:
      defaults:
        uid: 1002
      key: users:track
```    
`./users/templates/admins.sls`:
```
uid: {{ uid }}
gid: 0
group: root
```    
`./users/templates/developers.sls`:
```    
uid: {{ uid }}
gid: 1000
group: tomcat
```

**Steps to Reproduce the behavior**
Render the above pillar (e.g. locally with `salt-call`):
```
cd (directory of above example pillar)
salt-call --local --id test_minion --pillar-root="." --log-file=/tmp/salt-call.log --cachedir=/tmp/salt-call.tmp pillar.items --output=yaml
```

**Expected behavior**
Pillar structure with all included users:
```
local:
  users:
    tick:
      uid: 1000
      gid: 0
      group: root
    track:
      uid: 1002
      gid: 1000
      group: tomcat
    trick:
      uid: 1001
      gid: 1000
      group: tomcat
```
**Actual behavior**
Repeated include is missing:
```
local:
  users:
    tick:
      uid: 1000
      gid: 0
      group: root
    trick:
      uid: 1001
      gid: 1000
      group: tomcat
```

**Versions Report**
3002.1 (but also occurs on head)

**Additional context**
The reason is that `render_pstate` in `salt/pillar/__init__.py` tries to prevent recursive includes (in the set `mods`), but `mods` only keeps track of the included file not the target key.

It should also track the target key, so that the same template can be nested at different positions within the pillar.

**Comment by dwoz** [comment]
Will this get resolved with #58853

**Comment by sagetherage** [comment]
@dheuvels can you take a look at the linked PR to see if this will solve your issues in the Aluminium release?

**Comment by dheuvels** [comment]
@sagetherage 
I don't think #58853 fixes the issue. The pillar example above is still missing a key, when rendered with `pillar.items`.
The cause is in `salt/pillar/__init__.py`, but that file hasn't been changed.

**Comment by dheuvels** [comment]
I added a [comment in 59000](https://github.com/saltstack/salt/pull/59000#issuecomment-782707595) that said the issue was fixed, because after [2f6bf9596e](https://github.com/saltstack/salt/commit/2f6bf9596ef57d09bf0e539bd17b16003bb96666) repeated includes are not ignored anymore.

But then I realized all included files seem to get the same parameters from the `defaults` statement of the first include. In my example all users included from the `developers.sls` template get the same uid 1001.

I am using a Jinja based approach now, to simulate the desired behavior. With a Jinja based importer like so:
`./users/templates/_importer.sls`:
```    
users:
{%- for import in imports %}
{%- with uid = import.uid %}

  {{ import.key }}:
{%- filter indent(width=4) %}
{% include import.template %}
{%- endfilter %}

{%- endwith %}
{%- endfor %}
```    

And then expressing the main include in `./users/init.sls` as follows:
```
include:
  - users.templates._importer:
      defaults:
        imports:
          - key: tick
            template: users/templates/admins.sls
            uid: 1000
          - key: trick
            template: users/templates/developers.sls
            uid: 1001
          - key: track
            template: users/templates/developers.sls
            uid: 1002
```

The only alternative would be doing the includes (and merging) during state execution (the map.jinja approach), but that has too many drawbacks in my opinion.

I don't see how to resolve the conflict in [PR 59000](https://github.com/saltstack/salt/pull/59000), now that the semantics of the `mods` variable have changed. The Jinja based workaround is sufficient for me.

However the Behavior is still not the one that the [Documentation](https://docs.saltproject.io/en/latest/topics/pillar/#including-other-pillars) suggests.

**Comment by whytewolf** [comment]
so I just tested this. and it seems to be working  at least a little better in 3006.1 the key is no longer missing. if there are still issues with the generated pillar of multiple included pillar, please open a new ticket.
