### ISSUE TITLE
[BUG] State pip.installed fails when upgrade is True with pip version 20.3

### ISSUE THREAD

**Issue by ramboramjad** [saltstack/salt#59100]
# Problem description

function ``pip.installed`` fails when running it with `` upgrade: True `` with pip3 v10+. After looking through the code I noticed that the state calls the function ``pip.list_all_versions``. This module in turn runs the command ``[your running python] -m pip install {pkgname}==versions`` in my case it will run ``python3 -m pip install pip==versions `` the idea behind the "random" word `` versions `` is that pip would return all available versions if it mismatches. However in pip version 10+ it does not return the `` from versions: xx xx `` anymore. Due to this it gives an error and pip will not be installed. 

# Testing/Research
output from the command line when running the command myself with pip v9.0.3:

```
# python3 -m pip install pip==blas
Collecting pip==blas
  Could not find a version that satisfies the requirement pip==blas (from versions: 0.2, 0.2.1, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.8.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.2, 1.2.1, 1.3, 1.3.1, 1.4, 1.4.1, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 6.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.1.0, 6.1.1, 7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.1.0, 7.1.1, 7.1.2, 8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.1.0, 8.1.1, 8.1.2, 9.0.0, 9.0.1, 9.0.2, 9.0.3, 10.0.0b1, 10.0.0b2, 10.0.0, 10.0.1, 18.0, 18.1, 19.0, 19.0.1, 19.0.2, 19.0.3, 19.1, 19.1.1, 19.2, 19.2.1, 19.2.2, 19.2.3, 19.3, 19.3.1, 20.0, 20.0.1, 20.0.2, 20.1b1, 20.1, 20.1.1, 20.2b1, 20.2, 20.2.1, 20.2.2, 20.2.3, 20.2.4, 20.3b1, 20.3, 20.3.1)
No matching distribution found for pip==blas
```

output from the command line when running the command myself with pip v20.3:

```
# python3 -m pip install pip==blas
ERROR: Could not find a version that satisfies the requirement pip==blas
ERROR: No matching distribution found for pip==blas
```

Here is my minion debug output:

```
[DEBUG   ] pip: Using pip from currently-running Python
[DEBUG   ] An exception occurred in this state: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call
    *cdata["args"], **cdata["kwargs"]
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2087, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/pip_state.py", line 867, in installed
    **kwargs
  File "/var/cache/salt/minion/extmods/states/pip_state.py", line 330, in _check_if_installed
    desired_version = available_versions[-1]
TypeError: 'NoneType' object is not subscriptable
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call
    *cdata["args"], **cdata["kwargs"]
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2087, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/pip_state.py", line 867, in installed
    **kwargs
  File "/var/cache/salt/minion/extmods/states/pip_state.py", line 330, in _check_if_installed
    desired_version = available_versions[-1]
TypeError: 'NoneType' object is not subscriptable
```

# My state snippet:

```
pip3:
  pip.installed:
    - name: pip
    - upgrade: True
```

Note: if i comment the `` - upgrade: True `` It runs fine.

# Versions report:

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.3.12
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1160.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```

**Comment by andreasnuesslein** [comment]
the underlying pip ticket: https://github.com/pypa/pip/issues/9139

**Comment by MrMino** [comment]
FYI even if [my PR](https://github.com/pypa/pip/pull/9405) for `pip` goes through, this will not work after [`packaging`](https://github.com/pypa/packaging) drops `LegacyVersion` support, as `pip` uses `packaging` to parse these. See [pfmoore's comment](https://github.com/pypa/pip/pull/9405#issuecomment-753655272).

**Comment by sagetherage** [comment]
we fixed what we can for `Aluminium` closing for now @MrMino let me know if you want to open this back up or if you want to submit a new issue for your latest comment. Both work I would prefer to have a new issue if you don't mind.

**Comment by MrMino** [comment]
> @MrMino let me know if you want to open this back up or if you want to submit a new issue for your latest comment.

This wasn't my issue, I was just informing you about part of a feature being removed from Pip.

**Comment by ahrex** [comment]
@sagetherage would it be OK to re-open this ticket?

I'm using salt version 3003 (Aluminium) and I still experience the problem.

Thanks!
