### ISSUE TITLE
[BUG] boto_vpc.route_table_present fails with TypeError

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#59281]
**Description**

The `boto_vpc.route_table_present` state can fail in ordinary cases now (since 3002 AFAICT):

```
[ERROR ] An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call
*cdata["args"], **cdata["kwargs"]
File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2106, in wrapper
return f(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/salt/states/boto_vpc.py", line 1123, in route_table_present
profile=profile,
File "/usr/lib/python3.6/site-packages/salt/states/boto_vpc.py", line 1438, in _subnets_present
assoc_ids = [x["subnet_id"] for x in route_table["associations"]]
TypeError: list indices must be integers or slices, not str
```

https://github.com/saltstack/salt/commit/f78706934ffb83c8d215c7c7ec12bcbdd7d8bd45#diff-1f72651468451cc4bde8de43a9b68cdf21e63dcf0f2f5804943bb92a7f780c70R1491 in #58636 broke this AFAICT.  The deprecated method and the new method have different returns and so a drop-in replacement was not appropriate.  The new method returns a list.  Other places in the code do... https://github.com/saltstack/salt/blob/da6819735ce055f16e326472cb1768faece72ad6/salt/states/boto_vpc.py#L1216 ... to handle this.

**Setup**

`foo.sls`:

```sls
create_route_table:
  boto_vpc.route_table_present:
    - name: foo
    - vpc_id: vpc-4321dbca
    - routes:
      - destination_cidr_block: 0.0.0.0/0
        instance_id: i-abcd1234
```

**Steps to Reproduce the behavior**

AWS setup, then `state.apply foo`.

**Expected behavior**

No exception, state completes.

**Versions Report**
<details><summary>salt --versions-report</summary>

Also includes latest `boto` and `boto3`.

```text
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-60-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**

ZD-6200.

Workaround is to directly patch `salt/states/boto_vpc.py` with `route_table = route_table[0]` above the problem line.

**Comment by oeuftete** [comment]
The calls at https://github.com/saltstack/salt/blob/da6819735ce055f16e326472cb1768faece72ad6/salt/states/boto_vpc.py#L645-L662 have the same issue once the result is used at https://github.com/saltstack/salt/blob/da6819735ce055f16e326472cb1768faece72ad6/salt/states/boto_vpc.py#L731.

**Comment by oeuftete** [comment]
Re https://github.com/saltstack/salt/issues/59281#issuecomment-758906586, it appears working around this by getting the first element returned can expose another problem, which is that associations from the route table [don't necessarily have subnet ids](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_route_tables):

> SubnetId (string) --
>
> The ID of the subnet. A subnet ID is not returned for an implicit association.

... and so this can happen at https://github.com/saltstack/salt/blob/da6819735ce055f16e326472cb1768faece72ad6/salt/states/boto_vpc.py#L785

```text
File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call
  *cdata["args"], **cdata["kwargs"]
File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2106, in wrapper
  return f(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/salt/states/boto_vpc.py", line 707, in subnet_present
  if not _verify_subnet_association(route_table_desc, _describe["subnet"]["id"]):
File "/usr/lib/python3.6/site-packages/salt/states/boto_vpc.py", line 786, in _verify_subnet_association
  if association["subnet_id"] == subnet_id:
KeyError: 'subnet_id'
```

@cmcmarrow Let me know if this should be a separate issue, or can be addressed in this issue.

**Comment by cmcmarrow** [comment]
@ouiea we should keep this in the ticket

**Comment by dfidler** [comment]
I had to setup some labs for some salt training that I'm doing and was hit by this and thought I'd do a quick patch which turned into a trip down the rabbit hole.

There are  a number of issues that are all loosely tied to this issue.  They are...
1. methods that manage objects by name (rather than by id) inevitably call describe-* to get the id form the name; these cause failures because they usually expect a return object, but the describe methods are returning lists of objects (as @oeuftete observed)
2. Any method that deals with subnet / route table associations is broken.  It looks like the underlying object specification changed.  Where once doing a describe-route-tables once returned {..., "associations": { "subnet_id": .... , 'route_table_id": ..... }} the now has a route_table_association_id.  I couldn't find a module method that allowed me to query for those objects (the get_resource_id() method fails because it tries to find a "get_all_route_table_associations()" method to fetch them, but that doesn't exist in boto).  I had hacked around it by fetching all subnets in a vpc (which does have the association to the route table) and the route table (which also gives me the association id).  Then I just compare and match - but it's a hack.
3. there seems to be an assumption that certain attributes like "route_table['associations']" (mentioned above) always exist.  I don't know if this was the case, but it looks like now, if an object doesn't have those relationships, they are omitted from the return object.

Unfortunately, I need to abandon this for now as I've got a deadline to meet.  I've got dirty-hack of a fix for boto_vpc._subnets_present() if anyone wants to see what code looks like when it's written by someone who doesn't have an intimate relationship with a module's codebase (or the boto libs).

I am sure I've used this module before for creating vpc/subnet/route tables and I thought it worked back then so i can only assume one of the following has happened:
1. the module was originally written for an earlier version of the ec2 api; if I look at the VPCConnection object, it looks like it's assuming APIVersion: 2014-10-11 (iirc); that's pretty old but maybe a change was made to use that version to gain new functionality and that has broken it?
2. The underlying boto modules have changed and maybe I just need an earlier version of boto to get them to work
3. Some small tweaks were made in this version and we didn't have sufficient test coverage to catch the issues.

With any luck, someone sees this and says, "oh, just move to a prev version of the API" or some equally easy fix.  Otherwise, I think this one will require new scaffolding in the execution module to support routing_table_associations (and hopefully with a more elegant piece of code than what I came up with.

My info:
* OS: CentOS 7
```
# pip3 list | grep boto
boto            2.49.0
boto3           1.17.33
botocore        1.20.33
```

```
# salt-master --versions
Salt Version:
          Salt: 3002.5

Dependency Versions:
          cffi: 1.9.1
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 0.6.4
     gitpython: 1.0.1
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: 0.9.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.15.2.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

**Comment by sagetherage** [comment]
fixed here: https://github.com/saltstack/salt/commit/32ed7d05f0af1f07a0144cf5594370a5d65e70b3

**Comment by defanator** [comment]
@sagetherage @cmcmarrow @dfidler @oeuftete gentlemen, I'm still experiencing the original issue reported in https://github.com/saltstack/salt/pull/59656, and I've just added some findings here in comment: https://github.com/saltstack/salt/pull/59656#issuecomment-963272428

Please let me know whether I should create separate issue, or this could be covered e.g. by reopening this one.

I'm open to provide any additional details if required.

**Comment by defanator** [comment]
@sagetherage @cmcmarrow @dfidler @oeuftete seeing the same with 3006.1 :(

**Comment by oeuftete** [comment]
@defanator At least half of the people you've tagged here no longer work on the project (myself included), and the issue is closed.  I'd recommend opening a new issue.

**Comment by defanator** [comment]
Thank you for responding @oeuftete, appreciate it.

To anyone who might land here in future, the fix from https://github.com/saltstack/salt/pull/59656 still works and can be applied to 3006/3006.1.
