### ISSUE TITLE
[BUG] Slack salt engine stopped working February 24th due to deprecation of API

### ISSUE THREAD

**Issue by cristian-popa** [saltstack/salt#59612]
**Description**
Salt slack engine stopped working today February 24th 2021. Based on my research I think is due to this:  https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api 

"The final date for existing apps and custom integrations is now February 24th, 2021."

**Setup**

Slack engine that worked perfectly fine till today, no config changes. Debug log starting today. I've added a Diagnostic line in slack.py to check the data returned from slack api see lines between ========== lines in the debug output

```
.............
[DEBUG   ] Requesting URL https://slack.com/api/users.list?token=[removed] using GET method
[DEBUG   ] Using backend: tornado
[DEBUG   ] Response Status Code: 200
[DEBUG   ] Requesting URL https://slack.com/api/channels.list?token=[removed] using GET method
[DEBUG   ] Using backend: tornado
[DEBUG   ] Response Status Code: 200
===========================================================
Print Diagnostic line 229 of /usr/lib/python3.6/site-packages/salt/engines/slack.py:  print(ret["message"]) prints out method_deprecated 
=============================================================
[CRITICAL] Engine 'slack' could not be started!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/engines/slack.py", line 949, in start
    client.run_commands_from_slack_async(message_generator, fire_all, tag, control)
  File "/usr/lib/python3.6/site-packages/salt/engines/slack.py", line 787, in run_commands_from_slack_async
    for msg in message_generator:
  File "/usr/lib/python3.6/site-packages/salt/engines/slack.py", line 513, in generate_triggered_messages
    token
  File "/usr/lib/python3.6/site-packages/salt/engines/slack.py", line 230, in get_slack_channels
    channels[item["id"]] = item["name"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/engines/__init__.py", line 135, in run
    self.engine[self.fun](**kwargs)
  File "/usr/lib/python3.6/site-packages/salt/engines/slack.py", line 951, in start
    raise Exception("{}".format(traceback.format_exc()))
Exception: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/engines/slack.py", line 949, in start
    client.run_commands_from_slack_async(message_generator, fire_all, tag, control)
  File "/usr/lib/python3.6/site-packages/salt/engines/slack.py", line 787, in run_commands_from_slack_async
    for msg in message_generator:
  File "/usr/lib/python3.6/site-packages/salt/engines/slack.py", line 513, in generate_triggered_messages
    token
  File "/usr/lib/python3.6/site-packages/salt/engines/slack.py", line 230, in get_slack_channels
    channels[item["id"]] = item["name"]
TypeError: string indices must be integers
```

**Steps to Reproduce the behavior**
Try to use the slack engine, I used to have forced slack client=1.0.0 due to other issues but no slack client version is working now.

**Expected behavior**
Slack engine should work. 

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
salt --versions-report
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.7
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: 3.0.4
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 5.10.13-x86_64
        system: Linux
       version: CentOS Linux 7 Core
 

```
</details>

**Additional context**
I guess the only fix would be to migrate to slack SDK:  https://slack.dev/python-slack-sdk/v3-migration/ . Am I missing any workaround? 
Looks like Slack published these deprecations more than one year ago, curious if there is a process to stay ahead of these moving forward.

**Comment by cristian-popa** [comment]
Fixed my local version: 
/usr/lib/python3.6/site-packages/salt/utils/slack.py
Line 54 change from:
"rooms": {"request": "channels.list", "response": "channels"},
to
"rooms": {"request": "conversations.list", "response": "channels"},

**Comment by xeacott** [comment]
@cristian-popa Would you like to make a PR for those changes? There's other changes that need to happen to the slack module due to the changes from Feb. 24th that we are also aware of.

**Comment by ITJamie** [comment]
The above PR did not fix the engine itself. It still has issues.

```
Sep 10 09:45:20 saltdirector salt-master[440948]: [CRITICAL] Engine 'slack' could not be started!
Sep 10 09:45:20 saltdirector salt-master[440948]: Traceback (most recent call last):
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 933, in start
Sep 10 09:45:20 saltdirector salt-master[440948]:     client.run_commands_from_slack_async(message_generator, fire_all, tag, control)
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 777, in run_commands_from_slack_async
Sep 10 09:45:20 saltdirector salt-master[440948]:     for msg in message_generator:
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 504, in generate_triggered_messages
Sep 10 09:45:20 saltdirector salt-master[440948]:     all_slack_channels = self.get_slack_channels(
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 222, in get_slack_channels
Sep 10 09:45:20 saltdirector salt-master[440948]:     channels[item["id"]] = item["name"]
Sep 10 09:45:20 saltdirector salt-master[440948]: TypeError: string indices must be integers
Sep 10 09:45:20 saltdirector salt-master[440948]: During handling of the above exception, another exception occurred:
Sep 10 09:45:20 saltdirector salt-master[440948]: Traceback (most recent call last):
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/engines/__init__.py", line 130, in run
Sep 10 09:45:20 saltdirector salt-master[440948]:     self.engine[self.fun](**kwargs)
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/loader.py", line 1241, in __call__
Sep 10 09:45:20 saltdirector salt-master[440948]:     return self.loader.run(run_func, *args, **kwargs)
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/loader.py", line 2274, in run
Sep 10 09:45:20 saltdirector salt-master[440948]:     return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/loader.py", line 2289, in _run_as
Sep 10 09:45:20 saltdirector salt-master[440948]:     return _func_or_method(*args, **kwargs)
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 935, in start
Sep 10 09:45:20 saltdirector salt-master[440948]:     raise Exception("{}".format(traceback.format_exc()))
Sep 10 09:45:20 saltdirector salt-master[440948]: Exception: Traceback (most recent call last):
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 933, in start
Sep 10 09:45:20 saltdirector salt-master[440948]:     client.run_commands_from_slack_async(message_generator, fire_all, tag, control)
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 777, in run_commands_from_slack_async
Sep 10 09:45:20 saltdirector salt-master[440948]:     for msg in message_generator:
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 504, in generate_triggered_messages
Sep 10 09:45:20 saltdirector salt-master[440948]:     all_slack_channels = self.get_slack_channels(
Sep 10 09:45:20 saltdirector salt-master[440948]:   File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 222, in get_slack_channels
Sep 10 09:45:20 saltdirector salt-master[440948]:     channels[item["id"]] = item["name"]
Sep 10 09:45:20 saltdirector salt-master[440948]: TypeError: string indices must be integers

```

**Comment by gediminasz** [comment]
The error persists after upgrading to Salt 3005.1:

```
CRITICAL [salt.engines     :108 ][CRITICAL][155205] Engine could not be started!
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 940, in start
    client.run_commands_from_slack_async(message_generator, fire_all, tag, control)
  File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 778, in run_commands_from_slack_async
    for msg in message_generator:
  File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 506, in generate_triggered_messages
    token
  File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 222, in get_slack_channels
    channels[item["id"]] = item["name"]
TypeError: string indices must be integers
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/engines/__init__.py", line 103, in run
    self.engine[self.fun](**kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 942, in start
    raise Exception("{}".format(traceback.format_exc()))
Exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 940, in start
    client.run_commands_from_slack_async(message_generator, fire_all, tag, control)
  File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 778, in run_commands_from_slack_async
    for msg in message_generator:
  File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 506, in generate_triggered_messages
    token
  File "/usr/lib/python3/dist-packages/salt/engines/slack.py", line 222, in get_slack_channels
    channels[item["id"]] = item["name"]
TypeError: string indices must be integers
```
