### ISSUE TITLE
Error in salt module documentation

### ISSUE THREAD

**Issue by infantvin** [saltstack/salt#59666]
### Description of Issue
The module referenced for group changes in salt is documented incorrectly.

Here https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.groupadd.html#salt.modules.groupadd.adduser

It says salt.modules.groupadd.add

However it has to be salt.modules.group.add

When we try to groupadd.xxx as a module name, we get an error saying the module named groupadd does not exist.

The example text has the correct module name in it.

The documentation needs to be changed to correctly reflect the name of the module (group instead of groupadd)

### Setup

Salt master and minion version 3000.3
We are using this inside a state file using the module.run state module.

### Steps to Reproduce Issue

This can be checked by run a salt command with groupadd.xxx or by using this in module.run inside a state file.

An error will be reported stating the module groupadd is not present.
Something similar to:

----------
          ID: docker_group_abcd
    Function: module.run
      Result: False
     Comment: Unavailable function: groupadd.adduser.

### Versions Report

From salt master. Similar on minions as well.

Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: 1.0.0
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 1.2.1
         Python: 3.6.8 (default, Apr 21 2020, 17:13:27)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.6 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.10.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo

**Comment by garethgreenaway** [comment]
@infantvin Thanks for the report.  The root of the issue here is the many of the modules have different filenames versus the virtual name of the modules.  We believe this PR will fix the issue, https://github.com/saltstack/salt/pull/58539.

**Comment by barbaricyawps** [comment]
@garethgreenaway , can you validate that this issue was resolved by that PR that got merged in? If so, can we close this issue?

**Comment by garethgreenaway** [comment]
@barbaricyawps Unfortunately it appears that the PR in question did not resolve the issue.
