### ISSUE TITLE
[BUG] chroot.sls failed: Object of type NamedLoaderContext is not JSON serializable

### ISSUE THREAD

**Issue by alexminder** [saltstack/salt#60475]
**Description**
From salt-3003 chroot.sls stop working.

**Setup**
Code:
```
resolvconf:
  module.run:
  - chroot.sls:
    - root: /mnt/gentoo
    - mods: resolvconf
```

Result:
```
          ID: resolvconf
    Function: module.run
      Result: False
     Comment: 'chroot.sls' failed: Object of type NamedLoaderContext is not JSON serializable
     Changes:
```

**Steps to Reproduce the behavior**
- `module.run` which call `chroot.sls` which call ANY state inside chroot dir

```
2021-07-01 18:24:42,332 [59323][salt.state       ][INFO    ] Running state [resolvconf] at time 18:24:42.332419
2021-07-01 18:24:42,333 [59323][salt.state       ][INFO    ] Executing state module.run for [resolvconf]
2021-07-01 18:24:42,349 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:42,355 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:42,371 [59323][salt.state       ][ERROR   ] Pillar override was not passed as a dictionary
2021-07-01 18:24:45,441 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:45,447 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:45,459 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:45,459 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:45,466 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:45,487 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:45,513 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:45,526 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:45,545 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:45,546 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:45,557 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:45,558 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:46,575 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:46,585 [59323][salt.loader      ][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
2021-07-01 18:24:46,622 [59323][salt.state       ][ERROR   ] 'chroot.sls' failed: Object of type NamedLoaderContext is not JSON serializable
2021-07-01 18:24:46,622 [59323][salt.state       ][INFO    ] Completed state [resolvconf] at time 18:24:46.622240 (duration_in_ms=4289.82)
```

**Expected behavior**
- Show state execution result inside chroot directory

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
# salt --versions-report
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 3.10.1
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.9.5 (default, Jun 14 2021, 02:45:08)
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: gentoo 2.7
        locale: utf-8
       machine: x86_64
       release: 5.10.27-gentoo-x86_64
        system: Linux
       version: Gentoo 2.7
```
</details>

**Comment by OrangeDog** [comment]
This may have been fixed in 3003.1: #60083

**Comment by alexminder** [comment]
I have tried 3003.1. It is different issues. Error still exists.

**Comment by alexminder** [comment]
Can I provide more information for issue fix

**Comment by waynew** [comment]
I was able to reproduce this with:

**/srv/salt/foo.sls**
```
test:
  module.run:
    - name: chroot.sls
    - root: /tmp/whatever
    - mods: test
```

**/srv/salt/test.sls** (matches mods)
```
blerp:
  test.nop
```

Ran `salt-call --local state.apply foo` and got this error.

Looks like it's definitely a problem on 3003 vs 3002.

I'm not sure if this is closely related or not:

```
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[ERROR   ] Module function chroot.sls threw an exception. Exception: Object of type 'NamedLoaderContext' is not JSON serializable
```

**Comment by waynew** [comment]
More context: I added a breakpoint in `module.run_` - it looks like it's failing somewhere within the loader. It's definitely failing before it gets to the `chroot.sls` module.

**Comment by tobyriddell** [comment]
The pillar variable (defined at salt/modules/chroot.py:306) is of type salt.loader.context.NamedLoaderContext and which has no default() method. When prep_trans_tar() tries to serialize it (salt/client/ssh/state.py:203) the default() method at /usr/lib/python3.10/json/encoder.py:160 is executed instead, and this raises the exception.

The comments in the default() method in encoder.py says: 

```Implement this method in a subclass such that it returns
a serializable object for ``o``, or calls the base implementation
(to raise a ``TypeError``).```

Since NamedLoaderContext is a subclass of collections.abc.MutableMapping it has no default() method.

I have implemented a workaround for my use-case (I am using salt-call) by modifying salt/client/ssh/state.py, see https://github.com/tobyriddell/salt/commit/cbec1bb93ccab30634df18ceffd45a64e0af5ee3. 

I haven't test the workaround thoroughly and since it modifies a file used by many other parts of Salt it may well be unpalatable to the Salt developers, but I wanted to share it as it hopefully sheds some light on the problem.

**Comment by alexminder** [comment]
What state of the issue?

**Comment by dwoz** [comment]
Fixed by 2bb3758ba2eb60a557e4a5c1bdb40e55b63f3ae5 ("Fix pillar data propagation for chroot and transaction_update modules"). Present in 3006.x, 3007.x, 3008.x, master. Verified: tests/pytests/unit/modules/test_chroot.py::test__create_and_execute_salt_state passes with __pillar__ set to a NamedLoaderContext. Closing.
