### ISSUE TITLE
[BUG] Memory Leak in EventPublisher process

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#61565]
**Description**

We've observed a memory leak in the EventPubisher process on the master. This can be seen by adding a simple engine to a salt-minion that sends lots of auth requests. It looks like the leak isn't specific to auth events. A large number of any events should trigger it.

**Setup**

```
import salt.crypt
import salt.ext.tornado.ioloop
import salt.ext.tornado.gen
import logging

log = logging.getLogger(__name__)


@salt.ext.tornado.gen.coroutine
def do_auth(opts, io_loop):
    while True:
        auth = salt.crypt.AsyncAuth(opts, io_loop=io_loop)
        log.info("ENGINE DO AUTH")
        yield auth.sign_in()


def start():
    io_loop = salt.ext.tornado.ioloop.IOLoop()
    __opts__['master_uri'] = 'tcp://127.0.0.1:4506'
    io_loop.spawn_callback(do_auth, __opts__, io_loop)
    io_loop.start()
```

**Versions**

v3004

**Comment by frebib** [comment]
Does the number of open file descriptors appear to increase too? I'm wondering if this is related to #61521

**Comment by dwoz** [comment]
Here is a patch that will address the issue for 3004. I've tested this against the master branch and I don't see the memory leak. Looks like the recent transport refactor inadvertently addressed the issue.

[0001-Slow-memory-leak-fix.patch.txt](https://github.com/saltstack/salt/files/7990169/0001-Slow-memory-leak-fix.patch.txt)

@frebib I don't believe this is the same issue as #61521. I believe the root of #61521 is caused by this [commit](https://github.com/saltstack/salt/commit/7af10f24d5d109eed310ddde8b93c091a14b6991#diff-5c50e51c81c653baf9b8826e3697ca74a40c3acab1a7e081b9babc43ab480163). We're probably creating multiple instances of events and transports which needs to be addressed. #61468 should be a step in the right direction.

**Comment by Zpell82** [comment]
is there any progress on this ? 
`Salt Version:
          Salt: 3006.4
 
Python Version:
        Python: 3.10.4 (main, Apr 20 2022, 01:21:48) [GCC 10.3.1 20210424]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: alpine 3.14.6 
        locale: utf-8
       machine: x86_64
       release: 5.15.0-87-generic
        system: Linux
       version: Alpine Linux 3.14.6 `
       
![image](https://github.com/saltstack/salt/assets/24464107/80284d5f-dd71-4ff3-b9de-9bff360ff81f)
![image](https://github.com/saltstack/salt/assets/24464107/b1ee584e-1eff-4a5e-a6a8-406f0035c54c)
![image](https://github.com/saltstack/salt/assets/24464107/0041ea56-a806-48ae-ba91-37d021cc9715)
![image](https://github.com/saltstack/salt/assets/24464107/31b2f7f2-0dee-4edd-a6f9-b83b4aae7c32)
![image](https://github.com/saltstack/salt/assets/24464107/038c00f4-5710-4e88-bc09-7c3bb5c3631a)

**Comment by Zpell82** [comment]
it looks a lot better in 3006.5 when using this https://github.com/saltstack/salt/commit/af12352cba4a4ecd3859addbe21ff7169546fc9c 
solution from minon.py will be observing over the Christmas holidays

**Comment by dwoz** [comment]
> it looks a lot better in 3006.5 when using this [af12352](https://github.com/saltstack/salt/commit/af12352cba4a4ecd3859addbe21ff7169546fc9c) solution from minon.py will be observing over the Christmas holidays

Fantastic news, thanks for the update.

**Comment by max-arnold** [comment]
How to debug a memory leak like this? tracemalloc or some other tools?

**Comment by dwoz** [comment]
@max-arnold

In the past we used to rely on the `__del__` to clean things like this up. That is generally considered an anti-pattern in python and we've been working towards cleaning that practice up. Most recently I've started adding warnings if an object is getting garbage collected without being properly closed (https://github.com/saltstack/salt/pull/65559). That has revealed several places which were cleaned up but just running our test suite.

We've also been working towards better debugging of running salt processes with better tooling.  We've added debug symbol packages in 3006.x and there is a newer tool [relenv-gdb-dbg](https://github.com/saltstack/relenv-gdb-debug) to help debug these kinds of issues.

**Comment by Zpell82** [comment]
looks a lot better when i review Eventpublisher 
![image](https://github.com/saltstack/salt/assets/24464107/7a451d7a-758a-4d27-8915-c283f29a1bee)

**Comment by Zpell82** [comment]
@dwoz i needed to do a flip on this row in the minion.py code 
![image](https://github.com/saltstack/salt/assets/24464107/2c4a2371-635c-4fca-92ac-9e8f9f4bf456)
if I don't do this I won't get any answers or scheduled events data from the  deltaproxy minions to the master

**Comment by network-shark** [comment]
@zpell82 sounds like a bug which should be an issue ?

**Comment by dwoz** [comment]
> @dwoz i needed to do a flip on this row in the minion.py code ![image](https://private-user-images.githubusercontent.com/24464107/294442543-2c4a2371-635c-4fca-92ac-9e8f9f4bf456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3ODA1OTMsIm5iZiI6MTcwNzc4MDI5MywicGF0aCI6Ii8yNDQ2NDEwNy8yOTQ0NDI1NDMtMmM0YTIzNzEtNjM1Yy00ZmNhLTkyYWMtOWU4ZjlmNGJmNDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDIzMjQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MzY4ODIwMWQ3OTdjMGJkM2NkYjZjMTNkYjg3OTg0NWVkOWJjNzVhNmNiMGU2ZGJjMDI2NzlmNDRhYmZjNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.alTudHU2cyhbN76trNqJGr6s-sajyORAoUCU-yUKRyA) if I don't do this I won't get any answers or scheduled events data from the deltaproxy minions to the master, it's just a quick fix probably not the best one, the issue is that the deltaproxy answer is a list if I remember correctly

@Zpell82 Can you open a separate issue for this?

**Comment by aalewis** [comment]
Yeah, seeing this in 3006.6 in testing as well.

**Comment by dwoz** [comment]
I believe this is resolved with `3006.7` can folks confirm?

**Comment by jheiselman** [comment]
I attempted to install 3006.7, but I got an error while trying to salt-pip install pygit2 to use with a git backend.

> ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'readelf'

OS is Debian Bullseye

Maybe a new dependency needs to be added to the deb?

**Comment by lomeroe** [comment]
I still see 3006.7's leaking in our environment...EventPublisher process is over 8GB memory in less than 24 hours after upgrading

A master still at 3006.4 EventPublisher up to 24GB in about 10 days since its last restart

These masters are both using an external job cache.  Masters not using an external job cache don't seem to leak noticeably - are others seeing the leak in 3006.6/etc using an external job cache?  Maybe the external job cache is a red herring, I haven't dug in to all that is all glued together and if that is handled by the EventPublisher process...

**Comment by jheiselman** [comment]
@lomeroe as a matter of fact, ours is using an external job cache (redis).

**Comment by lomeroe** [comment]
interesting...maybe there is something there with the external job cache and the EventPublisher process leaking (we are not using redis as our external job cache, so it would *seem* to not specifically be related to a single external job cache type at least)

@dwoz - thoughts?

**Comment by johje349** [comment]
This is still a problem in 3006.7 for us, and we have a cronjob to restart Salt master once a day. 
We are not using external job cache.

**Comment by lomeroe** [comment]
@johje349 @jheiselman - do either of you run orchestrations or other background jobs that utilize batch mode?  After restarting a master with the patch I mention in #66249, memory for the EventPublisher process hasn't gone over 400MB in almost 24 hours, which *seems* considerably better from what we have been seeing - typically it is several GB in a day.  Obviously need more time monitoring to really tell if it has something to do with it, so it could just be coincidental....

We've got quite a few orchestrations/api initiated jobs that use batch mode (all initiated on the masters exhibiting the issue), so if they were hanging up/never fully returning, I suppose it's possible that could cause memory issues in the EventPublisher process somehow.  I wouldn't have ever guessed that, but...

**Comment by jheiselman** [comment]
We do not have very many, but yes, we do have a few scheduled jobs (started via the salt-api) that utilize batch mode. None of our orchestrations use batch mode.

At this point in time, both of our salt-masters were last restarted four days ago. One of our masters is currently using 3.5 GB of memory and less than 1 GB on another. They share the same workloads/minions. There's no difference between the two. Their salt-api's are behind a load balancer, so some one of them may be getting heavier jobs than the other purely by chance. By the load balancer is configured for a simple round-robin so they should be getting the same number of jobs.

**Comment by johje349** [comment]
Yes we use orchestration states with batch set to 20%.

**Comment by lomeroe** [comment]
After 5 days, EventPublisher memory usage is still hovering around 400MB.  The only change made was applying the patch mentioned in #66249.  Seems fairly likely to me that issue causes memory usage increases in the EventPublisher process due to the jobs run in batch mode never actually ending.

**Comment by thinkst-marco** [comment]
@lomeroe's patch in #66249 worked for us in eliminating the memory leak we were observing in EventPublisher. We don't rely on orchestration, external job caches, or salt-api but do use batches. Thanks for the patch!
