### ISSUE TITLE
Issue with Salt-Syndic and Salt-Minion Responding to Higher Master

### ISSUE THREAD

**Issue by botfish** [saltstack/salt#6207]
Background info: I was originally running Salt 0.15.3 on Ubuntu Server 12.04. I have upgraded to Salt 0.16.0, but this did not seem to change anything. I can reproduce this issue consistently on my environment.

I have a simple 3 node topology:
A root master, running only salt-master, with the "order_masters" options set in the configuration file
A sub-master, running salt-master, salt-syndic, and salt-minion. The salt-syndic and salt-minion are connected to the root master (ie. Their configuration files have the root master's IP set)
A minion, running only salt-minion, connected to the sub-master

My problem is, that whenever I run test.ping (or manage.up) from the root master, I can only ever get a reply from the sub-master's salt-minon OR the minion's salt-minion, never both. It seems like the root master only communicates with either the salt-minion process on the sub-master or the salt-syndic process, but not both. From running the syndic and submaster minion in debug mode, I can see that the one that doesn't respond never even receives the command from the root master.

I can switch which one receives the command by restarting the service that is not responding and then restarting the root master's salt-master service. When the minion is the one receiving commands, the commands will pause as if waiting for the sub-master salt-minion to respond, but it never does. (Simply restarting the services on the sub-master does nothing, I have to restart the root master's service before I see any changes.) Both the salt-syndic and the salt-minion on the submaster seem to exchange keys with the root master just fine when they start, so they are communicating with the root master. This makes me suspect that the problem is with the salt-master service on the root master.

Obviously the salt-syndic is working, because I can communicate just fine with the minion (the one that is connected to the submaster) when that one is the one that is last restarted. Also, this is a simple setup for testing purposes - there is nothing running on these machines except for SaltStack. (I have a Python script I am using to deploy salt-syndic topologies that I can include if anyone thinks it would be helpful.)

I originally posted this as a discussion on the mailing list here: https://groups.google.com/forum/#!topic/salt-users/_dr_OOIzzJY

**Comment by jettero** [comment]
I'm reading this last comment from 2014-09-10 and … now I'm wondering if I have my stuff set up all wrong; as if this bug is still open, my syndic and minion are sharing the same ID and this is the reason the syndic crashes from time to time. ugh.

Is this still a thing?

**Comment by thatch45** [comment]
we have recently added code to resolve this back in 2015.5, but we also had an issue with the syndic which exacerbated our fix, that issue issue was solved in a recent PR:
#33021

So if you try the very small patch found in there it might help out, this fix has been applied to all currently supported versions and will be in upcoming releases

**Comment by bhperry** [comment]
I still see this behavior from time to time on salt 2018.3.0

Salt syndic will just stop responding to the top-level master every once in a while. The syndic process is still running, and it logs nothing about this. Simply doesn't respond anymore. Only way I've found to fix it is to go onto the host and reboot the syndic process.

I was under the impression that you were supposed to have a salt-minion on the same host as salt-syndic and with the same ID as per this note in the docs:
```
Note

To reduce the amount of time the CLI waits for Minions to respond, install a Minion on the Syndic or tune the value of the syndic_wait configuration.
```

Is that not correct? Or is the salt-syndic simply loosing its connection and never reopening it?

**Comment by WangWenchao** [comment]
I test the 2019.2.0 still have this problem 
```
root@master3:~# salt '*' test.ping
master3.example.net:
    True
master4.example.net:
    True
root@master3:~# salt '*' test.ping
master3.example.net:
    True
master4.example.net:
    True
root@master3:~# salt '*' test.ping
master3.example.net:
    True
master4.example.net:
    True
master5.example.net:
    True
root@master3:~# salt '*' test.ping
master3.example.net:
    True
master4.example.net:
    True
master5.example.net:
    True
root@master3:~# salt '*' test.ping
master4.example.net:
    True
master3.example.net:
    True
root@master3:~# salt '*' test.ping
master3.example.net:
    True
master4.example.net:
    True
root@master3:~# salt '*' test.ping
master3.example.net:
    True
master4.example.net:
    True
root@master3:~# salt '*' test.ping
master3.example.net:
    True
master4.example.net:
    True
```
