### ISSUE TITLE
[BUG] 3004.2 Docker: salt-master stops polling gitfs remote (MultiprocessingLoggingQueue and 'ProcessManager FileserverUpdate' processes are gone)

### ISSUE THREAD

**Issue by thedude42** [saltstack/salt#62799]
**Description**
When running the salt master in docker (3004.2 DIGEST:sha256:648823860888ff455b3b14a2b73b16788db6ef8ea2ac37a2e1fd472a9a8ff310) after some time (can be up to a week) salt-master stops polling the configured gitfs remote, and on inspection the MultiprocessingLoggingQueue process and ProcessManager FileserverUpdate process appear to have died and neither is restarted. The salt-master polling of ext_pillar is not affected and continues to function as expected.

**Setup**
master config:
```
fileserver_backend:
  - gitfs

file_roots:
  base:
    - /srv/states

default_top: base
state_top_saltenv: base
top_file_merging_strategy: merge_all

pillar_roots:
  base:
    - /srv/pillar

gitfs_provider: pygit2
gitfs_base: master

gitfs_remotes:
  - <states repo url>

ext_pillar:
  - git:
    - master <pillar repo URL>

user: salt

event_return: [postgres]
master_job_cache: postgres
returner.postgres.host: '<postgres server hostname>'
returner.postgres.user: 'salt'
returner.postgres.passwd: 'salt'
returner.postgres.db: 'salt'
returner.postgres.port: 5432
```

Dockerfile:
```
FROM saltstack/salt:3004.2

RUN deluser salt && addgroup -g 450 -S salt && \
    adduser -s /bin/sh -SD -u 450 -G salt salt && \
    chmod -R 2775 /etc/pki /etc/salt /var/cache/salt /var/log/salt /var/run/salt && \
    chgrp -R salt /etc/pki /etc/salt /var/cache/salt /var/log/salt /var/run/salt && \
    echo "starting apk update" && apk update && echo "finished apk update" && apk add postgresql-dev gcc python3-dev musl-dev gnupg && pip3 install psycopg2 pygit2
```

- [ x ] on-prem machine
- [ x ] container (Kubernetes, Docker, containerd, etc. please specify)

**Steps to Reproduce the behavior**
1. prepare bind mount directories for /etc/salt, /var/cache/salt /var/log/salt and /srv
2. create a system user on the execution host for salt with uid:gid 450 
3. Build the container with the above Dockerfile
4. place the above master config in the corresponding host directory of the bind mount for /etc (in the below docker run example it would be /var/dockermounts/saltmaster/etc/)
5. ensure the values in the master config for <states repo url> and <pillar repo URL> are set and the URLs are reachable anonymously from the execution host 
6. execute the docker run like so (assuming the dirpath for the bind mounts start at /var/dockermounts/saltmaster/): `docker run -d --name salt --hostname salt -u 450 --restart always --network host -v /var/dockermounts/saltmaster/etc:/etc/salt -v /var/dockermounts/saltmaster/cache:/var/cache/salt -v /var/dockermounts/saltmaster/logs:/var/log/salt -v /var/dockermounts/saltmaster/srv:/srv <built container name:tag>`
7. observe the request polling for the salt states (from master config `gitfs_provider: pygit2`) from salt-master until it stops
8. notice that the polling for salt pillar (from master config `ext_pillar:`) does not stop

**Expected behavior**
salt-master continues polling the gitfs configured remote, and the MultiprocessingLoggingQueue process and ProcessManager FileserverUpdate are restarted after they die. Additionally, some logging of this event should probably happen regardless of whether the situation can be recovered from.

**Screenshots**
Here is a before and after of the output of `ps` on the execution host running the salt-master. In this case you can see the processes die after about 35 hours of uptime:
```
Tue Sep 27 17:00:01 UTC 2022
salt     3205016 3205014  0 16:22 ?        00:00:05 /usr/local/bin/python /usr/local/bin/salt-master ProcessManager
salt     3205031 3205016  0 16:22 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master MultiprocessingLoggingQueue
salt     3205095 3205016  0 16:23 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master ZeroMQPubServerChannel
salt     3205098 3205016  0 16:23 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master EventPublisher
salt     3205104 3205016  6 16:23 ?        00:02:31 /usr/local/bin/python /usr/local/bin/salt-master Maintenance
salt     3205131 3205016  0 16:23 ?        00:00:01 /usr/local/bin/python /usr/local/bin/salt-master EventReturn
salt     3205132 3205016  0 16:23 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master ReqServer_ProcessManager
salt     3205135 3205132  0 16:23 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master MWorkerQueue
salt     3205143 3205132  0 16:23 ?        00:00:04 /usr/local/bin/python /usr/local/bin/salt-master MWorker-0
salt     3205145 3205132  0 16:23 ?        00:00:04 /usr/local/bin/python /usr/local/bin/salt-master MWorker-1
salt     3205146 3205132  0 16:23 ?        00:00:04 /usr/local/bin/python /usr/local/bin/salt-master MWorker-2
salt     3205147 3205132  0 16:23 ?        00:00:04 /usr/local/bin/python /usr/local/bin/salt-master MWorker-3
salt     3205148 3205132  0 16:23 ?        00:00:04 /usr/local/bin/python /usr/local/bin/salt-master MWorker-4
salt     3210814 3205016 17 16:58 ?        00:00:18 /usr/local/bin/python /usr/local/bin/salt-master ProcessManager FileserverUpdate
```

```
Thu Sep 29 03:00:01 UTC 2022
salt     3205016 3205014  0 Sep27 ?        00:00:41 /usr/local/bin/python /usr/local/bin/salt-master ProcessManager
salt     3205095 3205016  0 Sep27 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master ZeroMQPubServerChannel
salt     3205098 3205016  0 Sep27 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master EventPublisher
salt     3205104 3205016  6 Sep27 ?        02:24:56 /usr/local/bin/python /usr/local/bin/salt-master Maintenance
salt     3205131 3205016  0 Sep27 ?        00:01:03 /usr/local/bin/python /usr/local/bin/salt-master EventReturn
salt     3205132 3205016  0 Sep27 ?        00:00:06 /usr/local/bin/python /usr/local/bin/salt-master ReqServer_ProcessManager
salt     3205135 3205132  0 Sep27 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master MWorkerQueue
salt     3205143 3205132  0 Sep27 ?        00:00:26 /usr/local/bin/python /usr/local/bin/salt-master MWorker-0
salt     3205145 3205132  0 Sep27 ?        00:00:25 /usr/local/bin/python /usr/local/bin/salt-master MWorker-1
salt     3205146 3205132  0 Sep27 ?        00:00:05 /usr/local/bin/python /usr/local/bin/salt-master MWorker-2
salt     3205147 3205132  0 Sep27 ?        00:00:06 /usr/local/bin/python /usr/local/bin/salt-master MWorker-3
salt     3205148 3205132  0 Sep27 ?        00:00:05 /usr/local/bin/python /usr/local/bin/salt-master MWorker-4
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
$ salt --versions-report
Salt Version:
    Salt: 3004.2

Dependency Versions:
    cffi: 1.14.6
    cherrypy: unknown
    dateutil: 2.8.1
    docker-py: Not Installed
    gitdb: Not Installed
    gitpython: Not Installed
    Jinja2: 2.11.3
    libgit2: 1.1.0
    M2Crypto: Not Installed
    Mako: Not Installed
    msgpack: 1.0.2
    msgpack-pure: Not Installed
    mysql-python: Not Installed
    pycparser: 2.17
    pycrypto: Not Installed
    pycryptodome: 3.9.8
    pygit2: 1.6.1
    Python: 3.7.13 (default, Apr 20 2022, 03:16:50)
    python-gnupg: 0.4.4
    PyYAML: 5.4.1
    PyZMQ: 18.0.1
    smmap: Not Installed
    timelib: 0.2.4
    Tornado: 4.5.3
    ZMQ: 4.3.1

System Versions:
    dist: alpine 3.14.6
    locale: UTF-8
    machine: x86_64
    release: 5.4.0-109-generic
    system: Linux
    version: Alpine Linux 3.14.6
```
</details>

**Additional context**
I had been running an older container build of version 3004.2 when I first saw this issue and the gitfs remote polling would stop after about 1 day consistently. I rebuilt it last month when the latest build was published and it seemed to have improved but after 8 days the salt-master stopped polling gitfs for states. In the last week it seems to be dying after about 2 days.

Can't tell if this is memory related but the salt-master does appear to be steadily increasing memory usage over time without any drop until the container is restarted to resolve the polling issue.

What other things can I do to gather data on why the MultiprocessingLoggingQueue and 'ProcessManager FileserverUpdate' appear to be crashing?

**Comment by OrangeDog** [comment]
Is this only seen in Docker containers? Does this also happen with 3005?

**Comment by thedude42** [comment]
> Is this only seen in Docker containers? Does this also happen with 3005?

Need to test this. Due to the time-related nature of this issue (typically it takes 2 days for the issue to show up regardless of activity on the salt-master or git repo) it may be a week or so before being able to answer.

**Comment by thedude42** [comment]
For whatever reason, the same configuration won't work in 3005.1:

```
$ salt --versions-report
Salt Version:
    Salt: 3005.1

Dependency Versions:
    cffi: 1.15.1
    cherrypy: Not Installed
    dateutil: 2.7.3
    docker-py: 4.1.0
    gitdb: 2.0.6
    gitpython: 3.0.7
    Jinja2: 2.10.1
    libgit2: 1.5.0
    M2Crypto: Not Installed
    Mako: Not Installed
    msgpack: 0.6.2
    msgpack-pure: Not Installed
    mysql-python: Not Installed
    pycparser: 2.21
    pycrypto: Not Installed
    pycryptodome: 3.6.1
    pygit2: 1.10.1
    Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
    python-gnupg: 0.4.5
    PyYAML: 5.3.1
    PyZMQ: 20.0.0
    smmap: 2.0.5
    timelib: Not Installed
    Tornado: 4.5.3
    ZMQ: 4.3.2

System Versions:
    dist: ubuntu 20.04 focal
    locale: utf-8
    machine: x86_64
    release: 5.4.0-109-generic
    system: Linux
    version: Ubuntu 20.04 focal
```

when I try to start the service:
```
● salt-master.service - The Salt Master Server
     Loaded: loaded (/lib/systemd/system/salt-master.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-10-05 05:40:11 UTC; 7min ago
       Docs: man:salt-master(1)
             file:///usr/share/doc/salt/html/contents.html
             https://docs.saltproject.io/en/latest/contents.html
    Process: 646151 ExecStart=/usr/bin/salt-master (code=exited, status=1/FAILURE)
   Main PID: 646151 (code=exited, status=1/FAILURE)

Oct 05 05:40:11 atlantis salt-master[646151]:     return _func_or_method(*args, **kwargs)
Oct 05 05:40:11 atlantis salt-master[646151]:   File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2267, in os_data
Oct 05 05:40:11 atlantis salt-master[646151]:     osarch = __salt__["cmd.run"]("dpkg --print-architecture").strip()
Oct 05 05:40:11 atlantis salt-master[646151]:   File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 939, in _run_quiet
Oct 05 05:40:11 atlantis salt-master[646151]:     return _run(
Oct 05 05:40:11 atlantis salt-master[646151]:   File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 692, in _run
Oct 05 05:40:11 atlantis salt-master[646151]:     raise CommandExecutionError(
Oct 05 05:40:11 atlantis salt-master[646151]: salt.exceptions.CommandExecutionError: Specified cwd '/etc/salt/master' either not absolute or does not exist
```

however:
```
$ ls -l /etc/salt/master
-rw-r--r-- 1 root salt 9615 Jul 24 21:33 /etc/salt/master
```

File contents of  /etc/salt/master is the same as above.

**Comment by thedude42** [comment]
I started a test of `Salt: 3005.1` on bare metal to see if this issue reproduces. Will try to update this issue within 7 days regardless of the outcome.

**Comment by OrangeDog** [comment]
You need [setproctitle](https://pypi.org/project/setproctitle/) installed for Salt to get process titles.

**Comment by thedude42** [comment]
Ahhh, thanks! working now :)

```
salt      718709       1 11 16:43 ?        00:00:04 /usr/bin/python3 /usr/bin/salt-master MainProcess
salt      718855  718709  0 16:43 ?        00:00:00  \_ /usr/bin/python3 /usr/bin/salt-master PubServerChannel._publish_daemon
salt      718856  718709  0 16:43 ?        00:00:00  \_ /usr/bin/python3 /usr/bin/salt-master EventPublisher
salt      718859  718709  1 16:43 ?        00:00:00  \_ /usr/bin/python3 /usr/bin/salt-master Maintenance
salt      718935  718709 51 16:44 ?        00:00:04  \_ /usr/bin/python3 /usr/bin/salt-master EventReturn
salt      718936  718709  1 16:44 ?        00:00:00  \_ /usr/bin/python3 /usr/bin/salt-master ReqServer ReqServer_ProcessManager
salt      718939  718936  0 16:44 ?        00:00:00  |   \_ /usr/bin/python3 /usr/bin/salt-master ReqServer MWorkerQueue
salt      718941  718936  9 16:44 ?        00:00:00  |   \_ /usr/bin/python3 /usr/bin/salt-master ReqServer MWorker-0
salt      718944  718936  9 16:44 ?        00:00:00  |   \_ /usr/bin/python3 /usr/bin/salt-master ReqServer MWorker-1
salt      718945  718936  9 16:44 ?        00:00:00  |   \_ /usr/bin/python3 /usr/bin/salt-master ReqServer MWorker-2
salt      718946  718936  9 16:44 ?        00:00:00  |   \_ /usr/bin/python3 /usr/bin/salt-master ReqServer MWorker-3
salt      718947  718936  9 16:44 ?        00:00:00  |   \_ /usr/bin/python3 /usr/bin/salt-master ReqServer MWorker-4
salt      718943  718709  0 16:44 ?        00:00:00  \_ /usr/bin/python3 /usr/bin/salt-master FileServerUpdate
```

**Comment by thedude42** [comment]
So just an update on the status of my testing...

I temporarily abandoned my bare metal test because for whatever reason I couldn't get the saltmaster to function correctly with my minions. I could execute `salt-call` from minions just fine, but any use of `salt '<tagrget>' ...` from the salt-master I was testing resulted in the following:

```
'str' object has no attribute 'pop'
```

I ensured the minions I was testing with were at the same version as the master (3005.1) but that didn't make a difference.

As an aside, this is the reason why I favor using docker over directly installing the salt packages, as this host had an absolute bare minimum of python packages installed and yet even with the new "Onedir" packaging for saltstack, something was amiss. Therefore I abandoned testing on bare metal for now and switched to using the hub.docker.com container tagged `salt:3005.1`, just updating the `FROM` clause in the Dockerfile listed above.

FWIW once I did have gitfs working on bare metal with the Onedir install the `FileServerUpdate` never died, but I didn't have it running long enough for a real test (because I wanted to ensure everything in the salt-master was actually working for the test to be as close to the actual issue being reported). Once I had `setproctitle` installed I did notice that with my master config, salt-master no longer launches the `MultiprocessLoggingQueue` which gives me some hope as that process seems closely related to (or minimally associated with) this issue.

**Comment by thedude42** [comment]
Quick update: so far this problem does not appear for me in 3005.1 docker. In 3004.2 the `FileServerUpdate` process almost certainly would have died by now. I'll keep an eye on things and update this issue if I see anything new, but it is looking like the issue was resolved in 3005.1.

**Comment by thedude42** [comment]
Another week, everything is running reliably. I'm pretty confident we can say the issue I am reporting is fixed in 3005.1 :)

**Comment by rosscdh** [comment]
Running 3005.1 gitfs alpine still broken im afraid
https://github.com/saltstack/salt/issues/62637#issuecomment-1452903614
