### ISSUE TITLE
[BUG] After upgrade to 3005.3, failure to fetch latest pillar data after being updated in git pillar repo branch

### ISSUE THREAD

**Issue by Ikramromdhani** [saltstack/salt#65467]
### Description of Issue
A minion/master is unable to get the new pillar data from an alternative branch in git after it was updated on remote git pillar repository. This was working with 3005.1, but broke after upgrade to 3005.3. It also seem to be the case for those using 3006.3. Please refer to community discussion: https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1697576330136199

### Setup
Amazon Linux 2 salt master, configured with git repository for states and pillar data.

- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] on-prem machine
- [x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

### Steps to Reproduce Issue
Master config
```
ext_pillar:
- git:
  - __env__ ssh://git@xxxxxxxxxxxxxxxxx/repo.git:
    - root: pillar
git_pillar_pubkey: xxxxxxxxxxxxxxxx
git_pillar_privkey: xxxxxxxxxxxxxxxxxxx
git_pillar_update_interval: 60
pillar_merge_lists: True
```
Push an update to an existant pillar called test in repo.git on branch testpillar. On a minion, run salt-call pillar.get test pillarenv=testpillar

**Expected behavior**  

The new value of pillar test should be visible in the output of the salt call on the minion.

**Actual behavior**

The minion get the old data of pillar test. Please note that when executing the same comand after deleting `/var/cache/salt/master/git_pillar`, the minion get the correct value
### Versions Report

```
Salt Version:
          Salt: 3005.3

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: 1.5.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.10.1
        Python: 3.9.18 (main, Sep 18 2023, 18:18:39)
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: amzn 2
        locale: utf-8
       machine: x86_64
       release: 4.14.318-241.531.amzn2.x86_64
        system: Linux
       version: Amazon Linux 2
```

**Comment by OrangeDog** [comment]
3005.2 changed how git pillars were cached to fix a security issue. Having to clear the cache after upgrading is probably expected.

**Comment by HL-SaltBae** [comment]
> Having to clear the cache after upgrading is probably expected.

This does NOT only affect the pillar cache across upgrades.

With a running 3006.3 master, the master will NOT refresh a git_pillar branch after the first time that branch is fetched.

Steps to test:
1. Have git_pillar configured with `__env__` like in the bug report
2. Create a new branch in the git_pillar repo
3. Have any minion pull the pillar data using `pillar.items pillarenv=<branchname>`
4. Notice that the data aligns with what's in the branch
5. Commit a new change to the branch in the git_pillar repo
6. Do any or all of the following:
      * Wait for the master `loop_interval` to expire and observe that the master log file indicates that the git_pillar remote is up-to-date
      * run `sudo salt-run git_pillar.update` on the master and observe that the return for the pit_pillar repo in question is "None"
      * restart the master
      * run `saltutil.refresh_pillar` on the minion in question
7. Repeat pulling pillar data with any minion using `pillar.items pillarenv=<branchname>`
8. Notice that the minion does NOT receive new pillar data from the new commit on the branch, and instead returns the same pillar data that was on the branch when the master first fetched the branch
9. Repeat 5,6,7 as many times as you want
10. Ultimately stop the master process, `rm -f /var/cache/salt/master/git_pillar`, restart the master process
11. Go to step 3 and repeat forever

**Comment by Ikramromdhani** [comment]
Are there any chances we may get a fix for this soon? It affects both 3006 and 3005 and it was introduced after the CVE patches so it makes sense to have it fixed within both versions

**Comment by HL-SaltBae** [comment]
@cmcmarrow do you have any insight into this? I think this regression happened as a result of your CVE patch https://github.com/saltstack/salt/commit/6120bcac2ee79b6e8b104612941432841eb0c8c3

**Comment by ITJamie** [comment]
Theres been no github activity on @cmcmarrow 's account since sept. Safe to say hes no longer involved on the project ☹️

**Comment by Ikramromdhani** [comment]
I would like to add another detail: We tried to use the new released version 3005.5 which contain additional CVE patches, and we noticed that the pillar refresh issue is partially fixed and happens only on branches containing `/` for example: `feature/test/pillar`  .  I hope this helps fixing the issue

**Comment by HL-SaltBae** [comment]
I had wondered if `/` in the branch name might be a factor, but someone on the Slack said they tested that and it happened with or without the `/`. Good news if true!

**Comment by dmurphy18** [comment]
@Ikramromdhani Can you upgrade to latest Salt 3006 and retry, Salt 3005 has passed it's bug fix (last August 2023) and it about to run out of CVE support on the Feb 25th 2024, 24 days from now.

At this stage nothing will be getting done to Salt 3005 given that it is dead in 24 days, hardly time to debug/test/fix/release cycle, esp. since would have to build classic packages and there is a couple of days in just getting that done.

**Comment by donkopotamus** [comment]
We are also observing this error after recently upgrading from `salt-3004` to `salt-3006.4`:
* We have not moved to `salt-3006.6` due to #65691 
* However diffing `salt/utils/gitfs.py` gives no reason to believe the bug is now absent in `3006.6`.

We have observed that when we use `__env__` to effectively map `pillarenv` to a branch name that:
* if we create a new branch `feature/testing` that is not already in the cache, this will be pulled correctly; and
* if we then add a new commit on it, or amend `HEAD`, that the changes **will not** be pulled; 

However, if we create a new branch named `testing` then it will be pulled, and subsequent changes to it will be pulled.  That is, it seems that only **branches with a `/` in them do not update**.  Unfortunately we use branch names like `release/*` or `feature/*`, like many people do so its a severe issue for us at the moment!

(This evidence conflicts with https://github.com/saltstack/salt/issues/65467#issuecomment-1921904438, although the commenter had not actually confirmed it themselves)

**Note:** 
- We are using `GitPython` rather than `pygit2`
- We do **not** see this issue with `gitfs` ... changes to our state files are pulled ... it is only `git_pillar`

**Comment by Ikramromdhani** [comment]
@donkopotamus , that is what I was about to confirm. Tested today with 3006.6 using pygit2 and still have issues pulling changes for pillars when relying on pillarenv branch having `/`. 
@dmurphy18 any clues if this is candidate to be fixed within 3006.7 or 3007?

**Comment by dmurphy18** [comment]
@Ikramromdhani Won't make it for Salt 3006.7, that is close to release, waiting on clean tests in the pipeline.  Possibly for 3007, but on my backlog, dealing with https://github.com/saltstack/salt/issues/65816, which may be related, writing tests for that fix now.
So it is on the block but limited hands since the buyout.  Get to it when I can.

**Comment by max-arnold** [comment]
Not sure if it helps, but it looks like the CVE fix in 3005.2 and then https://github.com/saltstack/salt/pull/65017 in 3005.3 that mitigated a negative effect of that fix, probably contributed to this issue

**Comment by dmurphy18** [comment]
Yup, the set of changes that Chad did and had to be adjusted, applied to both the gitfs changes he did along the pillarenv and cache changes, etc.  That is why I expect some linkage to the gitfs changes.

**Comment by Ikramromdhani** [comment]
Just a heads up that we tested 3006.7 and the problem is still there I hope we can have a permanent fix on 3007 version. This problem is holding us for performing salt upgrades.

**Comment by Ikramromdhani** [comment]
@dmurphy18 since the issue fix did not make it to 3007. Just would like to ask if there are specific version to target? Thank you

**Comment by Ikramromdhani** [comment]
Do we have a timeline on when we are getting this fix released? We were trying to upgrade since last year and this is the only issue holding us back. Checked the release notes for 3006.9 and did not see it included there so was wondering if this is going to be included in 3006.10 and if yes, do we know when is it going to be released? This way we can plan our upgrade accordingly.
Thank you!

**Comment by dmurphy18** [comment]
@Ikramromdhani Actually working this at the moment, would help to just check still occurs on 3006.9, attempting to setup similar environment.

**Comment by mdschmitt** [comment]
I'm seeing it in 3006.9, yes.

**Comment by dmurphy18** [comment]
@Ikramromdhani Sorry but this is on the back-burner and I have to get back to it, given the reduced size of the team, some fireballs got thrown which had to be handled. Be assured it is on the list, and the fix is half done, but tests to be written if memory recall is correct. Apologies but only so much time in the day, with a smaller team.

**Comment by dmurphy18** [comment]
Interestly running steps 1-6 above gave the following which could explain why removing ```/var/cache/salt/master/git_pillar``` clears the problem, and the problem is not related to parsing but something else:
```
[root@ip-10-2-15-188 ~]# salt-run git_pillar.update
[WARNING ] git_pillar_global_lock is enabled and update lockfile /var/cache/salt/master/git_pillar/work/ytJQkKKFhtVSWNNtBJtuZsiCG5luCEeu2TYadrIBNq0=/master/update.lk is present for git_pillar remote '__env__ https://github.com/dmurphy18/test_repo.git' on machine_id ec213523339d64177a5b48e038e84fbb with pid '116273'. Process 116273 obtained the lock for machine_id ec213523339d64177a5b48e038e84fbb, current machine_id ec213523339d64177a5b48e038e84fbb
[WARNING ] Update lock file is present for git_pillar remote '__env__ https://github.com/dmurphy18/test_repo.git', skipping. If this warning persists, it is possible that the update process was interrupted, but the lock could also have been manually set. Removing /var/cache/salt/master/git_pillar/work/ytJQkKKFhtVSWNNtBJtuZsiCG5luCEeu2TYadrIBNq0=/master/update.lk or running 'salt-run cache.clear_git_lock git_pillar type=update' will allow updates to continue for this remote.
__env__ https://github.com/dmurphy18/test_repo.git:
    False
[root@ip-10-2-15-188 ~]#
```

using simplified ```/etc/salt/master``` since doing ssh only complicates access
```
ext_pillar:
  - git:
    - __env__ https://github.com/dmurphy18/test_repo.git:
      - root: pillar

pillar_merge_lists: True
git_pillar_provider: gitpython
```
test_repo.igt has ```main``` and ```test_pillar`` branches

**Comment by dmurphy18** [comment]
Given this appears to be an issue with '/' in the name of the field, I think changes from PR 65017 to salt/utils/gitfs.py, could be the culprit, the added
```
        if hasattr(self, "name"):
            self._cache_basehash = self.name
        else:
            hash_type = getattr(hashlib, self.opts.get("hash_type", "md5"))
            # We loaded this data from yaml configuration files, so, its safe
            # to use UTF-8
            self._cache_basehash = str(
                base64.b64encode(hash_type(self.id.encode("utf-8")).digest()),
                encoding="ascii",  # base64 only outputs ascii
            ).replace(
                "/", "_"
            )  # replace "/" with "_" to not cause trouble with file system
```
whereas previously just did the decode and replace of '/' with '_'. Here the now presented name is not getting sanitized, and functions such as os.listdir will interpret the '/' as a path separator.

This is just a thought that I wanted to record and not forget, not saying its the problem, just a probable cause

**Comment by dmurphy18** [comment]
@Ikramromdhani Working away on this but wanting to make sure I am addressing everything.
```
Please refer to community discussion: https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1697576330136199
```
Unfortunately the contents of that Slack discussion are no more, and I was wondering if you have them saved off anywhere that could be shared with me.  Writing tests and want to make sure I have all the bases covered.

**Comment by dmurphy18** [comment]
@Ikramromdhani Wondering about this, since in my testing I was only able to reproduce the issue  where git pillar was not updated , if I failed to commit my changes and just pushed to the branch without doing a commit.

In GitPython fetchinfo I was getting 4, HEAD_UPTODATE, until I did a commit and then pushed that up and got commits to compare, old vs new, and picked up the changes accordingly.

**Comment by donkopotamus** [comment]
@dmurphy18 The issue, as we have experienced it (and continue to experience) is when we have a `pillarenv` that points to a branch with a `/` in it.  Then we observe the following:

- suppose we stop the `salt-master` and destroy the cache; then start the `salt-master` (*); then
- the first request for pillar data for will cause the branch to be cached and served correctly; and
- then all updates on that branch will never be sync'ed ... ie we push changes to the branch and we do not see corresponding changes to pillar data unless we do (*) again

**Comment by Ikramromdhani** [comment]
thank you @donkopotamus that is what we are experiencing as well. The problem is happening only with `pillarenv` that have a value containing `/` example `feature/something/FOO`. The changes within states for `saltenv` having the same value are being updated but for `pillarenv` they are being cached and never updated even if there is a push. The git_pillar clear cache does not help either. We tried adding a cron job to work around that but did not help

**Comment by dmurphy18** [comment]
@lkoenigsberger @donkopotamus Just want to make sure that the branches with the ```/``` do have new commits on them, and not just changes with a push.
Trying it now with a branch with ```/``` in it, but want to make sure of bug duplication environment.

**Comment by dmurphy18** [comment]
So added my local git pillar branch, a modification of the testing git pillar repo, see https://github.com/dmurphy18/salt-test-pillar-gitfs.git, with a branch ```doggy/moggy``` and changes are detected after running ```salt-run git_pillar.update 2>&1 | tee ./mymaster_14.log```, similar to ```salt '*' saltutil.refresh_pillar```.

The ```/etc/salt/master``` portion
```
ext_pillar:
  - git:
    - __env__ https://github.com/dmurphy18/salt-test-pillar-gitfs.git
    - branch https://github.com/dmurphy18/salt-test-pillar-gitfs.git
    - testmount https://github.com/dmurphy18/salt-test-pillar-gitfs.git
    - doggy/moggy https://github.com/dmurphy18/salt-test-pillar-gitfs.git

git_pillar_provider: gitpython
```
As part of the CVE fixes, it was found that cache updates where being made when they should not have been (bad code) and that was removed, hence wondering if the problem is that you are expecting cache updates to be made implicitly, when they should always have been explicit.

Otherwise, am I testing this incorrectly, but the change of ```breed: weim``` to ```breed: dashund```, committed and pushed up to the git repo was detected once ```salt-run git_pillar.update``` was executed.

**Comment by donkopotamus** [comment]
> Just want to make sure that the branches with the / do have new commits on them, and not just changes with a push

Yes, the problem has been that when we push changes on a branch (that would affect the `pillar`) we have not seen those appear on the `salt-master` whenever the branch has `/` in the name.  Branches without a slash **would** propagate changes.

> wondering if the problem is that you are expecting cache updates to be made implicitly, when they should always have been explicit

Yes, I have been expecting cache updates to happen implicitly ... because prior to this issue appearing they always have been implicit, driven by `loop_interval` (prior to `salt-2018`) and now driven by `gitfs_update_interval` or `git_pillar_update_interval ` perhaps.  Every 60 seconds stale branches would be re-fetched (and I believe that branches without a `/` are still currently refreshed every 60 seconds).

Having to manually refresh the `git_pillar` would seem to defeat the convenience of it

**Comment by dmurphy18** [comment]
@donkopotamus Will take a look at ```git_pillar_update_interval``` to see what is happening there, but the implicit cache update per salt 2018, not coming back, it was coding error that had the cache getting updated when it should not have been.

**Comment by OrangeDog** [comment]
It would probably be helpful to clarify which of the three (or more?) pillar caches you are talking about.

`/var/cache/salt/master/git_pillar` is indeed supposed to automatically update every `git_pillar_update_interval` (or every `loop_interval` in old versions). That's what this bug is about - it not doing so when there's a `/` in the branch name, which presumably gets encoded incorrectly when constructing a path.

**Comment by dmurphy18** [comment]
Well made the changes in the branch, committed and pushed, and admittedly didn't wait the 60 seconds that ```git_pillar_update_interval``` is set to, since many distractions (people asking questions), so time interval exceeded.

```
root@ip-10-2-3-186:/home/admin/dev# date
Wed Oct 30 03:20:06 PM UTC 2024
root@ip-10-2-3-186:/home/admin/dev# date
Wed Oct 30 03:31:00 PM UTC 2024
```
And the pillar information was updated with the change.

**Comment by dmurphy18** [comment]
Did it again and waited two minutes (sampling theory for a one minute update), and the change in the git pillar branch was received and updated.

Unless exact steps to reproduce this issue, then will mark as 'cannot reproduce', btw: here are my versions reports
```
root@ip-10-2-3-186:/home/admin/dev# salt-run --versions
Salt Version:
          Salt: 3006.9
 
Python Version:
        Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.11
     gitpython: 3.1.43
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.17.0
         smmap: 5.0.1
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-25-cloud-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
 
root@ip-10-2-3-186:/home/admin/dev# salt-call --local test.versions
local:
    Salt Version:
              Salt: 3006.9
     
    Python Version:
            Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]
     
    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
      cryptography: 42.0.5
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.11
         gitpython: 3.1.43
            Jinja2: 3.1.4
           libgit2: Not Installed
      looseversion: 1.0.2
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 22.0
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.19.1
            pygit2: Not Installed
      python-gnupg: 0.4.8
            PyYAML: 6.0.1
             PyZMQ: 23.2.0
            relenv: 0.17.0
             smmap: 5.0.1
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4
     
    System Versions:
              dist: debian 12 bookworm
            locale: utf-8
           machine: x86_64
           release: 6.1.0-25-cloud-amd64
            system: Linux
           version: Debian GNU/Linux 12 bookworm
```

**Comment by OrangeDog** [comment]
The obvious difference is that @dmurphy18 is using gitpython, while @Ikramromdhani is using pygit2.

**Comment by dmurphy18** [comment]
@OrangeDog IF you review the issue, it was originally about GitPython, not pygit2.  If users are having issues with pygit2 then please open a different issue with the details. One bug - one issue.

**Comment by dmurphy18** [comment]
@OrangeDog Others had mentioned use of gitpython, will redo testing with pygit2 as per original poster

**Comment by dmurphy18** [comment]
Tried it with pygit2 v1.13.1 (current version used in CI/CD) and no problem, got the update on the branch after waiting 2 minutes. Will try with latest pygit2 v1.16.0 release on Oct 11th 2024.

**Comment by dmurphy18** [comment]
@Ikramromdhani Can you retry your issue with 3006.9 and pygit2 v1.13.1 to see if you encounter the issue.
Appears to be issue with the latest pygit2 v1.16.0, and not just related to having a ```/``` in the branch name, encountering issues with branches without a ```/``` in their name.

**Comment by donkopotamus** [comment]
@dmurphy18 Is the suggestion that this should be currently working on stock `3006.9` + `gitpython`?  (I will double check our situation but I believe we still observe this on our production systems running `3006.9`)

**Comment by dmurphy18** [comment]
@donkopotamus I cannot reproduce the issue using GitPython, running into issues with pygit2 above 1.13.1 version that is used for testing in our CI/CD pipelines.

**Comment by donkopotamus** [comment]
@dmurphy18 I have confirmed we are still experiencing this issue on `3006.9` (with `gitpython`) ... here I make a branch `some-branch` and define `some-var: 100` in the pillar.

### Example ###
```
$ sudo salt-call config.get saltenv
some-branch

$ sudo salt-call config.get pillarenv
some-branch

# using `pillar.items` simply as it automatically causes the pillar to be refreshed
$ sudo salt-call pillar.items | grep -B 1 some-var
    some-var:
        100

# now push a change on the branch to change `some-var: 200`
$ sleep 120
$ sudo salt-call pillar.items | grep -B 1 some-var
    some-var:
        200        <== Its changed
```
The above is as expected.  Now I do the **exact same thing** on a branch called `some/branch`
```
$ sudo salt-call config.get saltenv
some/branch

$ sudo salt-call config.get pillarenv
some/branch

# using `pillar.items` simply as it automatically causes the pillar to be refreshed
$ sudo salt-call pillar.items | grep -B 1 some-var
    some-var:
        100

# now push a change on the branch to change `some-var: 200`
$ sleep 120
$ sudo salt-call pillar.items | grep -B 1 some-var
    some-var:
        100        <== it has NOT changed
```
Note that while the pillar didn't change, any changes I make to salt **states** on that branch **do** change.

### Relevant Config (Maybe) ###
```
git_pillar_provider: GitPython
git_pillar_includes: false
ext_pillar:
  - git:
    # the `base` environment is provided by the `main` branch
    - main git@.../some-repo.git
      - root: salt/pillar
      - env: base

    # map other environments to the corresponding branch
    - __env__  git@.../some-repo.git
      - root: salt/pillar
```

**Comment by Ikramromdhani** [comment]
We will try to test the `3006.9` with pygit2 `v1.13.1` but just to be clear the latest pygit2 version works ok with 3005 salt prior to CVE patches.

**Comment by dmurphy18** [comment]
@Ikramromdhani latest pygit2 1.16.0 has deprecated and removed functionality( due to 1.15.0), hence wonder how 3005 could possibly work, e.g. use of ```oid``` which is gone since 1.15.0 pygit2  Parts of this code has not changed in 9 years, so I would check again.

**Comment by Ikramromdhani** [comment]
I apologize, I have just rechecked and we are using `1.14.0`

**Comment by dmurphy18** [comment]
@donkopotamus Just making sure, all of your changes on branch are committed and pushed ?, since I am doing the same and seeing the changes, regardless of pillarenv

**Comment by donkopotamus** [comment]
@dmurphy18 I understand why such questions need to be asked but yes, changes are definitely committed and pushed!  (I've also repeated it this morning)
 
This isn't an isolated test really ... I've tested each minor `3006.x` release as we've rolled it out on our systems (after we first observed when bumping from `3004 -> 3006.4`.  We also regularly observe it as a "gotcha" where a developer will push changes on a `feature/...` branch (or merge changes in a `release/...` branch) and then become confused about why their pillar changes are not coming into effect!  When observed we stop the master, destroy `/var/cache/salt/master/git_pillar` and start the master, after which changes then come into effect.
 
What else can we provide that might help us close the gap between your test, and our production systems?  The config snippets I posted above are our only pillar related config changes on the master, with all other pillar related setting being the default.
 
Here is our `salt-run --versions`
```
┌╴XXX@XXX - fish - subnet: XXX
└╴/e/s/master.d> sudo salt-run --versions
Salt Version:
          Salt: 3006.9
 
Python Version:
        Python: 3.11.7 (main, Aug 23 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)]
 
Dependency Versions:
          cffi: 1.17.1
      cherrypy: Not Installed
  cryptography: 43.0.1
      dateutil: 2.9.0.post0
     docker-py: Not Installed
         gitdb: 4.0.11
     gitpython: 3.1.43
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.1.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.1
     pycparser: 2.22
      pycrypto: Not Installed
  pycryptodome: 3.21.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0.2
         PyZMQ: 26.2.0
        relenv: Not Installed
         smmap: 5.0.1
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.5
 
System Versions:
          dist: rhel 9.4 Plow
        locale: utf-8
       machine: x86_64
       release: 5.14.0-427.37.1.el9_4.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 9.4 Plow
```

**Comment by donkopotamus** [comment]
@dmurphy18 I believe I have located a symptom of the problem that might help.  Its all about the location of the marker file `fetch_request` in the `work` directory.

Take my test case above where I created both a branch `some-branch` and `some/branch`.  Then we check the state of the cache on the master
```
# change into the relevant **work** directory on the master
master$ cd /var/cache/salt/master/git_pillar/work/<opaque-hash>

master$ ls
some/    some-branch/

# look at the contents of those ... `some-branch` has a `fetch_request` marker file in it
master$ ls some-branch/
fetch_request

# but the directory corresponding to `some/branch` does **not**
master$ ls some/branch
<empty>

# instead the marker is in the parent `some/` (which is not a valid branch in and of itself)
master$ ls some/
branch/    fetch_request
```

Now ... suppose I push a change that affects the pillar, as in my previous example

```
# the `git_pillar_refresh_interval` is 60 so this is very conservative
minion$ sleep 120

# check the value of `some-var` ... its still `100`, should be `200`
minion$ sudo salt-call pillar.items | grep -A 1 some-var
    some-var:
        100

# now ... put a `fetch_request` into `some/branch` **on the `master`**
master$ sudo touch /var/cache/salt/master/git_pillar/work/<opaque-hash>/some/branch/feature_request

# back to the minion ... sleep again
minion$ sleep 120

# check the value of `some-var` ... its still `100`, should be `200`
minion$ sudo salt-call pillar.items | grep -A 1 some-var
    some-var:
        200   <== MAGIC!
```

**Comment by donkopotamus** [comment]
A further refinement of the above:
```
# we push a change, altering `some-var: 200 -> 300` 
minion$ sudo salt-call pillar.items | grep -A 1 some-var
    some-var:
        200  <== change not propagated

# took a break for an hour, confirmed its still not propagated
minion$ sudo salt-call pillar.items | grep -A 1 some-var
    some-var:
        200  <== change not propagated

# on the master, we **move** the `fetch_request` out of `some/` and into `some/branch`
master$ cd /var/cache/salt/master/git_pillar/work/<opaque-hash>/some
master$ sudo mv fetch_request branch/

# some time later, maybe 30 seconds or so, its reappeared in `some/` and still exists in `some/branch`
master$ ls . branch/
.:
branch/    fetch_request

branch/:
fetch_request
```
Meanwhile, on the minion we sleep for five minutes ...
```
# five minutes later, the state of the `work` cache on the master still looks the same
master$ ls . branch/
.:
branch/    fetch_request

branch/:
fetch_request

# on the minion, we now ask for the pillar, having ensured that `some/branch/fetch_request` exists
minion$ sudo salt-call pillar.items | grep -A 1 some-var
    some-var:
        300   <== Hooray!

# on the master, the `fetch_request` has been removed from `some/branch` as a result of our pillar query
master$ ls . branch/
.:
branch/    fetch_request

branch/:
```
As `fetch_request` has been removed from `some/branch` we're back to the situation that we won't see updates on the branch until we create such a file there

**Comment by donkopotamus** [comment]
####  Summary ####

* Something decides where to put `fetch_request` marker files in the `work` directory;
* It is only putting them in the **top** most directories, not the final directories corresponding to the actual branch;
    * Thus branches that have no `/` do have a `fetch_request` while branches that do, do not have such a file;
* Directories that do not have a `fetch_request` are not re-fetched when we ask for their pillar;
* If we manually create such a file via eg `touch` ... then they **will** be fetched, and the marker file removed

**Comment by donkopotamus** [comment]
> I currently have no idea if they affect a cache for specific named branches

It does not ... if we replace the `ext_pillar` definition with one that does **not** use `__env__` eg:
ext_pillar:
```
  - git:
    ...

    # 
    - another/branch  git@.../some-repo.git
      - root: salt/pillar
```
then the cache directory looks slightly different, and does not use the branch name at all.  (This **may explain why you cannot reproduce it** ... are you using `__env__` or a specific named branch?).  Instead we get a different file layout:
```
# change into the relevant **work** directory on the master
master$ cd /var/cache/salt/master/git_pillar/work/<opaque-hash>

master$ ls
_/
```

### The Problem? ###

So, looking at `salt/utils/gitfs.py`:
* If we use `__env__` then we will end up with `gitfs` having `repo.get_salt_working_dir()` being eg `<cache-dir>/work/<opaque-hash>/some/branch`
* If we do not, then we will have `gitfs` having `repo.get_salt_working_dir()` being eg `<cache-dir>/work/<opaque-hash>/_`
* This is due to this snippet in `GitProvider.__init__`
  ```
        self._cache_basename = "_"
        if self.id.startswith("__env__"):
            try:
                self._cache_basename = self.get_checkout_target()
  ```
Now ... look at what's dropping these `fetch_request` files (`GitBase.fetch_remotes`)
```
        for repo in self.remotes:
            name = getattr(repo, "name", None)
            if not remotes or (repo.id, name) in remotes or name in remotes:
                try:
                    # Find and place fetch_request file for all the other branches for this repo
                    repo_work_hash = os.path.split(repo.get_salt_working_dir())[0] <= THIS IS HASH DIR
                    for branch in os.listdir(repo_work_hash):  <== PROBLEM HERE!!
                        # Don't place fetch request in current branch being updated
                        if branch == repo.get_cache_basename():  <== PROBABLY TRUE WHEN NOT __env__
                            continue
                        branch_salt_dir = salt.utils.path.join(repo_work_hash, branch)
                        fetch_path = salt.utils.path.join(
                            branch_salt_dir, "fetch_request"
                        )
                        if os.path.isdir(branch_salt_dir):
                            try:
                                with salt.utils.files.fopen(fetch_path, "w"):    <== CREATED `work/<opaque-id>/some/fetch_request`
                                    pass
```
Assuming that `repo_work_hash` is the eg `<cache-dir>/work/<opaque-hash>` then this only iterates over the **topmost** directories in the working directory, meaning we will visit `some/` but **not** visit `some/branch`.  (I've now injected logging there and confirmed that).

Next looking at `fetch_request_check`
```
    def fetch_request_check(self):
        fetch_request = salt.utils.path.join(self._salt_working_dir, "fetch_request")  <=== LOOKING FOR `work/<opaque-id>/some/branch/fetch_request`
        if os.path.isfile(fetch_request):  <== THIS TEST FAILS SO WE DO NOT FETCH
            log.debug("Fetch request: %s", self._salt_working_dir)
            try:
                os.remove(fetch_request)
            except OSError as exc:
                log.error(
                    "Failed to remove Fetch request: %s %s",
                    self._salt_working_dir,
                    exc,
                    exc_info=True,
                )
            self.fetch() <== WE DON"T DO THIS
            return True
        return False
```

**Comment by OrangeDog** [comment]
Related, but I wonder what happens if you name a branch `../../../../../../../etc`? New CVE perhaps?

**Comment by dmurphy18** [comment]
@OrangeDog I take you out behind the bike shed :rofl: , joking.

Some interesting takes on that parameter input, beginning to think might need some sanity checking on valid input etc. , brings horrors of **Perl** (Halloween/Day of the Dead/All Saints Day after all) and sanity checking from a couple decades ago to mind.
Will have to consider it, and bring that up in standup.

Good Point.

**Comment by OrangeDog** [comment]
I'm pretty sure it would only be an issue if you never ran a minion on the master, as if you can control the repo you can already add states to do whatever you want.

**Comment by donkopotamus** [comment]
> Related, but I wonder what happens if you name a branch `../../../../../../../etc`

@OrangeDog Thankfully a git ref [cannot contain `..`](https://git-scm.com/docs/git-check-ref-format):

> Git imposes the following rules on how references are named:
> ...
> 3. They cannot have two consecutive dots `..` anywhere.

**Comment by Ikramromdhani** [comment]
@dmurphy18 any updates on this issue? we would like to move to using 3006 and we were wonder if a fix could be included in 3006.10

**Comment by aPollO2k** [comment]
I'm affected by this issue. The only workaround I found is to run on salt master:

`rm -rf /var/cache/salt/master/git_pillar/`

I would be happy to assist with testing or providing feedback if needed. However, I am not a developer, so I won't be able to contribute directly to fixing the code.

Let me know if there's anything I can do to help further.

**Comment by dmurphy18** [comment]
@Ikramromdhani I have been unable to reproduce this with GitPython and pygit2 < 1.15.0 (1.15.0 and above has its own problems, see https://github.com/saltstack/salt/issues/67017).

I am going to be gone on Christmas Break and then PTO, so won't be working on this till new year 2025.
Note been unable to work on it due to CI/CD changes with loss of AWS (Broadcom infrastrucutre changes) so been busy on bootstrap.

So apart from the later versions of pygit2, there has to be something else in your environment which is affecting functionality, since I am unable to reproduce the issue.  Is there any other detail that could be added ?, will be rereading this so see if there is something I missed too.

**Comment by donkopotamus** [comment]
@dmurphy18 @Ikramromdhani Can you review again this sequence of comments on this issue, which I believe identifies the **exact cause of the issue**:
- https://github.com/saltstack/salt/issues/65467#issuecomment-2450990570
- https://github.com/saltstack/salt/issues/65467#issuecomment-2451056354
- https://github.com/saltstack/salt/issues/65467#issuecomment-2451060181
- https://github.com/saltstack/salt/issues/65467#issuecomment-2451138801

The latter in particular **identifies the problem** as the piece of code that is responsible for dropping `fetch_request` marker sentinels on the filesystem (see my comments embedded in it such as `<== PROBLEM HERE!!`).

> I have been unable to reproduce this with GitPython

@dmurphy18 Also relevant in there is the following:
- this problem **only** occurs if you are using an `__env__` definition for `git_pillar`. i.e. this breaks:

  ```
  ext_pillar:
    - git:
      ...

      # map other environments to the corresponding branch
      - __env__  git@.../some-repo.git
        - root: salt/pillar
  ```
  but this does not
  ```
  - git:
   ...

   # 
   - another/branch  git@.../some-repo.git
     - root: salt/pillar
```
Can you confirm that you are using an `__env__` definition when attempting to reproduce it?

### A WORKING FIX ###

If I alter the mentioned code to instead **walk** the tree at `repo_work_hash`, rather than simply using `listdir` to drop sentinels at the top level, then a `fetch_request` is placed at all directory nodes and then those branches such as `some/branch` **are definitely** updated.

@Ikramromdhani I, for example, no longer blow away the entire `cache` directory ... instead I simply

    sudo touch /var/cache/salt/master/git_pillar/work/<opaque-hash>/some/branch/fetch_request

on the branch I need fixed and 60 seconds later that branch will have been updated.  (Clearly I don't like having to do this manually all the time though!)

**Comment by Ikramromdhani** [comment]
@dmurphy18 can you confirm you still cannot reproduce when using a configuration as below:
```
ext_pillar:
- git:
  - __env__ <pillar_repository>:
    - root: pillar
git_pillar_pubkey: <key_pub>
git_pillar_privkey: <key_priv>
git_pillar_update_interval: 60
pillar_merge_lists: True
```

**Comment by dmurphy18** [comment]
@Ikramromdhani Wondering if you had a chance to test with the external pillar in my last post yet ?
Been gone since before Christmas on vacation and only returned to work and would like to finish this issue

**Comment by dmurphy18** [comment]
@Ikramromdhani Back and looking at this again, it was a long PTO.
@donkopotamus Thanks for that info, examining it now

**Comment by dmurphy18** [comment]
@Ikramromdhani Did do the __env__ with GitPython, will try with pygit2, see
```
david@david-XPS-15-9570:~/dev/fix_65467/notes$ cat master_conf.txt 

ext_pillar:
  - git:
    - __env__ https://github.com/dmurphy18/salt-test-pillar-gitfs.git
    - branch https://github.com/dmurphy18/salt-test-pillar-gitfs.git


git_pillar_provider: gitpython
```
Once I get my test environment set back up.

**Comment by dmurphy18** [comment]
@donkopotamus Thanks for those comments, ```__env__``` and ```<cache-dir>/work/<opaque-hash>/some/branch``` with os.listdir, and how to tell a real directory structure and a name with a directory separator in it, need to go away and figure a way to do that.

Getting a test environment to check that and back up to speed after a long vacation.

**Comment by Ikramromdhani** [comment]
@dmurphy18 , we are still witnessing the issue with pygit2: 1.14.0 and 3006.9

**Comment by OrangeDog** [comment]
That doesn't sound like a great solution, as branch names can also contain `-`.
Is there something wrong with @donkopotamus 's fix?

**Comment by donkopotamus** [comment]
@dmurphy18 As @OrangeDog notes, substituting `'/' -> '_'` precludes the possibility of having branches named both `a/b` and `a-b`.

Git [ref names](https://git-scm.com/docs/git-check-ref-format) are specifically **designed** to generally map well, and be safe, on filesystems.  The current method of mapping them onto a directory structure does not seem wrong in any sense ... its simpy the traversing of that structure that is wrong.

i.e I think:
- the branch name `a/b/c` should continue to be mapped to the directory `a/b/c`  (thats exactly how `git` itself would represent the branch in a checked out repository, by using `.git/refs/heads/a/b/c`
- instead of using `os.listdir` to traverse that structure, it should simply be walked with `os.walk`

**Comment by dmurphy18** [comment]
@donkopotamus @OrangeDog Did I mention I hate gitfs 🤣 , I was duplicating this https://github.com/saltstack/salt/blob/2b44a6ce9a9c387b08ff3abb2bb025c5acece112/salt/utils/gitfs.py#L3387
and yeah, I refactored that line, but the replace '/' with '-' was originally there for 5 years previously.

I am wondering why ```os.walk``` would be any better given 
```
os.walk(top, topdown=True, onerror=None, followlinks=False)[¶](https://docs.python.org/3.10/library/os.html?highlight=os%20listdir#os.walk)
Generate the file names in a directory tree by walking the tree either top-down or bottom-up. For each
```
So would it not also treat the '/' in a git branch name as an ```os.sep``` too, similar to ```os.listdir```

Understanding the replacement of '/' with dash '-' does preclude ```a/b``` with ```a-b```, but that would also be the same with use of underscore, as used in the cache base hash , see https://github.com/saltstack/salt/blob/2b44a6ce9a9c387b08ff3abb2bb025c5acece112/salt/utils/gitfs.py#L483-L488

Noting the ```a/b``` and ```a-b``` clash would be for use with ```__env__``` or pillarenv, but the outcome would be an extra cache refresh, which should not be too bad a side effect.

Still to put the changes out for team review, so I am sure they will have some comments too.

Please let me know If I am wrong in my logic about a minor side effect.

**Comment by idenkov-tc** [comment]
We are trying to upgrade from 3002.2 to something newer(onedir) and stumbled upon this issue. Using __env__/gitfs

However we do not have `/` in our branch name, but we do have `-` and `_`

**Comment by donkopotamus** [comment]
> Understanding the replacement of '/' with dash '-' does preclude `a/b` with `a-b`, but that would also be the same with use of underscore, as used in the cache base hash , see
> 
> [salt/salt/utils/gitfs.py](https://github.com/saltstack/salt/blob/2b44a6ce9a9c387b08ff3abb2bb025c5acece112/salt/utils/gitfs.py#L483-L488)
> 
> Lines 483 to 488 in [2b44a6c](/saltstack/salt/commit/2b44a6ce9a9c387b08ff3abb2bb025c5acece112)
> 
>  self._cache_basehash = str( 
>      base64.b64encode(hash_type(self.id.encode("utf-8")).digest()), 
>      encoding="ascii",  # base64 only outputs ascii 
>  ).replace( 
>      "/", "_" 
>  )  # replace "/" with "_" to not cause trouble with file system 

@dmurphy18 Just a side comment on this first before talking about `os.walk` ... I may be misunderstanding what is happening here, but my reading of this code is:

- `id` is the branch name, and it may or may not contain `/` ... eg `a/b/c`
- it is **not** having any kind of `/ -> _` replacement done on it (thereby potentially clashing with `a_b_c` ... rather it is being **hashed**
   - and then since the **hash** may contain `/` (but not `_` as that isn't in the standard `b64` alphabet), that is replaced to ensure the hashed branch name is a valid directory name.

So there is no potential for clash here beyond the extremely miniscule possibility of a hash collision

**Comment by donkopotamus** [comment]
### Summary ###

@dmurphy18 @OrangeDog 

This is a long and detailed response but this might be a good summary of my thoughts:

- The current structure of checkouts is fine, there is **no need to munge branch names** with `/ -> -`
- The current structure of the `work` directory is fine, there is **no need to munge branch names** with `/ -> -`
- The current way of deciding whether a checkout needs updating, based on a subdirectory of `work` is **fine**
- The problem is tiny and simply in how `fetch_request` is dropped inside the the subdirectories of `work`

My proposed solution is just a few lines of code, but I may well be missing something altogether.

### Details ###

> I am wondering why `os.walk` would be any better given
> 
> ```
> os.walk(top, topdown=True, onerror=None, followlinks=False)[¶](https://docs.python.org/3.10/library/os.html?highlight=os%20listdir#os.walk)
> Generate the file names in a directory tree by walking the tree either top-down or bottom-up. For each
> ```
> 
> So would it not also treat the '/' in a git branch name as an `os.sep` too, similar to `os.listdir`

Yes ... but in this case that is exactly the point.  Currently, branch names that contain a `/` are directly mapped into a directory structure.  Thus if we are using `__env__` and we have a repo with branches `a/b/c`, `d/e` and `f`, then `git_pillar` will aim to check these out at eg

    /var/cache/salt/master/git_pillar/<opaque-hash>/a/b/c
    /var/cache/salt/master/git_pillar/<opaque-hash>/d/e
    /var/cache/salt/master/git_pillar/<opaque-hash>/f

These are the working directories, with their git repos being in:

    /var/cache/salt/master/git_pillar/<opaque-hash>/a/b/c/.git
    /var/cache/salt/master/git_pillar/<opaque-hash>/d/e/.git
    /var/cache/salt/master/git_pillar/<opaque-hash>/f/.git

This is the current situation for how `class GitPillar(GitBase)` does checkouts of particular branches when `__env__` is in effect, and:

- this works fine;
- git rules around branch names mean the branch names are all valid directory paths, without any need to recode `/` etc
    - further, it is impossibly to to have a situation where you have a branch names `a` as well as `a/b/c`

Next, `class GitPillar(GitBase)` has created a mirror of this directory structure in `<cache-root>/work/<opaque-hash>` as:

    /var/cache/salt/master/git_pillar/work/<opaque-hash>/a/b/c
    /var/cache/salt/master/git_pillar/work/<opaque-hash>/d/e
    /var/cache/salt/master/git_pillar/work/<opaque-hash>/f

This also is absolutely fine for all the reasons given above.

When the pillar is fetched, how does it decide if it needs refetching?  If the pillar for `a/b/c` is fetched then [fetch_request_check](https://github.com/saltstack/salt/blob/2b44a6ce9a9c387b08ff3abb2bb025c5acece112/salt/utils/gitfs.py#L1307) is called:

https://github.com/saltstack/salt/blob/2b44a6ce9a9c387b08ff3abb2bb025c5acece112/salt/utils/gitfs.py#L1307-L1309

ie it looks for `<cache-root>/work/<opaque-hash>/a/b/c/fetch_request` ... and if that exists then it updates the checkout in `<cache-root>/git_pillar/<opaque-hash>/a/b/c`.  That is it is looking for the following files:

    /var/cache/salt/master/git_pillar/work/<opaque-hash>/a/b/c/fetch_request
    /var/cache/salt/master/git_pillar/work/<opaque-hash>/d/e/fetch_request
    /var/cache/salt/master/git_pillar/work/<opaque-hash>/f/fetch_request

This logic is also fine, and works perfectly well.

But where do those `fetch_request` files **come** from? These are generated in [fetch_remotes](https://github.com/saltstack/salt/blob/2b44a6ce9a9c387b08ff3abb2bb025c5acece112/salt/utils/gitfs.py#L2768) with this snippet:

https://github.com/saltstack/salt/blob/2b44a6ce9a9c387b08ff3abb2bb025c5acece112/salt/utils/gitfs.py#L2791-L2803    

The **intent** of this code should be to drop ` fetch_request` marker file in **every branch** that is in the `work` directory, ie:

    /var/cache/salt/master/git_pillar/work/<opaque-hash>/a/b/c
    /var/cache/salt/master/git_pillar/work/<opaque-hash>/d/e
    /var/cache/salt/master/git_pillar/work/<opaque-hash>/f

Instead, as it uses `os.listdir`, it drops files in:

    /var/cache/salt/master/git_pillar/work/<opaque-hash>/a    [this doesn't even correspond to a branch]
    /var/cache/salt/master/git_pillar/work/<opaque-hash>/d    [this doesn't even correspond to a branch]
    /var/cache/salt/master/git_pillar/work/<opaque-hash>/f

Now, requests for the `pillar` corresponding to `f` will cause it to be refreshed before its returned.  But requests for eg `a/b/c` will not (as it checks for `<cache-root>/work/<opaque-hash>/a/b/c/fetch_request` which does not exist)

How do we drop a `fetch_request` in every terminal subdirectory of `<cache-root>/<opaque-hash>`?  We can use `os.walk`:

- it generates tuples of the form `(path, sub_dirs, files)` ... we can find terminal directories by filtering for those where `sub_dirs` is empty
- the `path` is the full path, including eg `<cache-root>/<opaque-hash>` so we then normalise for that using `os.relpath`

For example:

    repo_work_hash = os.path.split(repo.get_salt_working_dir())[0]
    branches = [
        os.relpath(path, repo_work_hash) 
        for (path, subdirs, files) in os.walk(repo_work_hash) if not subdirs
    ]
    for branch in os.listdir(repo_work_hash):
        # Don't place fetch request in current branch being updated
        if branch == repo.get_cache_basename():
            continue
        ...

Note that this logic all still works fine for the GitPillar when `__env__` is **not** in effect, as the branch is then stored simply in a subdirectory called `_` and `os.walk` will still find it.  (I have not looked deeply into what will happen with `gitfs` itself, as opposed to `git_pillar`, but the former also seems to simply have `_` in the `work` directory so again `os.walk` should be fine here)

**Comment by dmurphy18** [comment]
@donkopotamus Had the PR passing and it got merged as I was about to edit it to try the os.walk (had played around with os.walk and similar to the git branch name 'doggy/moggy' in a test file).

The PR was passing all tests and had the milestone set for 3006.10, and close to release, hence it made sense to merge it (by the merge master - had requested that this morning before I saw your comment, was on PTO Friday and only saw it after lunch).

Hence opened new Tech-Debt issue to fix this up to use the os.walk approach after the 3006.x branch is released which is immanent, see https://github.com/saltstack/salt/issues/67722

Hence closing this Issue since PR https://github.com/saltstack/salt/pull/66954 has been merged

**Comment by Ikramromdhani** [comment]
@dmurphy18 so do we expect to have this released as part of 3006.10? and if yes do we have ETAs for that? Thank you
