### ISSUE TITLE
[BUG] apt pkg.managed changes key file

### ISSUE THREAD

**Issue by MartinEmrich** [saltstack/salt#65763]
**Description**
A `pkgrepo.managed` state with a key_url modifies the key file, resulting in an apt error message.

**Setup**
* Debian 12
* Salt-Minion 3006.5

**Steps to Reproduce the behavior**

My example: install Jenkins. (from https://www.jenkins.io/doc/book/installing/linux/#debianubuntu)

State:
````
jenkins-lts:
  pkgrepo.managed:
    - name: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    - file: /etc/apt/sources.list.d/jenkins.list
    - aptkey: False
    - key_url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
````

**Expected behavior**

Install Key file and source.list file as specified.

**Screenshots**

Error message:
````
----------
          ID: jenkins-lts
    Function: pkgrepo.managed
        Name: deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
      Result: False
     Comment: Failed to configure repo 'deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/': W: GPG error: https://pkg.jenkins.io/debian-stable binary/ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5BA31D57EF5975CA
              E: The repository 'https://pkg.jenkins.io/debian-stable binary/ Release' is not signed.
     Started: 11:19:20.251128
    Duration: 1545.135 ms
     Changes:
----------
````

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.5

Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-16-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```
</details>

**Additional context**

IMHO related to #64130 ff., in that Salt tries to be "smart" regarding apt repo management, instead of just do what it's told (put files in the right places).

Downloading the key file manually with `wget`, it results in a different file:
````
# file jenkins.io-2023.key jenkins-keyring.asc
jenkins.io-2023.key: PGP public key block Public-Key (old)
jenkins-keyring.asc: OpenPGP Public Key Version 4, Created Mon Mar 27 17:11:07 2023, RSA (Encrypt or Sign, 4096 bits); User ID; Signature; OpenPGP Certificate
````

And moving the downloaded key file to the specified file name makes apt happy:
````
# mv jenkins.io-2023.key jenkins-keyring.asc
# apt-get update
OK:1 http://security.debian.org/debian-security bookworm-security InRelease
Ign:2 https://pkg.jenkins.io/debian-stable binary/ InRelease
Holen:3 https://pkg.jenkins.io/debian-stable binary/ Release [2.044 B]
Holen:4 https://pkg.jenkins.io/debian-stable binary/ Release.gpg [833 B]
OK:5 https://repo.saltproject.io/salt/py3/debian/12/amd64/latest bookworm InRelease
OK:6 http://ftp.de.debian.org/debian bookworm InRelease
OK:7 https://repo.saltproject.io/salt/py3/debian/11/amd64/3006 bullseye InRelease
OK:8 http://ftp.de.debian.org/debian bookworm-updates InRelease
Holen:9 https://pkg.jenkins.io/debian-stable binary/ Packages [26,0 kB]
OK:10 http://repo.zabbix.com/zabbix/5.5/debian bookworm InRelease
Es wurden 28,9 kB in 1 s geholt (44,8 kB/s).
Paketlisten werden gelesen… Fertig
````

Having seen some massaging of the key files with some "gpg", "dearmor" and similar commands in some installation docs for some packages in the past, my guess is that Salt is doing something like that to the key file regardless of whether it needed or not, resulting in a wrong file (format?) in this case.

**Comment by MartinEmrich** [comment]
Luckily, #56828 acts in my favour for now: once I downloaded the key file manually, salt thinks that state is fulfilled.

**Comment by heimdull** [comment]
I just had the same issue where the key file is changed to a format that does not work. Doing a simple wget works fine.

deb [arch=amd64 signed-by=/usr/share/keyrings/ACCC4CF8.asc] https://apt.postgresql.org/pub/repos/apt bookworm-pgdg main

salt puts the file in keyrings but if I run file on the file from salt its:
/usr/share/keyrings/ACCC4CF8.asc: OpenPGP Public Key Version 4, Created Thu Oct 13 20:19:14 2011, RSA (Encrypt or Sign, 4096 bits); User ID; Signature; OpenPGP Certificate

if I just download with wget I get this file type:
ACCC4CF8.asc: PGP public key block Public-Key (old)

**Comment by Akm0d** [comment]
Cannot reproduce the issue -- This should be working in salt v3007.0 and later.

**Comment by MartinEmrich** [comment]
@Akm0d still present in 3006.9:

Salt still silently deamours the downloaded ASCII-armoured key, but saves it as the file name present in the `pkg.managed` state. For apt, the file name extension matters, so it won't accept a binary keyring file if it ends with `.asc`.

As 3006.9 ist AFAIK a LTS release, could you reopen? Thank!

**Comment by Akm0d** [comment]
I can reopen it, but if I can't reproduce the issue it's just going to sit here forever.  Can you provide me with updated steps that reliably demonstrate the issue?

**Comment by MartinEmrich** [comment]
@Akm0d thanks!

It is exactly that salt state:
```
jenkins-lts:
  pkgrepo.managed:
    - name: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    - file: /etc/apt/sources.list.d/jenkins.list
    - aptkey: False
    - key_url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
```

Before applying, make sure to delete `/etc/apt/keyrings/jenkins-keyring.asc` and `/etc/apt/sources.list.d/jenkins.list`. Salt will not update the key file if they are already present (which by chance opens up a workaround).

Then just apply. The `key_url` points to a key file in ASCII-armoured format (text format with the characteristic `-----BEGIN PGP PUBLIC KEY BLOCK-----` first line). APT also expects this format due to the `.asc` file extension.

After applying, you will find the file `/etc/apt/keyrings/jenkins-keyring.asc` actually being a (binary) OpenGPG keyring file. Instead of just downloading the key file, Salt apparently "deamours" the file, i.e. converting it to  the binary format.

I found code in Salt which does this, but have yet to read enough of it to see if this activity calls it: https://github.com/saltstack/salt/blob/master/salt/modules/aptpkg.py#L1958-L1979

**Comment by MartinEmrich** [comment]
I added a `print` and `traceback.print_stack()` call to it (hacking around on that minion directly in /opt/saltstack), and indeed it is called:

```
...
[INFO    ] Executing state pkgrepo.managed for [deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/]
[DEBUG   ] The functions from module 'cp' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded cp.cache_file
[DEBUG   ] Requesting URL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key using GET method
[DEBUG   ] Using backend: tornado
/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/netutil.py:493: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  context = ssl.SSLContext(
XXXX _decrypt_key called
  File "/usr/bin/salt-call", line 11, in <module>
    sys.exit(salt_call())
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/scripts.py", line 444, in salt_call
    client.run()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/call.py", line 50, in run
    caller.run()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 95, in run
    ret = self.call()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 200, in call
    ret["return"] = self.minion.executors[fname](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    ret = _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    ret = _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/state.py", line 1480, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 3570, in call_high
    ret = self.call_chunks(chunks)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2759, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 3283, in call_chunk
    running[tag] = self.call(low, chunks, running)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/decorators/state.py", line 44, in _func
    result = func(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2440, in call
    ret = self.states[cdata["full"]](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    ret = _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1296, in wrapper
    return f(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkgrepo.py", line 575, in managed
    __salt__["pkg.mod_repo"](repo, saltenv=__env__, aptkey=aptkey, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    ret = _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/aptpkg.py", line 2881, in mod_repo
    if not add_repo_key(path=str(fn_), aptkey=False, **func_kwargs):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/aptpkg.py", line 2395, in add_repo_key
    key = _decrypt_key(cached_source_path)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/aptpkg.py", line 2304, in _decrypt_key
    traceback.print_stack()
[TRACE   ] Loaded cmdmod as virtual cmd
[DEBUG   ] The functions from module 'cmd' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command gpg in directory '/root'
[INFO    ] Executing command apt-get in directory '/root'
[TRACE   ] stdout: Hit:1 http://download.bareos.org/current/Debian_12  InRelease
Hit:2 http://security.debian.org/debian-security bookworm-security InRelease
...
```

**Comment by JonathanTreffler** [comment]
> Then just apply. The `key_url` points to a key file in ASCII-armoured format (text format with the characteristic `-----BEGIN PGP PUBLIC KEY BLOCK-----` first line). APT also expects this format due to the `.asc` file extension.
> 
> After applying, you will find the file `/etc/apt/keyrings/jenkins-keyring.asc` actually being a (binary) OpenGPG keyring file. Instead of just downloading the key file, Salt apparently "deamours" the file, i.e. converting it to the binary format.

I ran into the exact same issue and saw the same behavior as described above by @MartinEmrich of salt converting the key to the binary format, which it should not for .asc files on the latest version of salt (3007.1) on debian 12.

### Workaround

I found the following workaround:

Rather than trying to get salt not to deamour the key just let it do that and change the file extension of signed-by path to .gpg so apt undestands how to parse it correctly :)

In my case for the docker repo:
#### before:
```yaml
docker_repo:
  pkgrepo.managed:
    - humanname: Docker
    - name: deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ grains['oscodename'] }} stable
    - file: /etc/apt/sources.list.d/docker.list
    - key_url: https://download.docker.com/linux/debian/gpg
    - clean_file: True
    - aptkey: False
```
#### fixed:
```yaml
docker_repo:
  pkgrepo.managed:
    - humanname: Docker
    - name: deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ grains['oscodename'] }} stable
    - file: /etc/apt/sources.list.d/docker.list
    - key_url: https://download.docker.com/linux/debian/gpg
    - clean_file: True
    - aptkey: False
```

### Logs:

after applying the state labeled "before" running apt update throws the following errors:
```console
~ apt update
[...]
Get:4 https://download.docker.com/linux/debian bookworm InRelease [43.3 kB]                         
Err:4 https://download.docker.com/linux/debian bookworm InRelease                                          
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
[...]
Reading package lists... Done
W: GPG error: https://download.docker.com/linux/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/debian bookworm InRelease' is not signed.
```

**Comment by dwoz** [comment]
Fixed on all supported branches (3006.x, 3007.x, 3008.x, master) by e8ca9b84f2b (PR #69375). `_decrypt_key` now returns the cached path unchanged when the destination keyring ends in `.asc`, matching apt-secure(8). Same root cause as #68464. Closing.
