### ISSUE TITLE
[BUG] Increase the number of inotify when changes are applied repeatedly

### ISSUE THREAD

**Issue by QuinoRay** [saltstack/salt#66449]
**Description**
Setup an inotify beacon and refresh beacons. Every time beacons are refreshed inotify file handles are leaked.

**Setup**
`dnf install salt-minion`
Example beacons file
```yaml
beacons:
  inotify:
    - disable_during_state_run: True
    - coalesce: True
    - files:
        /etc/nginx/nginx.conf:
          mask:
            - delete
            - modify
```

**Steps to Reproduce the behavior**
On the master server salt run:
`salt <name_server> state.apply`

On the slave server using lsof -
`lsof | grep -E 'salt.*inotify'`

**Expected behavior**
There must be a constant number of open 
```yaml
/opt/salt 1817561    root   46r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817562 python3.1    root   46r  a_inode    0,14    0    13770 inotify\n
/opt/salt 1817561 1817659 /opt/salt    root    46r  a_inode    0,14    0    13770 inotify\n
/opt/salt 1817561 1817660 /opt/salt    root    46r  a_inode    0,14    0    13770 inotify\n
/opt/salt 1817561 1817665 /opt/salt    root    46r  a_inode    0,14    0    13770 inotify\n
```
But there's more every time
```yaml
/opt/salt 1817561    root   46r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561    root   48r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561    root   49r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561    root   50r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817562 python3.1    root   46r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817562 python3.1    root   48r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817562 python3.1    root   49r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817659 /opt/salt    root   46r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817659 /opt/salt    root   48r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817659 /opt/salt    root   49r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817660 /opt/salt    root   46r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817660 /opt/salt    root   48r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817660 /opt/salt    root   49r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817665 /opt/salt    root   46r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817665 /opt/salt    root   48r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817665 /opt/salt    root   49r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817666 /opt/salt    root   46r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817666 /opt/salt    root   48r  a_inode    0,14    0    13770 inotify
/opt/salt 1817561 1817666 /opt/salt    root   49r  a_inode    0,14    0    13770 inotify
```

**Versions Report**
```yaml
Salt Version:
          Salt: 3006.7

Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 8.9 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 4.18.0-372.9.1.el8.x86_64
        system: Linux
       version: Rocky Linux 8.9 Green Obsidian
```

**Comment by QuinoRay** [comment]
A workaround for this problem is to restart the salt service once a week, then the number of **inotify** decreases. But this doesn't seem to be the right solution. 
Perhaps there are other ways to workaround this problem that I can apply now without waiting for it to be fixed in the next release?

**Comment by dmurphy18** [comment]
Can you retry this with the latest Salt 3006.9, as some number of fixes for leaks have been fixed since 3006.7.

**Comment by QuinoRay** [comment]
The problem is still present in version 3006.9. 
I see that a fix has been pushed to version 3006.10. Should I expect a fix in this version?

Or maybe you can tell me which python module this bug is associated with so I can try to fix it myself?

**Comment by twangboy** [comment]
Is this still an issue with 3006.14?

**Comment by piterpunk** [comment]
This is still an issue with 3007.8, so I believe it's still happens in 3006.14 and others.

Just after start (and running an `state.highstate` and startup) the Minion, it have fifteen inotifiers open:
```
# lsof -n | grep -E 'salt.*inotify' | wc -l
15
```
After run another `state.apply` without parameters:
```
# lsof -n | grep -E 'salt.*inotify' | wc -l
20
```
And after some time with the highstate being applied hourly:
```
# lsof -n | grep -E 'salt.*inotify' | wc -l
95
```

The code to close (and remove) the notifiers is this one:

```python
def close(config):
    config = salt.utils.beacons.list_to_dict(config)
    beacon_name = config.get("_beacon_name", "inotify")
    notifier = f"{beacon_name}.notifier"
    if notifier in __context__:
        __context__[notifier].stop()
        del __context__[notifier]
```

I did put some debug messages in this code to see what is happening:

```python
def close(config):
    config = salt.utils.beacons.list_to_dict(config)
    beacon_name = config.get("_beacon_name", "inotify")
    notifier = f"{beacon_name}.notifier" 
    #for line in traceback.format_stack():
    #    log.debug("STACK: {}".format(line.strip()))
    log.warning("PNK: Should close {}".format(notifier))
    if __context__:
        for i in __context__:
            log.debug("CONTEXT: {}".format(i))
    else:
        log.debug("CONTEXT: empty")
    if notifier in __context__:
        log.warning("PNK: Closing {}".format(notifier))
        __context__[notifier].stop()
        del __context__[notifier]
        log.warning("PNK: Closed {}".format(notifier))
```

And the `__context__` is most always empty when `inotify.closed` is called, which we can see in this log snippet:

```
2025-11-10 13:42:33,907 [salt.loaded.int.beacons.inotify :367 ][WARNING ][13636] PNK: Should close watch_resolv_conf.notifier
2025-11-10 13:42:33,907 [salt.loaded.int.beacons.inotify :372 ][DEBUG ][13636] CONTEXT: empty
2025-11-10 13:42:34,904 [salt.loaded.int.beacons.inotify :367 ][WARNING ][13636] PNK: Should close watch_resolv_conf.notifier
2025-11-10 13:42:34,904 [salt.loaded.int.beacons.inotify :372 ][DEBUG ][13636] CONTEXT: empty
2025-11-10 13:42:35,904 [salt.loaded.int.beacons.inotify :75 ][WARNING ][13636] PNK: Creating watch_resolv_conf.notifier
2025-11-10 13:42:35,909 [salt.loaded.int.beacons.inotify :81 ][DEBUG ][13636] CONTEXT: inotify.queue
2025-11-10 13:42:35,909 [salt.loaded.int.beacons.inotify :81 ][DEBUG ][13636] CONTEXT: watch_resolv_conf.notifier
2025-11-10 13:42:35,909 [salt.loaded.int.beacons.inotify :89 ][WARNING ][13636] PNK: Created watch_resolv_conf.notifier
2025-11-10 14:42:33,906 [salt.loaded.int.beacons.inotify :367 ][WARNING ][13636] PNK: Should close watch_resolv_conf.notifier
2025-11-10 14:42:33,906 [salt.loaded.int.beacons.inotify :372 ][DEBUG ][13636] CONTEXT: empty
2025-11-10 14:42:34,904 [salt.loaded.int.beacons.inotify :367 ][WARNING ][13636] PNK: Should close watch_resolv_conf.notifier
2025-11-10 14:42:34,904 [salt.loaded.int.beacons.inotify :372 ][DEBUG ][13636] CONTEXT: empty
2025-11-10 14:42:35,904 [salt.loaded.int.beacons.inotify :75 ][WARNING ][13636] PNK: Creating watch_resolv_conf.notifier
2025-11-10 14:42:35,908 [salt.loaded.int.beacons.inotify :81 ][DEBUG ][13636] CONTEXT: inotify.queue
2025-11-10 14:42:35,908 [salt.loaded.int.beacons.inotify :81 ][DEBUG ][13636] CONTEXT: watch_resolv_conf.notifier
2025-11-10 14:42:35,908 [salt.loaded.int.beacons.inotify :89 ][WARNING ][13636] PNK: Created watch_resolv_conf.notifier
2025-11-10 15:42:33,905 [salt.loaded.int.beacons.inotify :367 ][WARNING ][13636] PNK: Should close watch_resolv_conf.notifier
2025-11-10 15:42:33,905 [salt.loaded.int.beacons.inotify :372 ][DEBUG ][13636] CONTEXT: empty
2025-11-10 15:42:34,906 [salt.loaded.int.beacons.inotify :367 ][WARNING ][13636] PNK: Should close watch_resolv_conf.notifier
2025-11-10 15:42:34,906 [salt.loaded.int.beacons.inotify :372 ][DEBUG ][13636] CONTEXT: empty
2025-11-10 15:42:35,904 [salt.loaded.int.beacons.inotify :75 ][WARNING ][13636] PNK: Creating watch_resolv_conf.notifier
2025-11-10 15:42:35,908 [salt.loaded.int.beacons.inotify :81 ][DEBUG ][13636] CONTEXT: inotify.queue
2025-11-10 15:42:35,908 [salt.loaded.int.beacons.inotify :81 ][DEBUG ][13636] CONTEXT: watch_resolv_conf.notifier
2025-11-10 15:42:35,908 [salt.loaded.int.beacons.inotify :89 ][WARNING ][13636] PNK: Created watch_resolv_conf.notifier
```

So, the empty `__context__` makes the old notifier to not be removed by `inotifier.close` and forces the creation of a new one, every time `notify.beacon` is called. It seems to me that, during the reload called by applying the highstate, the `__context__` is cleared before `inotifier.close` is called.

**Comment by piterpunk** [comment]
I guess it was by luck, I got one instance of the Notifier being closed:

```
2025-11-09 01:47:38,591 [salt.utils.extmods :77 ][INFO ][22113] Creating module dir '/var/cache/salt/minion/extmods/beacons'
2025-11-09 01:47:38,596 [salt.utils.extmods :87 ][INFO ][22113] Syncing beacons for environment 'base'
2025-11-09 01:47:38,596 [salt.utils.extmods :89 ][INFO ][22113] Loading cache from salt://_beacons, for base
2025-11-09 01:47:38,596 [salt.fileclient :242 ][INFO ][22113] Caching directory '_beacons/' for environment 'base'
2025-11-09 01:47:38,602 [salt.utils.extmods :103 ][DEBUG ][22113] Local cache dir: '/var/cache/salt/minion/files/base/_beacons'
2025-11-09 01:47:38,616 [salt.beacons :130 ][INFO ][21589] Closing beacon watch_resolv_conf. State run in progress.
2025-11-09 01:47:38,616 [salt.loaded.int.beacons.inotify :367 ][WARNING ][21589] PNK: Should close watch_resolv_conf.notifier
2025-11-09 01:47:38,616 [salt.loaded.int.beacons.inotify :370 ][DEBUG ][21589] CONTEXT: inotify.queue
2025-11-09 01:47:38,617 [salt.loaded.int.beacons.inotify :370 ][DEBUG ][21589] CONTEXT: watch_resolv_conf.notifier
2025-11-09 01:47:38,617 [salt.loaded.int.beacons.inotify :374 ][WARNING ][21589] PNK: Closing watch_resolv_conf.notifier
2025-11-09 01:47:38,617 [salt.loaded.int.beacons.inotify :377 ][WARNING ][21589] PNK: Closed watch_resolv_conf.notifier
```

Here the created Notifier was killed. But even after that, there is two calls for `inotifier.close` with `__context__` empty:

```
2025-11-09 01:47:38,861 [salt.config :2214][DEBUG ][21589] Including configuration from '/etc/salt/minion.d/beacons.conf'
2025-11-09 01:47:38,861 [salt.config :2051][DEBUG ][21589] Reading configuration from /etc/salt/minion.d/beacons.conf
2025-11-09 01:47:39,076 [salt.minion :2605][DEBUG ][21589] Refreshing beacons.
2025-11-09 01:47:39,617 [salt.loader.lazy :914 ][DEBUG ][21589] Override __grains__: <module 'salt.loaded.int.beacons.inotify' from '/opt/saltstack/salt/lib/python3.10/site-packages/salt/beacons/inotify.py'>
2025-11-09 01:47:39,618 [salt.beacons :130 ][INFO ][21589] Closing beacon watch_resolv_conf. State run in progress.
2025-11-09 01:47:39,618 [salt.loaded.int.beacons.inotify :367 ][WARNING ][21589] PNK: Should close watch_resolv_conf.notifier
2025-11-09 01:47:39,618 [salt.loaded.int.beacons.inotify :372 ][DEBUG ][21589] CONTEXT: empty
2025-11-09 01:47:39,969 [salt.loader.lazy :1015][DEBUG ][22113] The functions from module 'beacons' are being loaded by dir() on the loaded module
2025-11-09 01:47:40,104 [salt.loader.lazy :1015][DEBUG ][22113] The functions from module 'beacons' are being loaded by dir() on the loaded module
2025-11-09 01:47:40,617 [salt.beacons :130 ][INFO ][21589] Closing beacon watch_resolv_conf. State run in progress.
2025-11-09 01:47:40,617 [salt.loaded.int.beacons.inotify :367 ][WARNING ][21589] PNK: Should close watch_resolv_conf.notifier
2025-11-09 01:47:40,617 [salt.loaded.int.beacons.inotify :372 ][DEBUG ][21589] CONTEXT: empty
2025-11-09 01:47:41,616 [salt.loaded.int.beacons.inotify :75 ][WARNING ][21589] PNK: Creating watch_resolv_conf.notifier
2025-11-09 01:47:41,620 [salt.loaded.int.beacons.inotify :81 ][DEBUG ][21589] CONTEXT: inotify.queue
2025-11-09 01:47:41,620 [salt.loaded.int.beacons.inotify :81 ][DEBUG ][21589] CONTEXT: watch_resolv_conf.notifier
2025-11-09 01:47:41,620 [salt.loaded.int.beacons.inotify :89 ][WARNING ][21589] PNK: Created watch_resolv_conf.notifier
```

When this pattern happens (create, close with `__context__`, 2 x close without `__context__`), the inotify file descriptors kept stable. But after I restarted the Minion, it returns to the previous behaviour with the number of inotify always growing. The different behaviour is not related with anything that I do, but it seems that once it starts working fine, it continues working until I restart the minion. Sadly, the "working fine" behaviour is very rare, got it by chance two times in dozens of restarts.
