### ISSUE TITLE
Minion Environment Is Being Ignored

### ISSUE THREAD

**Issue by ekristen** [saltstack/salt#9805]
Basically I have two environments configured and I have my minions isolated via their configuration file to a specific environment. However when I run state.highstate, minions match up to both top.sls files that reside in different environment definitions.

dev/top.sls

```
dev:
  '*':
    - users
```

test/top.sls

```
test:
  '*':
    - users
```

I have minions whose configuration specifically have environment: test and environment: dev, according to the docs it should isolate them to a specific environment on the master, the behavior indicates otherwise.

Current workaround is to use compound matching and to set the grain environment:dev and then always do 'G@environment:dev|testing' in all my top.sls definitions. 

Salt version: 0.17.4

**Comment by ekristen** [comment]
This is still a bug :(

**Comment by ekristen** [comment]
`salt-call` and `salt` from master both default to `base` environment even when the the `/etc/salt/minion` `environment` variable is set to a specific environment.

**Comment by ekristen** [comment]
Adding `saltenv=<environment>` to the command does work to set the right environment.

**Comment by ekristen** [comment]
Bump

**Comment by basepi** [comment]
I added this to my list. If it's just a config issue at this point I feel like it shouldn't be too difficult to track down.

**Comment by JohnMaguire** [comment]
I had setup my vagrant provisioner to install a `minion` file with `environment: develop`, in hopes that the user could `vagrant ssh` and then call `salt-call --local state.highstate` and have the Vagrant machine provisioned. Seems this is still a bug.

**Comment by JohnMaguire** [comment]
Interestingly, `salt.highstate` seems unaffected while `state.apply` is:

```
root@packer-virtualbox-1445705454:/home/vagrant# salt-call --local state.apply salt-minion
[INFO    ] Wrote new gitfs_remote map to /var/cache/salt/minion/gitfs/remote_map.txt
[INFO    ] Loading fresh modules for state activity
local:
    - No matching sls found for 'salt-minion' in env 'base'
root@packer-virtualbox-1445705454:/home/vagrant# salt-call --local state.highstate
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'develop', ** done ** 'top.sls'
```

**Comment by JohnMaguire** [comment]
Actually, based on quickly glancing the code, it seems like `highstate` might default to a different env if the requested one isn't available. Not sure I'm reading the code correctly though.

**Comment by ekristen** [comment]
I'm happy to report that this bug is now fixed AFAICT. When running salt-call locally I no longer have to supply saltenv as a cli argument. The `environment` value from the minion config is properly honored. 

Thanks everyone!

**Comment by bryceml** [comment]
This bug seems to have come back in version 2018.3.0.  Doesn't seem to affect 2017.7.4.  This is on ubuntu xenial using the repo.saltstack.com repo's packages.

I get the following when running salt-call state.apply or salt-call state.highstate or state.top top.sls:

[ERROR   ] The 'base' saltenv has no top file, and the fallback saltenv specified by default_top (base) also has no top file

my base environment is not used because I don't want anything to happen unless I specify the saltenv.  I put 'environment: prod' in /etc/salt/minion

**Comment by thetoolsmith** [comment]
Yes, i can confirm this bug is back. I just upgraded to 2018.3.0 to fix one issue, and not the environment key in minion config is not being realized.

**Comment by Nklya** [comment]
Changing `environment` key in minion config to `saltenv` helped me.

**Comment by bryceml** [comment]
I guess this was intentional.  I wish it would have been a more graceful change.  https://docs.saltstack.com/en/latest/topics/releases/2018.3.0.html#environment-config-option-renamed-to-saltenv

**Comment by KristianWindsor** [comment]
Any update on this issue?
